### ISSUE TITLE
Add a feature to allow for vampire drain on extended non charging layovers.

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#1]

**Comment by EVGrokker** [comment]
Presumably this would be slider adjusting rated miles of loss per hour?

**Comment by aesculus** [comment]
TBD

**Comment by aesculus** [comment]
Where do we get the vampire drain factors from?  Have the user input SoC drain per day/hour in My Cars and then on the origin/destination pairs factor in the difference?  Could get confusing and juicy.

**Comment by aesculus** [comment]
Right now in MST the user has the ability to override the segments origin SoC level. The user can easily figure out how many days they are going to be parked, do the mental math for their car and then subtract that amount of energy from the carry over.

The gain is not worth the pain and I am rejecting this idea.
