### ISSUE TITLE
Optimize all trip segments at one time

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#10]
Must do this in trip order.

**Comment by EVGrokker** [comment]
After this issue is resolved, **Plan | Optimize Segment** should be renamed to **Optimize Route** to match the busy dialog. That's the preferable name for the function. The current name is a bandaid to try to cover for the fact that optimization is currently segment-based, not the entire trip.

**Comment by aesculus** [comment]
And not Optimize Trip?

**Comment by EVGrokker** [comment]
I suppose either would work, but route seems  slightly more descriptive of what's actually happening, since trip encompasses more than just the route. Trip includes itineraries, non-charging waypoints, etc. 

You could counter that the app is called EV **TRIP** Optimizer, and #10 is the heart and soul of the app.

**Comment by aesculus** [comment]
I guess. I just hope route does not have a segment stigmatism. Of course it could just be Optimize.

**Comment by EVGrokker** [comment]
Optimize Routing?

**Comment by aesculus** [comment]
Implemented in V1.2 (9). Needs some more work for MST trips to be totally.

**Comment by EVGrokker** [comment]
Help me understand what's changed. Let's assume a three-segment trip. You optimize segment 1 from the Plan Menu | Optimize Segment. Segments 2 and 3 are optimized at the same time?

Does the change you've made increase the amount of time that the app is recalculating, because it's touching all the segments?

**Comment by aesculus** [comment]
> Help me understand what's changed. Let's assume a three-segment trip. You optimize segment 1 from the Plan Menu | Optimize Segment. Segments 2 and 3 are optimized as part of the same operation?

Yes. A flag is set on all segments that the app needs to recalc those (chargers already picked and some energy settings - destination minimums) are set.

> Does the change you've made increase the amount of time that the app is recalculating, because it's touching all the segments?

I tried to minimize this. So that answer is yes in total, but only when you go to that segment. 

The one you are on gets calculated BAU. Then for example the first segment will not be recalculated until you go there, but then that will cause the next segment to be recalculated when you go there etc. Once you have passed all the segments the will no longer need recalculations unless you optimize again or change an upstream segment.

There could be an option to refine the destination energy based on the first pass, but it's not being done yet. It is an enhancement issue #349.

**Comment by EVGrokker** [comment]
>The one you are on gets calculated BAU.

What does BAU mean?

**Comment by EVGrokker** [comment]
Does implementation of this feature mean that white destination pins should no longer appear?

**Comment by aesculus** [comment]
I would say yes or mostly, but there could be some issues that might cause them to show up. I ave not hunted down every place to see if it can still be triggered, but I did turn it off in the one place I knew it was used extensively and changed it to a request to do auto calculation instead.

Let's play with it a bit to see if we ever see any again.

Personally there really is no reason for them anymore. The clue to optimization now would be if you see yellow or red pins, or you just think you have made enough changes that you want to optimize just to be sure.

**Comment by aesculus** [comment]
Business As Usual

**Comment by EVGrokker** [comment]
If they show up we can figure out why and what the right response is. (I'm now thinking of white pins as "surrender flags", as in waving the white flag.)

**Comment by aesculus** [comment]
So I did have them show up when I imported a trip. That kind of makes sense. Since the trip was not created for my car, it had to be optimized, hence the white destination flags.  But as soon as I optimized, I never saw them again.

So if when you import one of your shared trips, you should see them too.

**Comment by EVGrokker** [comment]
Interesting. 

So if I import a multi-segment trip you send me, and the destination pins show in white, in  that instance it would mean "optimization needed, because this trip was created with another user's parameters."?

**Comment by EVGrokker** [comment]
Would that always be the case with imported trips?

What if I import my own trip (after a wipe/reinstall cycle)?

**Comment by aesculus** [comment]
Always. It does not know the underlying car did not change.

Trips are associated with a car index. Whichever one is active. There is no car details associated with a trip.

**Comment by EVGrokker** [comment]
If I'm understanding correctly, we can position this as a feature by design.

"When importing trips, you will need to optimize the trip to recalculate it with your current vehicle characteristics and preferences. This is true even if your are importing a trip you previously exported yourself."

Is that an accurate statement?

**Comment by aesculus** [comment]
Yes

**Comment by aesculus** [comment]
And BTW if you ever want to copy a trip to another car, you do this too.

Issue #256

**Comment by EVGrokker** [comment]
Disclaimer: I know this is an oversimplification of the objective of this enhancement, and that I have little comprehension of what's going on under the hood, but I have an idea for how to break down complex trips for auto optimization.

You've often pointed out that building a trip manually, in segments, works well, and is in fact how the app originally worked. I haven't seen many problems with Point A - Point B optimization. It's only when you throw in off-route waypoints that things get challenging (the Utopia - Kearney - Gillette conundrum).

Here's my simple-minded concept. Can you treat each leg (between waypoints) as if it were a separate trip, computing those routes, then splice these legs together into the larger route, finally doing the optimization and power computation passes afterwards? In this scenario, a waypoint and a hinge point are equivalent, so segmentation shouldn't matter.

If this is a totally ignorant suggestion, feel free to simply say "won't work". You don't need to explain why. I'm just trying to leverage the fact that manual routing seems to work fine, and it should be able to build on that strength when doing multi-segment optimization.

**Comment by aesculus** [comment]
I had to explain this very thing to my wife, a non techie, last night, so here it goes again. :-)

When I originally adapted the app to do multiple segments this is exactly what I did, and how < V1.2 works.  Each segment is a different trip and is optimized one at a time and glued together. The tricky part is the amount of energy shared between segments makes a difference in the routing.  You see this in the Gillette Example.

So while the routing can be set to make it go though Gillette in this manner I have to reserve enough energy to make it back out the other side. How much energy?  There are hacks in >V1.2 that try to guess, with some level of reliability.  It looks at where you are heading and what chargers are near there and tries to guess how far away they are in order to determine how much energy it would need to reserve to get there.  There are problems with this approach, one being their are multiple solutions and some are better than others.

As an experiment you can test this theory out by going to combinations of Salina, Gillette, Grand Island and Guthenburg and see what overall times you see. There is a 20+ minute difference when you swap some chargers for another or charge for different times. A true optimizer can find the best route/charging time.

So the only answer I have found right now is that when I come up to a waypoint I have to try various min soc to arrive at that waypoint, and see which are valid. Then use that 'list' on the next portion of that route, one by one, and see which yields the best result. Then that is the preferred means to get to that waypoint. Then rinse and repeat.

I am currently at the rinse and repeat stage and am not certain where I can stop that process and start anew. Need to think about that some. Is there anything that would let me start fresh? At first glance a charger but no, some chargers are better than others. A supercharger? Maybe if there are no other reachable options. A stop would an extended time? Probably. That resets the clock for sure.

So that is the project for today to figure out what can reset the model to have to stop carrying over energy.

**Comment by EVGrokker** [comment]
Been there. See attached:

![progeng](https://cloud.githubusercontent.com/assets/26678403/25709078/887ad072-30a5-11e7-9f8b-ca4fb80f7d7d.jpg)

**Comment by aesculus** [comment]
:-)

**Comment by EVGrokker** [comment]
v 1.2.0 (13)

New Trip: Fremont CA - Custer SD, Auto
Default Settings: 15% SoC, Model S, 2-wheel drive, 85kWh, 19" wheels
Elko NV SC: Require, Segment
Billings MT: Require, Segment
Menu: Optimize Routing

The app hangs up for a long time at the first step, then finally displays the following. Note the mis-formatted `<br>` tags in the screen capture below.

Suggested text when this condition is encountered:
~~There is no known route through Superchargers!
You may want to reduce your reserves, look for additional charging stops or reduce your energy consumption.~~
No available supercharger routing. Try adding charging stops manually. 
To share this trip with our support team, select **Feedback Report** from the Main menu, with a brief problem description.

![noknownroute](https://cloud.githubusercontent.com/assets/26678403/26029017/7d575f0e-37e8-11e7-9ac8-765e271d2193.PNG)

**Comment by aesculus** [comment]
OK. The <br> easy to remove. Leftover from an HTML based alert.

I will also look at why this trip failes.

Question: After removing the <br> will this dialog work with the error message like it is?  I was also planning on changing the second icon to this too:
![791-warning](https://cloud.githubusercontent.com/assets/283364/26029122/470c4e88-37e2-11e7-8ad5-adac72fa19eb.png)

**Comment by EVGrokker** [comment]
I just ran the same trip after changing my Settings to 20% SoC and Model X90D, 5 seater, got the same results - couldn't find SC routing. In looking more closely at the segments, it appears that you're not forcing the Departure hinge pin SoC values to the Default Origin SoC (90%), that might help.

**Comment by EVGrokker** [comment]
>Question: After removing the `<br>` will this dialog work with the error message like it is? I was also planning on changing the second icon to this too:

Are you referring to changing the icon to the left of 'Obtaining Routing' to an alert icon?  If so, yes, I agree that's a good idea. It emphasizes where in the process the failure occured.

**Comment by EVGrokker** [comment]
Same error with this trip:
New Trip: Seattle WA - Santa Barbara CA, Auto
Require/Segment at Springfield OR SC
Add Waypoint: Petaluma CA SC
Optimize Routing.

**Comment by aesculus** [comment]
Alert text changed in V1.2 (14) along with alert icon.

**Comment by aesculus** [comment]
>New Trip: Fremont CA - Custer SD, Auto
Default Settings: 15% SoC, Model S, 2-wheel drive, 85kWh, 19" wheels
Elko NV SC: Require, Segment
Billings MT: Require, Segment
Menu: Optimize Routing

Tried this and did not get a hang. Everything worked OK.

I wonder if there is some sort of timing thing why these are not working on your phone but do OK for me?

**Comment by aesculus** [comment]
Can you reshare the failed trip with me and be sure to use the Feedback Report so I can dupe the stuff exactly.

**Comment by aesculus** [comment]
Please try this with V1.2 (21).  I hope I am getting closer.

**Comment by aesculus** [comment]
I believe with V1.2 (58) this has been satisfied but there may still be some lingering issues that will be addressed on a case by case basis.
