### ISSUE TITLE
Waypoint Info popup formatting/layout problems with buttons

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#110]
I'm not sure what caused the attached layout problems in the screen shot below, as I don't think it always displays like this. It appears that the layout manager decided the buttons were too wide for the container. Is it possible to use an icon instead of 'View', perhaps the little man, or an eye?

---

![img_0309](https://cloud.githubusercontent.com/assets/26678403/24587228/93cec124-1767-11e7-951a-476950a4e220.PNG)

![images](https://cloud.githubusercontent.com/assets/26678403/24587268/0d354998-1768-11e7-9802-6e9e962e9891.jpeg)

**Comment by aesculus** [comment]
I will need to look at this on the iPhone. Not sure why it takes up so much of the screen. Probably something with the Retina display.

**Comment by aesculus** [comment]
I tried this on an iPhone 6S+ and this is what I get using V1.1.3 (2)
![img_7259](https://cloud.githubusercontent.com/assets/283364/24595506/fc7815ca-17eb-11e7-8f57-6cdf97568f6b.PNG)

**Comment by EVGrokker** [comment]
The faulty layout only happened once for me, and I don't know what triggered it. Until it's repeatable I'd suggest leaving this open but low priority.

**Comment by EVGrokker** [comment]
I can reproduce this bug.

New Trip. Origin: Seattle WA. Destination: Ocean Shores WA. Calculate.

After trip calculates, touch lighting bolt to display superchargers.

Touch Aberdeen WA supercharger pin (closest to Destination pin).

Touch Include. Trip recalculates.

Touch Aberdeen SC pin again. Button display is jumbled.

![img_0316](https://cloud.githubusercontent.com/assets/26678403/24610121/3acaf61c-1832-11e7-9b23-dbe8f1b9d12c.PNG)

**Comment by aesculus** [comment]
OK. I will give it a try.  I think I might tighten up the buttons a bit. I noted in my image above the button spacing seemed a bit tighter than your iPhone.  A tiny quirk between models. Go figure.

**Comment by aesculus** [comment]
Please test this in V1.1.3 (3)

**Comment by EVGrokker** [comment]
Button layout still gets wrapped to two lines sometimes, but icons don't overlay buttons.

**Comment by aesculus** [comment]
Lets try this again with V1.1.3 (4)

**Comment by EVGrokker** [comment]
Still a problem in v 1.1.3 (4)

1) New Trip: Seattle WA - Moclips WA
2) Add waypoint - Tesla Supercharger - Centralia WA
3) Touch Centralia waypoint pin:

![img_0329](https://cloud.githubusercontent.com/assets/26678403/24705257/f08549ec-19bf-11e7-84f7-da31a2ed24ef.PNG)

**Comment by aesculus** [comment]
V 1.1.3 (5) has the spacing even closer. Hopefully it's enough now

**Comment by aesculus** [comment]
Replaced with icons in V1.1.3
