### ISSUE TITLE
Consider showing Minimum Stop Time in Infowindow

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#114]
It's not shown today, just total stop time.

Note this is a bit complex in that the minimum stop time only gets set if the charger time does not reach that amount of time. Its really the total stop time that gets shown.

I am not convinced yet this needs to be implemented but have it here as a discussion/consideration placeholder.

**Comment by EVGrokker** [comment]
Addressed by #103
