### ISSUE TITLE
Plan Trip screen: Add option to display current location

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#117]
Add an on-screen icon (see _Suggested location icon_ below), which can be toggled to enable display of user's current location on the Map tab of the Plan Trip screen. 

If the Google Maps API offers it, an indication of the current direction (which way the device is pointed) would be useful as well (see _Blue location dot_ graphic below).

The icon should have two visual states - grayed out when current location is not enabled, and darker when current location is enabled. Suggested location would be top right are of map tab, with globe icon located below.

Enabling current location (transitioning from not enabled to enabled) should recenter the map on the device's current location at current zoom level.

Possible options for context menu selections (displayed by a long press) could be 'Recenter map on current location' and 'Zoom to include current location and destination'.

---

Suggested location icon:
![unknown](https://cloud.githubusercontent.com/assets/26678403/24607691/daafddce-1827-11e7-9e29-291df15f0ddc.jpeg)

---
Blue location dot with cone showing device orientation
![unknown-1](https://cloud.githubusercontent.com/assets/26678403/24607615/86d6e800-1827-11e7-9acb-05c13cb36061.jpeg)

**Comment by aesculus** [comment]
I'll have to find a place for this. Settings is already too crowded. We will need to think of a redesign.

But is this not getting away from the planning aspect and moving it toward a driving tool we thought was not a good idea?

I am sort of in favor of making a list of future 'during trip' like features that could come in a V2.0 or something if/when.

**Comment by EVGrokker** [comment]
I was thinking the control would on the map tab where the globe icon is now, causing the globe to move down. 

I wouldn't have thought of suggesting this if all my waypoints had made it to the calendar. Let's back-burner this for a future release as you suggest.

**Comment by aesculus** [comment]
>I wouldn't have thought of suggesting this if all my waypoints had made it to the calendar. Let's back-burner this for a future release as you suggest.

Must have missed this in another thread. Which one had this issue?

**Comment by EVGrokker** [comment]
Issue #37, most recent comment, last bullet.

**Comment by aesculus** [comment]
If we add this feature I think it should come from a toggled map icon. Upper left corner is good for this but the Map/Satellite buttons are in the way. I never use the satellite view and I propose that I replace that with this location icon.

Also do you want anything more than just a blinking dot or would you also want tracking and zooming to a default zoom factor when the icon is toggled?

**Comment by EVGrokker** [comment]
I hate satellite view as well. Data-hungry, obsolete imagery, etc. If users complain, we could say "it was satellite view or live tracking… we chose live tracking." 

No blinking dot, a blue dot with orientation arrow (I can screenshot if you need a reference). 

I am opposed to tracking at this time, it will set user expectations sky high. "Find me on the map" is the functionality here.

**Comment by aesculus** [comment]
> No blinking dot, a blue dot with orientation arrow (I can screenshot if you need a reference).

Always. You see what happens when I think (note the calendar alert debacle)

> I am opposed to tracking at this time, it will set user expectations sky high. "Find me on the map" is the functionality here.

OK. So not toggle then? Just a press on the icon and the map moves to the location of the device? Should the device location icon then go away after a few minutes?

**Comment by EVGrokker** [comment]
Sorry, definitely a toggle, like the lightning bolt button for superchargers. Either your current position is displayed on the map, or it isn't. But no tracking.

Here's a perfectly usable sample from the Tesla mobile app.

![current location](https://cloud.githubusercontent.com/assets/26678403/25307011/ab1ffa42-2756-11e7-8e4f-831778700d2f.png)

**Comment by aesculus** [comment]
BTW the globe on the Tesla Mobile App turns on the satellite view. :-)

Their location toggle does not turn off for me. It just seems to pan the map.  :-(

**Comment by EVGrokker** [comment]
You're in the same location as your car. :)

**Comment by aesculus** [comment]
Yes. but if I toggle the menu icons neither map icons goes away. So they are always active as long as you are on the location panel. That's ok for that app because that is the only purpose of the location panel. Our app is not that way.

So in our app the toggle on:
- turns on device location dot
- pans the map to the device location
- does not zoom the map nor will it continue to pan if you drive?
Toggle off:
- removes the device icon from the map
- does not stop tracking (because it never did from the third bullet above)?

So the third bullets is the question. We will not track correct?

**Comment by EVGrokker** [comment]
Desired behavior:

Location toggled on:
- Crosshair button (location button) changes appearance to 'On' state.
- Blue location dot displayed
- Map location panned to current device location once, but does not continuously update map to match device location. If user pans away, we don't want to fight with them about where the map is centered.
- Blue dot location is updated, maybe every 5 seconds. Needs empirical feedback while moving. 
- I would propose that the zoom level is not changed when dot is displayed. User knows how to zoom.
- If user wants to recenter map on device location, they toggle location button off and back on.

Location toggled off:
- Crosshair button changes appearance to 'Off' state
- Blue dot removed from display.
- Tracking ceases. We don't want to consume power when we're not displaying location.

**Comment by aesculus** [comment]
This OK for the location button?

![image](https://cloud.githubusercontent.com/assets/283364/25308175/11b2ab12-2764-11e7-8fe8-ca1f489e4b2b.png)

**Comment by EVGrokker** [comment]
Looks good. What about the toggled state? Thicker? Black vs gray?

**Comment by aesculus** [comment]
Toggled icon

![image](https://cloud.githubusercontent.com/assets/283364/25308285/8bc4c9b6-2765-11e7-95af-815094fea07a.png)

**Comment by EVGrokker** [comment]
Is that inverted? Looks ominous.

**Comment by aesculus** [comment]
It is inverted.  I could make it bolder and black

**Comment by EVGrokker** [comment]
My instinct is grayed, thinner, fainter for the OFF state, black, bolder, stronger for the ON state.

**Comment by aesculus** [comment]
How about this for on?

![image](https://cloud.githubusercontent.com/assets/283364/25308431/e4775fee-2768-11e7-95f6-9276c852a92b.png)

**Comment by EVGrokker** [comment]
Yes, let's try that combo.

Is this now a 1.2 feature?

**Comment by aesculus** [comment]
Yeah. I should have some code from another project that should drop right in here.

**Comment by aesculus** [comment]
![image](https://cloud.githubusercontent.com/assets/283364/25308863/5db197bc-2773-11e7-85ef-8fc62e666748.png)

**Comment by EVGrokker** [comment]
My initial reaction was to make the background transparent, but now I see that the other buttons are all backed with white. Scale and weight look good. Let's see the enabled version.

**Comment by aesculus** [comment]
![image](https://cloud.githubusercontent.com/assets/283364/25308899/25edbe7c-2774-11e7-8d71-1e70c2c70dea.png)

**Comment by aesculus** [comment]
>  I see that the other buttons are all backed with white.

That appears to be a Google maps thing to reduce miss reads from the background I guess.

**Comment by EVGrokker** [comment]
The enabled version looks thick. What about using the same thickness that you have for disabled for both, but a lighter gray for disabled and black for enabled?

**Comment by aesculus** [comment]
It does look a bit chunky. Let me put it on a diet.
![image](https://cloud.githubusercontent.com/assets/283364/25309020/5d7ae25a-2776-11e7-95fd-9e4f3522e0fb.png)

**Comment by EVGrokker** [comment]
In looking at the globe, the peer button in the upper right corner, my eye wants to see symmetry like they're related. Would it be possible to clone the circle element of the globe (same size and thickness), add the crosshair lines, then create two versions of that, one gray, one black?

**Comment by aesculus** [comment]
Believe it or not but they are the same
![image](https://cloud.githubusercontent.com/assets/283364/25309048/2ea26146-2777-11e7-86ee-2d5cb8b4189c.png) 
![image](https://cloud.githubusercontent.com/assets/283364/25309050/3ea30730-2777-11e7-80e5-7dce66d0ff29.png)

**Comment by aesculus** [comment]
I think it's the blue tab drawing your eyes differently.

**Comment by EVGrokker** [comment]
Same diameter, but globe looks like a thinner width. Optical illusion?

**Comment by aesculus** [comment]
No. The location is black. Let me fix that

**Comment by EVGrokker** [comment]
Implementation detail: if location services disabled, touching button does nothing.

**Comment by aesculus** [comment]
How is this?

![image](https://cloud.githubusercontent.com/assets/283364/25309159/4d11cc90-277a-11e7-868a-b35bea79401e.png)

**Comment by EVGrokker** [comment]
👍

**Comment by aesculus** [comment]
>Implementation detail: if location services disabled, touching button does nothing.

That might be better than what I just coded which was not displaying it at all. I like your way better

**Comment by aesculus** [comment]
Yes it strobes too. V1.2 (0)

![image](https://cloud.githubusercontent.com/assets/283364/25309684/64781430-2788-11e7-87c1-be6fd97adccf.png)

**Comment by EVGrokker** [comment]
It looks like the stroke width got fat/chunky again in the production version. I created two circles with the same stroke width as the globe, black and grey.

The bottom row is what I think the outer circle should look like in the enabled and disabled states.

<img width="93" alt="crosshair comparison" src="https://cloud.githubusercontent.com/assets/26678403/25315748/7ce59210-2817-11e7-8e0b-cd4c8a4e3d21.png">

**Comment by aesculus** [comment]
Do you just want it black then, without beefing it up?  I was worried that it would not be significant enough to notices, but then that blink blue thing probably will tell them something is up. :-)

Here is plain black with no fattening.

![image](https://cloud.githubusercontent.com/assets/283364/25319163/70ee64d6-284f-11e7-852a-7e38b45ce2ad.png) 
![image](https://cloud.githubusercontent.com/assets/283364/25319181/9e7e37f0-284f-11e7-9674-ff81c830335e.png)

**Comment by EVGrokker** [comment]
Let's try it and see how it feels. 

Is there an option in the Google API that adds a pointer to the blue dot, showing the current direction the device is pointing?

**Comment by aesculus** [comment]
No. In fact that blue strobing dot is a hack I did years ago.  Google API has nothing for a directional indicator. In fact they really don't even have an indicator.  You can use any graphic you want.

I would have to build like 12 graphics in order to support direction. Not worth it to me at this time.

Also today I am only getting the lat/lng of the device, not the heading. That would involve a lot more work and potential issues that might come up.

**Comment by aesculus** [comment]
How about this for the toggle on state?

![image](https://cloud.githubusercontent.com/assets/283364/25319440/0b9826e0-2853-11e7-99a1-8fbe539e6dbd.png)

**Comment by EVGrokker** [comment]
Nice!

**Comment by EVGrokker** [comment]
Moving the straight lines across the circle edge and adding the interior circle is a winner.

**Comment by aesculus** [comment]
Does this mean use the last icon? :-)

**Comment by EVGrokker** [comment]
The design you have in 1.2 (2) looks good, apart from issue #311, the vertical alignment does not match the globe.
