### ISSUE TITLE
Waypoint enhancement: Add option to export single waypoint to email

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#118]
In addition to being able to export an entire segment to device calendar, add the ability to export a single waypoint to device calendar, using a direct interaction with the waypoint.

Two ideas for implementation:
1. Add a button to the Waypoint info popup. Available real estate is in short supply. 
2. Long-press on the waypoint icon in Map view shows a context menu popup with 'Add to calendar' as an option. (Other ideas for this context menu: 'Segment', 'Delete', 'Join'.)

**Comment by aesculus** [comment]
Where would this be actioned from?

**Comment by EVGrokker** [comment]
I suggest combining this enhancement proposal with issue #37.

As far as where it would be initiated, I'd suggest adding a Share icon to the waypoint inspector in the upper right corner, opposite the heart icon.
Share options would include 'Add to my calendar', 'Email' and 'Message'. This would be useful for quickly notifying the person you're visiting of your route and ETA. 'Email' and 'Message' would send an image of the dialog. 

---

![img_0355](https://cloud.githubusercontent.com/assets/26678403/25004199/4eb2f298-2010-11e7-8e03-b7027ce246d9.PNG)

**Comment by aesculus** [comment]
I think that is a great idea and a good design, but I have a technical issue I broke my pick on with this before.  

If you not the car has the Favorite heart over on the right side. When the app came out I had it over there too. But it turns out one of the platforms (I think it was Android but not certain) had an issue with that. This dialog is a hacked standard Google Infowindow. It has a close button on the upper right. Try as I may I could not fully disable that button on one of the platforms. Whenever the user pressed the heart (or the dislike on chargers) it closed the dialog instead of saving the favorite.

Never came up with a solution after days of trying, so I just moved the favorite/dislike to the other side.

**Comment by EVGrokker** [comment]
What if the heart were in top left corner, as it is now, and the share icon were immediately to the right of the heart? Ideally, the name would still be centered.

**Comment by aesculus** [comment]
The title is not centered but just to the right of the favorite/dislike. I think it could cause it to look odd when the titles are longer.

**Comment by EVGrokker** [comment]
The next possible location would be to add a 6th slot to the button row for the share icon, which would invoke a popup with the options described above.

**Comment by aesculus** [comment]
I think this is the best fallback.  I will revisit my attempts at the upper icon one more time before I do this though.

And if I am successful, what about moving the favorite/dislike over to the right to match the car where I wanted it to begin with?

**Comment by EVGrokker** [comment]
If you can pull it off to your satisfaction, sure, go for it. 

There's a slight overloading of that real estate between iOS expectations and Tesla's UI. My sense is that users put on their "I'm working on iOS right now" and expect things in the top right to be close buttons. 

There's certainly some value in matching Tesla's layout, but I don't always agree with the choices on a small screen, for example the Tripp Summary dialog layout, as previously discussed. The car has a nearly infinite canvas, phones have a teeny-weeny canvas.

The more I think about it, I think adding it to the button row makes the most sense organizationally. Right now the user knows that buttons in upper left corners of dialogs are toggles. Share doesn't match the expectation.

**Comment by aesculus** [comment]
OK. Then the bottom it is.  Where do you want it positioned (order)?

Also is there an equivalent function we would do for a charger that is not a waypoint, or just have it disabled like we do for the Edit icon?

Is this icon OK so it matches the others?
![image](https://cloud.githubusercontent.com/assets/283364/25017221/c6118f76-2037-11e7-824f-6a4d3c478899.png)

**Comment by EVGrokker** [comment]
That curvy arrow icon is obsolete in iOS (I think it was changed ~iOS 7 to the straight-up arrow), but I personally don't care, especially since you're trying to be platform-neutral. iOS users will understand it.

As far as order, we never really discussed that for the 5-slot layout. One could argue that delete should be in the last position.

What do you think of this layout?
[help]  [view]  [share]  [segment/require]  [edit]  [delete]?

And yes, I would keep the 6-slot layout across all dialogs of this style, with unused icons disabled for visual consistency.

---

![img_0355](https://cloud.githubusercontent.com/assets/26678403/25017943/c2c23e28-2042-11e7-8feb-d0a733170073.PNG)

**Comment by aesculus** [comment]
>That curvy arrow icon is obsolete in iOS (I think it was changed ~iOS 7 to the straight-up arrow), but I personally don't care, especially since you're trying to be platform-neutral. iOS users will understand it.

This OK in black?

![image](https://cloud.githubusercontent.com/assets/283364/25018125/1e5c7044-203b-11e7-8b1a-61d661199e84.png)

>As far as order, we never really discussed that for the 5-slot layout. One could argue that delete should be in the last position.

What do you think of this layout?
[help] [view] [share] [segment/require] [edit] [delete]?

I am good with that. Lets see how much anquist is caused by moving the buttons. :-)

>And yes, I would keep the 6-slot layout across all dialogs of this style, with unused icons disabled for visual consistency.

OK. I could not come up with any scenario that I would want to share a charger in that was not a waypoint.

I am not going to get to this right away so if we come up with something I will include it.

**Comment by EVGrokker** [comment]
If you're going to use the straight-up sharing icon, the one below on the right is the current one for iOS.
![unknown](https://cloud.githubusercontent.com/assets/26678403/25018384/6e68f234-2044-11e7-81dd-e75493fbeb67.png)

If you don't have the ability to use that one, I'd use the curved one you suggested initially, like the one on the left.

**Comment by aesculus** [comment]
OK. Now back to the real subject. Adding the single waypoint to the calendar. 

That is not so hard. And it's not too hard to remove it too when the trip gets deleted since it will come with the ugly code #37 .

It is going to get real hard and confusing though if I add this to the auto chargers. Is it OK if it's only for manually added/required chargers?  

What about destinations, especially or pseudo segment destinations?

Anyway the implementation of this may be a bit of a challenge so stay tuned.

**Comment by EVGrokker** [comment]
How about making Share available for manually added waypoints, Origins and Destinations? (Destinations could be segment or final).

Here's how I'd see using this:
- You and I agree to meet at a waypoint for some activity. I share the waypoint with you.
- I'm visiting a friend, and I want him to see what time I'm expecting arrive, with some fancy eye candy generated by my cool EVTO app. I email him my Destination waypoint (his house), with my arrival time embedded.
- I've previously planned an EVTO multi-stop route, and I want the car to guide me to it. I add it to my calendar, which then gets synced with the car, and I can select it.

I'm fine with not enabling the feature for auto-charge stops.

I do have issues with the code attached to the calendar entry, detailed in #37. We can discuss those there.

**Comment by aesculus** [comment]
This sounds like two things:
- sharing a waypoint with someone - maybe not an EVTO user? How should that be done? Calendar email invite?
- adding a waypoint to your devices calendar so you can navigate to it

The later is already done via the calendar feature for the entire segment so it does not sound like that is really needed here and is redundant.

I think I might be able to do the first via an email calendar invite. Needs some investigation.

**Comment by aesculus** [comment]
I have added the new icon disabled to test the look and fit.
V1.1.4 (2)

**Comment by EVGrokker** [comment]
If you decide to revisit the top row icon placement, putting the heart icon on the right side to match the car layout, I'd suggest putting '?' in the top left corner.

**Comment by aesculus** [comment]
We need to revisit this issue again.  It's been awhile.

My biggest concern now is that I have no place to put this feature on the Waypoint Inspector.  I cannot use the right top corner as it was a problem in Android I think.  At least one of the device types thought it was a click to a hidden button below.  Google is obviously looking at a touch to an area vs an object.

Oddly enough I never get any questions of comments about the calendar interface. Either people are not aware of it or don't use it. I think it's a great feature and I constantly have my phone calendar leading the way for my stops whenever I get in the car, EVTO derived or not.

**Comment by EVGrokker** [comment]
This is still very much on my wish list for the next release. I've just been staying away from it while you've been working on server tuning issues.

When you're ready to focus on this, let me know so we can drill down. Issue #37 is a major component.

**Comment by EVGrokker** [comment]
>My biggest concern now is that I have no place to put this feature on the Waypoint Inspector. I cannot use the right top corner as it was a problem in Android I think. At least one of the device types thought it was a click to a hidden button below. Google is obviously looking at a touch to an area vs an object.

I thought the placement of the export icon was already resolved, since there's an inactive placeholder for it in the third position. You added it 4/13 in the comments above.

**Comment by aesculus** [comment]
That got killed when we found out we ran out of room on the tiny iPhone SE (basically and iPhone 5) 320px wide.

**Comment by EVGrokker** [comment]
I'm confused. I'm looking at a six-icon button array in the Waypoint Inspector in v 1.2.0 (36), including an (inactive) export icon in position 3. Are you saying that you removed it from smaller phone-sized devices, but left it in place for larger phone-sized devices?

In reviewing the comments above, I don't see anything about layout on a smaller screen being a problem. Did we discuss that in another issue elsewhere?

![exporticon](https://user-images.githubusercontent.com/26678403/27002192-1818f8c6-4d98-11e7-8fba-1491681c07a9.PNG)

**Comment by aesculus** [comment]
Nevermind :-)

**Comment by EVGrokker** [comment]
A thread on TMC requesting the ability to export individual address (waypoint) to car:
https://teslamotorsclub.com/tmc/threads/sending-addresses-from-phone-to-car.84572/

**Comment by aesculus** [comment]
Before I attack this I want to make sure it is still needed.  What is the logic again for only exporting a single waypoint instead of a segments waypoints?

**Comment by EVGrokker** [comment]
The original thinking was that if you were actively driving a route on the in-car T nav system, and wanted to add a waypoint sourced from EVTO, you could send the single waypoint from EVTO to the calendar, then fetch it from the in-car UI to add it as a detour to the current route.

The other option (send via mail/message) would be to share a single waypoint with someone. For example, you and I are meeting up at an unfamiliar location. Rather than sending me a written description that you type in, you can export the waypoint into a mail message with all of the info already included.

**Comment by aesculus** [comment]
I think the later makes sense, and matches the icon too.  

The former should actually be covered in the existing feature. BTW if you added a new waypoint all the other calendar events would be wrong and need to be refreshed which is covered by the app today. If you Add Calendar again then it first deletes all existing waypoint events and then applies them again based on new information.

So should I proceed with the email thing?  Can you post a shell of what type of info you would like in the email?  Note this is done via the Segment Details menu right now for the entire segment if you want to see an example.

**Comment by EVGrokker** [comment]
For an email export, I'd see the name, address, and arrival time as the minimal relevant info to be contained in an email.

I would format the title of the email as `Waypoint from EVTO`, with the formatted content:

`<waypoint name>`
`<waypoint street address>`
`<waypoint city>`

`Arrival: <waypoint arrival time>`

For example, if I were exporting the Ellensburg Supercharger waypoint to you (snapshot below), the body of the email would be simply:

<hr/>

Ellensburg Supercharger
1620 Canyon Rd
Ellensburg, WA

Arrival: 9:42 am

<hr/>

If the user wants to append additional information, they can easily add to the content, much the same as the way a Feedback report is prepared.

![waypointinspector](https://user-images.githubusercontent.com/26678403/28490404-7fbe8daa-6e96-11e7-8b06-ab2815eb8473.PNG)

**Comment by aesculus** [comment]
> If the user wants to append additional information, they can easily add to the content, much the same as the way a Feedback report is prepared.

Do you mean I should provide a popup dialog like the Feedback Report to prompt them for any additional attributes or that they can fill them in themselves in the email message?

**Comment by EVGrokker** [comment]
I was envisioning an email template like the Feedback report, since they'd also have to supply the recipient. And if they want to add anything to the content, they can easily do so before sending it.

Also, if possible, it would be nice to have the option to send a text message instead of an email using the native messaging app. On iOS, the Messages app is typically invoked from a share menu like this, I'm sure there's something similar for Android.

**Comment by aesculus** [comment]
I was trying to see if you needed the pre email dialog like the Feedback Report vs the direct email as in the Segment Details email.

The pre email dialog would allow the user to select additional items in the email but it's more work of course.

I can look into the sms option, but then you will want WhatsApp or something. :-)

**Comment by EVGrokker** [comment]
I don't see any need for a pre-dialog, just a pre-populated email.

Meessaging options would be welcome. I assume there are URL schemes for messages and WhatsApp.

**Comment by aesculus** [comment]
This will require changing the underlying social media platform which today is solely email. See Issue #491.

**Comment by aesculus** [comment]
Implemented as an email message in V1.2 (63)

**Comment by EVGrokker** [comment]
v 1.2.0 (63)

A couple of fine-tuning suggestions:
- Change the Subject line to 'EVTO Waypoint ~Message~'
- When inserting the address, add a line feed after the street address. 

Current formatting:

```<waypoint name>```
```<street address>, <city>, <state>, <country>```

Proposed (note comma removed after street address):

```<waypoint name>```
```<street address>```
```<city>, <state>, <country>```

**Comment by aesculus** [comment]
I removed 'Message' in V1.2 (64). 

Unfortunately I have no control over the address as it's one item with no separate street, city, state and country.  Sometimes there are all the elements and sometimes not. It's just one big string.

**Comment by EVGrokker** [comment]
I realize that the formatting and content is unpredictable, but what if you were to apply a regex to split the content at the first comma, which would normally be the end of the street address component? It seems like that should almost always work.

**Comment by aesculus** [comment]
I can do that. The word 'almost' is probably correct.

**Comment by aesculus** [comment]
New line added in V1.2 (65)

**Comment by EVGrokker** [comment]
The export icon looks grayed out (disabled) compared to the other button imagery in the dialog. Can you darken it to match the others? I think it could also be moved up and slightly to the left to center it more. It appears that there's a gray ring around it, like the question mark icon, but I think the appearance should be more similar to the eye and scissors images on either side, which don't have the gray ring.

![export](https://user-images.githubusercontent.com/26678403/28752701-12a8b13e-74e3-11e7-9d52-dbe56fea7fbe.PNG)

**Comment by aesculus** [comment]
Since we changed the scope to email vs a calendar upload I just changed the icon to a email icon so it's more clear and matches the other icons better. V1.2 (67)

**Comment by EVGrokker** [comment]
If/when you add the option to share the waypoint via messaging (#491) you will need to change the icon back to something generic, like the export icon, with a pick list of options.

If you think that you might add additional waypoint sharing options in the future, I'd suggest keeping the upward arrow image, then displaying a dialog similar to the Favorites list. At this time, it can contain a single option, 'Email', but would additionally have 'Messages', 'WhatsApp', 'Twitter', 'Facebook' in the future. Those selections could be controlled by a group of checkboxes in Settings, but for the moment, there's no need to add that as long as there's only one option.

**Comment by aesculus** [comment]
Then the icon should be this:

![share_icon](https://user-images.githubusercontent.com/283364/28786391-f29939d6-75cd-11e7-91a2-5a7d24bb5279.png)

**Comment by EVGrokker** [comment]
You can make the case that the 'one node splitting to two' can be construed as sharing, but it's not at all consistent with any UI imagery that the user would be familiar with (at least not on iOS). I'm still in favor of a traditional sharing icon to cover all anticipated use cases.

**Comment by aesculus** [comment]
OK. My Android roots were showing.  They use different icons for the same purpose.

**Comment by aesculus** [comment]
In 1.2 (69) both platforms have their own specific icon for sharing. Lets see how we deal with this in the help file. :-)

**Comment by EVGrokker** [comment]
If you'd rather use a single icon for sharing, I'm OK with the node splitter.
