### ISSUE TITLE
'Retrieving Supercharger Data' occurs as frequently as every 10 seconds 

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#119]
In some conditions, the 'Retrieving Supercharger Data' popup occurs 5-6x per minute without any user activity. I disabled location services in both the app and device settings, force-quit the app and restarted, and the behavior was as expected, no frequent popups. 

This is more than a UI annoyance - it costs battery and server hits.

**Comment by aesculus** [comment]
Never seen this before. It should only happen once when the app starts. I can look at the logic and see why this might continue just to be sure.

Another enhancement I can make is to only check weekly, the minimum frequency that I update the chargers. At worse case a user might be missing a charger for a week.

**Comment by EVGrokker** [comment]
I'm also seeing it with location services disabled.

**Comment by aesculus** [comment]
It has nothing to do with location services. When the app starts up it checks with the server to see if the supercharger file has been updated. If so it downloads the newest one and caches it.

So the biggest hit it is supposed to have is a quick message with the last file date and then an OK response or if needed, a 500k file comes back.

**Comment by EVGrokker** [comment]
I haven't seen this with v 1.1.3 (4)

**Comment by aesculus** [comment]
OK. Open it up again if it shows up. I am going to do one tweak here today. I am going to wait to check users location after this supercharger fetch. Perhaps the two are meddling with each other.

**Comment by EVGrokker** [comment]
I'm seeing this again with 1.1.13 (10).

**Comment by aesculus** [comment]
I did not touch that area I promise

**Comment by EVGrokker** [comment]
This might be a connectivity issue. I'm currently in a hotel with slow wifi and 1 to 2 bars of signal strength. I had an email message that wouldn't send, so I turned off wifi to use cellular instead. The mail message sent immediately. I returned to EVTO and it appears that I'm not seeing the frequent attempts to load supercharger data. Maybe you could track how many attempts you've made, and after a few failed, display a popup telling user they have poor connectivity, then quit trying during the time that EVTO is active. Next time the app is activate, try again.

**Comment by aesculus** [comment]
OK. Odd that I really on do check one time to my knowledge but obviously something is causing it to repeat. I will pursue it. I do agree it's a connectivity issue.

BTW I know this issue happens in the IAP area and I have a counter there.

**Comment by EVGrokker** [comment]
I haven't seen this behavior recently, closing for now.

**Comment by EVGrokker** [comment]
I'm seeing the "Retrieving Supercharger Data" popup again. This seems to happen in the following scenario:
- EVTO is open with a calculated route
- User switches away from EVTO to another app
- User returns to EVTO

**Comment by EVGrokker** [comment]
Here's another sequence that seems to trigger overly-frequent fetches of the supercharger database:
- New Route, Seattle-Santa Barbara, Manual.
- With the entire trip shown on screen, touch the lighting bolt button.
- Not every time, but this action seems to trigger the fetch as well.

**Comment by aesculus** [comment]
I never tried going away from the app and back again.  I will try it and see what happens.

The toggle of the lightening bolt should not do anything other than load the chargers already fetched. Are you sure it says "Retrieving Supercharger Data" and not just blank spinner? If so this is a bug and I could not find it in the code, but I can put a trap in to test for it. I did change the message that now says "Loading Superchargers" just so it's more clear.

The only times it should fetch are:
- When the apps starts up it will check if the chargers are current and if not reload the chargers
- You made a change to settings - probably could make sure you changed the region but ...

**Comment by EVGrokker** [comment]
I'm definitely seeing multiple loads within a session in the latest release, similar to the original issue. Not sure what's triggering it, I was just guessing about losing and regaining focus.

**Comment by EVGrokker** [comment]
v 1.2.0 (37)

I haven't seen this behavior in quite some time.

**Comment by aesculus** [comment]
It seems to be somehow related to the network. But not necessarily bw related. Maybe latency?

**Comment by aesculus** [comment]
OK. I
