### ISSUE TITLE
After fresh install, Main screen Plan Trip button does not open Plan Trip dialog

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#123]
1) Fresh install of 1.1.3 (3)
2) Complete Getting Started screens
3) Touch **Plan a Trip** button 
4) **Hint** dialog appears explaining how to add waypoints and optimize routes.
5) Touch **Got It**
6) **Hint** dialog dismisses, but Plan Trip dialog does not appear.

**Comment by aesculus** [comment]
I have disabled the Hint panel and the app now opens the New Trip dialog automatically if no trip is current.

Version 1.1.3 (4)

I think this dialog is redundant with the change we made to Auto/Manual in the New Trips panel. If you think the Hint panel is still needed, reopen this item.
