### ISSUE TITLE
Specifying destination charger when planning new trip is ignored

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#125]
v 1.1.3 (3)

1. Plan a Trip: Origin: Seattle WA, Destination: Sand Dollar Inn, Moclips WA.
2. Destination charger type: NEMA 14-50.
3. Enable Out & Back 
4. Calculate

After trip calculates, touch segment 1 destination pin. Charger Type shows as No Charger.

**Comment by aesculus** [comment]
Fixed V1.1.3 (4)

**Comment by EVGrokker** [comment]
Not fixed in 1.1.3 (4).

1) Plan trip from Seattle - Sand Dollar Inn, Moclips WA
2) Destination charger type: NEMA 14-50
3) (Fails with Out & Back checkbox setting enabled or disabled)
4) Calculate
5) Touch destination pin, Edit. No charger info.

**Comment by aesculus** [comment]
I reopened this again. In last nights test it was there and now it's not. I swear. :-(

**Comment by aesculus** [comment]
I wonder if I compiled before I saved the file? Anyway I tried it again tonight in V1.1.3 (5) and it seems to be working. Hopefully it will work for you too.

**Comment by EVGrokker** [comment]
It's partially working. Here's what's happening.

Create an Out & Back from Seattle to Sand Dollar Inn, Moclips WA. Set the destination charger type to NEMA 14-50. Calculate the route.

In the return segment, the origin charger type is correctly set as NEMA 14-50. However, in the outbound segment, inspecting the destination waypoint info dialog shows no charger.  

Obviously, EVTO is correctly calculating the trip, factoring in the destination charger. But the user looks at the destination pin and sees no charger, which looks like an error.

**Comment by aesculus** [comment]
> Obviously, EVTO is correctly calculating the trip, factoring in the destination charger. But the user looks at the destination pin and sees no charger, which looks like an error.

It's worse than that. The optimizer wiped out the charger. :-(

Fixed in V1.1.3 (6)
