### ISSUE TITLE
Enhancement: Show arrival/departure battery state for charging stops

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#126]
Example trip:
[sqwuvc5vwfinu736tkfuu] PIN [1234]

Load trip, select segment 1. Touch supercharger icon. Note that text says 'Charge to:' value of 80%. Propose enhancing battery image to show arrival SoC as solid green (as it current is), and incremental departure SoC as striped green. Change numbers below battery to '49% ⌁ 80%'.

(Please ignore the quick modeling of concept, just enough to get the point across.)

![img_0322](https://cloud.githubusercontent.com/assets/26678403/24657217/4334222e-18fa-11e7-9484-fd3299453eb6.PNG)

**Comment by aesculus** [comment]
While a cool idea, I already use two phases of the charger battery for another purpose:

Check out the Return to Last Charger feature.

Plus I also have the Reserve for Local travel adding a color.

**Comment by EVGrokker** [comment]
I'm happy to use the same design scheme for all presentations of a split battery status. I think seeing the inbound/outbound SoC at a glance would be a nice design enhancement.

**Comment by EVGrokker** [comment]
The fact that there are multiple contexts for presenting split battery status doesn't create a problem as long as it's clear from the context what the two values represent.

**Comment by aesculus** [comment]
Perhaps, but we would need a matrix to make sure we are not trying to do 3 at once. I already have a bit of an issue when one level is less than another but the order is wrong. For example I like to present the SOC in order of arrival. So if the first one is 60% and the second one is 15%, the text is OK but the 60% overshadows the 15%.  I am pretty sure I still have some issues here that you will notice later. :-)

**Comment by aesculus** [comment]
>I'm happy to use the same design scheme for all presentations of a split battery status. I think seeing the inbound/outbound SoC at a glance would be a nice design enhancement.

I agree. Something to think through. Maybe add it to your V1.2 list

**Comment by EVGrokker** [comment]
v 1.2.0 (30) 

I find myself missing the split battery display in the waypoint inspector for non-destination charging stops. A non-charging waypoint doesn't need it.

If possible, I'd propose using the zap icon the split the arrival and departure SoCs at charging stops. I have a crude version of that above, but the orientation of the zap is wrong.

If it's not possible to use the zap as a separator, I'd stick with the ' + ' separator like the Destination Reserve formatting. The difference in the color and style of the upper section of the charging is adequate to explain the meaning.

Also, note that the battery outline and the fill are not aligned.


![chargetime-batterylayout](https://cloud.githubusercontent.com/assets/26678403/26762215/501aff84-48f3-11e7-8ad8-e5b2ac4abb90.PNG)

**Comment by aesculus** [comment]
Would you accept this?  I think the zap icon will screw up my algorithm for the battery and this was easy.

![image](https://cloud.githubusercontent.com/assets/283364/26770812/b3086124-496e-11e7-894e-b1a6b8984915.png)

**Comment by EVGrokker** [comment]
Looks good.
