### ISSUE TITLE
Segment Details screen: Improve visual indication of selected waypoint, typo

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#127]
1. When selecting a waypoint from the list, the light gray background to indicate selected is very subtle. Suggest either more contrast, or a darker border around selected waypoint.

2. The list of segment waypoints should be titled 'Segment Waypoints', not 'Trip Waypoints'.

**Comment by aesculus** [comment]
I fixed the typo.

The selected item is consistent with the other lists in the app. If you want them changed universally make a new issue to that effect and I will look into it. Might not be easy or worth it.
