### ISSUE TITLE
Main screen Help comments

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#128]
1. 2nd paragraph: '…additional fine-tuning of ~~projected~~ predicted power consumption.'

2. 2nd paragraph: 'With EVTO ~~installed on your mobile device~~, you can plan trips on your mobile device at your convenience, wherever you are.'

3. Main screen Menu Items|Settings|Routing Preference: dagger should be superscript

4. Main screen Menu Items| Compare Trips: footnote dagger should be superscript

**Comment by aesculus** [comment]
Fixed in V1.1.3 (4)
