### ISSUE TITLE
Fix ugly message when location in device is set to Ask.

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#13]
iOS issue. Right now it shows cryptic stuff.  Not sure what version of iOS Ask is supported on. V10 has Never and Allow.

**Comment by aesculus** [comment]
This happens on a fresh install.

**Comment by EVGrokker** [comment]
I'm not seeing any unusual behavior with respect to Location services in 1.1.4.

**Comment by aesculus** [comment]
Just wait. :-)
