### ISSUE TITLE
Plan Trip|Reverse Route 

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#130]
When reversing a segment, the dialog 'Confirm Reverse' displays **Cancel** and **Copy**.

1. The **Copy** button should be labeled **Reverse**.
2. The current segment should not be copied and added to the Current Trips list. That's appropriate for Copy Segment, but Reverse should simply reverse the trip without duplicating it.
3. The dialog text should read 'The current segment will exchange the origin and destination points and recalculated, reversing the route.'

**Comment by aesculus** [comment]
> The current segment should not be copied and added to the Current Trips list. That's appropriate for Copy Segment, but Reverse should simply reverse the trip without duplicating it.

It does it this way for non subscriptions but for a subscription I was copying and reversing.

**Comment by EVGrokker** [comment]
This seems like an unnecessary complication between Standard and MTS versions.

There's already a copy mechanism available. If a user wants to create a separate version of the route, but reversed, they'd simply copy the route, then reverse the copy. 

If you maintain separate behavior between Standard and MTS, you'd also need to have different dialogs describing the different behavior. Assuming that users graduate from Standard to MTS, changing the behavior of Reverse (from in-place in the Standard version, to copy-and-reverse in MTS) would be a UX inconsistency.

**Comment by aesculus** [comment]
> changing the behavior of Reverse (from in-place in the Standard version, to copy-and-reverse in MTS) would be a UX inconsistency.

Isn't there already an inconsistency and this just adheres to it?

In a non subscription you really only ever have one trip.  In this case I am replacing that one trip with it's reverse.

But with a subscription you can have multiple trips so I am basically copying the trip and reversing the route, still keeping your original intact because you have the ability for multiple trips.

Plus this way saves an extra step in that they don't have to do a copy and then reverse.

**Comment by EVGrokker** [comment]
'Copy' is well understood functionality independent of EVTO. A user who wants to create a copy of a route (technically, duplicate) would immediately see how to do that from the menu selection.

'Reverse' only implies swapping origin and destination.  

I find my Current Trips becoming very cluttered, so much so that I need to go and clean it out regularly. Arguably, that's because I'm testing lots of sample routes, but still, I'd prefer to only have routes that I actually intend to keep over and reuse over time.

We can agree to disagree, and you get the final vote, but I'm firmly in the "don't replicate when reversing" camp.

**Comment by aesculus** [comment]
> We can agree to disagree, and you get the final vote, but I'm firmly in the "don't replicate when reversing" camp.

Maybe a poll. :-)

Lets ponder this one for awhile.

**Comment by aesculus** [comment]
Fixed in V1.1.3

**Comment by EVGrokker** [comment]
Thank you for implementing this. There is a minor tweak needed before closing this issue. 

1. Create a segment, Seattle to Moclips. The segment is now called 'Moclips'.
2. Reverse it. The segment is now called 'Moclips - Reverse'.
3. Reverse it again. The segment is now called 'Moclips - Reverse - Reverse'. Oops. 

Rather than implementing logic to look for a '- Reverse' suffix and removing it, I think it would make more sense to simply rename the segment based on its destination, as if the trip was originally created with those inputs. 

If the user copies (duplicates) the route, they can rename it as they please.

**Comment by aesculus** [comment]
Fixed in V1.1.4
