### ISSUE TITLE
Main menu|Feedback

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#131]
Dialog title: Should be 'Feedback Report' to match menu item, prefixed with same note icon.

Type of report: Comment
Include active trip: Not checked
Comments: <nice comments>

Touch **Prepare**

Dialog closes and returns to Main screen, but no further feedback. Did the mail go? I expected to see a prepared email, but nothing. If I reselect Feedback Report, everything I entered is still there.

**Comment by aesculus** [comment]
It's a bug. Will look at.

**Comment by EVGrokker** [comment]
Update, v 1.1.3 (4)
Email is now successfully composed, but the To: field is empty. Should be pre-addressed with support email address.

Also, suggest reorganizing content of email so that the user-composed content is at the top, and the app metrics are at the bottom.

**Comment by aesculus** [comment]
Now fixed in V1.1.3 (5) to include support@digitalautoguides.com in the mailto:
