### ISSUE TITLE
Edit Segment Details dialog, Time and Date fields comment

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#132]
When touching either Time or Date fields, a spinner is displayed allowing user to change to a specific time or date. Two buttons are shown, 'Clear' and 'Done'.

Why would a user want to clear time or date?

**Comment by aesculus** [comment]
My iPad only shows a Clear button.  Can you attach a picture?

>Why would a user want to clear time or date?

??? I did not make the control. :-(

**Comment by EVGrokker** [comment]
![img_0323](https://cloud.githubusercontent.com/assets/26678403/24665621/ccb022a6-1912-11e7-880d-b47298a4aebb.PNG)

**Comment by aesculus** [comment]
I'll see if I can hack the control to remove the Clear and Done buttons.

**Comment by aesculus** [comment]
So far none of the hacks for this work. It seems to be a defined function in iOS and I can't override it. Note the iPad only has a Clear button.
