### ISSUE TITLE
Plan Trip screen enhancement: Touching title area open Edit Segment details dialog

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#134]
Propose that touching the segment name in the title bar is functionally equivalent to selecting the 'Edit Segment Details' item in the Plan trip menu.

**Comment by aesculus** [comment]
I tried this quickly and could not get it to work. Will require a lot more time.

**Comment by aesculus** [comment]
Too much effort for little gain.
