### ISSUE TITLE
When editing waypoints, 'Minimum SOC (%)' is ambiguous

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#14]
I find the ‘Minimum SOC (%)’ label ambiguous. Is it the SOC at arrival? Departure? Why is it minimal? Under what circumstances would the minimum not be met? 

I think changing the label for the slider would help remove some of that ambiguity.

A couple of possible alternatives for en-route waypoints:
Minimum Departure SOC
Minimum SOC at Departure
Departure SOC
Preferred Departure SOC

When destination info is displayed, maybe 'Arrival SOC'.

**Comment by aesculus** [comment]
The app has been changed to Minimum Arrival SOC (%) in V 1.1.2

See if this is acceptable
![image](https://cloud.githubusercontent.com/assets/283364/24326643/03d8b34c-1170-11e7-8901-ec776fba6987.png)

**Comment by EVGrokker** [comment]
I suggest that the label ~~**Minimum Stop Time (min)**~~ be revised to **Minimum Stop Time (mins)**. Other than that change, the dialog looks good.

**Comment by aesculus** [comment]
Done
