### ISSUE TITLE
Multiple routes shown after Plan Trip with Auto Waypoint Charger Selection enabled

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#141]
v 1.1.3 (4)

1. Plan Trip: Seattle WA - Sand Dollar Inn, Moclips WA
2. Waypoint Charger Selection: Auto
3) Calculate

After optimization, 3 routes are displayed. Presumably, since we selected Auto, there should only be one route shown. 

Attempted manually selecting Optimize Segment, same three routes are shown.

Are multiple routes shown because a charging stop is not required to make it to the destination, so a route is not forced?

If Auto is selected, recommend that only one route is displayed, presumably fastest/shortest.

This issue may be related to #138

**Comment by aesculus** [comment]
It actually has nothing to do with any of the above. In Google Maps you can either have it give a primary route or multiple possible routes.  I had selected the later. You can select each route to see the driving time.

But this probably causes some confusion. If you optimize and no charges are added it still shows up to three routes. If a charger is added after optimize it will just show one route. But interestingly it might not be (but is most likely) the primary route shown before optimize.

So do you think I should just turn this off and only show one route?

**Comment by EVGrokker** [comment]
At best, this is confusing. EVTO has done a power consumption prediction for one of the routes, but we don't know which one. I can touch individual routes to see the estimated time, but that doesn't select the route to be the one I want to take. If there were a mechanism to show the available the routes, let me pick one by touching it, then recalculate based on my selection, this would be fine, even preferable. If you can't do that, then you need to only display the route for which the power consumption applies. If the user wants to force a different route, they need to do so manually by inserting a via waypoint.

**Comment by aesculus** [comment]
> If there were a mechanism to show the available the routes, let me pick one by touching it, then recalculate based on my selection, this would be fine, even preferable.

Write this up as a new feature. Probably 2.0

For now I am removing this multi-route thing in V.1.13 (6)
