### ISSUE TITLE
Enhancement: Add Favorite option in Edit Waypoint dialog.

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#142]
The current process to make a waypoint a favorite is tedious. Suggest adding a checkbox or touchable heart icon to Edit Waypoint dialog allowing user to indicate this waypoint is a favorite.

**Comment by aesculus** [comment]
I might be able to put the touchable heart in the header of Add/Edit Waypoint. It would work exactly the same as the heart in the waypoint InfoWindow dialog.

>The current process to make a waypoint a favorite is tedious

Can you explain why it is tedious? You just select a waypoint from the map and toggle the heart. No need to Edit the waypoint at all.

**Comment by EVGrokker** [comment]
Considering the steps required to create a favorite:

1. I want to create a 'Home' favorite. In order to do so, the waypoint needs to exist in the context of a route. 
2. Create a route with my home address as the origin, and a destination.
3. After the route is created, open the origin waypoint, touch Edit.
4. Edit the Name field to 'Home', Save.
5. Touch origin pin again.
6. Touch Heart to make it a favorite.

You should be able to set the Favorite status at step 4 while renaming to 'Home'. Having to exit and reopen the waypoint dialog pin is tedious.

I am not suggesting that you remove the ability to Favorite from from the waypoint dialog, that's useful for waypoints that you don't need to rename. But for waypoints with custom names, or with charger options, being able to Favorite them from the edit dialog would be intuitive and useful.

**Comment by EVGrokker** [comment]
If you're skeptical about the tediousness of the steps required, please try it yourself from scratch, with the objective of creating a 'Home' favorite with a charger.

**Comment by aesculus** [comment]
OK. I get it.

>Edit the Name field to 'Home', Save.

There used to be a way to have a name for the origin when you made a new trip but that got confusing and it went away when I added automatic origin location.

This whole favorite thing needs work clearly.

**Comment by EVGrokker** [comment]
See UI suggestion in issue #162 for an approach to implement a UI allowing user to add current address as a saved waypoint.

**Comment by aesculus** [comment]
Implemented in V1.2 (57). I added a heart icon to the header so you can toggle the favorite on/off. It will also toggle the heart icon on the Waypoint Inspector at the same time since the only way you can get to the Edit Waypoint is via the WP Inspector.

When the dialog is for a new waypoint, the heart is disabled.

**Comment by EVGrokker** [comment]
v 1.2.0 (57)
(This comment was posted in #162, replicated here as that was a different issue)

<hr/>
The alignment of the heart is incorrect on an iPhone 7+. See screen capture at bottom.

I'm uncertain about implementing this feature this way. There are two hearts on the screen, one in the title bar, one to the right of the address field. It's not obvious which does what.

There's another issue here as well. What is the proper behavior for a required supercharger? Should it be possible to apply a heart to a supercharger, as well as give it a thumbs-up?

Proposal: Suppose that touching the heart at the end of the address field brought up the list of existing favorites, plus a line at the top of the list saying something to the effect of "add this address as a favorite". That way there would only be a single heart on the screen, removing any ambiguity.

Proposed sequence to add a favorite:
- User types and selects validated address
- User touches heart to right of address field
- '~~Choose Location~~' 'Favorites' dialog is displayed, with current address at the top of the list, prefixed with a '+' icon to add this waypoint to the favorite list.

![chooselocation](https://user-images.githubusercontent.com/26678403/28265483-3570c3b8-6aad-11e7-983e-3c0c427a0b0c.PNG)



<hr/>

(This image is supplied for reference only, as the heart icon is misaligned.)

![favoriteheart](https://user-images.githubusercontent.com/26678403/28264871-351f4b3a-6aaa-11e7-9e8d-14ceb9e011a0.PNG)

**Comment by EVGrokker** [comment]
v 1.2.0 (58)

The heart is now aligned, but I have some concerns about this implementation.
1. The heart is blue, which makes it very hard to see against the gray background of the header (for me, at least).
2. I'm uncomfortable about adding a second icon to the otherwise non-interactive header bar.
3. After trying this implementation, and reconsidering my earlier proposal to integrate adding a favorite into the favorites popup (invoked by touching the heart to the right of the address), I think using the existing heart button to open the list, and adding it from there, would be preferable for simplicity and ease of explanation.

**Comment by aesculus** [comment]
>The heart is blue, which makes it very hard to see against the gray background of the header (for me, at least).

I can used a different color or brighter blue

>I'm uncomfortable about adding a second icon to the otherwise non-interactive header bar.

Can't comment on your feelings. :-)

>After trying this implementation, and reconsidering my earlier proposal to integrate adding a favorite into the favorites popup (invoked by touching the heart to the right of the address), I think using the existing heart button to open the list, and adding it from there, would be preferable for simplicity and ease of explanation.

This was easy to do and your proposed idea much more difficult. I also don't think the proposal is very intuitive in that the little heart is where you go to GET addresses, not add them.  And when I first looked at it I just thought the + icon was different and was part of Add Waypoint instead of adding to a favorite.

**Comment by EVGrokker** [comment]
At a minimum, I'd suggest moving the heart to the right side of the header bar. But I'll stick with my recommendation to integrate the function with the existing favorites list.

**Comment by EVGrokker** [comment]
I think making the heart empty (an outlined frame) for unselected, and filled (black) for selected would solve the visibility issue with the heart located in the header. Black matches the color of the listed waypoints in the Favorites list, and the framed appearance is the same as in the Waypoint Inspector, so there's some visual consistency.

**Comment by aesculus** [comment]
I tried to mirror what is going on in the Waypoint inspector for both look and feel.  When I tried the outline it seemed to get lost. That is why I went with the white background instead of the outline.

I brightened up the color some. See if this helps.

**Comment by EVGrokker** [comment]
v 1.2.0 (59) 

The heart is more visible in the current release.

However, touching the heart after validating the address (in the Add Waypoint dialog) apparently does nothing.

**Comment by aesculus** [comment]
Correct. It is grayed out in the Add Waypoint dialog since you can only make a waypoint a favorite and it's not a waypoint yet.

**Comment by EVGrokker** [comment]
I'm confused. The intent of the issue was to make it possible to favorite an added waypoint during its creation. Even if the user declines to add it to the route, touching the heart to make it a favorite is still a valid action. Why display the heart in the dialog if you don't intend the user to be able to use it?

**Comment by aesculus** [comment]
I'll have to rethink the approach a bit then.  Right now the heart acts as a toggle in real-time.  If I do it for a new waypoint I have some issues:
- New waypoints don't have a name or address until the user enters an location and it's validated
So I will need to have a special version of this for new waypoints vs existing (it's the same dialog so it will require some trickery) that basically saves the desire for making it a waypoint until after Save completes.

**Comment by aesculus** [comment]
This was fixed back in V1.2 (61). It now supports saving New Waypoints as favorites

**Comment by EVGrokker** [comment]
Updated help text (#170) to describe functionality of additional heart button.
