### ISSUE TITLE
Conflict between destination pin color and destination waypoint dialog battery icon

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#143]
In the image below, the Moclips WA - Bend OR segment shows a green destination pin, but the waypoint info dialog shows a yellow battery.

I'm not sure which is correct, but the colors should be consistent.

![img_0328](https://cloud.githubusercontent.com/assets/26678403/24704218/8c4308c4-19bb-11e7-99ca-7455c1388f73.PNG)

**Comment by aesculus** [comment]
This is normal. Pushpin should show the rule we spelled out in the help. It's dependant on your settings.

Battery is always set to match what the car has: greater than 20% is going to be green. Red shows up at 10%. Otherwise yellow.
