### ISSUE TITLE
Waypoint info dialog: Capitalization of US states should always be all caps

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#144]
In the image below, the trip segment was defined with Bend OR as the destination. When rendering the waypoint info dialog, the state abbreviation should be properly capitalized as 'OR'.

![img_0328](https://cloud.githubusercontent.com/assets/26678403/24704325/0384b5ae-19bc-11e7-8402-8a4500fdc637.PNG)

**Comment by aesculus** [comment]
Fixed in V1.1.3 (5).

I had done some case capitalization for some reason which affect states. Not sure why I did that at this point but if it comes back again I will have a record of why in this thread.
