### ISSUE TITLE
Opening/dismissing waypoint dialog always invokes Segment summary list

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#145]
v 1.1.3 (4)

In the Plan tab of the Plan Trip screen, touching a waypoint to open the Waypoint info dialog, then touching outside the dialog to dismiss it, always opens the Segment Summary dialog. This should not happen if the Segment Summary list was not previously displayed.

I'm guessing this is related to the resolution of an earlier enhancement to the Segment summary dialog, when touching an individual waypoint would present that waypoint info dialog without the Segment Summary list, then closing that waypoint info dialog would redisplay the Segment Summary list.

**Comment by aesculus** [comment]
Odd, but I am not seeing this behavior. Are you just touching the map background to dismiss the Infowindow?

It would be related to the change that was made as noted.

**Comment by EVGrokker** [comment]
I am dismissing the waypoint info dialog by touching outside the dialog boundary on the map background.

**Comment by aesculus** [comment]
I can look at the code in this area but not able to duplicate this on three devices. Have not tried the iPhone 6S+ yet as it's not at hand.

**Comment by aesculus** [comment]
Just for the heck of it can you give me the share info for this trip? Or does this do this for all of your trips? And has it always done this or are you just seeing this behavior recently?

**Comment by EVGrokker** [comment]
I think I understand what's causing this behavior.

If you calculate a route, then touch any waypoint, it's dismissed when touching outside the waypoint info dialog, as expected.

Now, select Segment Summary and touch any waypoint. The waypoint info dialog is shown. Tapping outside the waypoint info dialog closes it and returns to the Segment Summary, which is correct behavior. Tap outside the Segment Summary to close it. 

Now, tap a waypoint on the map. The waypoint info dialog is shown. Now, tap outside to close it. The waypoint dialog is closed, but the Segment Summary is redisplayed.

You have a flag indicating whether or not to show the Segment Summary dialog after closing a waypoint dialog which is not being cleared after closing the Segment Summary dialog.

**Comment by aesculus** [comment]
>You have a flag indicating whether or not to show the Segment Summary dialog after closing a waypoint dialog which is not being cleared after closing the Segment Summary dialog.

Yeah. I think I found this out when I was trying to fix something else. I used a flag that was supposed to be the index but forgot its from 0 so a 0 had two meanings. It's now been set to -1 for nothing so hopefully this fixes it. If not, open it back up again.

V1.1.3 (6)
