### ISSUE TITLE
Out & Back without destination charger does not include Auto charger selection

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#147]
1) New Trip: Seattle WA to Moclips WA, no destination charging. Auto charger assignment

Final destination (segment 2) shows -25% SoC upon arrival.

There is a supercharger along the route (Aberdeen WA) that could be included.

**Comment by aesculus** [comment]
I am not seeing this behavior using the Sand Dollar Inn.  First segment gets to destination with ~40%. Next segments charges at Aberdeen to 64% and then back to Seattle with 15% SOC on arrival.

Share the trip if you see otherwise.

**Comment by EVGrokker** [comment]
ID [7x3dm5n5athagzoofpr5do] and the PIN [1234]

**Comment by aesculus** [comment]
Nope: But just to be sure.  Until V1.4 comes out (hopefully), you will have to optimize each segment in order from start to finish if you make any upstream changes. Ie if you change segment 3 or a 5 segment trip you will have to optimize 3,4,5 in that order. Hence the need for our white destination icons.

Again my goal for V1.4 is to press Optimize once for the entire trip.
