### ISSUE TITLE
When editing waypoints, 'Minimum stop time (min)' is ambiguous

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#15]
I think the intent is “I expect to spend at least x minutes at this Waypoint while charging, even if that’s more than needed to reach my desired SOC.”

So maybe it would be adequate to simply say ‘Stop Time (mins)’ or 'Planned stop time (mins)'?

**Comment by aesculus** [comment]
It's intended to be the minimum stop time. So if you want to stop for an hour and charging will require 30 minutes, the time would still be one hour.  However if your minimum stop time is 30 minutes and charging takes one hour, the estimated stop time would be 1 hour.

It just lets the app know you never want to leave before an hour is up no matter how much charge time is required.
