### ISSUE TITLE
Plan Trip help edits v 1.1.3 (5)

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#150]
Some edits required for the Plan Trip help menu:

**Automatic Waypoints**
Automatic waypoints are ~~defined by the optimizer and are charging waypoints~~ charging waypoints selected by EVTO.

**New Trip**
Enabling the 'This is an Out and Back trip' checkbox ~~(a Pro feature)~~† plans the trip…

Append '_†Pro version feature_' at the end of the section with same formatting as Main menu help.

**Add Segment**
Append dagger to title, should read **Add Segment**†

Append '_†Pro version feature_' at the end of the section with same formatting as Main menu help.

**Add Waypoint**

To use a frequently-used address stored as a Favorite, touch the black heart **to display the list of saved Favorites**. ~~and your~~ Select a favorite to load its address.

~~You can they reuse these waypoints as described above.~~

**Copy as New Trip**
Append dagger to title.
Append '_†Multi-Trip Subscription feature_' at the end of the section with same formatting as Main menu help.

**Comment by aesculus** [comment]
>Add Waypoint
To use a frequently-used address stored as a Favorite, touch the black heart to display the list of saved Favorites. and your Select a favorite to load its address.

Can you review this? It's supposed to copy the address, name and charger type. Note that this is related to your whole issue with favorites. Especially item https://github.com/aesculus/EVTO-App-Feedback/issues/27 which was fixed but I left open because of the whole Favorite issues.

**Comment by aesculus** [comment]
Can you take a stab at the Add/Edit Waypoint help. I will get a place prepared for it.

**Comment by EVGrokker** [comment]
> Can you take a stab at the Add/Edit Waypoint help. I will get a place prepared for it.

I will do so, I'll try to have something by tomorrow.

**Comment by EVGrokker** [comment]
> Can you review this? It's supposed to copy the address, name and charger type. Note that this is related to your whole issue with favorites. Especially item #27 which was fixed but I left open because of the whole Favorite issues.

Add Waypoint
_Inserts a waypoint into the current trip segment._ 
Enter a POI or an address, or touch the heart to display a list of previously saved Favorites. Selecting a favorite populates the name, address and charger type fields. You can also specify a minimum stop time at the waypoint, and the minimum SoC you'd like to arrive with. If the minimum SoC is achievable, EVTO will try to adjust previous charging stops to accommodate the SoC target specified.

**Comment by aesculus** [comment]
Done. V1.1.3.3 (6)
