### ISSUE TITLE
Opening Segment Summary while waypoint displayed should dismiss waypoint info

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#153]
1. Touch a pin to display its waypoint info
2. Touch menu to select Segment Summary
3. Waypoint info remains on screen.

The proper behavior would be to dismiss an open waypoint dialog when the menu is displayed.

**Comment by aesculus** [comment]
>The proper behavior would be to dismiss an open waypoint dialog when the menu is displayed.

But remember the summary screen is how you can get to each waypoint dialog and move the map. Every tap in the summary scrolls the map and opens the waypoint info.

**Comment by EVGrokker** [comment]
But if you opened a waypoint directly from the map screen, then select a menu item, any menu item, you're off on a new mission. Even though opening segment summary does indeed lead to a situation where user might be tapping waypoints to display their info, they should do so with a clean slate.

**Comment by aesculus** [comment]
OK. Got it.
Fixed in V1.1.3 (6)
