### ISSUE TITLE
Export Simple Google Static Map

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#156]
As an quick alternative to a real Google Map of the trip, create a static map that can show the trip even without a connection.  User might have to save or bookmark this in Google Maps. TBD.

**Comment by EVGrokker** [comment]
Does Google Maps have a cache feature for a given view? I seem to vaguely recall that this was an enhancement in the last year or so. Maybe only for the dedicated app.

**Comment by aesculus** [comment]
They have a static map that I can make. It contains the background for a certain bounds and any additional markers I add. I think the route too hopefully.

**Comment by aesculus** [comment]
I think this is still relevant in a different context. It appears some users have been using EVTO without a connection and it works with the exception of having no map background.

The SoC and Consumption charts still work but there is no map.  If there was a static map it could at least help the user visualize where they are going.

**Comment by EVGrokker** [comment]
What's your thinking here? To do a screen snapshot and save it to the user's photos?

**Comment by aesculus** [comment]
Well this is basically dead based on Google's licensing requirements. I read it again last night.

While I could create a static map using their api's (not trivial and would cost $) and they deliver it as an image, you are not allowed to cache the image. It can only be used on a webpage that is linked to Google in real-time.
