### ISSUE TITLE
Main screen layout issue 

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#159]
v 1.1.3 (6)

Notice in the attached image that 'Digital Auto Guides' is squeezed up against the device status bar. 

Suggest horizontal centering with menu hamburger.
 
![img_0338](https://cloud.githubusercontent.com/assets/26678403/24797631/f6af34a8-1b46-11e7-8e95-ca18f701f95c.PNG)

**Comment by aesculus** [comment]
Fixed in V1.1.3 (7)
