### ISSUE TITLE
Adding a waypoint by long-pressing map uses wrong address

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#160]
1. Create a New Trip: Seattle WA -  Moclips WA, single segment, Auto select.
2. I decide to add Aberdeen supercharger, but using the map interface.
3. Touch and hold below route line, between Astoria OR and I-5. 
4. Select Charger Type: Tesla Supercharger
5. Touch in Address field, type 'Aberdeen', select 'Aberdeen Supercharger', Save
6. Waypoint is added where I touched, not where I typed.
7. Touch waypoint icon, Edit to inspect waypoint address.
8. Note that address is correct, but displayed location is wrong.

Trip ID: [c6pixbxnqqrdj7ga8wtuit]

**Comment by aesculus** [comment]
Confirmed. Fixed in V1.1.3 (7)
