### ISSUE TITLE
Adding waypoint doesn't let me specify charger type

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#161]
v 1.1.3 (6)

1. New Trip: Seattle WA - Moclips WA, single segment, Auto select
2. Plan Trip menu | Add Waypoint
3. Charger Type field is grayed out, won't let me specify Tesla Supercharger

**Comment by aesculus** [comment]
Tried to duplicate this on the iPad and it works fine.  The Charger Type looks grey but when touched it brought up the spinner.

**Comment by EVGrokker** [comment]
I tried the steps outlined above again on iPhone and got the same result - unable to select charger type.

**Comment by aesculus** [comment]
I'll try it on the iPhone tonight.

**Comment by EVGrokker** [comment]
Still an issue in 1.1.3 (7)

**Comment by aesculus** [comment]
Did not get a chance on this yet. But keep me honest. :-)

**Comment by aesculus** [comment]
Just tried this on the iPhone 6+S using V1.1.3 (12).  Everything worked OK.
