### ISSUE TITLE
Add Waypoint dialog: behavior of Name field

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#162]
v 1.1.3 (6)

The behavior of the Name field in the Add Waypoint dialog needs some thought.

When first presented, the user sees 'Waypoint Name' (Name field) and 'Enter a name or address' (Address field), with the Favorites icon.

We expect them to either type in the address field, or select a favorite. We do not expect them to type into the Name field.

If they do type something into the Name field, with the intent of pre-naming a waypoint they're about to select, that won't work, because the Name field is overwritten after they specify an address in the Address field.

A couple of possible approaches:
1. Simply remove the Name field from the Add Waypoint dialog. If they want to rename the waypoint, they can do so from the Edit Waypoint dialog. 
2. Disable the Name field until after an Address has been entered. At that point, the Name field has been populated, and they can edit it.

Since previous issues have proposed allowing the user to create a Favorite from this dialog, I'd suggest option 2. 

With respect to allowing Favoriting from this menu, I'd propose that if an address has been entered into the Address field, and the user touches the heart icon, an item above all the other saved favorites would be 'Save this waypoint as a favorite' (or something more terse), which would add this waypoint to the Favorites list.

![img_0339](https://cloud.githubusercontent.com/assets/26678403/24798168/7baf420e-1b49-11e7-9f21-923de68595cb.PNG)

**Comment by aesculus** [comment]
I agree that this confusing. It needs to be revisited in context of the Favorites update. At least one person was affected by this.

So for now I am disabling it when Add but once the waypoint has been saved, it will be enabled again.

Fixed in V1.1.3 (7)

**Comment by aesculus** [comment]
I added a heart icon to the header so you can toggle the favorite on/off.

**Comment by EVGrokker** [comment]
v 1.2.0 (57)

The alignment of the heart is incorrect on an iPhone 7+. See screen capture below.

I'm uncertain about implementing this feature this way. There are two hearts on the screen, one in the title bar, one to the right of the address field. It's not obvious which does what.

There's another issue here as well. What is the proper behavior for a required supercharger? Should it be possible to apply a heart to a supercharger, as well as give it a thumbs-up? 

<hr/>

![favoriteheart](https://user-images.githubusercontent.com/26678403/28264481-58999fc2-6aa8-11e7-8d0a-fc218da3c5e5.PNG)

**Comment by aesculus** [comment]
I'll fix the heart position. It's a carryover with some adjustments I have to make because of the iPhone header position.  I should have checked that before.

That is an interesting question about favoriting a disliked supercharger but has been there all along. They are really two different things under the cover.
- Favorting just catalogs the item so it can be used quickly when adding a waypoint
- Disliking a supercharger (has to be done when it is not a waypoint) is only to force the optimizer to penalize the location with 15 minutes of extra time when choosing chargers during optimization
