### ISSUE TITLE
Favorites dialog: Change name of entry cancelling action

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#163]
v 1.1.3 (6)

When the user selects the Favorites icon, they are presented with a list of saved favorites. 

The top item in the list is 'None', which is semantically correct, but not in line with what the user's thinking. If they inspect the list and don't find the waypoint they were looking for, they will cancel the action and return to the dialog to enter an address manually.

Suggest changing 'None' to 'Cancel', keeping the same slashed circle icon.

It's not that they don't want an Origin or Destination, they need to back out of this dialog and use a different approach to selecting it.

Alternatively, you could add a Cancel button at the bottom of the dialog and remove 'None' from the list. 

![img_0340](https://cloud.githubusercontent.com/assets/26678403/24798597/9db7768a-1b4b-11e7-8e8d-33308ff152ed.PNG)

**Comment by aesculus** [comment]
Fixed V1.1.3 (7)
