### ISSUE TITLE
Waypoint Info dialog - button layout

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#164]
I really like the look of the iconized buttons in the Waypoint Info dialog. Nice enhancement.

Below is a screenshot of a waypoint with what I think is 5 out of 6 possible buttons that might be displayed when users invoke this dialog: 

- View (eyeball)
- Segment (scissors)
- Delete (X)
- Edit (pencil)
- Help (?)

I believe the sixth possible button is Require (available with Automatic waypoints), which is mutually exclusive with Segment.

The proposal is to always use the same button layout so users can learn where the button they're looking for lives in the dialog layout, rather than being presented with a moving target with certain waypoint types.

Obviously, not all waypoints have all buttons available. Origins and Destinations don't have Delete, Segment or Require. Automatic waypoints don't have Segment or Edit.

For waypoints with some button functionality disabled, display the disabled button(s) in their normal location, but grayed out.

For situations where you're graying out either the Segment or Require icon (since they would share a location), suggest defaulting to a disabled Segment icon.

![img_0341](https://cloud.githubusercontent.com/assets/26678403/24798771/a0130218-1b4c-11e7-9ed5-0cc760662da8.PNG)

**Comment by aesculus** [comment]
>For situations where you're graying out either the Segment or Require icon (since they would share a location), suggest defaulting to a disabled Segment icon.

I am not following this statement.

**Comment by EVGrokker** [comment]
Let's assume that you have a standard button row composed of icons (L to R):

[eye] [scissors] [delete] [pencil] [?]

I'm proposing that all five buttons are always visible as placeholders, but some may not be active.

When displaying an automatic waypoint, Segment (scissors) is not applicable, so you would swap the pin icon into position 2, replacing the scissors icon. It's always going to be 5 visible buttons, regardless of what's actually touchable.

When position 2 is grayed out, for example Destination or Origin pins, it should be a scissors icon that's grayed out in position 2, not a pin.

**Comment by aesculus** [comment]
> When position 2 is grayed out, for example Destination or Origin pins, it should be a scissors icon that's grayed out in position 2, not a pin.

That was the "hidden" info I was looking for in my question above.

**Comment by aesculus** [comment]
Done. V1.1.3 (7)
