### ISSUE TITLE
Toggling from Plan Trip to Main, then back, sometimes loses display of segments.

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#165]
v 1.1.3 (6)

I can't replicate this behavior right now, but I've seen it on more than one occasion. 

Create a trip with two segments, then go to Main to make changes in the Settings dialog (I changed the SoC Reserve slider).

Save, Resume Trip. Upon returning to the Plan Trip screen, no routes are shown, and the map is centered on the Bay Area. The Segments icon correctly shows a badge of 2. Touching that and selecting one of the segments then causes the segments to be properly displayed.

**Comment by aesculus** [comment]
I've seen this too. Not sure what causes it. :-(

There could be a timing thing going on. I do some map initialization going to the trip panel and if Google or the network is slow, it might fall behind.

Let's keep this thread open and I will review all of this when I come up for air after the "real" problems get dealt with. :-)

**Comment by aesculus** [comment]
I have built a timer in V1.1.4 to test if the map is viable and wait for 1/2 second if not before displaying the route. It will do this 5 times before giving up and alerting with a message.

We can reopen this issue if we continue to see this behavior after V1.1.4
