### ISSUE TITLE
Waypoint Inspector dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#167]
<h3>Waypoint inspector</h3>
<p><i>Inspect, manage or use Google Street View to preview waypoints along your current route. To dismiss, touch anywhere outside of dialog.</i></p>

<h4>[heart] Toggle Favorite status</h4>
<p>Touch the heart icon to toggle the waypoint's Favorite status. Favorite waypoints may be quickly accessed when creating a new trip or adding waypoints to an existing trip.</p>

<h4>[eyeball] View location</h4>
<p>Touch the eyeball to display a dynamic Google Street View of the waypoint location. To return to the Waypoint inspector, touch the arrow to the left of the location address. </p>

<h4>[scissors] Split current segment into two segments<super>†</super></h4>
<p>The current route may be split at any waypoint by touching the scissors icon. The first segment will use the split point as its Destination. The second segment will use the split point as its Origin.</p>  
<p><super>†Requires Pro version IAP</super></p>
    
<h4>[pin] Convert automatic supercharger stop to waypoint</h4>
<p>When trips are optimized, EVTO automatically selects superchargers along your route, marked with an 'A'. Subsequent route optimizations may automatically select different superchargers, depending on weather conditions and your vehicle's characteristics. To keep an automatically selected supercharger as part of your route, touch the pin icon, converting it to a regular waypoint.</p>  
    
<h4>[X] Remove waypoint from route</h4>
<p>Touch the X icon to remove this waypoint from the current segment. The updated route will be recalculated.</p>

<h4>[pencil] Edit waypoint details</h4>
<p>Touch the pencil icon to display the <strong>Edit Waypoint</strong> dialog, where waypoint details are managed.</p>

**Comment by aesculus** [comment]
Fixed V1.1.3 (7)
