### ISSUE TITLE
Edit Waypoint dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#168]
<h3>Edit Waypoint</h3>
<p><i>Manage waypoint details.</i></p>

<h4>Name</h4>
<p>After specifying a waypoint's address, you can assign a more meaningful name to the waypoint, for example 'Lunch' or 'Rest Area'. Touch within the field to edit the waypoint name. Touch the <strong>X</strong> button to clear the current contents of the Name field.</p>

<h4>Address</h4>
<p>Touch in the Address field to search for a Point of Interest (POI) using its address or business name. Search results are dynamically updated as you type. Once you see the POI you're looking for, select it, and EVTO will fill in the details. The Name field will be automatically populated based on your selection, but you can assign a more meaningful name after specifying the address, as described in <strong>Name</strong> above.</p>
<p>Select a favorite waypoint by touching the heart icon, then selecting a favorite from the list.</p>
    
<h4>Charger Type:</h4>
<p>By selecting <strong>Tesla Superchargers</strong> from the Charger Type dropdown control, search results in the Address field will be limited to those matching supercharger locations. EVTO's supercharger database is updated frequently.</p>  

<h4>Allocated Charging</h4>
<p>The allocated charging time at this stop is displayed with the lightning bolt icon, along with the initial and final charging values. Non-charging time at this stop is displayed with the clock icon.</p>
<p>Allocated charging time is updated interactively as you adjust <i>Minimum Stop Time</i> and <i>Minimum Arrival SoC</i>. Increasing <i>Minimum Stop Time</i> above the initial value adds to the overall charging time. For example, if EVTO suggests a 20 minute charging stop, but you increase <i>Minimum Stop Time</i> to 45 minutes for a meal stop, the additional 25 minutes will be used to continue charging.</p>
<p>Increasing <i>Minimum Arrival SoC</i> causes EVTO to attempt to increase charging at a preceding stop, to provide a higher SoC upon arrival at this stop. This may have the effect of reducing the allocated charging time at this stop required to reach your next stop.</p>
    
<h4>Minimum Stop Time<sup>†</sup></h4>
<p>To allocate break time at a waypoint, adjust the slider to specify the required time. Use this for meal stops, shopping trips or visiting a local POI. For charging stops, specify the total charging time you wish to spend at this stop.</p>
<p><sup>†</sup><i>Requires Pro version IAP</i></p>

<h4>Minimum Arrival SoC (%)</h4>
<p>To reserve energy for local driving at this waypoint, adjust the slider to indicate the State of Charge (SoC) you'd like upon arrival. EVTO will do its best to adjust upstream charging to accommodate your preference, but may not always be able to achieve the specified SoC.</p>

<h4>Charging Mode <i>(Roadster only)</i></h4>
<p>Select <i>Standard</i> or <i>Range</i> mode for this charging stop.</p>

**Comment by aesculus** [comment]
Added V1.1.3 (7)

**Comment by EVGrokker** [comment]
Updated to reflect changed labels for Stop Time, Arrival SoC. (See issue #455)

**Comment by aesculus** [comment]
Updated in V1.2 (39)

**Comment by EVGrokker** [comment]
Added charging mode for Roadster users.

**Comment by aesculus** [comment]
Updated 1.2 (49)

**Comment by EVGrokker** [comment]
v 1.20. (52)

Added **Allocated Charging** section

**Comment by EVGrokker** [comment]
v 1.2.0 (55)
This needs to be updated to the latest revision.

**Comment by aesculus** [comment]
Updated in V1.2 (56)

**Comment by aesculus** [comment]
I updated charger type in the app too 1.2 (86)

**Comment by aesculus** [comment]
Updated with new subscription info
