### ISSUE TITLE
Add Waypoint dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#170]
<h3>Add Waypoint dialog</h3>
<p><i>Add a waypoint to the current route segment. Without a Subscription IAP, up to three additional waypoints may be added. Purchasing a Subscription IAP removes this limitation.</i></p>

<h4>Name</h4>
<p>After specifying a waypoint's address, you can assign a more meaningful name to the waypoint, for example 'Lunch' or 'Rest Area'. Touch within the field to edit the waypoint name. Touch the 'X' icon to clear the current contents of the Name field.</p>

<h4>Address</h4>
<p>Touch in the Address field to search for a Point of Interest (POI) using its address or business name. Search results are dynamically updated as you type. Select your POI from the displayed list of results, and EVTO will fill in the details. The Name field will be automatically populated based on your selection, but you can assign a more meaningful name after specifying the address, as described in <strong>Name</strong> above.</p>
<p>To save this new waypoint as a favorite, touch the heart button at the left edge of the title bar. The heart will turn blue.</p> 
<p>Select a previously-saved favorite waypoint by touching the heart icon, then selecting it from the list.</p>
<p>EVTO also supports pasting charging station details copied from PlugShare directly into the Address field.</p>

<h4>Charger Type:</h4>
<p>Select <i>No Charger</i> for non-charging waypoints.</p> 

<p>By selecting <i>Superchargers</i> or <i>Destination Chargers</i> before entering the address, search results in the Address field will be limited to those matching known charger locations. EVTO's charger database is updated frequently.</p>  

<p>To use a supercharger location not displayed by EVTO, enter the address of the supercharger, then select a matching address from the displayed list of results. Finally, select <i>Tesla Superchargers</i>. EVTO will use supercharger metrics to calculate SoC added during the stop.</p>

<p>Selecting a charger type after entering and selecting a matching address provides EVTO with the charger metrics for this stop. The selected Charger Type and Stop Time will be used by EVTO to calculate the incremental SoC during the stop. If a specific charger type is not listed, select one with a similar energy profile, and <a href="mailto:support@digitalautoguides.com">let us know about it</a>.</p>
    
<h4>Minimum Stop Time<sup>†</sup></h4>
<p>To allocate break time at a waypoint, adjust the slider to specify the required time. Use this for meal stops, shopping trips or visiting a local POI. For charging stops, specify the total charging time you wish to spend at this stop.</p>
<p><sup>†</sup><i>Requires subscription IAP</i></p>

<h4>Minimum Arrival SoC (%)<sup>†</sup></h4>
<p>To reserve energy for local driving at this waypoint, adjust the slider to the minimum State of Charge (SoC) you'd like upon arrival. EVTO will do its best to adjust upstream charging requirements. After adjusting this control, use the Segment Browser or the SoC panel for predicted energy upon arrival.</p>
<p><sup>†</sup><i>Requires subscription IAP</i></p>
    
<h4>Charging Mode <i>(Roadster only)</i></h4>
<p>Select <i>Standard</i> or <i>Range</i> mode for this charging stop.</p>

**Comment by aesculus** [comment]
Added V1.1.3 (7)

**Comment by aesculus** [comment]
Done. Also updated the Edit Waypoint one as well.

**Comment by EVGrokker** [comment]
v 1.2.0 (47)
Updated to explain how to use a ghost supercharger, added explanation about finding a charger type approximating the available power.

**Comment by aesculus** [comment]
Updated in V1.2 (48)

**Comment by EVGrokker** [comment]
Added Standard vs Range mode charging for Roadsters.

**Comment by aesculus** [comment]
Updated 1.2 (49)

**Comment by EVGrokker** [comment]
v 1.2.0 (52)

Edited _Minimum Stop Time_ and _Minimum Arrival SoC_ headers.

**Comment by EVGrokker** [comment]
v 1.2.0 (55)

This needs to updated to the latest revision.

**Comment by aesculus** [comment]
Updated in V1.2 (56)

**Comment by EVGrokker** [comment]
Updated to describe functionality of second heart button at left edge of title bar.

**Comment by aesculus** [comment]
Updated in V1.2 (69)

**Comment by EVGrokker** [comment]
Added sentence describing ability to paste exported PlugShare details into Address field.

**Comment by aesculus** [comment]
Do you think we need a bit more details on how this should work? ie how to use Plugshare app to do the copy?

**Comment by EVGrokker** [comment]
I started down that path, but backed off because I think for the context of online help, it should be just enough to reveal the capabilities, not a full tutorial. This would obviously be a candidate for a tutorial, where it can be covered in depth.

**Comment by aesculus** [comment]
OK. But I think I would use copied vs exported.  Also via PlugShare app its actually Shared via copy/paste if you want a simple explanation.

**Comment by aesculus** [comment]
Updated in V1.2 (70)

**Comment by EVGrokker** [comment]
Updated Charger Type description.

**Comment by aesculus** [comment]
Updated in V1.2 (86)

**Comment by aesculus** [comment]
Updated with new subscription info

**Comment by EVGrokker** [comment]
I revised the initial comment to include the three-waypoint limitation without a Subscription IAP. Please review.

**Comment by aesculus** [comment]
Updated in app
