### ISSUE TITLE
Add Streetview to Charger Infowindow

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#171]
So users can see what a charger looks like before they select it.

**Comment by EVGrokker** [comment]
Also to standard charger inspector.

**Comment by aesculus** [comment]
Yes. It is the same dialog.

BTW I was not clear but the charger help will be one help for both superchargers and non Tesla chargers.

**Comment by aesculus** [comment]
Added in V1.1.3 (7)
