### ISSUE TITLE
New Trip dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#172]
<h3>New Trip</h3>
<p><i>Create a new trip, replacing the current trip. Without a Subscription IAP, trips are limited to a distance of 500 miles (800 km) with three intermediate waypoints. Purchasing a subscription removes these limitations, and allows storage of multiple trips.</i></p>

<h4>Car</h4>
<p>Select the car profile to use for the new trip. With a subscription IAP, up to five car profiles are supported.</p>  

<h4>Origin</h4>
<p>Touch in the Origin field to specify your trip's starting location, using an address or business name. Search results are dynamically updated as you type. When a matching address is displayed in the results list, select it as your Origin. If you have enabled location services for EVTO, you can automatically use your current location as your trip's starting point.</p>
<p>Select a favorite waypoint by touching the heart icon, then selecting a favorite from the list.</p>
<p>EVTO also supports pasting a charging station copied from PlugShare into the Origin field.</p>

<h4>Destination</h4>
<p>Touch in the Destination field to specify your trip's end point, using an address or business name. Search results are dynamically updated as you type. When a matching address is displayed in the results list, select it as your Destination. </p>
<p>Select a favorite waypoint by touching the heart icon, then selecting a favorite from the list.</p>
<p>EVTO also supports pasting a charging station copied from PlugShare into the Destination field.</p>
    
<h4>Charger Type</h4>
<p>The charger dropdown list serves two functions.</p>

<p>Select a charger type <i>before</i> entering and selecting a matching address to limit search results to the type of charger selected, either Tesla Superchargers or HPWC destination chargers.</p> 

<p>Select a charger type <i>after</i> entering and selecting a matching address to inform EVTO of the type of charging available at the address.</p>  

<h4>Departure/Arrival Time</h4>
<p>Specify a departure or arrival time. The default departure time is specified in Settings, but may be overridden when planning the trip.</p>
    
<h4>Plan as a round trip<sup>†</sup></h4>
<p>Enabling this checkbox tells EVTO to use the supplied destination as both the destination for the  outbound segment, and the origin for the return segment. The supplied origin becomes the final destination, creating a round trip.</p>
<p><sup>†</sup>Requires Subscription IAP</p>

<h4>Waypoint Charger Selection</h4>
<p>Selecting <strong>Auto</strong> tells EVTO to automatically select supercharger stops along your route. Selecting <strong>Manual</strong> tells EVTO that you will manually select your charging locations. If your route requires the use of non-Tesla charging stations, select <strong>Manual</strong>, then add charging waypoints interactively from the map.</p>
<p>If you are planning a long trip that you intend to divide into daily segments, use <strong>Manual</strong> mode, then add waypoints at the daily stopping points before optimizing.</p>

**Comment by aesculus** [comment]
Done. V1.1.3 (7)

**Comment by EVGrokker** [comment]
Updated to reflect layout change implemented in #473. Updated some obsolete terminology.

**Comment by aesculus** [comment]
Updated in V1.2 (43)

**Comment by EVGrokker** [comment]
Can you check the formatting of the superscripted dagger in the **Plan as a round trip** section? It's tagged with `<super>` in the source, but it's rendered normally, not as a superscript.

**Comment by aesculus** [comment]
Fixed in V1.2 (44).

Turns out the tags must be `<sup>`

**Comment by EVGrokker** [comment]
Revised the source again, the footnote portion needed to updated as well.

**Comment by aesculus** [comment]
I had fixed in in the footnote and noticed that the source above was wrong. The sup was across the full footnote and not just the + so I fixed it here too.

**Comment by EVGrokker** [comment]
Is the source in the initial comment now correct?

**Comment by aesculus** [comment]
Yes

**Comment by EVGrokker** [comment]
Updated with PlugShare paste feature.

**Comment by aesculus** [comment]
Updated in V1.2 (70)

**Comment by EVGrokker** [comment]
Updated to describe function of charger picker before/after address validation as discussed in #512.

**Comment by aesculus** [comment]
Updated in V1.2 (85)

**Comment by aesculus** [comment]
Updated with new subscription info

**Comment by EVGrokker** [comment]
Updated to reflect addition of departure/arrival time in issue #174.

**Comment by aesculus** [comment]
Updated in app

**Comment by EVGrokker** [comment]
I revised the the initial description to include the proposed limitations for users without a purchased Subscription IAP. Please review and comment.

**Comment by aesculus** [comment]
Reading this:

> Create a new trip, replacing the current trip. Without a Subscription IAP, trips are limited to a distance of 500 miles (800 km) with three intermediate waypoints. Purchasing a subscription removes these limitations, and allows storage of multiple trips.

I realized that I did not code this exactly, nor did I intend to.  Here is what I coded and should be changed appropriately:
- I did not restrict the number of auto waypoints at all. So if the optimizer thinks it needs 5 to go 500 miles so be it (see comment below on out and back trips).
- I am currently checking that the max amount of waypoints is less not greater than 5, but that really should not count the auto waypoints to be fair.  So if a user needed 3 auto waypoints and still wanted to stop somewhere a few times or force a route, I think they should be allowed to.
- I have not coded a restriction on converting an auto waypoint to manual.

On the out and back trips: Currently to make the code and UI simple, I am just doing a straight line distance between origin and destination. So in theory a user could create a same origin/destination trip and then add a waypoint thousands of miles away. The auto router would happily give them all the charging stops (up to Google's 23) they needed to make the trip.

**Comment by EVGrokker** [comment]
Revised initial comment, please review.

**Comment by aesculus** [comment]
I think that works.

Do you think we should just let the hidden out and back feature slip by? Coding it could be a PITA and cost as much from Google as letting it go.

**Comment by EVGrokker** [comment]
When you say 'hidden out & back feature', you're referring to a Pro user without a subscription?

**Comment by aesculus** [comment]
No. The ability to enter the origin and destination as the same place (an out and back) which has a 0 crow flight distance.

**Comment by EVGrokker** [comment]
So there are actually two loophole scenarios:
- Construct an 'out & back' trip with the same origin and destination, and as many as 23 waypoints. 
- Purchase a Pro IAP, which enables round trips. The origin and intermediate destinations would be limited to 500 miles (as the crow flies), but the user could add up to 3 manual waypoints to each segment.

**Comment by aesculus** [comment]
Remember there is no longer an IAP Pro (someone asked me to remove it). :-)

**Comment by EVGrokker** [comment]
To clarify, all previous Pro features are now bundled with the Subscription IAP. Is that correct?

**Comment by aesculus** [comment]
Yep. The only value of Pro from before will get you x (TBD) months of free subscription if you did not also purchase a subscription.

I left all the Pro restrictions in place in the app but if you have a subscription the Pro flag is turned on, otherwise it is off (if you are outside of the free window).

**Comment by aesculus** [comment]
Here is the new menu
![image](https://user-images.githubusercontent.com/283364/31025181-6aa65ff6-a4f6-11e7-98d1-3c3f64ed4b54.png)

**Comment by aesculus** [comment]
Added to the app. I also changed the Pro comment in Car heading
