### ISSUE TITLE
Settings dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#173]
<h3>Settings</h3>
<p><i>Specify default settings used by EVTO when creating new trips</i></p>

<h4>SoC Reserve (%)</h4>
<p>Specifies your preferred State of Charge (SoC) upon arrival at charging stops. This setting is used as a default when planning new trips. Typical values are 15-20%.</p>

<h4>Default Origin SoC (%)</h4>
<p>Specifies the initial State of Charge (SoC) when starting a trip. Typical values are 80-90%.</p>

<h4>Default Start Time</h4>
<p>Specifies the default start time for new trips, or new segments added to existing trips.</p>

<h4>Time Format</h4>
<p>Select 12 or 24 hour format.</p>

<h4>Location services</h4>
<p>If you want EVTO to be able to use your current location as an origin for trips you plan, enable this checkbox. You will also need to allow EVTO to access your current location in your device's privacy settings.</p>
    
<h4>Physical Units</h4>
<p>Select <i>Imperial</i> or <i>Metric</i> to display distances appropriately for your locale.</p>

<h4>Battery Display Units</h4>
<p>Select <i>Percent</i> or <i>Distance</i> for remaining battery charge in the Waypoint Inspector and Segment Details.</p>

<h4>Routing preference<super>†</super></h4>
<p>Select your preferred routing preferences. <I>Minimize Travel Time</i> is the only option currently available.</p>  
<p><i><super>†</super>Requires Pro version IAP, defaults to <strong>Minimize Travel Time</strong> for standard version</i></p>
    
<h4>Continent</h4>
<p>Select your home continent from <I>North America</i>, <i>Asia Pacific</i> or <i>Europe</i>.</p>

**Comment by aesculus** [comment]
Done V1.1.3 (7)

**Comment by EVGrokker** [comment]
Updated to add Battery Display Units section.

**Comment by aesculus** [comment]
Updated in V1.2 (57)

**Comment by EVGrokker** [comment]
Updated to include addition of Default Start Time field and Time Format picker.

**Comment by aesculus** [comment]
Updated in V1.2 (87)

**Comment by aesculus** [comment]
Updated with new subscription info
