### ISSUE TITLE
Supercharger inspector dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#175]
<h3>Supercharger Inspector</h3>

<h4>[eyeball] View location</h4>
<p>Touch the eyeball to display a dynamic Google Street View of the supercharger location. To return to the Supercharger inspector, touch the arrow to the left of the location address.</p>

<h4>[pin]  Add supercharger to current route</h4>
<p>Touch the pin icon to add this supercharger to your current route as a waypoint.</p>

**Comment by aesculus** [comment]
I merged #176 with this one since it's the same dialog. Check it out
