### ISSUE TITLE
Charger inspector: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#176]
<h3>Charger Inspector</h3>

<h4>[eyeball] View location</h4>
<p>Touch the eyeball to display a dynamic Google Street View of the charger location. To return to the Charger inspector, touch the arrow to the left of the location address.</p>

<h4>[pin]  Add charger to current route</h4>
<p>Touch the pin icon to add this charger to your current route as a waypoint.</p>

**Comment by aesculus** [comment]
Updated V1.1.3 (7)

**Comment by aesculus** [comment]
<h3>Help</h3>
<h4>Charger Inspector</h4>
 <p>The Charger Inspector is where you can see the details of each charger that you can choose from.
    The charger name and address are at the top along with a Dislike icon, described below. The address and    other information such as charger types and numbers are followed by any amenities at this site
    (Superchargers only).
<h5>[icon]Dislike Icon</h5>
<p>You may dislike superchargers using this icon as a toggle. When red, EVTO will attempt to use another
    charger in it's place if possible.</p>
<h5>Amenities</h5>
<p>Amenities for superchargers are shown in iconic form and match the values in the car.</p>
<h5>[icon]View location</h5>
<p>Touch the eyeball to display a dynamic Google Street View of the charger location. To return to the Charger inspector, touch the arrow to the left of the location address.</p>
<h5>[icon]</span>Add charger to current route</h5>
<p>Touch the pin icon to add this charger to your current route as a waypoint.</p>

**Comment by aesculus** [comment]
I made some changes as above. See if you agree or edit and I will replace.

**Comment by EVGrokker** [comment]
When red, EVTO will attempt to use another charger in ~~it's~~ its place if possible.

Amenities for superchargers are shown in iconic form ~~and match the values~~, matching the amenity icons displayed on Tesla's in-car navigation screen.

**Comment by aesculus** [comment]
Done. V1.1.3 (7)

**Comment by EVGrokker** [comment]
Please post the HTML for this help panel.

**Comment by aesculus** [comment]
Here is the current help. You can delete this after you copy it and maybe remove all the other copies too so we only have the current one at the top.

    <p>The Charger Inspector is where you can see the details of each charger that you can choose from.
    The charger name and address are at the top along with a Dislike icon, described below. The address and
    other information such as charger types and numbers are followed by any amenities at this site
    (Superchargers only).
    <h4><img class="panel_help_icon" src="css/images/gray/778-thumbs-down.png" />Dislike Icon</h4>
    <p>You may dislike superchargers using this icon as a toggle. When red, EVTO will attempt to use another
    charger in its place if possible.</p>
    <h4>Amenities</h4>
    <p>Amenities for superchargers are shown in iconic form, matching the amenity icons displayed 
    on Tesla's in-car navigation screen.</p>
		<h4><span class="ui-btn-icon-notext ui-icon-eye ui-alt-icon menu-icon"></span>View location</h4>
		<p>Touch the eyeball to display<sup>†</sup> a dynamic Google Street View of the charger location. To return to the Charger inspector, touch the arrow to the left of the location address.</p>
    <p class="caveat"><sup>†</sup>Requires Pro version IAP</p>
		<h4><span class="ui-btn-icon-notext ui-icon-location ui-alt-icon menu-icon" ></span>
    Add charger to current route</h4>
		<p>Touch the pin icon to add this charger to your current route as a waypoint.</p>

**Comment by EVGrokker** [comment]
Updated for next beta.

**Comment by aesculus** [comment]
Updated in V1.2 (51)
