### ISSUE TITLE
General UI comment: Dialogs should have selection lollipops, copy disabled

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#177]
I notice that in dialogs, for example My Cars, it's possible on iOS to touch the screen in such a way that brings up the lollipop pins to drag and select an area to copy. 

Suggest that copy be disabled in dialogs so that this interaction is not possible.

**Comment by aesculus** [comment]
OK. I will look into this.  I have copy turned off in a lot of areas but don't like to turn it off everywhere because people (me?) like to copy some of the text, even none editable stuff.

**Comment by EVGrokker** [comment]
Screen shots

**Comment by aesculus** [comment]
>Screen shots

You mean as an alternative to Copy? Not the same. I like to use the text for other purposes. :-)

**Comment by EVGrokker** [comment]
It feels unpolished to me, but it's your call.

**Comment by aesculus** [comment]
OK. Its gone, but the first time I want it back it gets turned on again for selected areas. :-)
Fixed in V1.1.3 (7)
