### ISSUE TITLE
My Cars dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#179]
<h3>My Cars</h3>
<p><i>Specify characteristics of your Tesla to improve EVTO's accuracy when predicting energy requirements and recharging stops.</i></p>

<p>Use this dialog to describe your car's configuration in three categories: <strong>Model</strong>, <strong>Cockpit</strong>, and <strong>Energy</strong>.</p>

<hr/>
<h3>Model</h3>

<h4>Active Car</h4>
<p>Select your Tesla model from the dropdown list. The standard version of EVTO supports a single car configuration. Pro version users may configure up to five cars, or use multiple configurations for a single car. Multiple configurations may be useful if you occasionally pull a trailer or carry heavy loads.</p>
<p><i>Note: Individual trips are associated with specific car configurations.</i></p>

<h4>Car Name</h4>
<p>Personalize EVTO with your Tesla's nickname.</p>

<h4>Car Model</h4>
<p>Select your Tesla model from the dropdown list.</p>

<h4>Motor configuration</h4>
<p>Select your car's motor configuration:</p>
<ul>
<li>Two Wheel Drive</li>
<li>Two Wheel Drive with Performance</li>
<li>Dual Motor Drive</li>
<li>Dual Motor with Performance</li>
</ul>

<h4>Wheels</h4>
<p>Select your Tesla's wheel size. EVTO factors the range impact of larger wheel sizes when calculating energy requirements for a trip.</p>

<h4>Tires</h4>
<p>Select your Tesla's tires. Tire selection influences range calculations.</p>

<hr/>
<h3>Cockpit</h3>
<p><i>Note: Payload and Climate Control settings may be overridden for individual trips using the Edit Trip Details dialog.</i></p>

<h4>Payload</h4>
<p>Use this field to inform EVTO of additional weight in the car above the curb weight, including passengers and baggage. This helps EVTO estimate the required energy along your route.</p>
<p><i>Note: When using a tow hitch, include the weight of the additional load.</i></p>
        
<h4>Climate Control</h4>
<p>Use this field to specify your preferred cabin temperature while driving. If you don't anticipate using climate control while underway, uncheck the Climate Control checkbox.</p>
<p><i>Note: Enabling climate control during charging stops does not negatively impact range calculations for the trip.</i></p>

<h4>Pano Roof</h4>
<p>If you own a Tesla with a panoramic roof, enable this checkbox to increase range prediction accuracy.</p>

<h4>Rear Climate Control</h4>
<p>If your Model X is a 6 or 7 seater with a separate rear climate control feature, enable this checkbox to increase range prediction accuracy.</p>

<h4>5-seater</h4>
<p>If your Model X is a 5-seater model, enable this checkbox to improve the accuracy of EVTO's predictions, due to the lighter curb weight of this model.</p>

<hr/>
<h3>Energy</h3>
<p><i>Note: Speed Adjust and Power Factor settings may be overridden for individual trips using the Edit Trip Details dialog.</i></p>

<h4>Power Factor</h4>
<p>Use this slider to inform EVTO that you anticipate requiring extra energy for this trip, typically because you're towing a trailer, or have something attached to the car, like bicycles or skis. Positive numbers impose an energy penalty.</p>

<p>For example, a Power Factor of <i>10</i> imposes an additional energy requirement when EVTO plans your trip. You can also use a negative Power Factor setting to inform EVTO that you aggressively seek opportunities to reduce energy requirements whenever possible by using hypermiling techniques, like drafting.</p>
<p>Identifying an accurate Power Factor setting for your particular configuration requires trial and error experimentation. If you're towing a large trailer in the upper range of your car's towing capacity, start with a Power Factor of 50, compare your actual results to the predicted results, and adjust the Power Factor accordingly for subsequent trips.</p>
    
<h4>Speed Adjust</h4>
<p>Use this slider to inform EVTO that you typically prefer to drive over (or under) the posted speed limits. The slider is color-coded, reflecting that higher speeds incur an energy penalty, while lower speeds return an energy bonus. EVTO's speed calculations are based upon estimated speeds along your route, which often vary. Speed Adjust is an offset from the posted speed limits.</p>

<h4>Max Speed</h4>
<p>In addition to using Speed Adjust to indicate your preference to drive below posted speed limits, use Max Speed to set an absolute upper speed limit. For example, in a towing scenario, you might set Max Speed to 55.</p>

<h4>90% Range (mi or km)</h4>
<p>A new Tesla's battery pack is capable of the EPA range published by Tesla. Over time, your battery pack loses capacity. When charged to 90%, note the range indicated by the car, then input that number here. As your battery loses capacity, EVTO will use your current 90% value to improve the accuracy of its predictions.</p>

<h4>Battery</h4>
<p>Select your Tesla's battery size. EVTO uses your Tesla's battery size to plan charging stops and predict remaining State of Charge (SoC) upon arrival at waypoints.</p>
    
<h4>Charger</h4>
<p>Select your Tesla's charging capability. If your Tesla is configured with the High Amperage Charger Upgrade, your faster charging time will be factored in when charging with capable Tesla charging connections.</p>

**Comment by aesculus** [comment]
Done V1.1.3 (7)

**Comment by EVGrokker** [comment]
Ready for your review.

**Comment by aesculus** [comment]
Updated in V1.2 (37)

**Comment by aesculus** [comment]
The only issue I have is:

>For example, a Power Factor of 10 imposes an additional 10% energy requirement when EVTO plans your trip. 

While it's a bit nuanced, it's not an absolute factor as it does not apply to the total energy. So if someone (you?) compares, they will notice it's less than what they would expect.

**Comment by EVGrokker** [comment]
If it's not absolute, the label shouldn't include the '%' character. Given the nuance, and the fact that Speed Adjust isn't labeled, suggest the same for PF. I'll edit the help text tomorrow.

**Comment by aesculus** [comment]
OK. % gone.

**Comment by aesculus** [comment]
I have a beta user who wants the speed to be absolutely a certain number.  For example he wants to see 75 mph in the 'average' speed when on a long trip. He understands what's going on, but still ...

**Comment by EVGrokker** [comment]
I don't think that declaring an absolute speed makes sense. At best, a user can declare "I like to drive xx mph over the limit". Your time calculations are based upon the speed limits along the route, which will vary. If there's a stretch where the speed limit drops from 70 to 60, it's not reasonable for a user to say "I'm driving 75 no matter what". The fact that we have a SA factor is a huge step forward, and it seems to be working well. Let's let them try it and compare to real world results before spending any more time refining the feature.

**Comment by EVGrokker** [comment]
Updated to remove reference to % in Power Factor section, added sentence about initial settings for large trailers.

**Comment by aesculus** [comment]
I guess you will want to tweek this a bit with the new changes in V1.2 (37)

**Comment by EVGrokker** [comment]
Help text updated in 1st comment reflecting layout changes switching to tabbed interface. Ready for your review.

**Comment by EVGrokker** [comment]
Updated: ~~HVAC~~ Climate Control

**Comment by EVGrokker** [comment]
Updated to help hypermilers warm up during charge stops. Noted that Payload, Climate Control, Speed Adjust and Power Factor may be overridden in the Edit Trip Details dialog.

**Comment by aesculus** [comment]
Updated in V1.2 (37)

**Comment by EVGrokker** [comment]
Added note to Payload section reminding those towing to include the additional weight

**Comment by aesculus** [comment]
Updated in V1.2 (39)

**Comment by EVGrokker** [comment]
v 1.2.0 (71)

Updated to add Max Speed, rearranged items to match current layout of Energy tab.

**Comment by aesculus** [comment]
Updated in V1.2 (72)

**Comment by aesculus** [comment]
Updated in V1.2 (89) to reflect new location of speed adjust and power factor for trip segments.

**Comment by aesculus** [comment]
Updated with new subscription statement
