### ISSUE TITLE
Maintain Favorites dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#180]
<h3>Maintain Favorites</h3>
<p><i>Remove favorite status from waypoints, or remove dislike status from Tesla Supercharger sites. </i></p>
<p><img src="css/images/gray/748-heart.png"/> To remove a waypoint from the Favorites list, touch the heart button to display saved favorites, then touch the 'x' to remove a saved favorite from the Favorites list.</p>
<p><img src="css/images/gray/778-thumbs-down.png"/> To remove a thumbs-down dislike from a supercharger site, touch the thumbs down button to display disliked charger sites, then touch the 'x' to remove the thumbs-down rating assigned to that site.</p>

**Comment by aesculus** [comment]
Added V1.1.3 (7)

**Comment by EVGrokker** [comment]
Edited help text: ~icon~ button.

Please edit the initial comment ([heart], [thumbs down]) to include the proper html for the associated images.

**Comment by aesculus** [comment]
Updated in V1.2 (83)
