### ISSUE TITLE
Edit Segment Details dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#181]
<h3>Edit Segment Details</h3>
<p><I>Fine-tune a trip segment's details to improve the accuracy of EVTO's range prediction.</i></p>

<h4>Name</h4>
<p>Rename your trip segment.</p>

<h4>Date and Time</h4>
<p>Establish the departure date and time for the current segment. When planning a trip, each segment is calculated assuming the current date and time for departure. When planning a trip for a future date, set its date and time here. EVTO uses available weather and road condition reports to predict driving time and range. Touch the clock icon to reset time or date to the current time.</p>

<p><strong>Important note about departure times:</strong> The departure time for a segment is always displayed in the local time zone of the segment's origin, which may not be the same time zone that you are in when planning or reviewing a trip.</p>

<h4>Origin SoC %</h4>
<p>The State of Charge (SoC) you will charge to before departing on this trip segment. Tesla recommends charging to a higher level (90% or more) bfore departing on longer road trips, or a lower level (80% or less) when departing on shorter trips when recharging is not required. EVTO uses your initial SoC to improve the accuracy of its predictions. Your default SoC is adjusted in <strong>Settings</strong>, but you can tweak it for individual segments in this dialog.</p>
        
<h4>Local Travel<super>†</super></h4>
<p>When arriving at your destination, you may wish to reserve energy for local travel after completing this trip segment. Specify the distance of local travel you'd like to reserve, and EVTO will calculate the additional charging requirements. EVTO will make its best effort to adjust earlier charging stops to accommodate your reserve goal, but it may not be achievable. After planning a segment, consult the SoC tab in the Plan Trip screen to review EVTO's predictions. You may need to manually add an extra charging stop before arriving at your destination if you need a significant energy reserve for local travel.</p>
<p><i><super>†</super>Requires Pro version IAP</i></p>
    
<h4>Comments</h4>
<p>Add information specific to this trip segment for future reference, perhaps phone numbers, restaurant recommendations, or reminders.</p>

**Comment by aesculus** [comment]
Added V1.1.3 (7)

**Comment by aesculus** [comment]
I updated the help with the new Dest Reserve text.

I also changed all of the IAP requirements to use this text "Requires Pro version IAP" for consistency.

Fixed in V1.1.4

**Comment by EVGrokker** [comment]
Updated with additional text pointing out that Payload, Cabin and Power Factor are reused from this dialog when planning new trips. Minor edits. Please update this dialog help text with the revised content.

**Comment by EVGrokker** [comment]
v1.2.0 (28)
Updated to remove obsolete references to Cabin Temp, payload, etc.

**Comment by aesculus** [comment]
Updated in V1.2 (29)

**Comment by EVGrokker** [comment]
Updated to change Dest. Reserve to Local Travel.

**Comment by aesculus** [comment]
Updated in the app

**Comment by EVGrokker** [comment]
Updated with note about time zones in response to #335.

**Comment by aesculus** [comment]
Updated in V1.2 (32)

**Comment by aesculus** [comment]
Moved speed adjust and power factor into this help in V1.2 (89)

**Comment by aesculus** [comment]
Updated with new subscription info
