### ISSUE TITLE
Filter Chargers dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#182]
<h3>Filter Chargers</h3>
<p><I>Limit types of chargers displayed on the map</i></p>

<p>Touching the electrical outlet icon toggles the display of non-supercharger charging locations. By default, all of the charger types in EVTO's database are displayed. Use this dialog to filter which charger types are enabled for display:</p>

<dl>
  <dt>Charger types, typical configuration:</dt>
  <dd>NEMA 5-15 (Level 1): 120v delivered on a 15A circuit</dd>
  <dd>NEMA 5-20 (Level 1): 120v delivered on a 20A circuit</dd>
  <dd>NEMA 14-50 (Level 1): 240v delivered on a 50A circuit</dd>
  <dd>J1772 (Level 2): 240V delivered on a 40A circuit</dd>
  <dd>Tesla HPWC (Level 2): 240V delivered on a 50A or 100A circuit</dd>
  <dd>CHAdeMO (Level 3): DC fast charger, similar to Tesla supercharger. Requires adapter.</dd>
  <dd>SAE J1772 Combo (Level 3)DC fast charger, similar to Tesla supercharger. Requires adapter.</dd>
</dl>

**Comment by aesculus** [comment]
Added V1.1.3 (7)

**Comment by aesculus** [comment]
This was superseded by #361
