### ISSUE TITLE
Rate Trip dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#183]
<h3>Rate Trip</h3>
<p><I>Assign a rating to a completed trip</i></p>

<p>When completing a trip you may rate it with 1 to 5 stars. Use the Main screen menu to select <strong>Compare Trips</strong>, enabling a comparison matrix based on your assigned ratings. Rating a trip changes its status from <i>Plan</i> to <i>Taken</I>. Unrate a trip to return it to <i>Plan</I> status.</p>

**Comment by aesculus** [comment]
Added in V1.1.3 (7)
