### ISSUE TITLE
Edit Segment Details: change Cabin control to spinner

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#184]
Suggest changing Cabin control to a spinner with available climate control temperatures (I'm guessing 60 to 80?) plus 'Off'. Order would be 'Off', 60, 61…79, 80.

**Comment by aesculus** [comment]
I still cannot find a UI component to do this. :-(

**Comment by EVGrokker** [comment]
I'm assuming the problem is you can't mix text and numbers. How about a standard picker populated with text, Off, 60, 61…80, then convert the text to a numeric value when you parse the value?

**Comment by aesculus** [comment]
I don't really have much control over when it's a pull down picker vs when Apple decides to turn it into a spinner.  On the iPad it ended up as a long listed pick list. Not good.

**Comment by EVGrokker** [comment]
Sorry about the terminology. I thought Apple used 'picker' to mean a control that spins through values, like a date picker. I have used spinner on occasion to mean the same thing. So to clarify, what I'm hoping to see here is a picker with the described values. The user would spin through them to select the temp they want. 

That said, you can't control what sort of UI control is utilized? Why isn't it a problem for charger types?

**Comment by aesculus** [comment]
We are on the same page. For some reason the iPad and iPhone behave differently for the same type of control. Go figure.

**Comment by EVGrokker** [comment]
Is this because of the UI suite you're using?

**Comment by aesculus** [comment]
Yes.

**Comment by EVGrokker** [comment]
Can you change the contents of the control after it's been created? I'm thinking you could initially populate it with all text values to spoof it into using a picker, then swap in the numeric values.

**Comment by aesculus** [comment]
It's not that it's numeric, just that iPads don't seem to use the scroller in this case.  I thought at first it was because the list was smaller, but I loaded dozens of items into the list and it still came out a list vs a scroller.

**Comment by EVGrokker** [comment]
So you never see spinners on the iPad? Even for charger types?

**Comment by aesculus** [comment]
That is correct.

![image](https://cloud.githubusercontent.com/assets/283364/26363593/5a9d0b8e-3f96-11e7-969b-25ad43c2f89d.png)

**Comment by EVGrokker** [comment]
Ugh. 

How about changing the label to 'HVAC', and adding a checkbox representing on/off to the left of the numeric field. When checked, the numeric field would be enabled. When unchecked, the numeric field would be disabled.

**Comment by aesculus** [comment]
If I can fit it in for the phone, yes. I will give it a try and show you a sample if it seems to work ok

**Comment by EVGrokker** [comment]
Also, I believe we have an issue to add the climate controls to either My Cars or Settings so that there's a master location rather than just the Edit Segment Details dialog.

**Comment by EVGrokker** [comment]
See issue #135.

**Comment by EVGrokker** [comment]
UI framework does not support directly specifying a picker in design. Implementation changed to be a checkbox plus a temperature field. See related issue #315.

**Comment by aesculus** [comment]
Just to hassle you I changed the cabin temp to be a picker. :-)

At least in iOS iPhone. In the iPad it's a selector and in Android it's a scrolling list of radio's, go figure.

**Comment by EVGrokker** [comment]
It looks good on the iPhone.
