### ISSUE TITLE
Move all action buttons to right side of dialog

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#185]
Where help is defined for panel, include a standard help icon to the left side of the panel with the action buttons.

**Comment by EVGrokker** [comment]
Are there any panels for which help is not defined?

**Comment by aesculus** [comment]
Haven't done a full inventory yet. As soon as I finish adding all the help content you made I will know.

**Comment by aesculus** [comment]
The one I saw that needs editing was the Segment Details help.

**Comment by aesculus** [comment]
Done V1.1.3 (7)
