### ISSUE TITLE
My Cars Scrolling Issues

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#187]
It's often hard for uses to select a spot to scroll the my cars panel.  Also it would be nice if the scroll bar stayed active no matter what so the user could see that the panel needs to be scrolled.  This could allow the warning at the top of the panel to be removed.

**Comment by EVGrokker** [comment]
I've had the same problem. 

How about this: create a vertical grab bar along the left side of the dialog that can be touched and dragged vertically to move the contents of the right side. 

A crude concept image gratuitously using a tire tread texture as a grab surface:

![my cars concept](https://cloud.githubusercontent.com/assets/26678403/24832424/f6c8bf30-1c64-11e7-9d61-58181ce171da.png)

**Comment by aesculus** [comment]
Wow. Way cute. I am on it.

**Comment by aesculus** [comment]
No luck in getting this to work yet. Still at it.

**Comment by EVGrokker** [comment]
I want to revisit this discussion. 

Would it be possible to create a margin on either the left or right side as a grab surface to facilitate scrolling the panel? Independent of whether you can apply a graphic image to the area, as depicted in the rendering above, having an inactive surface to touch and scroll the panel would make it easier to navigate.

What about making the grab area non-scrolling - is that possible? In other words, the tire-tread area proposed above would be a fixed rectangle within the dialog, while the controls would be in a scrolling container.

**Comment by EVGrokker** [comment]
I have an alternate approach, working on a mockup.

**Comment by EVGrokker** [comment]
I think a tabbed design is inevitable, and it would be better to tackle it as part of the next release.

Key changes:
- Three tabs: _Interior_, _Exterior_, _Energy_
- The first tab is _Interior_, which has the car's name field and interior options.
- The second tab is _Exterior_, which describes the car's mechanical configuration
- The third tab is _Energy_, which describes the energy-related variables.
- I changed the model selection in _Exterior_ to a picker to save some real estate.
- I dropped a couple of text labels that didn't seem necessary
- Inevitably, there may be a need to add some controls to these panels that will still require some dragging, but it won't be nearly as challenging.


![mycarstabbed](https://user-images.githubusercontent.com/26678403/26980755-49768ea4-4cf0-11e7-9182-c384edf07d95.jpg)

**Comment by aesculus** [comment]
This looks reasonable. Can you see any issues with the fact that there are tabs and the user might not visit them?  Is that too much of a concen to protect the user from themselves and is the current scrolling issue larger than not visiting a tab?

Also why is the battery and charger not part of energy?

**Comment by EVGrokker** [comment]
We use tabs on the Plan screen. They're clearly labelled. Trying to maintain a scrolling list that just keeps getting larger is hopeless.

I was 1) grouping the dynamic, user editable energy stuff together and 2) trying to balance the real estate layout requirements. My thinking was that battery and charger are not very dynamic - only possible change is that user field-updates after initial purchase. Whereas the other energy stuff could change frequently. But I'm fine with moving them over to join Energy.

**Comment by aesculus** [comment]
Or change the tab labels. Not sure to what yet. I don't have a problem with the organization, just the label.

I was thinking Consumption vs Energy but that may be too big and abstract?

**Comment by EVGrokker** [comment]
Energy is more encompassing, covering Rated SoC, and makes it possible to move Battery and Charger there in the future if needed. And shorter. Can you tell I like Energy?

**Comment by EVGrokker** [comment]
Here's a collection of possible tab label combos:

<table>
  <tr>
    <th>Option</th>
    <th>Tab 1</th>
    <th>Tab 2</th> 
    <th>Tab 3</th>
    <th>Comments</th>
  </tr>
  <tr>
    <td>1</td>
    <td>Interior</td>
    <td>Exterior</td> 
    <td>Energy</td>
    <td>As initially proposed</td>
  </tr>
  <tr>
    <td>2</td>
    <td>Inside</td>
    <td>Outside</td> 
    <td>[zap icon]</td>
    <td>Simple</td>
  </tr>
  <tr>
    <td>3</td>
    <td>Internals</td>
    <td>Hardware</td> 
    <td>Power</td>
    <td>Tech-ish</td>
  </tr>
  <tr>
    <td>4</td>
    <td>Cabin</td>
    <td>Vehicle</td> 
    <td>Energy</td>
    <td>Modern. ('Cabin' > 'HVAC' in tab 1)</td>
  </tr>
  <tr>
    <td>5</td>
    <td>Cockpit</td>
    <td>Configuration</td> 
    <td>Consumption</td>
    <td>For Chris</td>
  </tr>
</table>

I do have a fondness for 'Cockpit' because of the airplane connotation. 

Option 4 would be the most space-efficient.

You can mix and match.

Let the voting begin.

**Comment by aesculus** [comment]
Easy to change in a heartbeat, so let let it simmer for awhile.

**Comment by aesculus** [comment]
Can we swap the order? Seems like the car model etc should be the first thing they pick. That's the most critical. ie Exterior > Interior > Energy

**Comment by EVGrokker** [comment]
That was a cheat to get the name field on the first tab. If you want to shuffle battery and charger to tab 3 to make room for the nickname with the other hardware that could work.

I think name field has to be on tab 1.

**Comment by EVGrokker** [comment]
Do you want another mock-up?

**Comment by aesculus** [comment]
That would help with the energy concern.

No. I think I am ok.  Mostly cosmetic but having to change some checkbox to selects means some code too.

**Comment by EVGrokker** [comment]
A reminder, remember that we also discussed adding a checkbox to enable/disable HVAC. It would make sense to make this change at the same time.

**Comment by EVGrokker** [comment]
One other comment about this change. Once a car is configured, user will interact with the energy tab probably 80% of the time, cabin 20%. It would be nice to return to the same tab you last used, eg if you're tweaking SA or PF.

**Comment by EVGrokker** [comment]
Take 2:
- Model (exterior) features are now in Tab 1
- Added HVAC on/off checkbox in Tab 2, renamed text field to 'HVAC'
- Moved Battery and Charger pickers to Tab 3. I placed them below SA and PF because I think the user will be looking for those more frequently.
- Jazzed up the labels


![mycarstabbed2](https://user-images.githubusercontent.com/26678403/26993442-40f1e3de-4d20-11e7-9d45-224f6af29f6a.jpg)

**Comment by EVGrokker** [comment]
Since I screen-grabbed from an older version, `Power Factor (%):` in tab 3 should remove `(%)`, leaving simply `Power Factor:` to match `Speed Adjust:`.

**Comment by aesculus** [comment]
Here you go. Two items I cannot deal with at the moment and are not show stoppers:
- There is a bit of gray to the right of the tabs
- The buttons on the bottom move with the tab content.

I did fix the width of the car picker so it matches the rest but this image does not show it.

![image](https://user-images.githubusercontent.com/283364/26993673-1cce9c42-4d19-11e7-88f2-62a80a6c7161.png)

**Comment by aesculus** [comment]
Implemented in V1.2 (37)

**Comment by aesculus** [comment]
> A reminder, remember that we also discussed adding a checkbox to enable/disable HVAC. It would make sense to make this change at the same time.

I will need a mock up or suggestion from my current images. Also it has to be applied here too:

![image](https://user-images.githubusercontent.com/283364/26994077-e5610e5a-4d1a-11e7-82e5-80c1064eea83.png)

**Comment by aesculus** [comment]
>One other comment about this change. Once a car is configured, user will interact with the energy tab probably 80% of the time, cabin 20%. It would be nice to return to the same tab you last used, eg if you're tweaking SA or PF.

Don't push your luck. :-)

Let me get some more important stuff done first and the if you absolutely can't live without it ...

**Comment by aesculus** [comment]
> Take 2:

Did not see this first. :-(

**Comment by EVGrokker** [comment]
No problem, I'll edit your version. Go work on something else. This is a major improvement and gets rid of a headache (scrolling) that wasn't going away on its own. I'm happy to work with this version in the next release while we kick around fine-tuning ideas.

Nice work.

**Comment by EVGrokker** [comment]
Revisions:
- Added HVAC on/off control. Note that toggling HVAC to OFF state should gray out and disable editing temperature setting.
- In tab 3, I like the battery and charger pickers below the SA/PF/90% fields, but I'll leave that up to you.
- Note that I rearranged the table of tab label candidates above to conform to your preferred External/Internal/Energy approach, and added a candidate, 'Model/Cockpit/Energy'.


![3tabs](https://user-images.githubusercontent.com/26678403/26994715-fdb61e54-4d25-11e7-9708-eb3b41c1b3fe.jpg)

**Comment by EVGrokker** [comment]
Question/Comment:

In my mockups I had placed the tab control below the My Car picker. My thinking was that there's only one My Car picker, and it should be accessible from any of the three tabs if you want to change cars.

In your mockup you placed the tab control at the top, and the My Car picker shows up in each of the three tabs. Is that picker the same control on all three tabs, or is it three different controls all synced up somehow?

**Comment by aesculus** [comment]
But the My Car is still available to all three tabs.

I changed mine to 'Model/Cockpit/Energy'

**Comment by aesculus** [comment]
![image](https://user-images.githubusercontent.com/283364/26998095-a73c2744-4d34-11e7-9197-cfa578c8710a.png)

**Comment by EVGrokker** [comment]
👍

**Comment by aesculus** [comment]
> Added HVAC on/off control. Note that toggling HVAC to OFF state should gray out and disable editing temperature setting.

You think so? I think they should be able to edit it anytime they want. But I will disable it in the calc if they uncheck the box.

**Comment by aesculus** [comment]
All but disabled Cabin Temp has been implemented in V1.2 (37). Note I had to change the error feature too. I am now using the common gray popup panel and do not leave the dialog and come back to it like before.

**Comment by EVGrokker** [comment]
>Note I had to change the error feature too.

To clarify, this is the error that occurs if a user selects an unsupported combination of features?

**Comment by EVGrokker** [comment]
Does the error occur upon the user touching Save?

**Comment by aesculus** [comment]
Both realtime and save.

**Comment by EVGrokker** [comment]
There are some issues with the My Cars dialog in 1.2.0 (37), but I'm going to close this issue and start new ones that are more specific, as the focus of this issue has been resolved.
