### ISSUE TITLE
In the 'What Car are You Driving' dialog, construct a meaningful car name

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#19]
For example, if they've specified a Model X 90D, construct 'My Model X 90D' rather than just 'My Car'. Folks initializing with multiple cars will appreciate that. Also, when naming a car, you need to check that it's not duplicating an existing car name.

**Comment by aesculus** [comment]
This is fixed in V1.1.2

**Comment by aesculus** [comment]
Will need to validate it's not a duplicate name

**Comment by aesculus** [comment]
Fixed in V1.1.3
