### ISSUE TITLE
Behavior of Charger Clusters

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#191]
Users Comment:

> One other item, it would be helpful if one could tap on one of the summary charging icons (the circles with the # of charger shown inside), and have the program bring up a table of choices.  Sometimes you have to zoom in really really close in order to get it to show the individual chargers (e.g. at the Lafeyette location).

Not sure what or how this would work with the UI.

**Comment by EVGrokker** [comment]
Tapping on a cluster could bring up the Filter dialog.

**Comment by EVGrokker** [comment]
Or tapping a cluster could compose a list of all chargers in the cluster, sorted by type. Maybe a button in that list could bring up the Filter dialog. 

Ultimately zooming in is the most effective filter.

**Comment by aesculus** [comment]
I am going to close this item because I think it was the result of a bug. This user could not open the charger clusters unless they made repeated zooms. That bug was fixed in . #196
