### ISSUE TITLE
Alternative Chargers Not Always Consistently Displayed

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#192]
From a user:
>No change in the route.  But, I did some more playing with the issue, and believe I've reproduced the original case.  It appears to be related to map zoom.  I have the screen zoomed out to see the full route, and all I see is the original "Kaiser Vacaville" J1772 icon in Vacaville.  Odd that there's only one, but ok.  I include it, and see the suggested charging time like I did.  Delete the waypoint, and it goes away.  Nothing else showing for Vacaville.  What I didn't notice was that the charging for Fairfield was sitting at 32.  If I zoom in, that breaks down into 14 for Fairfield, and 18 for the junction of 80 and 505 just north of Vacaville.  Zooming in further puts 5 in Vacaville, 12 in the Nut Tree area, and one in between.  So, part of the issue appears to be due to a combination of the lack of a complete J1772 charging database (smaller number of charging stations than I was expecting), and the algorithm for clumping the stations that do exist to be a bit coarser than perhaps desirable.  There is a lot of roadway between Fairfield and Davis, in this example, and showing no charging opportunities along that stretch of roadway isn't good.  But there's more...

>Zooming back to the full route and toggling the charging icon, there's now a total lack of charging between Sacramento (102 stations) and Benicia (10 stations).  Fairfield and Davis are blank!  Zooming in to the Cordelia to Davis section, it's now totally blank.  Here's the issue reproduced:  When I toggle the Plug icon, it does NOT display "fetching...".  Optimize does not change this.  I think perhaps that update process / thread got stuck somehow, so the stations it does know about are pushed into the larger summary icons, and when you zoom in, they aren't re-distributed into the closer view, leaving that whole stretch of roadway devoid of any charging opportunity.  That is what I saw.

**Comment by EVGrokker** [comment]
My uninformed observation is that your supercharger database is very complete, and your conventional charger database is sketchy,  compared to the plugshare database. For example, plugshare knows that the sand dollar inn in moclips WA has a 14-50 charger, EVTO does not.

**Comment by aesculus** [comment]
I am using NREL for my non superchargers.

Plug share wants my first born plus ...

**Comment by aesculus** [comment]
BTW I am only showing chargers that are close to the route (like a few miles)

**Comment by EVGrokker** [comment]
Given that you're publicly conceding that plugshare has a superior database, I think we need to acknowledge that in both the help and tutorials. I'd suggest a tutorial sourcing a charger from plugshare, and adding some text in the Filter Chargers help (local and Plan) describing the database as skeletal. I know an idea that has been proposed more than once is crowd sourcing chargers, but that's a future feature.

**Comment by aesculus** [comment]
I think this is a great idea.  In fact I think a series of "tips" like this would be good. The can be in context but it would also be nice to be able to go to a list of them and check them off as the user views them too.

BTW the NREL chargers are only for USA. Other regions have nothing.  Plugshare said they were reconsidering making their data available to other than larger commercial entities but had no time frame nor even a plan in place to do this. Just sort of a passing comment.

**Comment by aesculus** [comment]
I discovered that when a trip starts the alternative chargers won't display when toggled on unless you first take action on the Filter Charger dialog.
