### ISSUE TITLE
Main menu | Settings, My Cars | Help interaction issues

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#193]
Upon closing help by touching 'x' icon, focus is placed in Settings dialog's first control, which brings up a keyboard (which shouldn't happen). Closing the keyboard causes the lower 20% of the screen to be white, erasing the main screen background. 

Same issue with My Cars dialog. 

Is it possible to dismiss help panel when user touches outside of it?

**Comment by aesculus** [comment]
OK. I will take a look.

>Is it possible to dismiss help panel when user touches outside of it?

Maybe. Remember I had to hack this so anything is fair game at this point.

**Comment by EVGrokker** [comment]
Understood. Interaction with the waypoint inspector panel style seems to work better the Settings panel style.

**Comment by aesculus** [comment]
Yeah but still have the keyboard issue.

I think I can find a way to take care of the white bottom on My Cars and Settings.  Just have to refresh the screen.

**Comment by aesculus** [comment]
Another hack for the hack. Test in a few minutes on (8).

There will be a slight flash of the keyboard perhaps, but it will go away quickly. (I hope).
