### ISSUE TITLE
Displaying help in settings, my car, plan trip can't be done twice

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#194]
1.1.3 (8)
Opening help then dismissing, then attempting to reopen fails.
Can't touch away from help to dismiss. 
Touching away from dialog on new trip puts focus in first text edit box

**Comment by EVGrokker** [comment]
Also, very first invocation of help from new trip screen after clean install exited app. Will try to replicate.

**Comment by EVGrokker** [comment]
The problem when touching outside the help panel is that the touch is grabbed by the lower panel, causing focus to go into whatever dialog control is below the touch area. Rats.

**Comment by aesculus** [comment]
Which dialog is this? Or all?

Is it OK on non dialogs like main and trips and segment details?

**Comment by aesculus** [comment]
OK. I see this on all the dialogs. Will look at it.

**Comment by EVGrokker** [comment]
There seem to be two panel styles: the one used for Settings (I'll call that a dialog) and the one used for the waypoint inspector (I'll call that a popup). The dialog style panel has the problems. The pop-up style panels are working nicely.

**Comment by aesculus** [comment]
Interesting. They are the same under the covers.

But New Trip and Add/Edit Waypoint are a bit different in that they have two deal with two sources. Maybe that's the difference.

I see the same issues with Rate and Filter too as well as Cars and Settings.

>The problem when touching outside the help panel is that the touch is grabbed by the lower panel, causing focus to go into whatever dialog control is below the touch area. Rats.

I need to try this on the iPhone. Not an issue in the iPad. But if you tap on the help it puts focus on the dialogs first element.  Not so if you just scroll.

**Comment by aesculus** [comment]
Ah. The helps from the map pops did not need the hack because they did not violate the "one dialog rule". Those popups are outside of the UI framework and are done by Google with some major hacking by me visually.

**Comment by EVGrokker** [comment]
One heavy-handed approach would be to dismiss the lower (dialog style) panel on iPhone only when displaying help. A hack, but less offensive than focus going to an invisible control. Maybe revisit later in a minor release.

**Comment by aesculus** [comment]
Can you send me a screen shot of the lower panel area so I am certain I am dealing with the same issue?

I had to focus on the help icon so it would not go to another control. I think I can unfocus that just after which hopefully fixes the problem of not being able to go back to the help panel again.

**Comment by EVGrokker** [comment]
Touching the help panel inside the origin control below results in the keyboard popping up:



G

**Comment by aesculus** [comment]
I am still not getting where to touch to get the keyboard to pop up.

**Comment by aesculus** [comment]
I got rid of the problem of not being able to open the help twice. Now to figure out the tap problem

**Comment by EVGrokker** [comment]
I only have my phone with me and I'm trying to figure out how to paste an image without success. 

I will email you the image separately and then try to explain.

**Comment by aesculus** [comment]
OK. It's the same problem I am trying to solve. Tap anywhere on the help and it puts focus on the first field in the calling dialog. Working on it.

**Comment by EVGrokker** [comment]
Bring up help on the iPhone so that the help panel overlays the new trip dialog. Touching the help panel in an area that overlays an edit control, like the origin field causes focus to shift to that control while help is still displayed. And of course touching in an edit control brings up the keyboard.

**Comment by EVGrokker** [comment]
Ok, you understand.

**Comment by aesculus** [comment]
Actually touching anywhere on the help panel is causing this.  Reading your first description I thought it might be something different so I wanted to be sure.

**Comment by aesculus** [comment]
While I have you. You will notice some of the panels have the (X) always at the top and some the (X) scrolls with the panel title. Which do you prefer?

I kind of favor the fixed one functionally and the scrolling one visually

**Comment by EVGrokker** [comment]
I'm assuming that the 'x' is a requirement. If that's true, I'd rather see it fixed at the true top of the panel next to the title. If you could use CSS to give the top title line of the panel a darker, contrasting background color, that would help sell the close button.

**Comment by aesculus** [comment]
Its a requirement for the panels I mentioned in the other thread. It was part of the hack.  If I take some more time and exclude these panels then perhaps I can find a hack that does not need the button or have the focus problem.

**Comment by EVGrokker** [comment]
Agreed.

**Comment by EVGrokker** [comment]
Wow, nice.

**Comment by aesculus** [comment]
I can't find a better way to do this than what we have so I am going to attempt to clean it up and make it more solid. Just did not have the time before. Hope to get an update out for beta this evening.

See the need for Add Segment help and to review the Archive Trip one I made.

**Comment by aesculus** [comment]
Fixed in V1.1.3
