### ISSUE TITLE
New Trip, Settings  Help panel feedback

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#195]
1.1.3 (10)

Opening help, scrolling to bottom and back to top, 'x' is missing. Repeat scroll to bottom, back to top, 'x' now visible. 

Touching in help panel still activates first edit control in lower panel.

Settings: does not have the edit control activation problem, because there are no edit controls.

For both Settings and My Car panels, dragging up to scroll past the bottom of the panel, causing the ios springy look, the '?' icon doesn't spring up with the rest of the panel, it stays in place. Dragging the dialog down does properly move the '?' icon in place on the dialog.

**Comment by EVGrokker** [comment]
(disappearing 'x' was only the first time)

**Comment by EVGrokker** [comment]
Edit Segment Details behavior is different. Touching in help panel does not activate underlying text edit control while help is displayed, but when help is dismissed edit control is activated, keyboard shows then hides.

**Comment by aesculus** [comment]
I'll see what I can find. 

Do any work ok?

**Comment by aesculus** [comment]
The help that does not work is Settings, My Car, Maintain Favorites, Add/Edit Waypoint, New Trip, Edit Trip Segments. The others should be fine. They don't need my hack or the close button.

I need to get some very important functional fixes out that are keeping people from using the app.  So I propose that I hide the above help items, and release the app ASAP. While we are waiting on Apple I can see if there is a more solid way to get the help for the affected panels.  If I come up with a fix in the next day then I can always override the app that Apple has although it will set the distribution out.

**Comment by aesculus** [comment]
> For both Settings and My Car panels, dragging up to scroll past the bottom of the panel, causing the ios springy look, the '?' icon doesn't spring up with the rest of the panel, it stays in place. Dragging the dialog down does properly move the '?' icon in place on the dialog.

I need to couple the ? with the buttons so they move as a unit

**Comment by EVGrokker** [comment]
I agree that hiding the help button associated with the dialog style panels is best for now, until you have more time to spend. Getting the updated app into the hands of users is more important.

**Comment by aesculus** [comment]
Fixed in V1.1.3
