### ISSUE TITLE
Location services checkbox

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#197]
V 1.1.3 (10)
During a fresh install, if I decline to enable location services, EVTO grays out the unchecked Location Services checkbox in Settings.

Now I decide to enable location services. The settings checkbox is disabled, so I go to iOS device settings, privacy, allowing EVTO to access location while using the app. 

I go back to EVTO settings, expecting to see the Location Services checkbox not grayed out. But it's still grayed out. 

Thoughts: can you query the device privacy settings when displaying EVTO's Settings dialog to decide whether to enable or disable the checkbox? If so, that's the most elegant solution. If the user has changed privacy settings, they now can tick the Location Services checkbox in Settings. 

If you can't query the system to determine if the user has enabled location services for EVTO, you need to leave the Location Services checkbox enabled (not grayed out) always. If user ticks the checkbox but has not granted EVTO access at the system level, you would display a popup telling them to enable location services in their device settings.

Otherwise, there's no path to enable location services in the app after initially declining during installation.

**Comment by aesculus** [comment]
I just removed this whole location disable stuff.

Check it out in V1.1.4 (2)

**Comment by EVGrokker** [comment]
V 1.1.4(2)
I'm not seeing EVTO listed in the iOS Settings|Privacy|Location services list. Could this be related to the fact that it's a beta?

**Comment by EVGrokker** [comment]
I had to plan my first trip before I saw the 'Allow EVTO to access your current location?' dialog. I had already visited the Settings page and toggled the Location checkbox. No need to reopen.

**Comment by EVGrokker** [comment]
v 1.2 (2)
I'm reopening this. The following sequence doesn't flow correctly:
1. Fresh install, don't allow location services.
2. Calculate a simple trip.
3. Touch location icon, notice it doesn't do anything. 
4. Consult the Help screen, note that Location Services must be enabled for Location to work.
5. Go to Settings, enable Location Services.
6. Try to use Locate button. It doesn't work.
7. Reopen Settings, note that Location Services is unchecked, even though I checked it in step 5.

If the user toggles Location Services on within the app, you need to interrogate the system to discover if EVTO has access at the system level. If not, you need to display the dialog that requests user permission to enable location access.

**Comment by aesculus** [comment]
This behavior has changed since this post. You can no longer create a trip when location services is off if you don't put in an origin.

You cannot toggle location services in settings because the app was denied access to location features. When you turn them on at the device level then the settings should automatically be set to Location checked.
