### ISSUE TITLE
Add Segment: Help Text

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#199]
<p><i>Add a new segment to an existing trip.</i><super>†</super></p>

<p>Extend your trip by adding a new segment to the end of your current trip. Used to incrementally plan a multi-day road trip.</p>

<h4>Destination</h4>
<p>Touch in the Destination field to specify your trip's end point, using an address or business name. 
Search results are dynamically updated as you type.</p>

<p>Select a favorite waypoint by touching the heart icon, then selecting a favorite from the list.</p>
    
<h4>Destination Charger Type:</h4>
<p>If your destination offers charging, select the charger type from the dropdown list control. This 
allows EVTO to calculate the amount of time required to recharge to your preferred initial State of 
Charge (SoC), specified in <strong>Settings</strong>.</p>  
    
<h4>Waypoint Charger Selection:</h4>
<p><strong>Auto</strong> tells EVTO to automatically select supercharger stops along your route. <strong>Manual</strong> tells EVTO that you will manually select your charging 
locations. If your route requires the use of non-Tesla charging stations, select <strong>Manual</strong>, then add charging waypoints interactively from the map.</p>  

<p><super>†</super><i>Requires Subscription IAP</p>

**Comment by EVGrokker** [comment]
(Add this after the italicized description)

Extend your trip by adding a new segment to the end of your current trip. Used to incrementally plan a multi-day road trip.

(Also, under Waypoint Charger Selection, suggest removing 'Selecting' from first two sentences.)

**Comment by aesculus** [comment]
Changes made in V1.1.4

**Comment by EVGrokker** [comment]
v 1.2.0 (78)

Updated to indicate Pro version feature.

**Comment by aesculus** [comment]
Updated in V1.2 (79)

**Comment by EVGrokker** [comment]
Updated to include addition of Departure/Arrival time feature.

**Comment by aesculus** [comment]
Updated in app >V1.2 (99). Also updated subscription IAP info
