### ISSUE TITLE
Add the ability for a user to have their own car picture as the background.

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#2]

**Comment by EVGrokker** [comment]
This should be a per-defined car image. In other words, with a possible total of 5 cars, each car could have a different image displayed on the Main screen when it's the actively selected vehicle. Options might include both Paste from clipboard and Select from camera roll.

**Comment by aesculus** [comment]
It will probably have to be from the Camera roll.

**Comment by EVGrokker** [comment]
Agreed, motivated users can easily figure out how to get non-photo images into their camera roll.

**Comment by aesculus** [comment]
Changed in 4.0 to have no car
