### ISSUE TITLE
Feedback Report Help

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#200]

**Comment by EVGrokker** [comment]
I know you're going to think someone's hijacked my GitHub account, but I actually don't think this dialog needs a help button. You already have descriptive text at the top, and the choices seem self-descriptive. If you feel strongly it should be there for consistency, assign it to and I will get to it later in the week.

**Comment by aesculus** [comment]
I just thought for consistency since it is the only dialog that did not have a help button.

**Comment by EVGrokker** [comment]
Will do.

**Comment by EVGrokker** [comment]
Feedback help text is in issue #210.

**Comment by aesculus** [comment]
Done V1.1.4
