### ISSUE TITLE
Charger inspector - view icon disabled

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#202]
I'm poking around the map with the charger or supercharger overlay enabled. Touching a charger icon displays the inspector, but the view icon is always disabled.

**Comment by aesculus** [comment]
Do you need to Restore Purchases? This is a Pro feature

**Comment by EVGrokker** [comment]
Didn't realize that. Is that called out in the local help?

**Comment by EVGrokker** [comment]
Reopen that issue and I'll rewrite that local help for next release.

**Comment by aesculus** [comment]
> Didn't realize that. Is that called out in the local help?

It is now. :-)
