### ISSUE TITLE
Charger inspector icon layout

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#203]
There are only three icons displayed in the charger inspector - help, view, require. Suggest you place those in the same positions they would be in the five-icon layout for visual consistency. 

I think it would be fine to add disabled 'x' and pencil. They're not meaningful when the user is inspecting a potential charger location, but as soon as they pin (require) it, they become enabled. 

The benefit is that the user can rely on the layout always being consistent with the inspector.

**Comment by aesculus** [comment]
Added V1.1.4
