### ISSUE TITLE
Provide a way to preserve the my cars, favorites and settings between installs

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#209]
Right now there is no off device storage. You can share the trips with yourself but the My Cars, Settings and Favorites will all be lost.

This feature would preserve those user defined characteristics between installs. And added feature could be to share them between devices.

**Comment by EVGrokker** [comment]
For iOS devices, the obvious solution would be using iCloud storage. Any device logged into the iCloud account would be able to restore settings cached in the cloud.

**Comment by aesculus** [comment]
I'll look into this a bit deeper. I think Android may have something similar, but then of course I now have to maintain two different solutions.  This is related to storage of all trip data off device too. https://github.com/aesculus/EVTO-App-Feedback/issues/215

**Comment by aesculus** [comment]
Replaced with #542
