### ISSUE TITLE
Feedback Report dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#210]
Chris: Does Android have a review system like iOS? If so, and you want to solicit ratings in a low-key fashion, I'd suggest linking 'App Store' in the last paragraph to the appropriate, device-specific url for rating the app.

---

<h3>Feedback</h3>
<p><I>Let us know what's on your mind!</i></p>

<p>Use this form to quickly prepare an email with a comment, question or bug report. If your comment applies to a specific trip that you're currently planning, check the <strong>Include active trip</strong> checkbox to share your current trip with our development team.</p>
<p>We will respond to your feedback as quickly as possible.</p>
<p>If you're finding EVTO to be a useful companion to your Tesla ownership, please consider leaving a review in the App Store.</p>

**Comment by aesculus** [comment]
Yes Android has the same type of review mechanism. I even got dinged by a European user who got the app somehow before it was cleared to that market and complained it did not route correctly. :-)

Added in V1.1.4
