### ISSUE TITLE
Edit Segment Details: Dest. Reserve (mi) disabled (standard install)

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#214]
Is this a Pro version feature? If so, this should be called out in Help.

**Comment by aesculus** [comment]
Yes. It is. And so is setting the minimum stop time and adjusting the waypoint SOC

http://www.digitalautoguides.com/evto-features/

**Comment by EVGrokker** [comment]
Updated issue #181, noting IAP feature.

**Comment by EVGrokker** [comment]
Updated issue #170, noting IAP feature.

**Comment by aesculus** [comment]
Done in V1.1.4
