### ISSUE TITLE
Delete Cached Places Closest Chargers if Over 30 Days

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#216]
The server stores a list of places closest chargers so it does not keep repeating the same closest charger associations. Today these are manually deleted after 30 days in order to allow for new chargers to be deployed.

It would be nice if the server automatically refreshed these cached entries whenever they are accessed and found to be more than 30 days old.

**Comment by EVGrokker** [comment]
Is there a monetary cost associated with this? How would the app improve with this enhancement?

**Comment by aesculus** [comment]
There is a monetary cost (Google service) for not caching. Each routing request has to go look for closest chargers. Since the chargers never move and are rarely added to, it made no sense to keep repeating the same requests and getting the same answers (always based on proximity and fairly static drive times, not dynamic things).

The reason for discarding them after 30 days is that it would reduce storage (old school thinking) and allow for any new chargers that may have been added near the location as well as for any refinements Google made in drive times (not sure how often that happens).

**Comment by aesculus** [comment]
Moving to an new approach with issue #538
