### ISSUE TITLE
Edit Segment Details Help panel - focus goes to edit control when opening help

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#217]
v 1.1.4(1)

The problem we saw in 1.1.3 with the Help panel causing the first text edit field to become active is still present in the latest version. Similar to issue #193. I'm not seeing the problem with Settings or My Cars, so apparently you have a solution that needs to be applied here. I haven't tested the other dialogs of this style, this was the first.

---

![edit segment details](https://cloud.githubusercontent.com/assets/26678403/25030378/d8cc3194-2081-11e7-97db-8214bf939228.PNG)

**Comment by aesculus** [comment]
Is it just this one or others?  I was pretty sure I checked them out beforehand but who knows.

**Comment by aesculus** [comment]
OK. Found it. I had removed something (actually just commented it out luckily), that I thought was superfluous. It ended up being the fix for this problem that does not happen in every panel as you noticed.

Not sure what it is but I think this should fix it in V 1.1.4 (2)

**Comment by EVGrokker** [comment]
This seems to be fixed in 1.1.4(2) on the iPhone 7+.

**Comment by aesculus** [comment]
Cool
