### ISSUE TITLE
Add Waypoint dialog: Show magnified numbers for Minimum Stop Time, Minimum SoC

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#219]
In the Settings dialog, adjusting the SoC Reserve or Default Origin SoC sliders pops up a nice magnified window showing the slider value as you adjust it.

The Edit Waypoint dialog should have the same behavior for Minimum Stop Time and Minimum SoC sliders.

All dialogs with sliders should behave this way.

**Comment by aesculus** [comment]
Fixed in V1.1.4 (3)
