### ISSUE TITLE
Implement 'Swipe left to Delete' in Current Trips and Trips Archive

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#22]
Suggestion:
- Trips are listed in compact list form with Name/Date in the title bar (where date is the last time the trip was revised)
- Sorting options are By Name, or By Date.
- Touching a right-facing disclosure triangle at the left of the trip title bar expands the compact form to show the full detail of the trip, as you currently do, replacing the right-facing triangle with downward facing triangle to collapse the detail.
- Swiping left on a trip name title bar shows the Delete button, swiping right cancels.
- Touching the title bar makes that the active trip.

**Comment by EVGrokker** [comment]
See related discussion in #136 when reviewing this issue.

**Comment by aesculus** [comment]
In V1.2 (59) I have implemented a very simple swipe left to expose a red delete button on current trips and archive trips.  If you swipe right it will remove it. The Delete button will also be removed if you collapse or open another group or sort the group.

**Comment by aesculus** [comment]
Do you want Edit, Archive and Restore buttons overlayed on the list like the Delete button? There would be three buttons exposed, basically the singular action buttons for each item.

I noticed that the iOS mail app does this.

Note with the way I redesigned the layout a few releases ago I can't (easily) push the list item aside to expose the buttons but had to overlay them.  Just a nuanced UI thing but ...

**Comment by EVGrokker** [comment]
I'd like to see how it looks with Edit and Delete. Archive is likely a group action, so I think you can safely leave it out.

You already have a simple touch action to Restore a trip, which is intuitive. There should be some action associated with a simple touch, and Restore is the most obvious.

**Comment by aesculus** [comment]
This is added in V1.2 (61)

**Comment by EVGrokker** [comment]
This looks good. I'll point out the obvious, which is that this is not a native iOS implementation of a swipe on an item, but the behavior is similar enough that iOS users should accept it. 

I'd suggest removing 'Edit Trip Details' from the menu, since it would never make sense to multi-select trips for this function, and the swipe action is easier and more intuitive.

However, 'Delete' does make sense for multiple select, and the menu item is already labeled 'Delete Trips' (plural), so I'd leave that in place in the Current Trips menu.

After you weigh in, I'll edit the Current Trips help text to conform to the implementation.

**Comment by aesculus** [comment]
> I'd suggest removing 'Edit Trip Details' from the menu, since it would never make sense to multi-select trips for this function, and the swipe action is easier and more intuitive.

Doesn't Trip Status have the same implication? Note you can get to Trip Status today by selecting the gavel icon.  Maybe we should also add a button like Delete and Edit for Status too?

**Comment by EVGrokker** [comment]
Yes, you're right. Trip Status is already available by touching the gavel button. That can also be removed from the menu.

With respect to adding a third 'Status' button, along with 'Edit' and 'Delete' when the item is swiped, that's certainly an option, but in playing with this, I'm wondering if it might make more sense to integrate changing the status of a trip with the Edit Trip Details dialog. Your thoughts?

**Comment by aesculus** [comment]
>I'm wondering if it might make more sense to integrate changing the status of a trip with the Edit Trip Details dialog. Your thoughts?

We ran out of room and decided that a summary of the trip along with the ability to change from planned to completed along with the rating was the best option.

I will add the third button because I suspect many will not realize they can touch the gavel.

**Comment by aesculus** [comment]
Status button was added in V1.2 (62)
