### ISSUE TITLE
Increase Segment Summary title bar font size, spacing 

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#221]
The font size for Segment Summary header should be at least as large as the individual waypoint names in the list below. Also, I think a bit more space between the icon and 'Segment Summary' would improve the appearance of the header.

---
![segment summary](https://cloud.githubusercontent.com/assets/26678403/25041344/abf37cb8-20cc-11e7-838f-8ed5ebd3a976.PNG)

**Comment by aesculus** [comment]
I think this issue has been superseded.
