### ISSUE TITLE
Increase Segment Details header font size

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#222]
The font size of the 'Segment Waypoints' header above the list of segment waypoints should be increased to be at least the same size as the waypoint names in the list below it.

---
![segment details](https://cloud.githubusercontent.com/assets/26678403/25041438/3bfb5e16-20cd-11e7-96c0-6a5edaa07945.PNG)

**Comment by aesculus** [comment]
I am going to leave this one alone until we redesign this panel post 1.2
