### ISSUE TITLE
Trip Segments header should be renamed, resized

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#223]
The Trip Segments panel should be renamed to simply 'Trip Segments ~~Summary~~'.

The font size should be increased to at least the same size as the names of the individual segments listed. Adding a bit of space between the icon and the title would improve the appearance.

---

![trip segments](https://cloud.githubusercontent.com/assets/26678403/25041513/c7df0770-20cd-11e7-82f9-9bad2064441c.PNG)

**Comment by aesculus** [comment]
I have updated the title and icon position.

Need to discuss the size of the header font. I was trying to duplicate the car popup dialog which uses a smaller font in the header.

**Comment by EVGrokker** [comment]
v 1.1.4(4)

The header font still looks smaller than the list items font.. This is one of those situations where I think it makes more sense to make it look correct on the device, rather than trying to mimic the car display appearance.

**Comment by aesculus** [comment]
If you like what I did for the Segment Summary, I can do the same for this one. Holding for your opinion.

**Comment by EVGrokker** [comment]
Same comments for #227 apply here - make the top header fixed, move the metrics summary to the top as part of the header.
This issue should be merged with #279.

**Comment by aesculus** [comment]
The size has been changed in V1.2 (37)

Still waiting for final word if it should be call Trip Browser.

**Comment by EVGrokker** [comment]
v 1.2.0 (37)

Looks good.
