### ISSUE TITLE
Responsive layout proposal for phone-size devices: Disable landscape orientation

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#224]
There are many layout issues when attempting to use EVTO in landscape mode. I could begin creating issues listing the observed problems, but before doing so, I'd like to propose that you consider simply disabling landscape mode on phone-sized devices.

As far as I can tell, the only scenario in which landscape mode is useful, or required, is in the display of the Segment Summary and Segment Details panel, where it simply isn't readable in portrait mode. I'd suggest redesigning those info panels for phone-sized devices using iconography to allow them to be rendered intelligibly in portrait mode. If you concur, we can open an issue and discuss the implementation there.

One could make the case that for some routes, landscape mode would be preferable, but I think you could avoid a lot of headaches by disabling it now, and perhaps revisit it at some future date after the rest of the app has stabilized.

It's worth noting that Plugshare does not support landscape mode, nor does the Tesla mobile app. Remote S does support it, but it looks ridiculous.

**Comment by aesculus** [comment]
I have removed the ability to do Edit Trip Details, Edit/Add Waypoint and New Trip in landscape mode on phones. What shows is the Cancel button. If they rotate the device back again they can access the features.

Applied in V1.1.4 (4)
