### ISSUE TITLE
Main menu | Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#225]
Now that we have local help for the Settings dialog, the verbose description of Settings can be removed from the Main help text:

Suggested replacement:

[gear] **Settings**
_Displays the Settings dialog_
Adjust personal preferences describing your driving style and geographic location.

**Comment by aesculus** [comment]
Changed in V1.1.4 (3)

**Comment by EVGrokker** [comment]
Needs to be revised for 1.2.0

**Comment by EVGrokker** [comment]
Superseded by #412.
