### ISSUE TITLE
Plan Trip help text: Edits

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#226]
V 1.1.4(2)

**Zoom to Route**
Touch the globe to recenter the map and zoom to fit the ~~segments~~ segment's route. A long press ~~will zoom~~ zooms to display all segments of a multi-segment trip.

---

**Trip Segments ~~Summary~~** (see issue #223)

---

**Other Chargers**
Touch to toggle the display of non-supercharger locations. Use the **Filter Chargers** dialog to select the type of chargers to display.

---

**Pins**
Trip segments are marked with an Origin pin, a Destination pin, ~~and most likely additional Waypoint pins~~ automatic charging stops added by EVTO, and any additional waypoints you've added manually.

---

**Origin Pins**
Origin pins are blue with a white interior. An origin's SoC ~~depends upon the level specified in the Edit Segment Details dialog~~ is established by the default SoC Reserve in the **Settings** dialog, or the Origin SoC in the **Edit Segment Details** dialog.

---

**Destination Pins** (white)
…
Destination pins are white when a previous segment ~~has been changed but this route has not been optimized afterwards~~ has been updated, requiring this segment to be recalculated. To recalculate this segment, select Optimize Segment from the Plan Trip menu.

---

**New Trip**
…
Enabling the ~'This is an out and back trip'~ **This is an out and back trip** checkbox plans the trip in two segments,

**Comment by aesculus** [comment]
> Enabling the 'This is an out and back trip' This is an out and back trip checkbox plans the trip in two segments,

Should this now be a Plan as a round trip?

Fixed in V1.1.4 (3)

**Comment by EVGrokker** [comment]
**New Trip**
…
Enabling the ~'This is an out and back trip'~ **Plan as a round trip** checkbox plans the trip in two segments,

**Comment by EVGrokker** [comment]
Needs to revised for 1.2.0

**Comment by EVGrokker** [comment]
Superseded by #411
