### ISSUE TITLE
Waypoint Inspector help edits V1.1.4(2)

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#228]
_Given the rearrangement of the icon row in V1.1.4(2), the order of the help text needs to be rearranged to match. Added section for Share icon._

<h3>Waypoint Inspector</h3>
<p><i>Review and manage waypoint details.</i></p>

<h4>[heart] Toggle Favorite status</h4>
<p>Touch the heart icon to toggle this waypoint's Favorite status. Favorite waypoints may be quickly accessed when creating a new trip or adding waypoints to an existing trip.</p>

<h4>[eyeball] View location<super>†</super></h4>
<p>Touch the eyeball icon to display a dynamic Google Street View of the waypoint location. To return to the Waypoint Inspector, touch the arrow to the left of the waypoint address. </p>

<h4>[share] Share<super>†</super></h4>
<p>Touch the share icon to export this waypoint to your calendar, or email the waypoint description.</p>
<p><super>†Requires Pro version IAP</super></p>

<h4>[scissors] Split current segment into two segments<super>†</super></h4>
<p>The current route may be split at any waypoint by touching the scissors icon. The first segment will use the split point as its Destination. The second segment will use the split point as its Origin.</p>  
<p><super>†Requires Pro version IAP</super></p>
    
<h4>[pin] Convert automatic supercharger stop to waypoint</h4>
<p>When trips are optimized, EVTO automatically selects superchargers along your route, marked with an 'A'. Subsequent route optimizations may automatically select different superchargers, depending on weather conditions and your vehicle's characteristics. To convert an automatically selected supercharger as a required waypoint along your route, touch the pin icon, converting it to a regular waypoint.</p>  
    
<h4>[pencil] Edit waypoint details</h4>
<p>Touch the pencil icon to display the <strong>Edit Waypoint</strong> dialog, where individual waypoint details are managed.</p>
    
<h4>[X] Remove waypoint from route</h4>
<p>Touch the delete icon to remove this waypoint from the current segment. The updated route will be recalculated.</p>

**Comment by aesculus** [comment]
Fixed in V1.1.3 (4).  I also updated the icon to your favorite
![share_icon](https://cloud.githubusercontent.com/assets/283364/25067240/ed811e76-21f1-11e7-859d-07d72ebfc17c.png)

**Comment by EVGrokker** [comment]
When the Share icon is displayed in the Waypoint Inspector in its disabled state, it looks faint compared to the other disabled icons, and perhaps smaller. I haven't seen it enabled yet. Can you review for appearance, size and placement consistency (within the containing circle)?

**Comment by EVGrokker** [comment]
Help text needs to be revised to describe segment merging when deleting a hinge point (pseudo origin/destination).

**Comment by aesculus** [comment]
And don't forget to add the special case if you delete the last segments destination it will delete that entire segment, waypoints and all. Poof.

**Comment by aesculus** [comment]
Isn't this issue superseded by issue #305?

**Comment by EVGrokker** [comment]
Closed, #305 is the currently correct WI help text.
