### ISSUE TITLE
Plan tab: Google POIs - adding to route, 'View on Google Maps' should be removed

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#229]
This issue may be beyond your control with the Google API, but I'll note it anyway.

- Create a Origin - Destination route, say Seattle to Moclips WA.
- Zoom on in the route until you see a POI near the route. For example, I'm zoomed into Olympia WA, and the "Hands On Children's Museum" POI is visible just north of downtown.
- Touch the POI. A popup is displayed with the name and address of the POI, and a clickable 'View on Google Maps'.

Two observations:
1. What I'd expect to see here is 'Add to route'. If that's not possible, it would be useful to be able to copy the name/address so that it can be pasted into the 'Add Waypoint' dialog. Note that a long press on the POI does not trigger the Add Waypoint dialog.
2. The 'View on Google Maps' link is non-functional, which is fine, as there's no need to leave EVTO to see this. Is there any way to remove it?

**Comment by aesculus** [comment]
Interestingly Google just allowed access to these via an API.  I'll see how easy it is to implement.

**Comment by aesculus** [comment]
Removed these in V1.1.4 (9).  I will leave this open so we can revisit if/when we turn these on to make them waypoints

**Comment by EVGrokker** [comment]
This behavior is preferable for now. Touching somewhere on the map does nothing. Touching and dragging moves the map. Touching and holding brings up the Add Waypoint dialog.

**Comment by EVGrokker** [comment]
Retitled the issue. This is now an enhancement to be able to touch Google POIs on the map and add them to the current route.

**Comment by aesculus** [comment]
This is totally doable technically. We just have to figure out when.

**Comment by EVGrokker** [comment]
Currently proposed for 1.4.

**Comment by EVGrokker** [comment]
Original issue is resolved.
