### ISSUE TITLE
Feedback Report - clear fields after Prepare is touched

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#231]
Once a user has composed a feedback report and control is transferred to the email program, the fields should be reset to the their default values. I started to compose another report and the comments field was still populated with my prior report's content.

If the user prepares some content, but cancels instead of touching Prepare, the content should be preserved. They may have returned to the app to check something before filing the report.

**Comment by aesculus** [comment]
Fixed in V1.1.4 (3)
