### ISSUE TITLE
Rethinking reserved energy at the conclusion of a segment

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#232]
Currently, there are three ways to inform EVTO that the user would like to reserve energy upon arriving at the destination:
1. **Edit Segment Details** dialog, _Dest. Reserve (mi)_.
2. **Edit Waypoint**, _Minimum Arrival SoC_.
3. **Edit Waypoint**, enable the **Plan last charging stop for a return trip** checkbox.

These are each valid approaches, satisfying different objectives for the destination's reserve power:
1. User wishes to have reserve energy for destination driving.
2. User wishes they had purchased a larger battery pack, aka range anxiety.
3. User wishes to preserve enough energy to get back to the last charging stop.

Arguably, 1 and 2 address the same objective - the user wants some SoC upon arrival at the destination. 1 is expressed in miles of range, 2 is expressed as a charge level.

3 is an odd duck. It's kind of like planning a segment and a half. You're not specifying where exactly you're going after you leave your original destination, but you know you're going to need a charge, wherever you're headed, so you've banked enough to get you back to the nearest supercharger passed en route to the destination.

Using 1 or 2 in combination with 3, each contributing to the reserve allocation, creates potential for confusion. The battery label when a user has either 1 or 2 together with 3 is, well, ugly.

I'd like to propose that you change the way you handle 3. The goal is preserving enough energy to get back to the last charging stop. I think a better approach would be to inform the user of the minimum SoC they will need upon departure to return to the last supercharger, but not attempt to pre-charge or reserve that energy on their behalf. 

In the Segment Summary dialog, you could add an entry after the destination pin, maybe a pin with a lighting bolt. It would represent the nearest supercharger passed on the way to this destination, and the minimum SoC upon leaving this destination that would be required to return to it. In other words, it's not a part of the segment, it's just an advisory letting them know what they'll need in the tank to get back to a supercharger.

Of course, it's up to the user to manage their destination reserve. They may need to go in search of a local charging stop using Plugshare or a secondary resource like RV Parky. You've given them the answer to the most critical question - how much do I need to get back to the mothership? Coming up with the needed power is some combo of scrimping on the banked reserve or scavenging a local power source. Or maybe they top off before arriving at the destination. Let them decide how to budget the energy.

Making this change adds value to the Segment Summary panel, and trains the user to think more independently about how to manage their power once they're navigating off-route. EVTO says "you need at least this much to get back to a known source of fast charging power."

And, it paves the way for another UI change I want to propose regarding split battery icons. See issue #233.

**Comment by aesculus** [comment]
> 3 is an odd duck. It's kind of like planning a segment and a half. You're not specifying where exactly you're going after you leave your original destination, but you know you're going to need a charge, wherever you're headed, so you've banked enough to get you back to the nearest supercharger passed en route to the destination.

It was intended to mimic the car's behavior, to return you to the last place you charged at.  This was done way before segmenting, round trips etc.

At this point I may be in favor of removing it. As you said it's a bit of an odd duck.  I would be willing to test Tesla owners to show me how to do this on the car. I bet the number is in the single digits percent-wise. :-)

**Comment by EVGrokker** [comment]
My vote would be to comment out this feature for now. If you get some squawks, it could be revisited, but my bet is that no one would seriously complain.

In the car, that feature is like a lifeline, because you're actually past the planning stage - you may need it. In the app, we have the luxury of using time travel to play what-if games.  It's simply not a needed lifeline in the planning stages.

**Comment by aesculus** [comment]
I have removed the ability to plan for returning to the last charger from the New Waypoint dialog in V 1.1.4 (8).

**Comment by aesculus** [comment]
There actually is a 4th way EVTO reserves energy at a destination:

If there is a MST segment next, EVTO tries to determine how much energy the user will need to get to the next charger.  It will boost up the charger on the prior charger enough so the destination has enough energy to get the user to the next charging stop on their route,

So you may in fact see arrival SoCs at destinations that are larger than you expect.

**Comment by aesculus** [comment]
I want to reopen this discussion.

Right now it appears that reserving energy for local travel is turned off for multi segmented trips. That is probably a bug, but before I attempt to fix it I want to make sure of what we want to happen here.

The goal is for user to reserve enough energy to travel locally and then for me to throw that energy away in the start of the next segment. 

So do we want to allow destination travel at the hinge points?  If so I think I have some work to do here and I hope the server does not crater because of it. :-(

**Comment by EVGrokker** [comment]
It's turned off in Edit Segment Details, but it's still possible to bump the arrival SoC in the Waypoint Inspector for the destination.

We definitely need to support destination travel at hinge points.

This highlights the fact that there are multiple ways to reserve energy for local travel. It also draws in the discussion from #456 about philosophy and design intent of the app.

My preference would be that there's one way to reserve energy at destinations, whether they are single-segment final destinations or hinge-point intermediate destinations. And there's one interface to adjust for extra charging at a required charging stop.

My sense is that it makes more sense to separate charging overrides in the following way:

- Reserving energy for local travel upon arrival at a destination is done with Edit Segment Details
- Adjusting charging parameters (always upwards) for an individual charging stop is done with the Edit Waypoint dialog.

You can argue that sitting in a supercharger for an extra 30 minutes accomplishes the same thing as reserving for local travel, and I'd agree. We're not trying to force the user into a particular mental model of how to do things, but instead we're trying to offer a UI that matches the way they think about managing energy during the trip.

**Comment by aesculus** [comment]
> It's turned off in Edit Segment Details, but it's still possible to bump the arrival SoC in the Waypoint Inspector for the destination.

Yeah but that's completely different. Changing the arrival SoC means that the energy is availble for the next part of the trip (ok if it's the destination then you could make the case the trip is over ...)

When you reserve energy for destination travel it has to be accounted for in the prior charging scheme, but that energy is considered having been used when the trip starts again. Poof - gone.

>You can argue that sitting in a supercharger for an extra 30 minutes accomplishes the same thing as reserving for local travel, and I'd agree.

Only from a charging perspective, but not how the app will use that energy as above.

>We're not trying to force the user into a particular mental model of how to do things, but instead we're trying to offer a UI that matches the way they think about managing energy during the trip.

You're not but I am. :-)

Again my religious debate on how the app should figure out when and where to charge.
