### ISSUE TITLE
Split battery proposal (revisited)

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#233]
A continuation of issue #126, encompassing all potential split battery displays, and issue #232, revising how destination reserve SoC is managed. 

For this discussion, 'base SoC' means the portion of the battery from 0% to the Minimum Arrival SoC. The 'secondary SoC' is the dynamic portion, representing either a reserve or a charging target. 

Where is a split battery presentation useful?
1. Arriving at a destination. The base SoC portion is the predicted SoC upon arrival. The secondary SoC is the energy reserved by the user, either in **Edit Segment Details** or the destination's _Minimum Arrival SoC_. The graphic tells the user at a glance what to expect upon arrival, and how much of that was reserved for local driving.
2. Charging stops en route. The base SoC is the amount upon arrival. The secondary SoC is the target charging increment for the stop. 

These split battery icons would be shown in the waypoint inspector, and the Segment Waypoints area of Segment Details. Not all pins would use a split battery icon. An origin pin shows only the departure SoC, a single value. A non-charging waypoint shows the arrival/departure SoC, also a single value.

We need to communicate the base amount, which is common across all SoC icons. The style is already established, a solid rectangle (typically green, sometimes red or yellow, depending on SoC upon arrival).

The secondary SoC can represent one of two dynamic changes in SoC - either the reserve area is being consumed by local driving, dropping from the upper line to the dividing line, or the reserve area is being recharged, rising from the dividing line up to the charging target.

My proposal is that we use red slashed diagonal lines to represent projected consumption, since it represents a drain or a loss. We use green slashed diagonal lines to represent the charging target, since it represents a gain, or replenishment.

**Minimum SoC / Reserve (red, dropping, to be consumed), displayed with Destinations:**
![soc reserve](https://cloud.githubusercontent.com/assets/26678403/25053968/d21e41ac-2117-11e7-847e-4027546a183d.png)

**Arrival SoC / Charging target (green, rising, to be recharged), displayed with charging stops:**
![soc charging target](https://cloud.githubusercontent.com/assets/26678403/25053966/cf9f1c08-2117-11e7-9050-a505d39066bc.png)

**Comment by EVGrokker** [comment]
Here's a revised version of the Minimum SoC / Reserve icon with a gold color for the secondary section.  It doesn't look as threatening.

---
![soc reserve](https://cloud.githubusercontent.com/assets/26678403/25065142/dea6dc2c-21c6-11e7-8f6a-0ad8d756b7cd.png)

**Comment by aesculus** [comment]
I like that gold color

**Comment by EVGrokker** [comment]
It implies "valuable". Don't waste it. :)

**Comment by aesculus** [comment]
Implemented in V1.2 (23).
