### ISSUE TITLE
New Trip dialog help: edit

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#235]
The dagger noting that 'This is an out and back trip' should be superscripted: 

<h4>This is an out and back trip<super>†</super></h4>

**Comment by EVGrokker** [comment]
And it now should read (see issue #236):

<h4>Plan as a round trip<super>†</super></h4>

**Comment by aesculus** [comment]
Fixed in V1.1.4 (3)

FYI <super> does not work. I have to use <sup>. NBD. It's in my brain now but occasionally I forget to check.

**Comment by EVGrokker** [comment]
v 1.1.4(3)
Additional revision for Help:

Under Origin and Destination, insert [heart icon] before 'Select a favorite waypoint by touching the heart icon…'
