### ISSUE TITLE
New Trip dialog: Wording for out and back trip

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#236]
The wording for this feature is awkward. 

My sense is that 'Plan as round trip' would be more familiar to users.

One objection might be that you could also have a multi-segment trip whose final destination would be the same as the origin, and that would also be properly called a 'round trip'. Yes, but this is clearly an advanced trip, and users capable of planning this wouldn't be confused or misled by this checkbox.

**Comment by aesculus** [comment]
Are you referring to the checkbox label or the help panel?

**Comment by aesculus** [comment]
> One objection might be that you could also have a multi-segment trip whose final destination would be the same as the origin, and that would also be properly called a 'round trip'.

That is why it got labeled that way.

**Comment by EVGrokker** [comment]
>Are you referring to the checkbox label or the help panel?

The checkbox label, which of course then affects help downstream.

>>One objection might be that you could also have a multi-segment trip whose final destination would be the same as the origin, and that would also be properly called a 'round trip'.

>That is why it got labeled that way.

I understand, but I believe that simple round trips (two-segment) would be far more common among novice users. 'Round trip' would be for their benefit. Experienced users planning multi-segment trips would already understand how to return to the origin.

**Comment by aesculus** [comment]
Something to consider is the alternative where you put in the origin and destination as the same place and add waypoints. We discussed this before.

At first I did not think the app would do it but it does. So if I used the Out and Back checkbox as an indicator that someone just wanted to have a single segment trip that went somewhere and came back, would that be even better?  It would eliminate a lot of the confusion of the two segment stuff that many feel is over the top for a simple round trip.

**Comment by EVGrokker** [comment]
To clarify, you're proposing that a one-segment round trip would be constructed by inputting the same origin and destination, then inflating the trip with waypoints?

If that's the concept, my initial reaction is that it would not be an improvement over two-segment round trips. If I'm going somewhere, I have a goal in mind upon arrival - shopping, eating, visiting, whatever. There's some amount of time spent at the destination, then I intend to return. For me, I like thinking of the two segments as two separate events that have some things in common.

I wouldn't prevent a user from using the same origin and destination, then inflating to create a single-segment round trip. In fact, we could promote that as an advanced user tip, especially useful when you have a series of stops to make that bring you back to where you started, without any significant break time along the way. 

'Round trip' has a specific meaning in the travel industry. For an airline, it means that you're traveling to a destination then returning on another flight. Same for a train trip, bus trip, etc. I'm trying to leverage that commonly-understood meaning of the phrase.

**Comment by aesculus** [comment]
> To clarify, you're proposing that a one-segment round trip would be constructed by inputting the same origin and destination, then inflating the trip with waypoints?
No. You would input the origin (which would also be the destination) and the destination (which gets translated to a waypoint).

So essentially I would take the origin and make it the destination also, and then automatically add a waypoint that was what the user called the destination. Sounds tricky but it's just a magic trick.

> 'Round trip' has a specific meaning in the travel industry. For an airline, it means that you're traveling to a destination then returning on another flight. Same for a train trip, bus trip, etc. I'm trying to leverage that commonly-understood meaning of the phrase.

Exactly.  That is why I want to keep the Round Trip idea as a MST because it would most like be used for overnights etc. (don't ask me the number of times I have done same day round trips to Seattle or Dallas from Sacramento). :-)

The Out and Back idea came about because some users wanted to do same day trips to some place and return home again. I hacked the MST because I did not think I could do the single segment approach. You showed me I could a few weeks ago. so it's your fault. :-)

**Comment by EVGrokker** [comment]
We agree that we want to keep Round Trips as two-segment trips. That makes it a premium feature, probably the main reason someone would upgrade. Let's not give that away.

I just tried this, and it worked (almost) fine:
- New Trip (single segment, Auto). Origin: my home address. Destination: my home address.
- (Burlington supercharger was added as an automatic waypoint, which shouldn't have happened).
- Add Kirkland Costco as a waypoint.
- Add Seatac airport as a waypoint.

The route is exactly what I would expect, apart from the anomaly with the Burlington supercharger being added (I simply deleted it).

To summarize my position:
- Change the wording of the 'out and back' checkbox to **Plan as round trip**, as proposed in the opening comment of this issue. It would be grayed out in a standard install.
- Functionally, it's identical to the way out & back works today - it creates a two-segment round trip.
- Users wanting to do same-day round trips can use the advanced approach, entering the same address into both the Origin and Destination fields, then adding waypoints. There's no need to provide a special checkbox for this. I simply selected my home address from the Favorites list to populate both fields. Easy as can be.

**Comment by aesculus** [comment]
OK. What should we do about the same day out and backs? Should this be part of the infamous tips and tricks we have on another thread?

**Comment by EVGrokker** [comment]
I'll write up how to create same day out & back trips as an advanced tutorial. I'll start an issue with a checklist of Advanced Tips & Tricks that need to be written, with this as the first one.

I would suggest that these Advanced Tips & Tricks (AT&Ts) live on the website, not in the app.

**Comment by aesculus** [comment]
I changed the New Trip help accordingly too.

Fixed in V1.1.4 (3)

**Comment by aesculus** [comment]
> I would suggest that these Advanced Tips & Tricks (AT&Ts) live on the website, not in the app.

Ok. You do the text and I will build the web pages.

Should we add a menu item on the Main Panel menu like we have for FAQ and Tutorial?

**Comment by EVGrokker** [comment]
My first inclination is to have two sections for Tutorials, Beginner and Advanced. I'd rather not add another menu item.

**Comment by aesculus** [comment]
OK
