### ISSUE TITLE
Plan menu | Add Waypoint layout problems

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#237]
The layout for the Add Waypoint dialog broke in v 1.1.4(2):

---

![add waypoint from menu](https://cloud.githubusercontent.com/assets/26678403/25063497/d404601a-21a2-11e7-9015-395f55142ead.PNG)

**Comment by aesculus** [comment]
This happens sometimes. Will investigate how to prevent it. The quick fix is to leave the trip and come back to it.

**Comment by aesculus** [comment]
I cannot seem to find a way to reliably repeat this but do see it happening. I will try to post here if I can find a pattern

**Comment by aesculus** [comment]
I have made changes to this in V1.1.4 (9) in order to help the format. Since I cannot reliably reproduce it I am shooting a bit in the dark.

If we see other instances of this after V1.1.4 (9) we can comment here.

**Comment by aesculus** [comment]
I have worked on this again in V1.2 (37). Hopefully it's resolved and not totally flummoxed.
