### ISSUE TITLE
Invoking Add Waypoint dialog by pressing/holding on map location does not include Minimum time, SoC sliders

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#238]
v 1.1.4(2) 

This Add Waypoint dialog was invoked by pressing and holding on the map. The Minimum Stop Time and Minimum Arrival SoC sliders are missing. 

Also, note the same layout issue as #237.

---
![addwaypointfrommap](https://cloud.githubusercontent.com/assets/26678403/25063507/0bedae14-21a3-11e7-88fc-40b4d09ab6cb.PNG)

**Comment by aesculus** [comment]
I have noticed that too. It's an artifact of me trying to change the layout of the dialog based on device type and results of the search.

Definitely needs to be addressed.

The temp fix is to go back to the main panel and come back again.

**Comment by aesculus** [comment]
Fixed in V1.1.4 (3)
