### ISSUE TITLE
Missing Origin Prompt Should be More Obvious

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#239]
If a user creates a new trip and there is no origin (ie they have location services turned off or there was an error, the trip will be created and they will receive a warning that the first waypoint they define will be the origin.

When they start planning the trip the Add Waypoint dialog is forced upon them which is correct. However it does not clearly state that this waypoint is the origin. Since we disabled the waypoint names to remove confusion on where the user should actually place the location, the label that is placed in the name "Origin" is gray and does not stand out.

We need some other more obvious method of alerting the user that they are supplying the origin of the trip with this first Add Waypoint.

**Comment by EVGrokker** [comment]
Why not simply disallow New Trip creation without an origin?

**Comment by aesculus** [comment]
I probably need to enrich the logic for this. Right now I take the approach that the location services works. Later I find that it might not. I need to be more pessimistic I guess.

So I will look at validating the origin immediately.

**Comment by aesculus** [comment]
I have improved the location finding methods and in addition are making sure the user has selected an origin or has a valid location before saving the new trip.

Just in case something gets through, I have keep the logic in place to validate the origin later.

Fixed in V1.1.4 (3)
