### ISSUE TITLE
Segment Details panel: New design proposal

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#240]
Relevant issues: #224, #227 

As discussed previously, the data section of the Segment Details panel is unreadable in portrait format on a phone-sized device. #224 proposes eliminating landscape support. This issue provides a means for rendering the waypoint data legibly in a portrait format.

The proposed layout would change several aspects of the design:
- Touching an individual origin/waypoint/destination header would expand the space below it to show the details. Touching the header again would collapse it.
- The layout may not be complete (there were a few range items I didn't fully comprehend), but there's additional space available. Arguably, the Charger Type field is redundant, since the pin calls out the charger type.
- The labels are all right-aligned so that when switching from waypoint to waypoint the data doesn't jump around. 
- It probably makes more sense to have the waypoint map callout immediately below the expanded data section, with later waypoints below the map section. I think the map callout could be less tall that currently allocated. 

If you can implement segment-to-segment navigation as proposed in #227, user can easily navigate among all waypoints in all segments for the entire trip.

![segment details proposal](https://cloud.githubusercontent.com/assets/26678403/25064952/fc957ddc-21c2-11e7-9a78-c7014780432d.png)

**Comment by aesculus** [comment]
So each expansion would get it's own map?

**Comment by EVGrokker** [comment]
In a sense, yes. 

If the list of waypoints is completely collapsed, as it would be when the user first selects Segment Details from the Plan menu, you could show an overview map of the entire route below the destination header.
 
Upon touching an individual waypoint header, the area between the touched header and the next header would expand to create space for the data panel and the inset map for that waypoint. 

Touch that waypoint header again, it collapses, hiding the data panel and the inset map.

**Comment by EVGrokker** [comment]
But you could never expand more than one header at a time. If the user touched another header while one was already displayed, the earlier header would collapse, the new one would expand.

**Comment by aesculus** [comment]
OK. Let me think about how to implement this.

**Comment by EVGrokker** [comment]
This would be the same general design approach to be used in the Current Trips and Archived Trips panel.

**Comment by EVGrokker** [comment]
I think it would be a good idea to revisit this issue before the next major release. The layout in portrait mode on a phone-sized device doesn't work. Some ideas are proposed above.

**Comment by aesculus** [comment]
Updated in V1.2 (79)

**Comment by EVGrokker** [comment]
This new layout looks excellent. Much more readable on phone-sized devices.

What is ‘Intense’? Is it associated with ‘Outlook’?

If ‘Prob’ is the probability of Precipitation, would it make more sense on the same line as ‘Precip’?

I’d suggest adding the charge-to value under the battery image for the selected charging stop for consistency with the Waypoint Inspector, for example ‘42% > 82%’.

In the summary line at the bottom, you have segment distance, time and arrival. I’d suggest using the same icons and formatting that are used in the Segment Browser:

**363** mi. [stopwatch icon] **6:40**   ETA **2:39** pm

Again, this is a huge improvement.

**Comment by aesculus** [comment]
> What is ‘Intense’? Is it associated with ‘Outlook’?

Precip intensity. Changed to Intensity

>If ‘Prob’ is the probability of Precipitation, would it make more sense on the same line as ‘Precip’?

All three of those are related.

>I’d suggest adding the charge-to value under the battery image for the selected charging stop for consistency with the Waypoint Inspector, for example ‘42% > 82%’.

I left if off because when you switch to distance vs % it spells over and causes the line item to grow. Since the departure SoC was listed in the second line it would be redundant anyway.

>In the summary line at the bottom, you have segment distance, time and arrival. I’d suggest using the same icons and formatting that are used in the Segment Browser:

Done. Implemented in V1.2 (80)

**Comment by aesculus** [comment]
> If ‘Prob’ is the probability of Precipitation, would it make more sense on the same line as ‘Precip’?

I changed this to "Likely" in V1.2 (82)
