### ISSUE TITLE
Confirmation on Add to Calendar

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#242]
Comment from user.

>Btw, I don't know if it's necessary to have the 'do you really want to add' to your calendar etc.? If a trip is added in error it can easily be deleted from the calendar. Seems a bit of a messy note (being constructive of course!).

**Comment by EVGrokker** [comment]
I agree, the extra confirmation seems overly fussy. Recommend removing that dialog step.

**Comment by aesculus** [comment]
Removed in V1.1.4 (3)

**Comment by EVGrokker** [comment]
v 1.1.4 (4) This is broken since 1.1.4 (3). See #66 for additional details.

**Comment by aesculus** [comment]
I put this back in V1.1.4 (8)
