### ISSUE TITLE
[Basic Tutorial] Route Planning: A One-day Scenic Drive

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#243]
Posted to http://www.digitalautoguides.com/a-one-day-scenic-drive/

---

<h2>Route Planning: A One-day Scenic Drive</h2>
<p><I>Create a simple excursion that starts and ends at the same location.</i></p>

<h3>The Big Picture</h3>

![finalroute](https://cloud.githubusercontent.com/assets/26678403/25802839/67fbc7de-33b1-11e7-9cc6-5cd67bcedf14.PNG)

<p>Need to run some errands? Feel the need to do some sightseeing? If you're just out for a series of quick stops before returning home, here's a simple way to create a local round trip returning you to your starting location, while keeping an eye on your predicted power requirements.</p>

<h3>1. Plan a New Trip</h3>
<ol style="padding-left: 20px; list-style-type: lower-alpha;">
<li>Select <strong>New Trip</strong> from the main menu.</li>
<li>For the <strong>Origin</strong>, enter your starting address. Let's plan our round trip from the Tesla factory in Fremont CA. In <strong>Origin</strong>, enter <i>45500 Fremont</i>, then select the <i>Fremont CA</i> result from Google's list of suggestions.</li>
<li>For the <strong>Destination</strong>, enter the same address you entered in <strong>Origin</strong>. In <strong>Destination</strong>, enter <i>45500 Fremont</i>, then select the <i>Fremont CA</i> result from Google's list of suggestions.</li>
<li>For <strong>Waypoint Charger Selection</strong>, choose <i>Manual</i>.
</ol>

![nowheretogo](https://cloud.githubusercontent.com/assets/26678403/25802807/3cbf842a-33b1-11e7-863d-da02b4012cef.PNG)
<p align="center"><i>A trip to nowhere?</i></p>

<p>We now have a trip that starts and ends at the Tesla mothership, going exactly nowhere. Let's fix that by inflating the trip with some waypoints.</p>

<h3>2. Add Waypoints</h3>
<ol style="padding-left: 20px; list-style-type: lower-alpha;">
<li>We'll begin our trip by heading west to the Presidio in San Francisco. Select <strong>Add Waypoint</strong> from the menu, then enter <i>Presidio</i> into the address field. Select <i>Presidio, San Francisco</i> from the list. Touch <strong>Save</strong> to add the waypoint to our trip.</li>
<li>Touch the globe button to show the route. Nothing to get excited about yet.</li>
<li>Next, let's head down the coast to get some lunch in Half Moon Bay. Select <strong>Add Waypoint</strong> from the menu. Type <i>Sam's Chowder House</i>, then select the location on Cabrillo Highway in Half Moon Bay. Let's allow an hour for lunch by setting <strong>60</strong> in the <strong>Minimum Stop Time</strong> field. Touch <strong>Save</strong> to add the waypoint to our trip.</li>
<li>After lunch, let's head to the Santa Cruz Beach Boardwalk. Select <strong>Add Waypoint</strong> from the menu. Type <i>Santa Cruz Beach</i>, then select <i>Santa Cruz Beach Boardwalk</i> from the list. Let's allow 2 hours at the Boardwalk by setting <strong>120</strong> in the <strong>Minimum Stop Time</strong> field. Touch <strong>Save</strong> to add the waypoint to our trip.</li>
</ol>
<p>To see an overview of the entire route, touch the globe icon on the Plan screen. You should see the Big Picture at the beginning of this tutorial.</p>

<h3>3. Review Your Itinerary</h3>
<p>Let's review our itinerary. Select <strong>Segment Summary</strong> from the menu to review a list of our waypoints and key metrics. EVTO reports that our excursion is about 164 miles, and should require less than 50 kWh.</p>

![segmentsummary](https://cloud.githubusercontent.com/assets/26678403/25803071/7cb4ea9c-33b2-11e7-84d9-7edeff531abd.PNG)

<h3>4. Preview Our Final SoC</h3>
<ol style="padding-left: 20px; list-style-type: lower-alpha;">
<li>Touch the checkered pin to display the <strong>Waypoint Inspector</strong> at our destination. </li>
<li>For our car configuration and predicted weather on the day of our sight-seeing tour, EVTO predicts that we'll return with 25% in the tank.</li>
</ol>

![finalsoc](https://cloud.githubusercontent.com/assets/26678403/25803235/2a40e56c-33b3-11e7-990c-66ab3d7e1df2.PNG)

<p align="center"><i>Enough to make it all the way</i></p>

<h3>5. Preview Charging Options</h3>
<p>Just in case we take a few side trips along the coast and need a quick charge on the way back, let's take a look at where our charging options are located.</p>
<ol style="padding-left: 20px; list-style-type: lower-alpha;">
<li>Touch the lighting bolt symbol to overlay Tesla charger locations on the map.</li>
<li>No surprise, the Bay Area has lots of supercharging options.</li>
</ol>

![superchargers](https://cloud.githubusercontent.com/assets/26678403/25802927/ce9625ca-33b1-11e7-8ddc-dc36cb362587.PNG)
<p align="center"><i>Tesla supercharger locations in the Bay Area</i></p>

<h3>6. Do a Flip-Flop</h3>
<p>Just for the heck of it, let's have EVTO reverse the route.</p>
<ol style="padding-left: 20px; list-style-type: lower-alpha;">
<li>From the menu, select <strong>Reverse Route</strong>.</li>
<li>Select <strong>Segment Summary</strong> from the menu to review a list of our reversed waypoints.</li>
<li>Note that a new button is added at bottom of the dialog, <strong>Restore Auto Waypoint Order</strong>. This button appears anytime that you manually change a segment's waypoint order.</li>
</ol>

![reversed](https://cloud.githubusercontent.com/assets/26678403/25803124/a95efe66-33b2-11e7-9af7-26b7a46eac91.PNG)
<p align="center"><i>Reversed route</i></p>

<p>Well, there you have it. A nice, leisurely excursion along Highway 1 with no range anxiety. </p>

<hr/>

<p><i>Got an idea for a tutorial? <a href="mailto:support@digitalautoguides.com?Subject=Tutorial suggestion">Let us know!</a>
</p>

**Comment by EVGrokker** [comment]
![tesla tour](https://cloud.githubusercontent.com/assets/26678403/25071157/663c146c-226d-11e7-986b-b46749f67e5d.PNG)

**Comment by aesculus** [comment]
Are you going to use this one as the reverse route demo?  It could be a two step epilog.

**Comment by aesculus** [comment]
I created the tutorial but it's not linked yet pending your review.

http://www.digitalautoguides.com/a-one-day-scenic-drive/

There was a single image above that I was not sure what to do with.

**Comment by EVGrokker** [comment]
You can ignore the single image, that was related to a bug report #250. That image is the same as the Big Picture in the tutorial.

Here's some suggested text that you can post in [the EVTO thread on TMC](https://teslamotorsclub.com/tmc/threads/announcing-the-ev-trip-optimizer-for-tesla-app.87489/page-15):

---
<p>Speaking of Sunday drives, we've just posted a basic tutorial to help you plan one: <a href="http://www.digitalautoguides.com/a-one-day-scenic-drive/">Route Planning: A One-day Scenic Drive</a>. This tutorial demonstrates the creation of a short trip beginning and ending at the same location, perfect for a planning a leisurely one-day excursion.</p>
<p>If you haven't tried EV Trip Optimizer for Tesla (EVTO), it's a free <a href="https://itunes.apple.com/us/app/ev-trip-optimizer-for-tesla/id1124549080?mt=8">download for iOS</a> and <a href="https://play.google.com/store/apps/details?id=com.digitalautoguides.teslato">Android</a>. We're continuing to work hard, developing new features and polishing user interactions to make EVTO the preferred route-planning companion for all Tesla owners.</p>
<p>Check out <a href="http://www.digitalautoguides.com/#evto_main">our EVTO website</a> for a growing list of Tips & Tricks and other informative posts.</p>
<p>As always, please <a href="mailto:support@digitalautoguides.com?Subject=Tutorial suggestion">drop us a line</a> with suggestions for future tutorials, or just to say hi.</p>

**Comment by aesculus** [comment]
Posted

**Comment by aesculus** [comment]
Was this basic or advanced? I put it in basic.

**Comment by EVGrokker** [comment]
Basic's good, since it doesn't require Pro IAP and doesn't involve charging stops.
