### ISSUE TITLE
Segment Summary: Attempting to change waypoint order fails

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#244]
Trip: White House, [dzuimkdr5bqkth9f9aat3], tutorial in #243.

Trying to re-order the waypoints exposes a problem with the UI in the Segment Summary list. If the user touches in the arrow section, attempting to move that waypoint, the panel should not dismiss. It should stay up after the user releases the touch.

If they touch the left side where the waypoint name is, then the current behavior is correct.

I am observing that if I press and hold the arrow, the waypoint appears to move in the list, but when I reopen Segment Summary the order is the same.

**Comment by aesculus** [comment]
> If the user touches in the arrow section, attempting to move that waypoint, the panel should not dismiss. It should stay up after the user releases the touch.

So if the user moves an item you want the dialog to be modal?  If that is the case I will have to add a Cancel button.

> I am observing that if I press and hold the arrow, the waypoint appears to move in the list, but when I reopen Segment Summary the order is the same.

Note the new "button" that appeared below the list when you pressed an arrow named "Calculate New Routing"

![image](https://cloud.githubusercontent.com/assets/283364/25066810/3650fd76-21e6-11e7-810c-fdedc86d19a7.png)

**Comment by EVGrokker** [comment]
On the iPhone, that dialog dismisses after the arrow is touched because it thinks I want to inspect the waypoint. So I can't get to that button before the dialog goes away.

I think we have a couple of issues to wrestle with here. Waypoint reordering needs the dialog to be modal. Ideally we wouldn't have to hide the segment summary when displaying a waypoint details. When we dig into this panel's functionality we're also going to want to be able to delete waypoints from here. I'm envisioning a right to left swipe exposing a delete button. 

Hmm.

Generally, I don't think users would expect to use this as a means of clicking among their waypoints. They can do that easily on the map. When I look at this dialog, it feels like touching the pin should bring up that waypoint inspector, but touching the name shouldn't. Thinking ahead, I'd want to be able to drag a name to a different position in the list to reorder. And I'd want to slide right to left to expose the delete button. 

If you need to make it modal to keep the display up to allow reordering, that has to be the priority now. The UI for moving/deleting waypoints can wait until later, but we have to be able to reorder waypoints.

**Comment by EVGrokker** [comment]
Here's another approach to this.

We currently have a UI challenge on phone-sized devices with the conflict between needing to be able to select waypoints, and to reorder them, as discussed above. 

The mechanism for reordering waypoints has room for improvement. Issue #36 describes a different design, plus other ideas discussed within this issue.

Currently, if a user adds a waypoint out of sequence, EVTO does the right thing and inserts the waypoint in its logical order. For example, if I were creating a route from Seattle to Sacramento, added a waypoint at Lake Shasta, then Portland, the Portland waypoint would be on the route before Lake Shasta, even though it was added later.

What would you think of disabling waypoint reordering using the current mechanism, until we have a more friendly approach implemented?

**Comment by aesculus** [comment]
> Trying to re-order the waypoints exposes a problem with the UI in the Segment Summary list. If the user touches in the arrow section, attempting to move that waypoint, the panel should not dismiss. It should stay up after the user releases the touch.

That is the way it should work and does on my iPad.

> If they touch the left side where the waypoint name is, then the current behavior is correct.

Yes. It will then go to the map, show the Waypoint Inspector and any order changes will be lost because you did not secure them first with the button at the bottom.

> I am observing that if I press and hold the arrow, the waypoint appears to move in the list, but when I reopen Segment Summary the order is the same.

You must set them with the button at the bottom. And if you want, you ran restore the order later with a button in the same position.

> What would you think of disabling waypoint reordering using the current mechanism, until we have a more friendly approach implemented?

Some people depend on this today. It may not be the slickest UI in the world, but once you understand it's nuances it works pretty well IMHO.  I would rather let it stay the way it is until we can come up with a more logical UI.

And now that you understand the default is to let Google auto order everything, you may have some other ideas in this area too.

**Comment by EVGrokker** [comment]
>>Trying to re-order the waypoints exposes a problem with the UI in the Segment Summary list. If the user touches in the arrow section, attempting to move that waypoint, the panel should not dismiss. It should stay up after the user releases the touch.

>That is the way it should work and does on my iPad.

And it doesn't work this way on the iPhone. As soon as you release the arrow, the dialog is dismissed, before the user can touch the **Calculate New Route** button.

>>If they touch the left side where the waypoint name is, then the current behavior is correct.

>Yes. It will then go to the map, show the Waypoint Inspector and any order changes will be lost because you did not secure them first with the button at the bottom.

As noted above, it's impossible to secure the new order on a phone-sized device.

>>I am observing that if I press and hold the arrow, the waypoint appears to move in the list, but when I reopen Segment Summary the order is the same.

>You must set them with the button at the bottom. And if you want, you ran restore the order later with a button in the same position.

Understood. The **Calculate New Route** button is visible while the reordering arrow is being touched, but the dialog dismisses as soon as the arrow is released, before it can be touched.

>>What would you think of disabling waypoint reordering using the current mechanism, until we have a more friendly approach implemented?

>Some people depend on this today. It may not be the slickest UI in the world, but once you understand it's nuances it works pretty well IMHO. I would rather let it stay the way it is until we can come up with a more logical UI.

I wouldn't be opposed to leaving the arrow-based reordering UI intact for now if you were able to discriminate where the user touched in the **Segment Summary** dialog. If they touch the pin or the name, the behavior would be as it is now - the dialog is dismissed, then the **Waypoint Inspector** is displayed. The proposed UI change (on the iPhone) would be that when an arrow is touched and released, the dialog is _not_ dismissed - it remains displayed, and the user can then touch the **Calculate New Route** button.

>And now that you understand the default is to let Google auto order everything, you may have some other ideas in this area too.

My feedback on this is contained in issue #250.

**Comment by aesculus** [comment]
My bad. I forgot the special code I put in for iPhones on touch events and this list. I am not sure why I did not notice it when I tested on the iPad.

Should be fixed in V1.1.4 (8)

**Comment by EVGrokker** [comment]
Confirming this is fixed on iPhone in v 1.1.4(8).

**Comment by aesculus** [comment]
I'll take the win.

**Comment by EVGrokker** [comment]
v 1.2.0 (7)
This is once again not working properly. After touching an arrow to reorder a waypoint on the iPhone, the dialog immediately dismisses, making it impossible to recalculate the route.

**Comment by aesculus** [comment]
OK. I'll look at it again. When I switch to the format that will allow the arrows in the header I flummoxed up the logic for the segment move arrows.  I had to fix that and I probably broke the fix above.

**Comment by aesculus** [comment]
Please check if V1.2 (8) fixes this on the iPhone.

**Comment by EVGrokker** [comment]
V 1.2 (8) seems to fix the premature dialog dismissal.

**Comment by aesculus** [comment]
Way cool. I am not sure why it worked before quite frankly. I was in there the other day muddling about and it's possible I erased the former fix, but I don't see how.
