### ISSUE TITLE
Current Trips help text revision

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#246]
<h3>Current Trips</h3>

<i>Manages trips saved on your device. The Standard and Pro versions of EVTO supports a single trip. Purchase a Multi-Trip subscription to enable storage of multiple trips on your device.</i>

<h5>[icon] New Trip</h5>
<i>Displays the New Trip dialog</i>
<p>Creates a new trip. Standard version and Pro versions replace the current trip with your new trip. Multi-Trip subscribers saves the current trip, and creates a new one.</p> 

<h5>[icon] Activate Trip</h5>
<i>Selects a saved trip to activate</i>

<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you would like to activate, then touch <strong>Activate</strong> in the upper right corner to load the selected trip. To cancel, touch <strong>Cancel</strong> in the upper left corner.</p>

<h5>[icon] Copy Trip as New</h5>
<i>Selects a trip to copy</i>

<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you would like to copy, then touch <strong>Copy</strong> in the upper right corner to clone the selected trip. Trip metrics will be recalculated using current conditions and your car's characteristics.</p>

<h5>[icon] Reverse Route</h5>
<i>Selects a trip to copy and reverse</i>

<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you would like to copy and reverse, then touch <strong>Reverse</strong> in the upper right corner to create a reversed clone of the selected trip. Trip metrics will be recalculated using current conditions and your selected car's characteristics.</p>

<h5>[icon] Group by Rating</h5>
<i>Displays saved trips by assigned rating value</i>

<p>Current trips may be grouped and displayed by the year in which they were created (the default view), by the rating value you've assigned (0-5 stars), or by their status, 'Plan' or 'Taken'.</p>

<h5>[icon] Group by Status</h5>
<i>Displays saved trips by trip status</i>

<p>Current trips may be grouped and displayed by the year in which they were created (the default view), by the rating value you've assigned (0-5 stars), or by their status, 'Plan' or 'Taken'.</p>

<h5>[icon] Delete Trips</h5>
<i>Selects trip(s) to delete</i>

<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) you would like to delete, then touch <strong>Delete</strong> in the upper right corner.</p>

<h5>[icon] Archive Trips</h5>
<i>Select trips to archive</i>

<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) you would like to archive, then touch Archive in the upper right corner. Archive Trips requires a Multi-Trip subscription. Archived trips are removed from the Current Trips list, but retained on your device for future use.</p>

<h5>[icon] Share Trip</h5>
<i>Shares a trip with another EVTO user</i>

<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you would like to share, then touch <strong>Share</strong> in the upper right corner. The <strong>Share Trip</strong> dialog is displayed. Assign a 4-digit PIN, then touch <strong>Confirm</strong>. An email is composed with the unique trip ID and the assigned PIN. Enter the recipient's email address, then touch <strong>Send</strong>. The shared trip will be available to the recipient for 30 days.</p>

<h5>[icon] Import Trip</h5>
<i>Displays the Import Trip dialog</i>

<p>Enter the unique trip ID sent to you, the associated 4-digit PIN, then touch <strong>Import</strong>. The imported trip will be added to your list of current trips.</p>

<h5>[icon] Help</h5>
<i>Displays this help panel</i>

<p>You are here!</p>

**Comment by aesculus** [comment]
Updated in V1.1.4 (4)
