### ISSUE TITLE
Archived Trips help text revision

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#247]
<h3>Archived Trips</h3>

<i>The <strong>Archived Trips</strong> screen manages trips archived on your device. The standard and Pro versions of EVTO support a single trip. Purchase a Multi-Trip subscription to enable storage of multiple trips on your device.</i>

<p>Archiving a trip allows you to keep a trip on your device, but removes it from the <strong>Current Trips</strong> screen. This is useful for trips you take infrequently, but would like to keep available for future reference.</p>

<h4>[icon] Restore Trips</h4>
<i>Select trips to restore</i>

<p>Archived trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) you would like to restore, then touch <strong>Restore</strong> in the upper right corner.</p>

<h5>[icon] Group by Rating</h5>
<i>Displays archived trips by assigned rating value</i>

<p>Archived trips may be grouped and displayed by the year in which they were created (the default view), by the rating value you've assigned (0-5 stars), or by their status, 'Plan' or 'Taken'.</p>

<h5>[icon] Group by Status</h5>
<i>Displays archived trips by trip status</i>

<p>Archived trips may be grouped and displayed by the year in which they were created (the default view), by the rating value you've assigned (0-5 stars), or by their status, 'Plan' or 'Taken'.</p>

<h5>[icon] Delete Trips</h5>
<i>Selects trip(s) to delete</i>

<p>Archived trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) you would like to delete, then touch <strong>Delete</strong> in the upper right corner.</p>

<h5>[icon] Help</h5>
<i>Displays this help panel</i>

<p>You are here!</p>

**Comment by aesculus** [comment]
Updated in V1.1.4 (4)
