### ISSUE TITLE
Add Waypoint, Edit Waypoint, Settings dialog: Can't drag sliders

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#248]
When the Add Waypoint dialog is displayed, I can touch a point in the slider's range to change the value, but I can't touch and drag to dynamically change the values. This is also true in the Edit Waypoint dialog, and the Settings dialog.

I am almost certain these were draggable before.

**Comment by aesculus** [comment]
They are still draggable on my iPad and my iPhone too in V1.1.4 (3). You are dragging the little box on the slider?  In the last update I made sure that the big magnifying box worked on all of these.

**Comment by EVGrokker** [comment]
Just checked again to be sure. I can touch anywhere in the slider range and it will jump to that value, but I can't touch and drag to change. The magnifying box does work.

**Comment by EVGrokker** [comment]
I deleted 1.1.4(3), reinstalled, and now it works. Hmm.

**Comment by aesculus** [comment]
OK. I was going to have to march up there and show you how to use your finger. :-)

**Comment by EVGrokker** [comment]
So I suppose your standard response to my bug reports will now be "Have you tried deleting the app?"

**Comment by aesculus** [comment]
No. You should not have to.

For some reason a guy in the UK seems to have to for his iPad mini though. Still trying to figure that out too. And it crashes a few times and then its great until the next update.

**Comment by EVGrokker** [comment]
I have been in the habit of always doing a clean install between beta versions, just to be sure I go through all the settings screens with a fresh eye. I wouldn't have expected to see reinstalling make a difference, but now I know it can be a solution sometimes.

**Comment by EVGrokker** [comment]
I experienced this bug again in v 1.2 (2). Deleted and reinstalled from TestFlight, solved the problem. This is a weird one.

**Comment by EVGrokker** [comment]
I'm going to reopen. If we can find a reproduce the conditions maybe we can pin it down.

**Comment by aesculus** [comment]
V1.2 (2) has that layout bug. Need to test this again with V1.2 (3) without the layout issue too.

**Comment by EVGrokker** [comment]
Still seeing this elusive bug in 1.2.0 (7).

I've discovered that force-quitting the app and restarting resolves it, at least temporarily.

**Comment by aesculus** [comment]
So this is the slider issue, or the layout issue where the input box becomes tiny?

**Comment by EVGrokker** [comment]
This issue is specifically about the occasional inability to move the sliders in various dialogs. My observation is that after installation, the behavior is correct, then something triggers a condition where you can touch anywhere along the slider to change the value, but you can't touch and drag to dynamically change the value. I don't yet know how to reproduce the condition, but it happens frequently. Today I learned that force-quitting the app resets the condition. I'll keep trying to learn what triggers it.

**Comment by aesculus** [comment]
So if you touch an area within the slider the value gets set, but you cannot drag that little box?

**Comment by EVGrokker** [comment]
Exactamundo.

**Comment by aesculus** [comment]
OK. If this happens again try this: Rotate the device horizontal and then back vertical. No guarantees but I am curious.

Also is the little box stuck only on the far left (0) or can it also be stuck within the range?

**Comment by EVGrokker** [comment]
I can move it anywhere in the range by touching anywhere along the slider. But then I have to lift and retouch to get a new, different value. No dragging is a drag.

**Comment by aesculus** [comment]
I am just going to throw this out here for something to look at. Probably not relevant but it will help me remember later if needed:

I have been getting some errors lately in my development environment about slow networks causing Google fonts to not load occasionally. I think the slider control is using Google fonts but I am not certain. At least one report about wordpress was talking about issues regarding sliders and Google fonts and not working correctly. Too many not necessarily connected elements but since I have no knowledge of the underpinnings of the slider control,  I will just park this here.

**Comment by EVGrokker** [comment]
v 1.2.0 (42)
On the few times that I've seen this error recently, it's been after updating to a new release. Force-closing the app seems to resolve the problem. If this is a framework issue, we're not likely to be able to resolve it, so I think we just need to be aware of the issue, and either deal with it directly when users complain, or create a FAQ entry explaining how to resolve it.
