### ISSUE TITLE
Add Waypoint: Name field

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#249]
This was previously addressed in issue #162.

If I create a waypoint by touching a location on the map, or typing a descriptive name into the address field (Starbucks, Pacific Avenue, Tacoma), the address field is filled in. Once there's a valid address in the address field, the Name field should be enabled for editing. 

Currently, one has to add the waypoint, Save, then touch the pin to reopen the Waypoint Inspector, then edit the Name.

**Comment by aesculus** [comment]
Fixed in V1.1.4 (4)
