### ISSUE TITLE
Reversing a route whose origin and destination are the same does not have the desired outcome

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#250]
Trip: Tesla Factory, [83bnxru6ux2ri9fhgw6nw]

This is an edge case, but worth resolving.

If I create a single-segment round trip, EVTO decides the waypoint order for me, regardless of the order in which I add the waypoints:

1. New Trip: Origin and Destination - 45500 Fremont Boulevard, Fremont CA
2. Add Waypoint: Santa Cruz Beach Boardwalk, 60 minute stop
3. Add Waypoint: Sam's Chowder House, Half Moon Bay, 60 minute stop
4. Add Waypoint: Presidio, San Francisco 
5. Plan menu | Segment Summary

Notice that the waypoints are not in the order I entered them. Presidio is at the top of the list, Santa Cruz at the bottom. It's a logical order, but not the order I expected. I want to go to Santa Cruz first. (I tried this entering the waypoints in reverse order, but the sequence always comes out the same, with Presidio first.) I assume that this is an artifact of the routing algorithm.

If I reverse this route, EVTO faithfully swaps the origin and destination, which changes nothing - Presidio's still at the top.

Propose adding logic to the reverse route algorithm for special case handling when origin and destination addresses are the same. When this is the case, reverse the order of the waypoints instead of swapping Origin and Destination.

**Comment by aesculus** [comment]
> Notice that the waypoints are not in the order I entered them. Presidio is at the top of the list, Santa Cruz at the bottom. It's a logical order, but not the order I expected. I want to go to Santa Cruz first. (I tried this entering the waypoints in reverse order, but the sequence always comes out the same, with Presidio first.) I assume that this is an artifact of the routing algorithm.

By default I use Google's order. They do the trip based on most efficient time?

>If I reverse this route, EVTO faithfully swaps the origin and destination, which changes nothing - Presidio's still at the top.

That is correct. For this type of trip where Google is determining order based on travel time, you basically did nothing.

So try this:
- Bring up the Segment Summary
- Now move the Presido down and then move the Chowder House down, basically resetting the order
- Now press the Calculate New Routing button at the bottom of the list. Nothing should change.
- Now do your Reverse. You will see the routing is reversed.

Not pretty but. 
![image](https://cloud.githubusercontent.com/assets/283364/25215132/5a5f3698-2550-11e7-9b5a-ff2f2a497eda.png)

**Comment by aesculus** [comment]
Working as designed but you can comment on the design.

**Comment by EVGrokker** [comment]
This simply doesn't work on the iPhone. I press and hold the down arrow on the Presidio waypoint. It moves down one slot, so it's now below Sam's Chowder House. I can see the **Calculate New Routing** button at the bottom of the dialog, but as soon as I release my touch on the down arrow, the dialog is dismissed, so I can never apply the new waypoint order. With the current UI, it's impossible to reorder waypoints on the iPhone.

WRT reversing the trip on a 1-segment trip whose origin and destination are the same, I definitely think the behavior should be reversing the order of the waypoints. What other result would the user expect? This should be considered as a macro version of the manual reordering that's not currently possible on the iPhone.

The most likely real-world application of these one-day round trips is a series of errands, or a scenic drive. The user most definitely has a notion of the order they'd like to do them. I don't mind the first pass being optimized by Google, but any subsequent changes to the ordering should be retained. If the user were to select Optimize Segment I suppose it would necessarily revert to the Google-calculated route, but that's an acceptable tradeoff.

**Comment by aesculus** [comment]
I will force sticky waypoint ordering on single segment trips that are being reversed.

**Comment by aesculus** [comment]
If there is only one segment then the autorouting will be turned off automatically when the trip is reversed.

V1.1.4 (9)

**Comment by EVGrokker** [comment]
v 1.1.4 (9)
Trip ID: Tesla Tour, [7nm54b7em7n6bfio5aokj4] and the PIN [1234]

This is not yet working correctly. It's closer, but not quite right.

Following the steps in tutorial #243, I've inflated a trip starting and ending in Fremont with the following stops: 
1. Tesla
2. Presidio
3. Sam's Chowder House
4. Santa Cruz Boardwalk
5. Tesla

I put them in this order because I learned that's the same order that Google puts them when calculating the route.

Selecting Reverse Route from the Plan menu yields this waypoint order:
1. Tesla
2. Sam's Chowder House (should be Santa Cruz Boardwalk)
3. Santa Cruz Boardwalk (should be Sam's Chowder House)
4. Presidio
5. Tesla

Stops 2 and 3 are out of order.

**Comment by aesculus** [comment]
Forgot to reverse the sort order. Fixed again in V1.1.4 (10)
