### ISSUE TITLE
Edit Segment Details: Changing segment name doesn't update Plan panel header immediately

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#251]
After renaming a trip segment, I need to touch the Trip Segments Summary icon then select the segment before the header updates.

Changing the segment name in the Edit Segment Details dialog should update the header immediately when the dialog closes.

**Comment by aesculus** [comment]
Fixed in V1.1.4 (4). Not sure what happened here or why but this was commented out in the code. I uncommented it.
