### ISSUE TITLE
Add a "max leg duration" setting (via TMC)

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#252]
[From TMC user sneller:](https://teslamotorsclub.com/tmc/posts/2058153/)

Use case: with max leg duration set to 10 hours, the initial route from Houston to Fort Lauderdale might add waypoints in Loxley, AL & Whittier, FL (resulting in legs of 10, 10, and 2 hours). I look at the route and decide I can make it to Crestview, FL the first day and edit the waypoint (for extra credit, by dragging it along the route) to Crestview and the trip recalculates. Remainder of trip is now around 8 1/2 hours (<10 hits), so the second waypoint is removed as unnecessary and I'm good to go. 

I have to do this iteratively now and it'd be great to have it automated.

**Comment by aesculus** [comment]
Whoops. We both posted these at the same time. :-) #253

**Comment by aesculus** [comment]
This would be a Auto Trip Segmenting feature I guess.

**Comment by EVGrokker** [comment]
It's an interesting idea but it's deceptively complicated. What exactly are you looking for when you auto-segment? Towns? Motels? Destination chargers? 

I think my approach would be starting with a town at a reasonable stopping point, then searching for a destination charger and/or a hotel I have loyalty rewards with. But that's just me :)

**Comment by aesculus** [comment]
Yeah. I, like you, just tossed it into the pot because. Interestingly I got two of these types of requests within 24 hours of each other.

This is the reason I put the elapsed times on the Segment Summary and also have the Segment feature on the app.  But to use that you have to add a waypoint (your point above about what stop?).  What would I do, just convert that SC to a required SC and segment the trip automatically?  That would be pretty easy in the big scheme of things.

**Comment by EVGrokker** [comment]
I'm planning to write a tutorial on planning a multi-day road trip, let me explore this while I'm writing it. I'm sure I'll become opinionated. :)

**Comment by aesculus** [comment]
Check out what I have on the subject in the tutorial. There are actually 3 places that talk about this. See the long trip one for sure

http://www.digitalautoguides.com/trip-optimizer-tutorial/

**Comment by EVGrokker** [comment]
Will do.

**Comment by EVGrokker** [comment]
I could envision the following (probably a 2.0 feature):
- A Settings preference indicating my preferred daily endurance limits, in miles and/or hours
- Plan a trip starting with Day 1 Origin and Day n Destination
- EVTO drops cluster markers on the map in the vicinity of the daily hinge points
- Touching the cluster marker displays a list of candidate destination charging/hotel locations
- Selecting a suggested overnight stop location adds it as a hinge point, meaning it's added as a waypoint then scissored (segmented).

There's a *lot* of hand-waving in there. My gut is that this is a task best left to humans. I will revisit this issue after working on the tutorial.

I remember from my motorcycle touring adventures that route planning was a pleasant task. You're considering all sorts of intangibles from loyalty points to local services. To make this valuable the destination charging database would have to be really high-quality and up-to-date.

**Comment by aesculus** [comment]
Not sure if same poster or not but someone at TMC suggested they liked the way this divides the segments

https://www.myscenicdrives.com/

**Comment by aesculus** [comment]
What if I put an option in the Settings to recommend a stop after n hours from 0-12 (maybe a slider?). Anything larger than 0 would place a special pushpin (with a bed?) on the route for every estimated travel time (driving, stop and charging). The user can then use this to decide if they want to segment the trip there or at least put in a waypoint.

If they leave it at 0, the default, then no push pins would show. This is fairly trivial so I would do this as a standard feature.

**Comment by aesculus** [comment]
One issue would be how to reset the time counter. Clearly a new segment could do that, but if the trip is not segmented? Maybe that would be a reason to upgrade to Pro, to have it better show real world travel expectations.

**Comment by EVGrokker** [comment]
1. Definitely a Pro feature.
2. In what time frame/version are you thinking of tackling this? What you're proposing would be a quick solution, but I'd really like to see some polish and elegance applied to this feature. My fear is that once you put an alpha version of this in the wild, there will be so much feedback about how to make it smarter that all the other important improvements will languish.

**Comment by aesculus** [comment]
We can wait if you think that is better. Seems to be a lot of chatter about it but I suspect you are right. They probably want AP3 vs ACC. :-)

**Comment by EVGrokker** [comment]
If #89, Ability to delete segments, is functional in the next release, there's at least a way to accomplish trip itineraries iteratively. That's a good placeholder.

**Comment by EVGrokker** [comment]
Intermediate enhancement suggestion (baby step, actually) that would bring us a step closer to MDAR 1.0 (Multi-Day Auto Routing):
- Create a long trip, for example Fremont CA - Nashville TN, **Manual** charger selection
- Zoom into CA 
- Touch lighting icon to turn on supercharger locations
- Touch a supercharger icon, for example Barstow
- Enhancement: In the Charger Inspector, show distance from previous pin in current segment. If possible, predicted hours of driving to this location would also be useful.

This would allow you to easily do manual selection of waypoints for segmentation based on distance when first chopping up a long route without repeatedly asking EVTO to reoptimize.

**Comment by aesculus** [comment]
> This would allow you to easily do manual selection of waypoints for segmentation based on distance when first chopping up a long route without repeatedly asking EVTO to reoptimize.

Just to be sure: The current Trip/Segment summary shows the estimated total elapsed time at each waypoint.  So if I knew somebody wanted to stop traveling after 8 hours I could show them on the map (or nearest waypoint) where that is today.

**Comment by EVGrokker** [comment]
My scenario is slightly different. What I'm proposing is earlier in the planning stage. All I have is an origin and destination, thousands of miles apart. I'm starting a rough approximation of where I want to do my segmenting. The very best, most complete database you have is Tesla Superchargers, so we're going to take advantage of that.
In the example above, I've created a trip from Fremont - Nashville. I'm zoomed into SoCal, guesstimating where I might want to stop on day 1.
(At this point, I'm cheating by going to Google Maps to see how far it is from Fremont to Barstow. It tells me 385 miles, 6:04 driving time.)
So here's what I'd like to see when I touch the Barstow supercharger icon on the map. It's not yet part of the route. 
The algorithm would be "compute the time and distance from the earliest, closest pin in the current segment, and display those numbers below the charger name."
This would not be applicable to automatic charging stops, or manual charging stops.

It answers the question "how far is this charging stop from the last waypoint established on my route?"

![barstow route preview](https://cloud.githubusercontent.com/assets/26678403/25148007/b2899022-2436-11e7-9d2a-f7d7f9263ecf.png)

**Comment by aesculus** [comment]
OK. Then we would have to develop some sort of rule of thumb (based on model efficiency?) to guestimate travel time vs drive time (the charger thing).  Then we could do this. Weather and stopping longer than needed for charging or course could not be included here. That could make a big difference.

**Comment by EVGrokker** [comment]
I'm proposing no "secret sauce" computations at all. It's just distance and time, assuming traveling at the speed limit. No regard for charging stops, weather, nada.

**Comment by aesculus** [comment]
But is that really useful? Not to me with an EV. I would want to know the travel time to the charger, which would have to AT LEAST include how much charge time I had to incur to get there along with driving time.

But again, I think we can fake that with a WAG by efficiency of the car and estimating travel time per mile. I am sure that has been done by someone before but it should not be too hard. 

Let's say you can charge at 200 mph. So every 200 miles you would have to add another hour to the drive time to get travel time. What number should we use? 200 is way too fast because it's not linear. Maybe 100 or 125?

**Comment by EVGrokker** [comment]
I think you're overcomplicating it. All that information will be available the moment you add the charger to your route.

This is a "what if" tool. 

ME: "I'm heading from Fremont to Nashville. What if I decide to stay overnight in Barstow the first night? How far is that?" 
EVTO: 385 miles, about 6 hours of driving time.
ME: "Hmm, I know I'd probably need a couple of charging stops en route, but I'd clock 385 miles the first day, and probably 7-8 hours total time in the car by the time I add in charging, lunch and breaks. I know from experience that about 350 miles is my upper limit for the day, but it would feel good to get that far."
EVTO: Are you just going to sit there, or are you going to push some buttons?

**Comment by aesculus** [comment]
But you don't think it would be more useful to have an EV "rule of thumb". Maybe I am being overly pessimistic but the basic questions I get everyday point me to the fact that people would probably think driving time = travel time in an EV.

You would be shocked at how many uses trips I get where the user has the minimum SOC set to 25% and they want to charge to 100% at every charger.

**Comment by EVGrokker** [comment]
I see two compromises for this Time & Distance preview I'm proposing:

1. Distance only. I can do the driving time calculation in my head.
2. Distance, Driving time, and Clock time, using your EV "rule of thumb". 

For example, using my numbers above, I assigned an EV "rule of thumb" multiplier of 33%, adding 2 hours to my 6 hours driving time, coming up with 8 hours clock time. 

I wouldn't argue if you chose to do option 2. But the moment the user adds the charger to the route, that clock time estimate is history. But I wouldn't argue.

WRT users setting 25% SoC and charging to 100%, all I can say is that EVTO can help these poor souls become better planners. I get it - it's all about range anxiety. I felt the same way when I first started using cell phones, gotta keep it charged up. 

But if there's a group to surprise and delight, it's folks who are going out on a limb with the app, who will spread good word of mouth. "Wow, I was able to sketch out a 5-day Fremont to Nashville trip in fifteen minutes with EVTO, awesome." Those kind of comments and reviews will be gold.

By the way, in working on this Fremont-Nashville monster (and breaking EVTO in the process), I tried planning it with EV Trip Planner, A Better Trip Planner, Scenic Drive, everything I could get my hands on, and _none_ of them make it as easy as EVTO is on track to do.

**Comment by aesculus** [comment]
EVGrokker wrote:
> By the way, in working on this Fremont-Nashville monster (and breaking 
> EVTO in the process), I tried planning it with EV Trip Planner, A 
> Better Trip Planner, Scenic Drive, everything I could get my hands on, 
> and /none/ of them make it as easy as EVTO is on track to do.
That is really cool. These are some good apps to benchmark against. In 
general they are simpler to operate than EVTO. But I find too many 
limitations with them.

It's probably the pilot training in me, and hence the over complicated 
aspects.  If you have ever run out of gas 50 miles from an airport (not 
that I have but close), that sort of twinges a bit. :-)
-- 
Chris Couper

**Comment by EVGrokker** [comment]
After sleeping on this, I'd like to try another explanation of what I'm asking for. This is one of these features that I think would be very useful.

Let's call this the 'Rangefinder' feature. With an active current trip, touching a supercharger location brings up the Charger Inspector. Similar to the mockup I included in a previous comment, the distance from the previous waypoint in the current route is displayed under the charger name. Forget the driving time, just the distance.

For example, I'm working on my multi-segment tutorial. I'm starting with a Fremont - Nashville origin/destination, and I've added Denver as a waypoint in the middle. I observe that Denver is 1271 miles from Fremont, so I decide to subdivide that stretch into three days. I enable the display of superchargers along the route, and I see Winnemucca. I touch the Winnemucca pin, wondering how far it is from Fremont. That's where using the Rangefinder feature would be handy.

**Comment by aesculus** [comment]
I like the concept. I wonder if a linear timeline like chart would be useful also?

**Comment by EVGrokker** [comment]
![what-the-customer-really-needs-1](https://cloud.githubusercontent.com/assets/26678403/25185468/a99b18c4-24da-11e7-9da8-58ab85eb1312.jpg)

**Comment by aesculus** [comment]
While this is a cool concept I think it's mostly filled by issue #291
