### ISSUE TITLE
[Basic Tutorial] From the Frunk: All About Trips, Routes and Segments

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#258]
_This is a work in progress, not ready for publication. Images included at full scale, may be scaled when published._

---

<h3>Trips, Routes and Segments</h3>
<p><i>A visual guide</i></p>

<h4>The Big Picture</h4>

![image](https://user-images.githubusercontent.com/283364/39484016-2d592102-4d29-11e8-83da-8b87d0b000f5.png)

<p align="center"><i>Point A to Point B to Point C to Point D(enver), a three-segment trip</i></p>

<dl>
<dt>Trips</dt>
<dd>A <i>trip</i> is a <i>route</i> calculated by EVTO from an initial origin to a final destination. Trips may be broken up into a series of <i>segments</i> with intermediate destinations, for example overnight stops on a cross-country trip. In the map above, point <strong>A</strong> is the initial origin, points <strong>B</strong> and <strong>C</strong> are intermediate destinations. Waypoints are added along your route for charging, meals and other local stops. Trips may be created with automatic charging stops assigned by EVTO, or you may add charging stops manually.</dd>
</dd>

<dt>Routes</dt>
<dd>A <i>route</i> is composed of roads selected by EVTO for the current <i>segment</i>. Routes are influenced by waypoints, your car's characteristics, road conditions and available charging stops. EVTO does its best to assure your arrival at your destination with adequate reserves. </dd>

<dt>Segments</dt>
<dd>Trips are composed of one or more <i>segments</i>. A segment follows a <i>route</i> calculated by EVTO from an origin to a destination, with charging stops and waypoints along the way. A segment's calculated route is dynamic, based on your preferences, your EV's characteristics, and predicted weather conditions.<br/>
In the image above, the route between pins <strong>A</strong> and <strong>B</strong> is the first segment of the trip, San Jose CA to Winnemucca NV. The route between pins <strong>B</strong> and <strong>C</strong> is the second segment of the trip, Winnemucca to Salt Lake City UT. Pin <strong>B</strong> is a <i>hinge pin</i>, because it serves as both the <i>destination</i> of the first segment, and the <i>origin</i> of the second segment.<br/>
The route between pin <strong>C</strong> (also a hinge pin) and the checkered destination pin is the third and final segment of the trip, Salt Lake City to Denver CO. <br/>
The first and second segments are inactive, displayed with gray origin pins, gray route lines, and tiny almost hidden waypoints, if present. The third segment is the active segment, displayed with a blue origin pin, blue route line, and a checkered destination pin. Because the third segment is the active segment, its waypoints are displayed.<br/>
The Trip Segments button (center right edge of the map) is badged with a <strong>3</strong>, indicating that the trip includes three segments. <br/>
Touching the Trip Segments button displays the <strong>Trip Browser</strong> dialog, listing each segment and a summary of the entire trip:</dd>

![image](https://user-images.githubusercontent.com/283364/39484545-fce695c0-4d2a-11e8-8297-ceb9d73fd0cc.png)

<p align="center"><i>Trip Browswer dialog</i></p>
<dd>Touch any segment to make it the active segment. Touch outside the dialog to dismiss it. You may also directly touch any route line on the map to make it the active segment. </dd>

<dt>Round trips</dt>
<dd>By enabling the <strong>Plan as a round trip</strong> checkbox in the <strong>New Trip</strong> dialog, a two-segment round trip is created, automatically returning to your origin. </dd>

![image](https://user-images.githubusercontent.com/283364/39462635-9bb6beb4-4cc7-11e8-9cd3-380ae5b2ee8f.png)

<p align="center"><i>Outbound segment of a round trip</i></p>

In the image above, we created a round trip from Fremont CA to Chico CA. There are several visual cues indicating a round trip:
<ul>
<li>The destination checkerboard pin is gray instead of black, representing an intermediate destination.</li>
<li>The trip segments button (center right edge of the map) is badged with a <strong>2</strong>, indicating that the current trip includes two segments. Touching the trip segments button displays the <strong>Trips Browser</strong> dialog, listing each segment and a summary of the entire trip. Touching any segment makes it the active segment. Touch outside the dialog to dismiss it.
</li>
</ul>

<p>Touching the route line toggles between the outbound segment and the return segment. In the image below, there are several visual cues indicating a return segment:</p>

![image](https://user-images.githubusercontent.com/283364/39484834-d05dd530-4d2b-11e8-9fe7-9808f7f8f331.png)

<p align="center"><i>Return segment of a round trip</i></p>

<ul>
<li>The origin and destination pins have switched places. The origin is now Chico, the destination is now Fremont.</li>
<li>The destination checkerboard is black instead of gray, representing the final destination of the trip.</li>
</ul>

<p>Notice that both the route and the automatic charging stop on the return segment are different than the outbound segment. During charger selection, EVTO determined that this combination was optimal.</p> 
</dd>

<h3>Automatic vs Manual charger selection</h3>
<p>When initially creating a trip in the <strong>New Trip</strong> dialog, you have an option to use <i>Auto</i> or <i>Manual</i> waypoint chargers. This selection only affects the initial route calculations. Any subsequent changes to redefine to your trip, by adding waypoints or segmenting the trip, may require additional optimization using the <strong>Refresh Auto Chargers</strong> menu item.</p>

<dt>Automatic charger selection</dt>
<dd>
Select <i>Auto</i> when you want the quickest route from origin to destination along the supercharger network and you don't plan any additional stops. EVTO automatically selects charging stops.
</dd>

<dt>Manual charger selection</dt>
<dd>
Select <i>Manual</i> when you want to fine-tune your routing options. Specify your origin and destination, then add waypoints to inflate your route. Add any specific charging stops, and EVTO will predict your SoC at each stop. Or, after adding your waypoints, select <strong>Refresh Auto Chargers</strong> from the menu to let EVTO fill in any addtional auto charging stops.
</dd>

<h3>IAPs (The Fine Print)</h3>
<table style="width:100%">
  <tr>
    <th></th>
    <th>Free</th>
    <th>Subscription</th>
  </tr>
  <tr>
    <td>Single-segment trips</td>
    <td>✓</td> 
    <td>✓</td>
  </tr>
  <tr>
    <td>Multi-segment trips</td>
    <td></td>
    <td>✓</td> 
  </tr>
  <tr>
    <td>Current Trips</td>
    <td>One</td>
    <td>Many</td>
  </tr>
</table>
<ul>
<li>The Free version of EVTO supports creation of a single, one-segment trip at a time.</li>
<li>Purchasing a monthly or annual subscription unlocks support for multi-segment trips.</li>
<li>Purchasing a monthly or annual subscription unlocks support for storing multiple trips on your device.</li>
</ul>

<hr/>

<p><i>Got an idea for a tutorial? <a href="mailto:support@digitalautoguides.com?Subject=Tutorial suggestion">Let us know!</a>
</p>

**Comment by aesculus** [comment]
Updated and published
