### ISSUE TITLE
Edit Segment Details dialog: Layout enhancement

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#259]
The layout for the date field looks awkward. It should be a single line. I understand that the width of the content may dictate the taller control. 

Proposal:
Narrow the width of Time, Payload and Origin SoC% controls to accommodate the wider width required for Date.

---
![edit segment details - date](https://cloud.githubusercontent.com/assets/26678403/25088795/3ce93990-2336-11e7-82b0-1a7703f31e7d.PNG)

**Comment by aesculus** [comment]
In V 1.1.4 (4) I have made it a 40/60 split when on a phone in vertical mode. Hope that takes care of it.

Close this if it works for you after the update.

**Comment by EVGrokker** [comment]
I will check it out after receiving the next beta build.

**Comment by EVGrokker** [comment]
Looks much better.
