### ISSUE TITLE
New Trip Error dialog doesn't need Cancel and OK buttons

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#262]
When displaying this dialog, you don't need two buttons. **OK** is sufficient.

![new trip error](https://cloud.githubusercontent.com/assets/26678403/25127721/2e680e50-23f4-11e7-88fe-32e04a8e3949.PNG)

**Comment by aesculus** [comment]
Fixed in V1.1.4 (5)
