### ISSUE TITLE
Planning multi-segment trip, second segment shows 'Invalid date'

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#263]
Trip: Hyatt Centric Santa Barbara (Seaver), [do1p1i3lhlqrftahxf0ii]

Constructing a trip by establishing farthest point as initial destination, then scissoring down to create segments.

After initial segment snipped, make segment 2 active. Touch any of the automatic charger pins. Arrival time shows **Invalid date**.

- Select segment 1, origin. Note departure time is 4:07 am.
- Select segment 1, destination. Note departure time is 1:11 pm. (Note destination pin is white. Shouldn't a segment be auto-optimized after a scissoring?)
- Select segment 1, origin. Note departure time is **Invalid Date**.
- Optimize segment 2, now it has legitimate arrival times, but based upon my departure time being more or less the same as my segment 1 departure time. Hmmm.

**Comment by aesculus** [comment]
I have updated the segment routine. Lets keep this open for a while to see if this is resolved or not.

**Comment by aesculus** [comment]
Please test this on V1.1.4 (7).

>Select segment 1, destination. Note departure time is 1:11 pm. (Note destination pin is white. Shouldn't a segment be auto-optimized after a scissoring?)

No. It is auto calculated but non auto optimized. It won't check to see if the chargers are correct, it will just use the chargers that are there and determine if the route is appropriate.  If the route is not appropriate (push pins are yellow or red) the user can then optimize to reset the chargers.
