### ISSUE TITLE
Confirm Combine dialog typo: Combinging

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#264]
v 1.1.4 (4) The Confirm Combine dialog invents a new word, _combinging_.

_Combinging_. Verb. The act of combining two unrelated binging activities. 
"I combinged last night, streaming all episodes of _Better Call Saul_ while coding the latest routing features into EVTO."

Proposed wording:

**Confirm Segment Merging**
By deleting this waypoint, the adjacent segments will be merged into a single segment.
Cancel | **Merge**

---

![combinging](https://cloud.githubusercontent.com/assets/26678403/25128498/3b02baa4-23f7-11e7-92d9-eaca11d516ed.PNG)

**Comment by aesculus** [comment]
I kind of like the binging thing. :-)

Fixed in V1.1.4 (5)
