### ISSUE TITLE
Multi-segment trip, errors in naming segments

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#265]
v 1.1.4 (4)

Trip: Hyatt Centric Santa Barbara (Seaver), [do1p1i3lhlqrftahxf0ii]

In this trip, I initially segmented at Gilroy CA, then combinged that segment, and scissored a new segment at Atascadero. The Trip Segments dialog now shows the wrong segment names, still referring to the Atascadero stop as Gilroy. Note that Gilroy is listed twice as a segment name, even though it's no longer a stopping point:

---

![segment naming error](https://cloud.githubusercontent.com/assets/26678403/25128905/ecdffd12-23f8-11e7-918b-718e6d42fdb3.PNG)

**Comment by EVGrokker** [comment]
Also, in the trip cited above, note that the final segment should be named to match the final destination.

**Comment by aesculus** [comment]
The naming is broken for sure. How we should tackle this in the following scenarios with an initial trip from NY to CHG:
- User splits trip in Buffalo (parent trip was CHG). Now I think it would be CHG (Buffalo) for first segement and CHG for second.
- Now users splits CHG (Buffalo) trip at DET. Would east segment be call CHG (DET) and the western segment stays CHG (Buffalo)?
- Now we extend the last segment to Omaha.  Do all the pre CHG get renamed to Omaha and the last segment is just Omaha? like Omaha (CHG), Omaha (Buffalo) ...

**Comment by EVGrokker** [comment]
I think a much simpler approach would be that anytime a segment is split off, you simply name it with its destination. 

I don't see any need to keep trying to reuse the original destination in the individual segments. The user knows what their trip is. The single most identifying characteristic of any segment is its destination. 

In your example, the original segment would be Chicago. 
After the first split, you'd have Buffalo, Chicago. 
Then you'd have Buffalo, Detroit, Chicago. 
Then you'd have Buffalo, Detroit, Chicago, Omaha.

**Comment by EVGrokker** [comment]
And we still need the ability to rename trips, because once the user moves the goalpost to Omaha they're going to want to rename.  I think we have an open issue for that enhancement.

**Comment by aesculus** [comment]
To net it out it sounds like whenever I change a segments destination it needs to change the segment name?

How I got into this mess was thinking a trip would have a name and then the segments would show their destination in () after the trip name. Somewhere I screwed this up.

But of course the only way of changing the trip name would be to have some overarching trip, which we don't have. All I could do is to monitor the final segments name and go back and fix everything but that is bad because the use may have purposefully changed the name of a segment.

So back to the original statement you made. All segments when created, get the name of their destination waypoint initially? The user can then change it if they wish.

I'll look for the goal post one.

**Comment by EVGrokker** [comment]
1. Agreed: A segment's assigned name is the destination at the time when the segment is created. If the user renames it, so be it, unless they change the destination. In that case you change the name you the new destination. 
2. We do actually have an overarching trip name in Current Trips. But no mechanism for renaming it. That can wait for when you're focused on that dialog.

**Comment by EVGrokker** [comment]
See issue #94, No way to edit trip name.

**Comment by aesculus** [comment]
> We do actually have an overarching trip name in Current Trips. But no mechanism for renaming it. That can wait for when you're focused on that dialog.

Right now that name is the name of the first segment made.  So if they add segments it's still going to be the first segment made name.  

Do you need to open another issue, and can of worms for this, of should this be reflected in #94 ?

**Comment by EVGrokker** [comment]
I stand by the proposal in #94. Initial trip naming is as you do it now, based on destination. Add edit control to trip name in Current Trips, Archived Trips. Nothing fancier than that.

**Comment by aesculus** [comment]
Segment names are created now solely from the waypoint destination name.

V1.1.4 (5)

**Comment by EVGrokker** [comment]
v 1.1.4 (6)
Suggestion: If the destination is a town, include the state abbreviation in the segment name:
- Bend OR
- Kennewick WA
- Sacramento CA
