### ISSUE TITLE
Trip Segments dialog, truncating segment names

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#266]
When displaying a list of segment names derived from stops added by scissoring, it's possible to get something where the most important part of each segment name, the stopping point, is not visible in the list. See image below.

Propose that when necessary, you construct a truncated segment name consisting of the first word of the final destination, an ellipsis, then the last word, with the final segment being the trip destination.  For the image below, the abbreviated naming style would be:
- Hyatt… (Seaver)
- Hyatt… (Vacaville)
- Hyatt… (Atascadero)
- Hyatt Centric Santa Barbara

The most important part of those segment names is in parentheses.

Even if the user has renamed the individual segments, but the name is too long to display, this truncation approach should still be comprehensible.

---
![segment naming error](https://cloud.githubusercontent.com/assets/26678403/25129033/8ee91242-23f9-11e7-973a-0296c844fed8.PNG)

**Comment by aesculus** [comment]
I now just create the segment name from the waypoint name with no common trip name first.

V1.1.4 (5)
