### ISSUE TITLE
[Advanced Tutorial] Road Trip! Planning Multi-day, Multi-segment Trips

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#267]
Trip: 1. Winnemucca NV, [8vdc11g1s9ld4ptjmynibm]
_Work in progress, not ready for publication._

---

<h3>Route Planning: Multi-day, Multi-segment Trips</h3>
<p><i>Road Trip!</i></p>

<h4>The Big Picture</h4>
<p>When you're planning an extended road trip, EVTO is ready to help pin down your itinerary. Our strategy will be to use <i>Top-Down Trip Design</i>. We'll start with an origin and destination. Next, we'll segment the trip into day-sized chunks. Finally we'll do some housekeeping and have EVTO add automatic charging stops for each segment. We have a dorky name for that too, <i>Bottom-Up Resource Planning</i>. Put it all together, it's <i>Top-Down Trip Planning, Bottom-Up Resource Planning</i>…<br/><strong>TD-TD-BURP</strong>! </p>

![road trip](https://cloud.githubusercontent.com/assets/26678403/25151182/d487d67e-2441-11e7-849d-8713cfaacdd1.PNG)
<p align="center"><i>"Whaddya mean I can't make it? I bought the biggest battery!"</i></p>

<h4>1. Plan a New Trip</h4>
<p>We'll start with an origin and final destination. For this tutorial, we're planning a trip from the Tesla factory in Fremont CA to the <a href="https://driveelectricweek.org">National Drive Electric Week</a> rally in Nashville TN.</p>
<ul>
<li>Select <strong>New Trip</strong> from the main menu.</li>
<li><strong>Origin</strong>: <i>45500 Fremont Boulevard, Fremont CA</i></li>
<li><strong>Destination</strong>: <i>Nashville TN</i></li>
<li><strong>Waypoint Charger Selection</strong>: <i>Manual</i>
<li>Touch <strong>Calculate</strong></li>
</ul>
<p>As EVTO identifies a preliminary routing suggestion, consider the wisdom of Laozi:  <i>A journey of a thousand miles begins with a single step.</i> Given that our journey is actually 2,450 miles, we'll need a running head start of at least two and a half steps.</p>

<h4>2. Add required stops</h4>
<p>We'd like to visit some friends in Denver on this trip. It looks like the route that EVTO's proposing doesn't go through Denver.  All we need to do is add a Denver waypoint and EVTO will recalculate the route for us.</p>
<ul>
<li>Select <strong>Add Waypoint</strong> from the menu. </li>
<li>Enter <i>Denver</i>, then select <i>Denver CO</i> from the popup list of matching destinations.</li>
<li>Touch <strong>Save</strong> to add Denver to our route.</li>
<li>Notice that EVTO has updated our route to include Denver.</li>
</ul>

<h4>3. Estimate our daily segment distance</h4>
<p>Touch the Denver waypoint pin to open the <strong>Waypoint Inspector</strong>. We learn that the first half of our trip is 1271 miles. Touch the Nashville destination pin, and we learn that the second half of our trip is 1158 miles. Our next step is to plan our overnight stops, subdividing each half into three segments of roughly 400 miles per segment, for a total of six days on the road.</p>

<h4>4. Add the first overnight stop</h4>
<ul>
<li>Zoom the map to show California and Nevada.</li>
<li>Touch the lighting bolt button to display the Tesla supercharger overlay.</li>
<li>Zoom in on Nevada until you can see the individual charger locations.</li>
<li>Touch the Winnemucca charger pin to open the <strong>Charger Inspector</strong>.</li>
<li>Touch the pin icon to add the Winnemucca supercharger to our route.</li>
<li>Touch the Winnemucca pin again, and note that it is 398 miles from our origin.</li>
<li>At this point, you're probably noticing a lot of red SoC warnings. Fear not, range-anxious one. SoT (State of Tranquility) will arrive soon.</li>
</ul>

<h4>5. Add overnight stops for days 2, 4 and 5</h4>
<p>Since we know we'll be in Denver on the third night of our trip, we need equally-spaced stops for days 2, 4 and 5.</p>
<ul>
<li>Zoom into the Salt Lake City UT area, then touch the lighting bolt button to enable the Tesla supercharger overlay. Southeast of Salt Lake City touch the Price supercharger icon to open the Charger Inspector, then touch the pin to add this location as a charging stop.</li>
<li>Touch the Price supercharger pin again, noting that this charging stop is 470 miles from our previous stop in Winnemucca. That makes for a long day of driving, but hey, we <i>love</i> driving our EVs, right?</li>
<li>Using the same technique, add supercharger stops in Salina KS and St. Charles MO (west of St. Louis).</li>
<li>Touch the lighting bolt button to toggle the Tesla supercharger overlay off. If you're playing along at home, your trip should now look like this:</li>
</ul>

![road trip - stops added](https://cloud.githubusercontent.com/assets/26678403/25185928/dd9bcb2c-24db-11e7-92c5-ccf3820647ae.PNG)
<p align="center"><i>EVTO: Bringing new meaning to the term 'red states'.</i></p>

<h4>6. Specify Cockpit Parameters</h4>
<p>Adjusting the <strong>Payload</strong>, <strong>Cabin Temperature</strong> and <strong>Power Factor</strong> settings in the <strong>Edit Segment Details</strong> dialog provides EVTO with additional data to help refine predicted power consumption. These settings are remembered and applied to newly-created segments.</p>

<ul>
<li><strong>Payload</strong>: EVTO defaults to a payload of 400 lbs for your passengers and cargo. Your mileage may vary.</li>
<li><strong>Cabin Temperature</strong>: Some days I'm feeling like 68, some days I'm feeling like 72. I should probably get more exercise. A value of 0 tells EVTO you don't plan to use the car's HVAC system.</li>
<li><strong>Power Factor</strong>: A mysterious X factor used to tip EVTO that you're using more power than typical, perhaps because you're pulling a trailer. Or you fibbed about your payload. None of our business, really.</li>
</ul>

<h4>7. Segment the Trip</h4>
<p>Now that we've roughly anchored our daily trip stopping points and spec'd our cockpit parameters, we'll slice the trip into daily segments.</p>
<ul>

<li>Touch the Winnemucca NV pin to open the <strong>Waypoint Inspector</strong>. Touch the scissors icon to snip the upstream leg (Fremont - Winnemucca) into a separate segment.</li>
<li>Repeat this segment-snipping sequence for each of the Price UT, Denver CO, Salina KS and St. Charles MO pins. Afterwards, we'll have 6 segments.</li>
</ul>

<h4>8. Finalize the Segments with Bottom-Up Resource Planning</h4>
<p>Our general plan for this trip will be to depart by 8am each morning. To give EVTO as much information as possible for accurate planning, we'll now specify our departure date and time for each segment. It's BURP time!</p>
<ul>
<li>Touch the <strong>Trip Segments</strong> button (the folded map with the '6' badge, representing our 6 segments) to open the <strong>Trip Segments</strong> dialog.</li>
<li>Touch the <i>Winnemucca Supercharger</i> segment to make it the active segment, then touch outside the dialog to dismiss it.</i>
<li>From the menu, select <strong>Edit Segment Details</strong>.</li>
<li>Let's add a numeric prefix to each segment as we go. Touch at the beginning of the <strong>Name</strong> field, add <i>Day 1: </i>.</i>
<li>Touch in the <strong>Time</strong> field, adjust to 8:00 AM.</li>
<li>Touch in the <strong>Date</strong> field, adjust to your departure date.</li>
<li>From the menu, select <strong>Optimize Segment</strong>. EVTO optimizes the charger stops and recalculates the segment. Day 1 is good to go.</li>
<li>Rinse and repeat for each of the other segments: Dial in a departure time of 8:00 AM; Dial in the departure date (remembering to increment a day for each segment); Optimize the segment.</li>
</ul>

![road trip -final](https://cloud.githubusercontent.com/assets/26678403/25189399/44e523f0-24e6-11e7-9eb2-9c30bdb24d78.PNG)

<p align="center"><i>Good to go. Thanks, EVTO!</i></p>

<h4>Epilog: National Drive Electric Week Festivities</h4>
<p>Oh well, it looks like they moved <a href="https://driveelectricweek.org">the event</a> from Nashville to Huntsville AL this year. But now that you know how to plan a road trip, you're on your own. <i>Bon voyage!</i></p>

<hr/>

![chriscoupertd3](https://cloud.githubusercontent.com/assets/26678403/25187855/757844ac-24e1-11e7-8c02-febf0a0c43c7.jpg)
<p align="center"><i>EVTO's senior developer has been practicing Top-Down, Bottom-Up trip planning since last century. He's seen here as young motoring enthusiast, enjoying a top-down ride with dad in the family MG Roadster.</i></p>

<p><i>Got an idea for a tutorial? <a href="mailto:support@digitalautoguides.com?Subject=Tutorial suggestion">Let us know!</a>
</p>

**Comment by aesculus** [comment]
Replaced by #547
