### ISSUE TITLE
Converting an automatic charging stop to a required stop should keep the Waypoint Inspector open

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#268]
Currently, the behavior is to dismiss the Waypoint Inspector after converting an automatic charging point to a required stop. Since the user probably has a particular reason for the conversion, which will involve either setting a MinStopTime or SoC target, leave the Waypoint Inspector open so they can proceed with their objective.

**Comment by aesculus** [comment]
This is a bit more complex than it appears. Event though changing the waypoint type is only flipping one bit, it has implications on the Waypoint Inspector, the whole thing needs to be rebuilt, Also the push pin is different and so is its behavior.

Would closing it (which is done automatically because the route is actually being redisplayed) and then opening it up a second later be acceptable? I might be able to set some sort of flag after the refresh event to open the Waypoint Inspector in this instance.

**Comment by EVGrokker** [comment]
Closing/reopening might not be as elegant, but would be acceptable in the near term. The specific condition I was facing was that I was zoomed way in on a very long segment, and after the WI closed, the entire trip was shown, so I had to zoom way in again to find the pin I was editing.

If possible, try reopening after conversion, let's see how that feels.

**Comment by aesculus** [comment]
Ah. Got it.  Let me see what I can do but it's going to take some time.  At first I thought it would be trivial so that is why I jumped on it.

**Comment by EVGrokker** [comment]
Bugs first.

**Comment by aesculus** [comment]
> The specific condition I was facing was that I was zoomed way in on a very long segment, and after the WI closed, the entire trip was shown, so I had to zoom way in again to find the pin I was editing.

In V1.2 (69) I fixed your problem another way. I now don't change the map's bounds for a simple waypoint edit that won't change the routing.

**Comment by EVGrokker** [comment]
I'm not seeing that behavior, or perhaps I'm misunderstanding the explanation.

I have a segment from Seattle to Bend. I'm zoomed in on a charging stop in Longview, about midway. I open the waypoint inspector, change the name of the waypoint, which doesn't require any routing calculations, but upon closing the editor, the route is recalculated, and the map is zoomed out farther than when I select the segment from the Trip Browser.

**Comment by aesculus** [comment]
You don't have 69 yet. :-)
