### ISSUE TITLE
Favorited waypoints should remember charger type and details

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#27]
Currently, reusing an existing Favorite in a new trip loses the assigned charger info. This attribute should be persistent and editable in the Maintain Favorites panel.

**Comment by aesculus** [comment]
This should be fixed in V1.1.2

Needs to be verified.

**Comment by aesculus** [comment]
I may have miss read this request, as toggling the Favorite value will wipe out whatever is there. So if you had a charger assigned, toggled the favorite and then put it back where there was no charger, the charger would be wiped out.

However there was a bug that the charger info was not moving over on the original favorite setting and that has been fix.
