### ISSUE TITLE
Need to eliminate other segment endpoint pushpins that overlap current segment

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#275]
There are gray pushpins on the non active segment endpoints so the user can see where they terminate.  However they also appear on top of the active segments endpoints because they are co-terminus.

The app should not show the gray pushpins when they are collocated with the current segments endpoints.

**Comment by aesculus** [comment]
This is related to #283

**Comment by EVGrokker** [comment]
Bumping this issue, with an additional suggestion:

Touching an inactive hinge pin activates the associated segment, preferably treating the pin as an origin when there's a choice.

**Comment by aesculus** [comment]
I think you would always have to treat these as destinations because there will always be a destination at that location. The last inactive pin is only a destination.

**Comment by aesculus** [comment]
Never mind. It's a bit quirky after implementing it.  Sometimes the endpoint is a destination and sometimes it's an origin.  I am going to have to have you plan with it a bit to see if you can see a pattern that makes sense.  Find at least a three segment trip to play with and come at it from every segment.

Implemented in V1.2 (23)

**Comment by aesculus** [comment]
In V1.2 (29) I have made sure that no pushpins are duplicates of active pushpins.
