### ISSUE TITLE
Confirm Delete dialog: Include name of waypoint being deleted

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#276]
v 1.1.4 (7)

When displaying the Confirm Delete dialog, propose including the name of the waypoint being deleted.

Suggested wording:

**Confirm Delete**
[name of waypoint]
Do you want to delete this waypoint?
Cancel | **Delete**

---
![delete waypoint](https://cloud.githubusercontent.com/assets/26678403/25227206/ff4a019a-2584-11e7-86e7-b5140a78ffc8.PNG)

**Comment by aesculus** [comment]
Updated in V1.1.4 (8)

![image](https://cloud.githubusercontent.com/assets/283364/25237741/6056c796-25a0-11e7-8816-54abcd7b466c.png)
