### ISSUE TITLE
[Basic Tutorial] Shifting from Auto to Manual

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#277]
<h3>Route Planning: Shifting from Auto to Manual</h3>
<p><i>Exploring EVTO's Auto and Manual route planning modes</i></p>

<h4>The Big Picture</h4>

<p>EVTO automatically kicks into high gear when you supply a trip's starting and ending points: It selects a route, identifies charging stops, and displays the recommended route. Sometimes, you have a specific scenic route in mind, or a preference for particular points of interest. This tutorial explores two different approaches to route planning using <i>Auto</i> and <i>Manual</i>.</p>

<p><i>Note: EVTO uses parameters specified in <strong>Settings</strong> and <strong>My Cars</strong> to improve the accuracy of its predictions. If your numbers don't match ours, that's probably because you have a newer car with cooler features.</i></p>

![waypoint charger selection](https://cloud.githubusercontent.com/assets/26678403/25241251/89888246-25b2-11e7-97cd-ad9b3ad4adba.PNG)

<h4>1. Auto Mode</h4>
<p>When EVTO is initially installed, <i>Auto</i> is the default choice. <i>Auto</i> means EVTO will automatically select a route from your origin to your destination, seeking optimal charging stops, based on vehicle characteristics and predicted weather conditions at the specified departure time. Your most recent waypoint charger selection, <i>Auto</i> or <i>Manual</i>, is remembered the next time you create a new trip.</p>
<p>Let's create a simple trip using <i>Auto</i> charger selection:</p>
<ol type="a">
<li>Select <strong>New Trip</strong> from the main menu.</li>
<li><strong>Origin</strong>: We'll launch from Tesla HQ: <i>45500 Fremont</i>, selecting the <i>Fremont CA</i> result from the displayed list of destinations. </li>
<li><strong>Destination</strong>: Enter <i>Northstar</i>, then select <i>Northstar California Resort</i> from the displayed list of destinations.</li>
<li><strong>Waypoint Charger Selection</strong>: Select <i>Auto</i>.</li>
<li><strong>Calculate</strong>.</li>
</ol>
<p>EVTO calculates our route with an automatically suggested supercharging stop midway. That's it – all that's left is the driving! Enjoy your day shredding the slopes! The return trip is easy as can be, with two nearby superchargers.</p>

![northstar - auto](https://cloud.githubusercontent.com/assets/26678403/25490306/ad6da9e4-2b29-11e7-913a-52d456da4fd3.PNG)
<p align="center"><i>Use</i> Auto <i>to calculate optimal routes with automatic charging stops</i></p>

<h4>2. Manual Mode</h4>
<p>To include specific stops on the way to our destination, we'll use EVTO's <i>Manual</i> mode. Today, our snowboarding friend Bob from Roseville will be joining us. Bob always likes to stop at Rocklin's MOOYAH Burgers because, well, just because. After specifying our origin and destination, we'll add two waypoints and a charging stop.</p>

<ol type="a">
<li>Select <strong>New Trip</strong> from the main menu.</li>
<li><strong>Origin</strong>: We'll depart from Tesla HQ: <i>45500 Fremont</i>, then select the <i>Fremont CA</i> result from the displayed list of destinations. </li>
<li><strong>Destination</strong>: Enter <i>Northstar</i>, then select <i>Northstar California Resort</i> from the displayed list of destinations.</li>
<li><strong>Waypoint Charger Selection</strong>: Select <i>Manual</i>.</li>
<li>Touch <strong>Calculate</strong>.</li>
</ol>

![reddestpin](https://cloud.githubusercontent.com/assets/26678403/25491896/9a0445d4-2b2e-11e7-92ef-08902036b69c.PNG)
<p align="center"><i>The first step of a manually calculated route</i></p>

<p>This time, EVTO calculates our route without any charging stops. EVTO is urgently calling our attention to an impending electron shortage by displaying a red destination pin. No worries. We'll add our manual waypoints, then take care of any required charging stops.</p>

<h4>3. Add waypoints</h4>
<ol type="a">
<li>From the menu, select <strong>Add Waypoint</strong>.</li>
<li>Enter <i>Roseville CA</i> in the name field, then select <i>Roseville, CA</i> from the displayed list of results.  Bob prefers that we not know his actual address, but that's another story. So we meet him in downtown Roseville.</li>
<li>Bob's never ready on time, so let's add 20 minutes for <strong>Minimum Stop Time</strong>. Touch <strong>Save</strong> to add Roseville as a waypoint.</li>
<li>Just in case we forget <i>why</i> we're stopping in Roseville, let's rename the waypoint to <i>Pick up Bob</i>.</li>
<li>Touch the Roseville pin to open the <strong>Waypoint Inspector</strong>, then touch the pencil icon to open the <strong>Edit Waypoint</strong> dialog. Clear the name field at the top, then enter <i>Pick up Bob</i>. Touch <strong>Save</strong> to close the dialog.</li>
<li>Next, let's add <a href="http://www.mooyah.com/locations/rocklin-ca-203/">Mooyah Burgers</a>. For Bob. Sigh.</li>
<li>From the menu, select <strong>Add Waypoint</strong>.</li>
<li>Enter <i>Mooyah Burgers Rocklin</i> in the name field, then select the <i>MOOYAH Burgers, Fries  &amp; Shakes, Commons Drive, Rocklin CA</i> from the displayed list of results.</li>
<li>Experience dictates that I should allow about 30 minutes for Bob's flirting with Rosie, about 20 minutes longer than I need to finish my Reese’s® PB Cups Mint Chocolate Chip Shake. Dial in 30 minutes for <strong>Minimum Stop Time</strong>.</li>
<li>Touch <strong>Save</strong> to update our itinerary.</li>
</ol>

<p>Now we have an origin, two waypoints and a destination, but no planned charging stops.</p>

<h4>4. Add a charging stop</h4>
<ol type="a">
<li>Touch the lighting bolt button (lower right) to add the Tesla Superchargers overlay to the map.</li>
<li>Zoom in on the Roseville - Rocklin area until two individual charger locations are displayed.</li>
<li>Touch the southernmost <strong>S</strong> pin, between Roseville and Rocklin, to open the Charger Inspector.</li>
<li>Touch the pin button to add the Roseville Supercharger to our itinerary.</li>
<li>EVTO added the Roseville charging stop after the <i>Pick up Bob</i> stop, but I'd rather charge <i>before</i> picking up Bob. If you knew Bob, I'm sure you would agree.</li>
<li>From the menu, select <strong>Segment Summary</strong> to display our itinerary.</li>
<li>Touch and hold the downward arrow at right edge of <i>Pick up Bob</i> to move it below the <i>Roseville Supercharger</i> stop.</li>
<li>Touch the circular arrow to the right of <strong>Calculate New Routing</strong> to apply the new waypoint ordering.</li>
<li>Touch outside the <strong>Segment Inspector</strong> to dismiss the itinerary.
</ol>

<h4>5. Reserve some juice for local driving</h4>
<p>Finally, let's tell EVTO to reserve some energy for local driving in the North Lake Tahoe area.</p>
<ol type="a">
<li>From the menu, select <strong>Edit Segment Details</strong>.</li>
<li>In the <strong>Destination Reserve</strong> field, enter <i>50</i> miles.</li>
<li>Touch <strong>Save</strong> to close the dialog and recalculate the route.</li>
</ol>

<p>Finally, select <strong>Segment Summary</strong> from the menu to display our itinerary.</p>

![segment summary](https://cloud.githubusercontent.com/assets/26678403/25494521/280d6d26-2b37-11e7-9729-556d390ee2cd.PNG)

<p align="center"><i>Segment Summary showing our completed itinerary after rearranging waypoint order</i></p>

<hr/>

<h4>When to use <i>Auto</i>:</h4>
<ul>
<li>You're planning a simple origin to destination trip, and you don't care about where you stop – you just want the quickest route.</li>
<li>You want to impress your non-EV-owning friends with how EVTO makes it easy to quickly stare down range anxiety.</li> 
</ul>

<h4>When to use <i>Manual</i>:</h4>
<ul>
<li>You're planning a trip with specific stops or routing.</li>
<li>You'd prefer to select your own charging stops.</li>
<li>You promised Bob you'd take him snowboarding, and you wouldn't mind a MOOYAH burger.</li>
</ul>

<p>If you do stop into the Rocklin MOOYAH, please tell Rosie that Bob sends his regards… then be prepared for an earful.</p>

<hr/>

<p><i>Got an idea for a tutorial? <a href="mailto:support@digitalautoguides.com?Subject=Tutorial suggestion">Let us know!</a>
</p>

**Comment by EVGrokker** [comment]
Please try following the tutorial when you have a chance. The first time I added the waypoints, the Optimizing dialog stayed up forever until I touched the Back button to go to the main screen, then back to the Plan screen. This happened with both the Roseville and Placerville waypoints.

The second time I followed it, it did not have the problem.

Also, looking for feedback on tutorial tone and depth.

**Comment by aesculus** [comment]
This weekend

**Comment by aesculus** [comment]
I think the trip should be a bit longer and have more routing choices or at least have a bit more chargers. It needs to actually demonstrate it's doing something other than what the car would do.

What about adding the feature for local travel that would force a charge in the north lake area? Be careful with the Lake Tahoe Ski Resorts because there is no SC there. There are two in North Lake Tahoe.  So maybe go to Northstar as your destination.

You will need the ID [2vc9t4mbxct3j1qw09dq9q] and the PIN [1234]

**Comment by EVGrokker** [comment]
Updated with Northstar as destination, added Destination Reserve for Tahoe area driving. Rosie now works at the Rocklin Starbucks.

**Comment by aesculus** [comment]
The goto place at the Rocklin SC is MooYah hamburgers. :-)

http://www.mooyah.com/locations/rocklin-ca-203/

**Comment by EVGrokker** [comment]
Rosie suddenly quit the Rocklin Starbucks and now works at MOOYAH. Huh.

**Comment by aesculus** [comment]
It's a bit of a walk but you need to burn the calories. Now if they could get that snake charger and summons working ...

**Comment by aesculus** [comment]
All set

http://www.digitalautoguides.com/shifting-from-auto-to-manual

A couple of comments:
- Mooyah burgers is about 1/4 mile from the Rocklin SC FYI. 
- The segment summary image is one where you changed the order. That could confuse people if they tried to match it. If you select the button at the bottom you should be OK and it will clear that button from the summary

**Comment by EVGrokker** [comment]
- I revised the text with lots of minor edits. Rather than calling them out line by line, the easiest thing would be for you to recopy the HTML elements and paste into the DAG page. Note that I added caption elements below several of the images that did not previously have them.
- With respect to your comment that the Rocklin SC is near the MooYah… I think what you're saying is that it would make more sense to plan a charging stop there and walk to Mooyah. I agree, but because the route starts in the Bay Area, and I wanted to show rearranging waypoint order, this sequence has us arriving at MooYah at ~11:30 with sufficient charge. It's obviously not real-world optimal, but it serves the purposes of the tutorial.
- Not clear what you mean by 
>The segment summary image is one where you changed the order. That could confuse people if they tried to match it. If you select the button at the bottom you should be OK and it will clear that button from the summary 

I added a caption below the Segment Summary snapshot. Does that help? If not, please explain.
- In terms of the image size, in general they look overly large to me. Because T&Ts will be using a lot of screen shots, I'd suggest standardizing on a size for full-screen capture, and another size for cropped map images. I posted the images at full resolution so that you'd have plenty of detail to work with. I'd suggest trying reducing everything to 50% of original size to see how that looks.  The first image of the Auto and Manual buttons you can probably keep at full size.

**Comment by aesculus** [comment]
>I added a caption below the Segment Summary snapshot. Does that help? If not, please explain.

It looks like you had created the trip and then moved the waypoints. That caused the extra button to appear at the bottom of Segment Summary prompting you to Restore Waypoint Auto Order.  That would not be on the users panel because they would not reorder the waypoints

**Comment by EVGrokker** [comment]
I did move the waypoints. The text says that I added the supercharger, but wanted to charge before picking up Bob. If they were following along step by step they would see this.

**Comment by aesculus** [comment]
Missed that. Was that in the first instructions?

**Comment by EVGrokker** [comment]
It's always been there, even when Rosie worked at Starbucks in Placerville. :)

**Comment by aesculus** [comment]
Rats. OK. Just glossed over it I guess.

**Comment by EVGrokker** [comment]
You're a busy guy.

**Comment by aesculus** [comment]
Try it now

**Comment by EVGrokker** [comment]
Size of the maps and Segment Summary looks perfect.
Can you center Segment Summary?
And try reducing (and centering) the Big Picture Auto/Manual to maybe 75% or 50%? It's too big.

**Comment by EVGrokker** [comment]
Also, the tag line HTML is missing:

<hr/>

<p><i>Got an idea for a tutorial? <a href="mailto:support@digitalautoguides.com?Subject=Tutorial suggestion">Let us know!</a>
</p>

**Comment by aesculus** [comment]
OK. Try it now. The auto/manual image may be a bit too small for the browser

**Comment by EVGrokker** [comment]
Can you split the difference on the size of the Auto/Manual image? Halfway between what it is now and what it was.

Add an <hr/> element before the bottom tag line.

Everything else looks good.

**Comment by aesculus** [comment]
Look again

**Comment by EVGrokker** [comment]
The hr element needs a closing slash before the closing bracket.

**Comment by EVGrokker** [comment]
`<hr/>`

**Comment by aesculus** [comment]
Again

**Comment by EVGrokker** [comment]
OK, that's good for this page. I'm sending you mail about the intermediate links page to the tutorials.
