### ISSUE TITLE
Trip Optimization less than optimal after changing destination 

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#278]
1. New Trip
2. **Origin**: Fremont CA
3. **Destination**: _Lake Tahoe_ (select 'Lake Tahoe' from the displayed choices)

Route calculates, EVTO chooses Sacramento - Rocklin charging stop. All good.

4. Touch destination pin, edit
5. Change destination to _Lake Tahoe Ski Resorts_
6. Zoom into Rocklin charging stop.
7. Enable supercharger overlay.

Note that either the Iron Point Road or Palladio Parkway superchargers are the appropriate choices. Rocklin is no longer the appropriate charger choice.

Recalculating this route with Lake Tahoe Ski Resorts as the destination does indeed select Palladio Parkway as the auto charging stop.

**Comment by aesculus** [comment]
As designed.  EVTO does not do automatic optimization.  It does automatic calculations.  So if you want it to move automatic chargers, you have to manually select Optimize.
