### ISSUE TITLE
Trip Segments dialog: Display segment metrics with each segment

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#279]
In the **Trip Segments** dialog, propose displaying mileage, driving time and charging time beneath segment name.

For example, in the attached screen shot, the segments would have the additional info displayed:

**Winnemucca Supercharger**
401 mi   |   [car icon] 6:15   |   [lighting bolt icon] 1:34 

**Price Supercharger**
471 mi   |   [car icon] 7:00    |   [lighting bolt icon] 2:25

The car icon represents time spent driving, the lighting bolt icon represents time spent charging. Vertical bars (pipes) inserted for spacing suggestion (GitHub removes spaces).

---
![trip segments summary](https://cloud.githubusercontent.com/assets/26678403/25232157/ad99070c-2597-11e7-8c59-0f297531727c.PNG)

**Comment by aesculus** [comment]
OK. The original intent was for this dialog just to get users from segment to segment. Do you think adding this could interfere with that if the list was long?

**Comment by EVGrokker** [comment]
Smaller font is fine. We don't have a trip itinerary overview anywhere else, this is the logical place to look for it. With respect to long lists, I definitely still feel like the summary detail currently at the bottom of the list should be at the top, with the individual segments following. If you can make the top trip summary item be a non-scrolling header, all the better. I seem to recall you used this layout to mimic the in-car dialog appearance, but you know my feelings about that. :)

**Comment by EVGrokker** [comment]
You can use the same font size and general design style you're using in the Segment Summary dialog, that layout works well. If you do decide to move the summary item to the top, that decision would affect the Segment Summary dialog as well. :)

**Comment by EVGrokker** [comment]
I've mocked up a single line version with the added segment metrics. The scale and placement need tweaking, but the concept is accurate.

---

![trip segments w metrics](https://cloud.githubusercontent.com/assets/26678403/25274510/8e527d0e-264d-11e7-8452-11d9ffa8115b.png)
