### ISSUE TITLE
Calendar Update dialog text revision

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#281]
v 1.1.4 (8)

**Current text**:
~~You are going to add or update a calendar entry for each waypoint of this trip! Is that whay you want to do?~~

**Proposed text**:
Export waypoints and charging stops from the [segment name here] segment to your device calendar?

Cancel | **OK**

**Comment by EVGrokker** [comment]
Second dialog feedback, after pressing **OK**:

This is the dialog that can be removed from the flow.

**Comment by aesculus** [comment]
V1.1.4 (9)

**Comment by EVGrokker** [comment]
Uhm, the intent of **[segment name here]** was for you to insert the name of the segment when constructing the dialog.

---

![calendar dialog](https://cloud.githubusercontent.com/assets/26678403/25276379/25fedd6a-2657-11e7-8c84-fd55d2119e5d.PNG)

**Comment by aesculus** [comment]
Duh. Fixed in V1.1.4 (10)
