### ISSUE TITLE
Main menu: Wipe EVTO Data appears non-functional

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#282]
v 1.1.4 (8)

Touching the **Wipe EVTO Data** item in the main menu appears to have no effect. The menu is not dismissed.

My favorites are still intact, my Settings are still intact, My Cars are still intact…

I'd suggest a confirmation dialog confirming the deletion as well.

**Comment by aesculus** [comment]
Hmm. Did it wipe the trip data?
It was also supposed to close the app too. 


Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by EVGrokker** [comment]
Current trips are intact. There is no UI feedback to indicate that the menu selection was acknowledged, it's as if the menu item is inactive.

**Comment by aesculus** [comment]
I used the wrong verb. V 1.1.4 (9) should wipe it out for sure. :-)

**Comment by EVGrokker** [comment]
v 1.1.4 (9)
Still doesn't work.

I'm skeptical of the need for this. Why not just tell beta users to do a fresh install? Won't that accomplish the same thing?

**Comment by aesculus** [comment]
I was calling the same function twice and chasing my tail. 3rd times charm.

fixed in V1.1.4 (10)

I want to put to bed the notion that data is staying in the device after an uninstall/reinstall.

**Comment by EVGrokker** [comment]
1.1.4 (10)
Dialog is presented, but touching Wipe does not dismiss dialog. Cancel does dismiss dialog.

**Comment by aesculus** [comment]
I did not test this on the iOS device but did on my others. My bad. 

But it does seem to wipe the data.  The original intent was for it to shutdown the app.  That is what is not working now so I will have to dig a bit deeper on why.

**Comment by EVGrokker** [comment]
I will test to see if it's actually deleting data. Don't forget to remove this when you release the production version!

**Comment by aesculus** [comment]
Yeah. It goes along with turning the IAP stuff back on again. :-)

**Comment by aesculus** [comment]
FWIW from one of the beta testers that always has issues after updates and is a old beta user when the underlying data structure was in flux:

>Looking good on both iPad and iPhone.
Wipe seems to have worked as old trips cleared out but box which appears after hit 'wipe data' doesn't do anything when you press 'wipe' - but seems to work anyway. 

>All trips I've tried so far on both have worked fine!
