### ISSUE TITLE
Include All Waypoint Icons in Non Active Segments

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#283]
From a user:

>However I did notice that the little A markings that designate an automatically chosen supercharger do not show up on unselected routes. I believe it would be helpful for such indications to always be visible to help understanding the overall route.

**Comment by EVGrokker** [comment]
Is this coming from a beta tester or an end user?

**Comment by aesculus** [comment]
Beta. I am against it personally as I think it would be too cluttered. He is really pushing on the whole MST stuff which is good.

**Comment by EVGrokker** [comment]
I agree with you, but I do have an idea of a compromise solution that might fly. I will write it up here later.

**Comment by EVGrokker** [comment]
Here's what I propose:

For non-active segments, use a 'pinhole' marker to show the location of the inactive segment pins. The pinholes would include no other encoding - no SoC color, no 'A's for auto charging stops, nothing more than a pinhole showing where on the segment the pins are. 

If the user really needs to know whether a pinhole is charging stop or a lunch stop, they can toggle over to the segment in question to restore the active pins.

Here's a quick mock-up showing what I have in mind:

![multi-segment trip - pinholes](https://cloud.githubusercontent.com/assets/26678403/25272470/3b449a14-2645-11e7-91d7-c3979bc86a86.png)

**Comment by aesculus** [comment]
Added in V1.1.4 (10)

**Comment by EVGrokker** [comment]
This is fussy, but I think the pinholes should be a bit smaller. They should fit inside the route line. I'd guess about 2/3 the size you currently have. Look at the base of an origin pin for reference - it's about half the size.

**Comment by aesculus** [comment]
I brought them down 1 step (4 > 3). At 2 they were too small.
