### ISSUE TITLE
Rename 'Trip Segments' to 'Trip Inspector', 'Segment Summary' to 'Segment Inspector'

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#284]
Recent improvements have clarified my thinking about the architecture and hierarchy of EVTO.

We have various dialogs allowing the user to modify trip elements:
- The **Waypoint Inspector** is used to change the name, favorite status, charger selection
- The **Charger Inspector** is used to preview information about a charger, and can be used to add a charger to the current segment.
- The **Trip Inspector** (issue #94 not yet implemented) is used to rename the active trip.

We've established a pattern of 'inspectors' for editing. 

In that spirit, I propose that the Trip Segments dialog, invoked by touching the folded map button on the Plan page, be renamed to the **Trip Inspector** button. In practice, all this means is changing some text in the Plan menu help panel.

Similarly, I propose that the 'Segment Summary' menu item be renamed to **Segment Inspector**. This would mean changing the menu text, as well as some help text in the Plan menu help panel. 

The actual header for the Segment Inspector would be the l/r nav arrows, plus the name of the active segment:

For example:
<  Sand Dollar Inn & Cottages (1/3) >
< Winnemucca Supercharger (1/7) >

**Comment by EVGrokker** [comment]
Some additional observations:

'Edit Segment Details' is where the user tweaks the segment settings, including name, ETD, payload, cabin, Origin SoC and Dest Reserve.
'Segment Summary' is where metrics are displayed and waypoint order is managed.

'Edit Segment Details' described exactly what's available in that dialog.
'Segment Summary' or 'Segment Inspector' is a bit more vague. With a UI revision allowing moving between segments, 'Segment Inspector' makes sense, because you're inspecting the various segments and their metrics.

**Comment by aesculus** [comment]
I vote for this to be in V1.2

**Comment by EVGrokker** [comment]
WRT the dialog currently labeled 'Trip Segments':
- I'd still like to rename this 'Trip Inspector' 
- The content of the summary section should be moved up to below the header to match the layout of the Segment Summary.
- The content should be revised to be consistent with the Segment Summary content. In other words, use the zap icon for charging time, the car icon for driving time.

**Comment by aesculus** [comment]
I am still not sold yet on either summary or inspector. Inspector I don't like because it implies detail, which this dialog is not doing.

Summary would fit if the dialog was static.  But in addition to portraying summary info it:
- Jumps to the selected waypoint
- Allows reordering of waypoints
- Allows restoring waypoint order

**Comment by EVGrokker** [comment]
We could go simpler and simply have the header say 'Segments' and 'Trip'.

**Comment by aesculus** [comment]
Works for me. But shouldn't it be Waypoints (Segment) and Segments (Trip)? Those are what is being shown.

**Comment by EVGrokker** [comment]
When you touch the folded map icon (Trip Summary) it provides an overview of the entire trip and its component segments.

When you invoke the Segment Summary, it provides an overview of the entire segment and its component waypoints. 

So I feel that 'Trip' and 'Segments' is more encompassing of the respective content.

How about Trip Overview and Segment Overview? (I'm not sure, just a thought.)

**Comment by EVGrokker** [comment]
I've experienced a moment of clarity about this naming conundrum.

There are actually two separate issues: How we refer to the dialogs in question (in Help, or menus) and how they are titled when they are displayed. There is no need for the dialog header to contain the name we use to refer to the dialog. For example, we refer to the 'Waypoint Inspector' but that text never shows up anywhere except in documentation.

With that distinction in mind, consider the two dialogs shown side by side below. 

![summarycomparison](https://cloud.githubusercontent.com/assets/26678403/26725059/6e72a638-4751-11e7-96d7-4f09fb10977a.jpg)

**Observation 1:** From the user's perspective, the Segment Summary concerns the 3rd segment of their trip, terminating at the Fess Parker Inn in Santa Barbara. In the Edit Segment Details dialog, we name this segment by its destination, so the proper thing to do in the Segment Summary dialog is to use the same segment name as the title text. 

**Suggestion 1**: The Segment Summary dialog should use the segment's destination as the title text. In the image above, 'Segment Summary' would be replaced with 'Fess Parker Inn'.  With segment 1 active, the text would be 'Springfield Supercharger'. With segment 2 active, the text would be 'Petaluma Supercharger'.

**Observation 2**: From the user's perspective, the Trip Segments dialog refers to the trip named 'Fess Parker Inn' in the Current Trips dialog and the Edit Trip Details dialog. In other words, we've already established the convention that trips are named by their final destination, so the proper thing to do in the Trip Segments dialog is to use the trip name as the title text.

**Suggestion 2**: The Trip Segments dialog should us the trip's destination as the title text. In the image above, 'Trip Segments' would be replaced with 'Fess Parker Inn'.

I also have some comments about making the dialog styles consistent, but I'll add those to the appropriate issues.

**Summary recommendation**: We refer to these dialogs as the 'Segment Summary' and 'Trip Summary', but that text is not used in the rendered dialogs.

**Comment by aesculus** [comment]
I understand your concern and it's valid, however here are some issues I have:
- Trip and segment names can be quite large, often exceeding the available space in the header.
- The user can change the name of a segment at any time. And now that we have the concept of a trip name, that can be different again - even though it defaults to the original last segment name. Note if they add segments, the trip name does not change automatically.
- The Plan panel title already has the segment name, so there should not be confusion on what segment they are on.
- I think the dialogs titles should be consistent, especially as you state, we refer to them in the help and other places

So I favor sticking to fixed names for these two dialogs.

**Comment by EVGrokker** [comment]
Then that puts me back to using 'Trip Summary' and 'Segment Summary'. That's the way that I've written the draft help content in #409 and #410.

**Comment by aesculus** [comment]
'Trip Summary' and 'Segment Summary' is what it will be then in V1.2 (28)

**Comment by EVGrokker** [comment]
Just had a thought… what do you think about 'Trip Browser' and 'Segment Browser'?

**Comment by aesculus** [comment]
That could work nicely.

**Comment by aesculus** [comment]
Do we want to proceed with 'Browser"?

**Comment by EVGrokker** [comment]
Let's take a step back and reconsider this to make sure we select a really good option. 

**Trip Summary** (invoked by touching folded map)
- Itemizes trip segments with metrics
- Summarizes trip metrics
- Offers navigation to Segment Summary via long-press on a segment

**Segment Summary** (invoked from Plan menu on current segment, or long-press from Trip Summary)
- Itemizes segment stops with metrics
- Summarizes segment metrics
- Offers navigation to stops via touch on a stop

<table>
  <tr>
    <th>Candidate</th>
    <th>Suggests…</th> 
    <th>Comments</th>
  </tr>
  <tr>
    <td><i>Summary</i></td>
    <td>Encapsulation of details</td> 
    <td>No interaction suggested, ignores components</td>
  </tr>
  <tr>
    <td><i>Overview</i></td>
    <td>Abstraction of details</td> 
    <td> No interaction suggested, ignores components</td>
  </tr>
  <tr>
    <td><i>Browser</i></td>
    <td>Interactive interface to elements</td> 
    <td>Implies review and interaction</td>
  </tr>
  <tr>
    <td><i>Inspector</i></td>
    <td>Edit details</td> 
    <td>Overpromises. Editing is several touches away</td>
  </tr>
  <tr>
    <td><i>Analysis</i></td>
    <td>Review details</td> 
    <td>Seems overly technical, implies conclusions</td>
  </tr>
</table>

Assuming we go with Browser, the updated definitions would be something like:

**_Trip Browser_**: Review trip summary and component segments
**_Segment Browser_**: Review segment summary and component stops 

I'm good with _Browser_ if you are.

**Comment by aesculus** [comment]
In V1.2 (37).
- Changed Trip Summary to Trip Browser
- Changed Segment Summary to Segment Browser

**Comment by aesculus** [comment]
PS. I did a wholesale change of Summary to Browser and changed the help too.
