### ISSUE TITLE
Retain charger metrics when adding to route

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#285]
v 1.1.4 (9)
Currently, when inspecting a supercharger pin not currently assigned to the active segment, you include a line:

**Charging**
10 superchargers, available 24/7

After adding a charger to a route, either automatically or manually, this information is lost.

The proposal is to retain the charger metrics underneath the address line when viewed in the Waypoint Inspector:

**Aberdeen Supercharger**
416 Wishkah Street, Aberdeen WA
10 superchargers, available 24/7

**The Evergreen State College**
2700 Evergreen Parkway NW
Olympia WA
J 1772

**Comment by aesculus** [comment]
Added V1.1.4 (10)
