### ISSUE TITLE
Minimum Stop Time granularity

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#286]
v 1.1.4 (9)

Currently, the granularity of the Minimum Stop Time is 5 minutes, from 0 to 360 minutes. That many stopping points along the slider make adjustments fussy.

My sense is that typical stop times would be 0 to 120 minutes. A couple of ideas:

- Reduce the range to 120. If a user needs to stay longer than two hours, we recommend they segment and set a new departure time for the next segment. 
- Implement a non-linear scale to the slider, such that the first hour was in 5 minute increments, then the next hour was in 15 minute increments, then it jumps to 30 minute increments. The display would read 0:05 for the first hour, 1:15 for the second hour, 2:30 for longer increments. In other words, not raw minutes, but hours and minutes. (I know, this is a lot of work).

**Comment by aesculus** [comment]
I can't easily do a non linear slider but I can reduce the max time to 120 minutes or maybe we should just do it in 15 minute increments and allow a max of 240 minutes (4 hours) stop time.

**Comment by EVGrokker** [comment]
Or maybe 5 minute increments is OK. But I still think 2 hours is a good upper limit.

**Comment by aesculus** [comment]
You win the prize. :-)

I set it to 5 min/2 hours. See if this works for you. If not I can go to 10 minutes.
