### ISSUE TITLE
Unable to import trip to fresh install

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#287]
After a clean installation of EVTO, it's not possible to import a previously-exported trip unless another trip is created after the fresh installation.

For example, I delete EVTO, then reinstall. 
From the Current Trips dialog, I import a trip.
I can see the trip, but I can't activate it.

Proposal: When importing a trip without an active trip, make the imported trip the active trip.

**Comment by EVGrokker** [comment]
This also needs to work with installations without the Multi-Trip subscription.

Suggestion: Importing a trip automatically makes it the current trip. App goes to Main screen, 'Resume Trip' is displayed, leading to the imported trip.

**Comment by aesculus** [comment]
Can you validate that it is not the active trip?  You may not notice this because you only have one trip in the list and it's bold, so no contrast to the other list items.  If you select Back and Resume you will find that it is active.

So the question might be: Immediately go to the Plan Trip panel after a user Imports a trip.

**Comment by EVGrokker** [comment]
The trip is imported but it's not bold, and there's no way to select it to make it the active trip.

**Comment by EVGrokker** [comment]
I'll try a clean install and rerun the test.

**Comment by EVGrokker** [comment]
The trip is imported, and it is bold in the Current Trips panel after import. Activate Trip is not active. Touching Back to go to the Main screen shows 'Getting Started', not Resume Trip. So it's loaded, but there's no way to get to it.

**Comment by aesculus** [comment]
Select Getting Started and then immediately Let's Get Started. Then Resume.

This will be solved when I implement the request for skipping the Getting Started panels if a trip is defined.

**Comment by EVGrokker** [comment]
Ok. <grumble grumble grumble>

**Comment by aesculus** [comment]
This is not really broken so I am going to close it. It will be addressed with the changes on the app startup.
