### ISSUE TITLE
New Trip Error using Tesla Superchargers as Origin and Destination

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#288]
v 1.1.4 (9) Location services disabled since installation.

- **New Trip**
- **Destination Charger Type**: Tesla Superchargers
- **Origin**: Burlington Supercharger, Burlington WA
- **Destination**: Brewer Supercharger, Brewer ME
- **Waypoint Charger Selection**: Manual
- **Calculate**

New Trip Error dialog is displayed:
_You must select an origin or turn location services on!_

I enabled Location Services and tried again. Same error.

**Comment by EVGrokker** [comment]
Tried again with fresh installation, this time allowing Location services, and using Auto Waypoint charger selection. I get the 'Direction Services Failed' dialog, but it did calculate the route.

Manually disabled Location services in Settings, tried again with Auto. I get the New Trip Error as described in the first comment.

**Comment by aesculus** [comment]
Fixed in V1.1.4 (10)
