### ISSUE TITLE
Segment naming error: 'undefined' appended to segment names

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#289]
ID [g53cncvjtja99pkfok5kb5] and the PIN [1234]

The superchargers have 'undefined' appended to their names.

---

![supercharger undefined](https://cloud.githubusercontent.com/assets/26678403/25286459/0bbb64d6-267b-11e7-9545-8a608ad57f7b.PNG)

**Comment by aesculus** [comment]
An artifact on me adding the state, but incorrectly.  You will have to Use Edit Segment to wipe that off the segment names or just delete the trip.

Fixed in V1.1.4 (10).
