### ISSUE TITLE
Add 'Rangefinder' feature when displaying Charger Inspector

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#291]
(This idea came up as part of issue #252. The forked comments have been moved into this new issue.)

**Comment by EVGrokker** [comment]
Intermediate enhancement suggestion (baby step, actually) that would bring us a step closer to **MDAR 1.0** (Multi-Day Auto Routing) or **MDASH 1.0** (Multi-Day Automatic Segment Hack):
- Create a long trip, for example Fremont CA - Nashville TN, **Manual** charger selection
- Zoom into CA 
- Touch lighting icon to turn on supercharger locations
- Touch a supercharger icon, for example Barstow
- Enhancement: In the Charger Inspector, show distance from previous pin in current segment. If possible, predicted hours of driving to this location would also be useful. This would not be a 'secret sauce' calculation, just a simple "assume I'm going the speed limit" type of calculation. For example, if we're 250 miles from the origin, and it's all 65 MPH interstate, the estimated time would be 3.8 hours.

This would allow you to easily do manual selection of waypoints for segmentation based on distance when first chopping up a long route without repeatedly asking EVTO to reoptimize.

**Comment by EVGrokker** [comment]
(aesculus commented)
> This would allow you to easily do manual selection of waypoints for segmentation based on distance when first chopping up a long route without repeatedly asking EVTO to reoptimize.

Just to be sure: The current Trip/Segment summary shows the estimated total elapsed time at each waypoint.  So if I knew somebody wanted to stop traveling after 8 hours I could show them on the map (or nearest waypoint) where that is today.

**Comment by EVGrokker** [comment]
My scenario is slightly different. What I'm proposing is earlier in the planning stage. All I have is an origin and destination, thousands of miles apart. I'm starting a rough approximation of where I want to do my segmenting. The very best, most complete database you have is Tesla Superchargers, so we're going to take advantage of that.
In the example above, I've created a trip from Fremont - Nashville. I'm zoomed into SoCal, guesstimating where I might want to stop on day 1.
(At this point, I'm cheating by going to Google Maps to see how far it is from Fremont to Barstow. It tells me 385 miles, 6:04 driving time.)
So here's what I'd like to see when I touch the Barstow supercharger icon on the map, which is not yet part of the route. 
The algorithm would be "compute the time and distance from an earlier, closest pin in the current segment, and display those numbers below the charger name."

This would not be applicable to automatic charging stops, or manual charging stops. It would only be calculated and shown when the user has touched a charger icon on the map not currently part of the route.

It answers the question "how far is this charging stop from the previous waypoint established on my route?"

![barstow route preview](https://cloud.githubusercontent.com/assets/26678403/25148007/b2899022-2436-11e7-9d2a-f7d7f9263ecf.png)

**Comment by EVGrokker** [comment]
(aesculus commented)
OK. Then we would have to develop some sort of rule of thumb (based on model efficiency?) to guestimate travel time vs drive time (the charger thing).  Then we could do this. Weather and stopping longer than needed for charging or course could not be included here. That could make a big difference.

**Comment by EVGrokker** [comment]
I'm proposing no "secret sauce" computations at all. It's just distance and time, assuming traveling at the speed limit. No regard for charging stops, weather, nada.

**Comment by EVGrokker** [comment]
(aesculus commented)
But is that really useful? Not to me with an EV. I would want to know the travel time to the charger, which would have to AT LEAST include how much charge time I had to incur to get there along with driving time.

But again, I think we can fake that with a WAG by efficiency of the car and estimating travel time per mile. I am sure that has been done by someone before but it should not be too hard.

Let's say you can charge at 200 mph. So every 200 miles you would have to add another hour to the drive time to get travel time. What number should we use? 200 is way too fast because it's not linear. Maybe 100 or 125?

**Comment by EVGrokker** [comment]
I think you're overcomplicating it. All that information will be available the moment you add the charger to your route.

This is a "what if" tool.

ME: "I'm heading from Fremont to Nashville. What if I decide to stay overnight in Barstow the first night? How far is that?"
EVTO: 385 miles, about 6 hours of driving time.
ME: "Hmm, I know I'd probably need a couple of charging stops en route, but I'd clock 385 miles the first day, and probably 7-8 hours total time in the car by the time I add in charging, lunch and breaks. I know from experience that about 350 miles is my upper limit for the day, but it would feel good to get that far."
EVTO: Are you just going to sit there, or are you going to push some buttons?

**Comment by EVGrokker** [comment]
(aesculus commented)
But you don't think it would be more useful to have an EV "rule of thumb". Maybe I am being overly pessimistic but the basic questions I get everyday point me to the fact that people would probably think driving time = travel time in an EV.

You would be shocked at how many uses trips I get where the user has the minimum SOC set to 25% and they want to charge to 100% at every charger.

**Comment by EVGrokker** [comment]
I see two compromises for this Time & Distance preview I'm proposing:

Distance only. I can do the driving time calculation in my head.
Distance, Driving time, and Clock time, using your EV "rule of thumb".
For example, using my numbers above, I assigned an EV "rule of thumb" multiplier of 33%, adding 2 hours to my 6 hours driving time, coming up with 8 hours clock time.

I wouldn't argue if you chose to do option 2. But the moment the user adds the charger to the route, that clock time estimate is history. But I wouldn't argue.

WRT users setting 25% SoC and charging to 100%, all I can say is that EVTO can help these poor souls become better planners. I get it - it's all about range anxiety. I felt the same way when I first started using cell phones, gotta keep it charged up.

But if there's a group to surprise and delight, it's folks who are going out on a limb with the app, who will spread good word of mouth. "Wow, I was able to sketch out a 5-day Fremont to Nashville trip in fifteen minutes with EVTO, awesome." Those kind of comments and reviews will be gold.

By the way, in working on this Fremont-Nashville monster (and breaking EVTO in the process), I tried planning it with EV Trip Planner, A Better Trip Planner, Scenic Drive, everything I could get my hands on, and none of them make it as easy as EVTO is on track to do.

**Comment by EVGrokker** [comment]
(aesculus commented)

EVGrokker wrote:
 By the way, in working on this Fremont-Nashville monster (and breaking
 EVTO in the process), I tried planning it with EV Trip Planner, A
 Better Trip Planner, Scenic Drive, everything I could get my hands on,
 and /none/ of them make it as easy as EVTO is on track to do.
That is really cool. These are some good apps to benchmark against. In
general they are simpler to operate than EVTO. But I find too many
limitations with them.

It's probably the pilot training in me, and hence the over complicated
aspects.  If you have ever run out of gas 50 miles from an airport (not
that I have but close), that sort of twinges a bit. :-)
-- 
Chris Couper

**Comment by EVGrokker** [comment]
After sleeping on this, I'd like to try another explanation of what I'm asking for. This is one of these features that I think would be very useful.

Let's call this the 'Rangefinder' feature. With an active current trip, touching a supercharger location brings up the Charger Inspector. Similar to the mockup I included in a previous comment, the distance from the previous waypoint in the current route is displayed under the charger name. Forget the driving time, just show the distance.

For example, I'm working on my multi-segment tutorial. I'm starting with a Fremont - Nashville origin/destination, and I've added Denver as a waypoint in the middle. I observe that Denver is 1271 miles from Fremont, so I decide to subdivide that stretch into three days. I enable the display of superchargers along the route, and I see Winnemucca. I touch the Winnemucca pin, wondering how far it is from Fremont. That's where using the Rangefinder feature would be handy.

**Comment by EVGrokker** [comment]
(aesculus commented)

I like the concept. I wonder if a linear timeline like chart would be useful also?

**Comment by EVGrokker** [comment]
Consistent with the metrics iconography introduced elsewhere, I'm proposing this appearance (assuming you want to do a three-part prediction of miles, driving time, charging time).

<img width="320" alt="distance metrics" src="https://cloud.githubusercontent.com/assets/26678403/25305487/3dd31702-2739-11e7-9985-4356253338fe.png">

**Comment by aesculus** [comment]
I would love to add efficiency too but I don't think we have the room.

**Comment by EVGrokker** [comment]
Additional enhancement: If Location is currently enabled, rangefinder shows distance from current location.

**Comment by aesculus** [comment]
Here is what I put together. It's fairly basic.  I hijacked the not used waypoint sharing icon with a clock on the charger waypoint inspectors.  This then brings up a Range Estimator dialog that shows an approximate driving distance (it's approximate because I am using the crow flight distance * 1.15) and an estimated drive time (using average 65 mph).

Of course there is no way to use this for standard waypoints as we don't have any icon space left.  

![image](https://user-images.githubusercontent.com/283364/28687110-43103e96-72c2-11e7-9f83-fc8a0eb7e108.png)

**Comment by EVGrokker** [comment]
I like this.  

A couple of comments:
- What do you think about using the car icon as the button to invoke the popup, suggesting distance, as in "how far away is this charging stop"?
- I'd like to see more breathing space between the icon and the header in the popup.
- I originally thought 'Rangefinder' was a catchier name for the feature, but now that I see it implemented I realize that 'range' has special meaning for EV drivers, so I think we need to avoid that word. What would you think about titling the popup simply 'Distance'?
- I know that there's no help content yet, but when I invoked the empty template, it didn't come to the foreground, and I couldn't dismiss it.

**Comment by aesculus** [comment]
What about Drive Estimator?

I don't have a car icon in the same format as the other inspector icons so I need to stick with the clock. I think it's appropriate though.

I fixed the help dialog issue in V1.2 (66).

**Comment by aesculus** [comment]
I spent a few minutes creating a car icon as an option to the clock.

![drive_icon](https://user-images.githubusercontent.com/283364/28734312-34b81368-7395-11e7-8cf0-b86c580f93f9.png)

Which one do you want me to use in 67?

**Comment by EVGrokker** [comment]
How about Distance Estimator? That seems the most applicable to the functionality.

Let's try the car button in 67 to see how it looks.

**Comment by EVGrokker** [comment]
I'd suggest making this a Pro feature.

**Comment by aesculus** [comment]
> I'd suggest making this a Pro feature.
Done

**Comment by EVGrokker** [comment]
Looks good.

**Comment by EVGrokker** [comment]
It would be helpful to see at least some of the Origin and Destination names appended to the 'From Origin' and 'To Destination' labels. 

For example:

**From Origin (Petaluma):**
**To Destination (Santa Barbara):** 

If the name is too long to fit in the available width, it could be truncated:

**To Destination (Fess Parker Inn A Double…):**

**Comment by aesculus** [comment]
How about this? 

![image](https://user-images.githubusercontent.com/283364/29223025-e45c13fc-7e79-11e7-89de-7c6de082c7ed.png)

**Comment by EVGrokker** [comment]
v 1.2.0 (76)

This looks great.

**Comment by aesculus** [comment]
It's back to Rangefinder again. I also added the charger name at the top in V1.2 (79)

**Comment by EVGrokker** [comment]
Proposed enhancement: When Location is enabled, using the Rangefinder feature would display time and distance to selected charger from current location. The time and distance would be calculated from the location at the time time the feature was engaged - it's not dynamically updated.

(When Location is disabled, the functionality would be the same as it is currently, distances from the selected charger to the Origin and Destination points would be displayed.)

A total of three distances would be shown: 
From: [Origin] 
From: My Location
To: [Destination]

**Comment by aesculus** [comment]
In V1.2 (82) the current location is shown if the marker is turned on. If not the third row is disabled.

![image](https://user-images.githubusercontent.com/283364/29804365-fdfb7e22-8c36-11e7-87aa-15a1185289ab.png)

**Comment by EVGrokker** [comment]
Looks good.
