### ISSUE TITLE
[Basic Tutorial] Using EVTO with Tesla's Navigation System

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#292]
<h3>Using EVTO With Tesla's Navigation System</h3>
<p><i>Learn how to export EVTO waypoints to your in-car navigation system.</i></p>

<hr/>

<p><i>Got an idea for a tutorial? <a href="mailto:support@digitalautoguides.com?Subject=Tutorial suggestion">Let us know!</a>
</p>

**Comment by aesculus** [comment]
This has implement by [http://www.digitalautoguides.com/evto-export-to-navigation-system/](url)
