### ISSUE TITLE
Add Trip Date/Time on New Trip Dialog

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#296]
Default to the current date/time but let the user change these as needed. Also suggested that we allow for a default trip start time in Settings (Issue #297  ). 

These fields can be copied from the Edit Segment Details dialog and should replace the selection panel once the user has confirmed an address.

**Comment by EVGrokker** [comment]
Decision was made to default trip date to following day, at default start time specified in Settings.
