### ISSUE TITLE
Delete Last Segment

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#299]
Currently the app allows for merging segments, but not deleting segments. This makes sense for all but the last segment. There is no way to delete the last segment without first merging the last two segments, deleting the newly made waypoint that used to be the last segments origin, and then changing the address on the last segment destination to the former origins address.

**Comment by EVGrokker** [comment]
I like the concept, and the complexity of handling the last segment is doable. I'd propose folding this feature into the Trip Inspector revisions, issue #279.

Of course, the correct implementation would be swiping the segment, exposing a Delete button. :)

**Comment by aesculus** [comment]
> I'd propose folding this feature into the Trip Inspector revisions

Actually I was just going to turn on the Delete icon (X) for the last destination in the Waypoint Inspector. Then providing a prompt that that would delete that segment like the merge prompt does.

The work will be on you to explain it in help.

BTW did the waypoint inspector help ever get modified to describe the merge?

**Comment by EVGrokker** [comment]
>BTW did the waypoint inspector help ever get modified to describe the merge?

Damn. No, it didn't. That one's on me. I'll add an issue and assign it to the documentation guy.

**Comment by aesculus** [comment]
This was implemented in V1.2 (24).
