### ISSUE TITLE
Add the Model X 5 Seater as an option in My Cars

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#302]
The car has less weight and apparently makes a difference in the energy calculations.

**Comment by aesculus** [comment]
Added in V1.2 (1)

**Comment by aesculus** [comment]
Waiting to determine exactly how much it weighs. I have 90 kg as a default value for now.

**Comment by EVGrokker** [comment]
Since you're working in the My Cars dialog, do you want to take another whack at #187 for the 1.2 release?

**Comment by aesculus** [comment]
I will. It's usable but not ideal since it seems to depend on where you drag.

**Comment by EVGrokker** [comment]
According to [this thread](https://forums.tesla.com/forum/forums/5-seater), there's a 487 lb difference between the 5-seater and the heavier 6- & 7-seaters.

**Comment by aesculus** [comment]
That's a lot of weight and will probably make a big difference. I have updated the figure in the app. V1.2 (2)
