### ISSUE TITLE
Change Power Factor to Speed Factor

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#303]
Right now the power factor does include a speed adjustment but it does not change the estimated drive time. This needs to be revisited.  A few complaints on this.

Users seem to be more comfortable with the concept of speed adjustments (maybe by %?) than adjusting the power factor. The power factor does much more than adjust for speed, but many users are only comfortable with that one item and want to see their drive times adjust accordingly.

If this is done then we have to figure out another way to deal with  #towing.

**Comment by EVGrokker** [comment]
Proposal: Towing is a checkbox. Towing power penalty is a slider from 0 to 5 in 0.5 increments. The slider is disabled when the towing checkbox is disabled.

This could also be applied to rooftop racks or hitch-mounted storage boxes, anything that impedes the drag coefficient of the car.

**Comment by aesculus** [comment]
I was thinking of a pull down with various trailer types, None being the default. It could also include boxes, bikes etc. I suspect the average user would not know what to do with the slider.

**Comment by EVGrokker** [comment]
The problem with maintaining a list of trailer types will be the user who says "I have an 18' Airstream Bambi, why isn't that on the list?" Even if you go with generic descriptions, it's a losing battle.

The slider in my head would range from Light to Heavy, or Sleek to Bulky, something along those lines. At best we're talking an iterative process of them approximating the impact, right? This would be for the data geeks who really want to dial in their rig configuration. The ten settings would be so they could say "next trip I'll bump it up to 2.5, see how closely that tracks."

The help text could say "for a roof rack, start with a trailer factor of 1.0, see how that tracks to your actual energy penalty. For a trailer box, start at 2.0. For an 18' Airstream Bambi, start at 3.5. Please report back on the EVTO forum to let others know what settings work for you."

So maybe the 'Trailer' button should actually be something like 'Additional Drag Factor' or something like that.

**Comment by aesculus** [comment]
Probably yours is best. The poor My cars is getting big. Wait for the complaints. :-)

**Comment by EVGrokker** [comment]
Wait until we add the UI for users adding their own beauty shots to the Main screen. :)

**Comment by aesculus** [comment]
You mean a different picture for every My Cars? OMG.  I was thinking Settings. :-)

**Comment by EVGrokker** [comment]
Yes (ducks for cover)

**Comment by aesculus** [comment]
I created a new issue on towing (issue #306 ) so we can concentrate on the drive time here.

I have also refactored the name of this issue to reflect a change in direction for this problem.

The power factor is  bit more involved than just adjusting the speed of travel. But ultimately that is the biggest element.  It was intended to allow for driving style type too (ie a person who does not use regen much or does fast starts). But the bigger impact appears to be speed. And since the existing power factor does not change the speed of travel, it does not affect time of travel either. This means that time dependant calculations such as weather forecasts, heating/cooling, and travel time, are not fully supported.

So the issue is changing the Power Factor into a Speed Factor (or some other name).  There are some things to consider in doing this:
- Existing users will have to be alerted to the change of purpose
- Existing trips would have to be recalculated (since it would change the underlying speeds). I would not do this automatically but alert the user that they need to do this (how?).
- How should the speed factor be described? Today the pf is a % (1 = 10%). It goes from -1 to 6 in .1 increments. I would propose that the range should be -1 to 3 at most.
- The help would need to be rewritten
- The power factor tutorial (issue #295 ) would have a different purpose

**Comment by EVGrokker** [comment]
After factoring out towing considerations, the remaining variable is still a power factor, but the user's going to think of it in terms of speed, as you say. Let's assume for a moment that the slider is labeled 'Speed Factor', ranging from a negative to a positive value. 
 
As I user, I would assume that a neutral setting would mean that I typically drive at about the speed limit.

A negative setting would mean that I consciously drive slower, say 55 in a 65-70 mph zone, with the express intent of saving energy. That's about a 15% speed reduction (which actually yields a higher power savings, but that's a complexity best hid from the user).

A positive setting would mean that I like pushing the speed limit, let's say 80 in a 70. That's about a 15% bump (but again, higher in actual power costs, since that's non-linear). 

So my recommendation would be a slider that adjusts from -15% to +15% in 1% increments.

Your algorithm would take the slider value and normalize it to your secret sauce computations. 

This is another case where we're implying a degree of accuracy that ain't there, but it offers at least a means for folks to personalize the app and make them feel like the secret sauce computations are fine-tuned to them. The help will have disclaimers that actual real-world conditions will have a dramatic effect on the results. We'll also explain how they can review post-trip data back in to "calibrate" this slider, but seriously, it simply can't be the precise tool that some folks will expect.

In the help, I'd probably say "Lead foot Larry? +10! Slow lane Sally? -10!"

**Comment by aesculus** [comment]
I guess 15% is enough. That gets 65 mph to 75 mph.  If they are doing more than 10 mph over the speed limit they need help.  
I like the idea of the negative value too for both the energy stewards (or when you know you are not going to make it at speed, and for the trailer towing crowd that is supposed to be at 55 mph in California at least.

**Comment by aesculus** [comment]
Now that I have started to implement the speed factor I am beginning to understand some of the issues the App will face with this change:

- There are two ways to adjust the speed. Add a % or add an absolute value (ie 5 mph). I favor the later because this is how I see most people drive and it sort of seems socially acceptable, at least in NA
- The way the server model works both pf and the speed adjust have to be by the trip. I cannot have these by trip segments. I wish I could but I cannot, unless I totally replace the server code with something else
- The default value for pf and speed adjust come from the My Cars and is unique for each car
- When the trip is created it uses the current cars pf and speed adjust for the new trip
- Because the fp and speed are trip based, if they are changed the change will be applied to all trip segments. This means that either we move these to the Trip Edit dialog in Current Trips or if on the Edit Trip Segment panel, changing it there will have to update every segment. That could be confusing to the user, but would be more convenient than going all the way back to the Current Trips panel.
- All segmentation will receive the trips current pf and speed adjust.

Let me know what you think about all of this.

**Comment by aesculus** [comment]
Another option is to have the Edit Trip Details panel also be on the Plan menu. Then all items that are trip based are contained in that panel:
- Trip start date and time
- Overall trip name
- power factor
- speed adjust
- cabin temp and payload
- rating
- planned vs take status

The Edit Segment Details would be segment specific and would contain:
- Segment name
- segment start time and date
- segment origin SoC
- segment Destination reserver
- segment comments

**Comment by EVGrokker** [comment]
With respect to speed adjustments being trip-based, I'm fine with that. I think the way it's positioned is to "describe your driving style", so +5 would be on the aggressive end of the scale. Of course this is really just a hint to the optimizer, because there's no assurance that you can always go 5 above the limit. I would describe it as "when possible, I tend to drive above the speed limit", or "I tend to drive below the speed limit". The good news is that the user will ends up with extra energy when they can't consistently drive high than the limit. 
WRT trip vs segment tweaking, I'd suggest that you implement it as trip-based, linked to the car, positioned as a characteristic of the car (the car's driver, actually). Maybe 2.0 could revisit finer granularity but this would be a feature for the OCD crowd.

**Comment by EVGrokker** [comment]
WRT Edit Trip Details access, agreed that menu access should be from the Plan screen (tho I'd like to reduce the number of items in that menu. 

Secondary access to that dialog would be through a long press on the trip segments icon.  I have a issue requesting that enhancement already.

**Comment by aesculus** [comment]
>Secondary access to that dialog would be through a long press on the trip segments icon. I have a issue requesting that enhancement already.

Right now secondary (tertiary?) is from the Current Trips panel. I can add secondary access via the above in due time.

>tho I'd like to reduce the number of items in that menu.

Thoughts on that? Now is the time. I just added one. :-)

I would be good to dump the two copy one's (Reverse Route and Copy as New Trip). If they want these they can go over to the Current Trips panel.

**Comment by aesculus** [comment]
I have updated the Plan Trips menu accordingly #392

**Comment by EVGrokker** [comment]
v 1.2.0 (25)
My Cars: Speed Adjust adjusts from -20 to +10. Comments:
- I'd like to see the slider colored green for negative values, red for positive values to indicate the impact on energy. (I thought this was already implemented but it's not there in the current version.)
- We need to be clear what units this slider is calibrated in, and it needs to work for both kM and Mi per hour. If it represents percentage, and we consider a 70mph highway, +10 would represent 77mph, and -20 would represent 56mph, which is acceptable. +15 would represent 80.5mph, which might be better.
- Proposal: The scale is percentage, and goes from -20 to +20 for visual balance. On a 70MPH road, that would go from (roughly) 55mph to 85mph. No one's likely to set it to +20, but there's no harm in having it available, and it makes the slider look better.
- There may be some call for finer granularity, but I'd propose keeping the increments of 5 you currently are using until someone makes a compelling case.

**Comment by aesculus** [comment]
I decided not to do a percentage (although it's not coded yet so it's still open for debate) vs just an add. So regardless if you are using mph or kph it's going to add or subtract that amount to all speeds.

So with a speed adjust of 5, 30 mph > 35 mph; 65 mph > 70 mph; 100 kph > 105 kph. etc.

This is the way people seem to drive IMHO.  No matter what the speed is, they seem to feel that 5mph for example is within tolerances (ok not so much in Calif anymore - the new rule seems to be 10 mph, but good luck with that in speed traps - ie I 80 to SF).

**Comment by aesculus** [comment]
> I'd like to see the slider colored green for negative values, red for positive values to indicate the impact on energy. (I thought this was already implemented but it's not there in the current version.)

Thought I was loosing my mind.  I did not add the colors in the My Cars yet pending this discussion.  You will find them in the Edit Trip Details dialog for you to try.

**Comment by EVGrokker** [comment]
>I decided not to do a percentage (although it's not coded yet so it's still open for debate) vs just an add. So regardless if you are using mph or kph it's going to add or subtract that amount to all speeds.
So with a speed adjust of 5, 30 mph > 35 mph; 65 mph > 70 mph; 100 kph > 105 kph. etc.

This should work OK. I'd still prefer a balance between the same minus to plus offset so that zero's in the middle.

**Comment by aesculus** [comment]
Right now the biggest uses will be:
- users who the regular model does not fit (most likely -10% to 20%)
- trailer users ( most likely 20% - 60%)

So the balance makes sense for regular users but when you fold in the trailer users, not so much.

Later this could be alleviated by a special trailer feature but we are a long ways off from that.

**Comment by EVGrokker** [comment]
Wouldn't trailer users do two things to compensate: 1) A lower speed to comply with local law 2) Increased PF to account for increased energy requirements?

To be clear, I'm suggesting that the speed offset be centered +/- 20 units around 0, and PF would be either 0-based or skewed with more positive penalty values than negative.

**Comment by aesculus** [comment]
Yes for trailer users.  But a regular user might find that even after adjusting the speed factor they find they need a lower power consumption, hence the -10 thing.

The original goal for pf had two things in it. Internally it did adjust the speed, but not the time of travel. The other aspect was to change the overall consumption. The former will disappear when sa comes into play but not the later. That component of pf could still be needed to go negative (ie a very conservative driver who drives the speed limit, but slowly accelerates and never touches the brakes). @ohmman for example took a trip from LA to SF a few weeks ago and never got above 290 kWh/mi for 400 miles. Not sure how he did it but I have pictures. While the cabin was off, he said the winds were 0.  That is unheard of in my Model X.  I still need to dupe his trip once I have the model working again to see what I would predict but the older version was much higher naturally. More like average Model X values.

**Comment by EVGrokker** [comment]
v 1.2.0 (26)

I'm not seeing the effect of changing Speed Adjust in the My Cars menu:

- New Trip: Seattle WA to Portland WA
- Speed Adjust: 0
- Arrival SoC: 16%
- Average Speed: 64mph (as reported in waypoint inspector)

Change Speed Adjust to -10:
- Optimize Routing (to be sure that trip is recalculated)
- Arrival SoC: 16%
- Average Speed: 64 mph

Change Speed Adjust to +10:
- Optimize Routing
- Arrival SoC: 16%
- Average Speed: 64 mph

**Comment by aesculus** [comment]
Sorry for the confusion. Just the UI has been implemented. Wanted your approval there before I actually applied the functionality. That will take a few days after I get the server code working in todays model.

**Comment by EVGrokker** [comment]
Ah, ok. Can you put a tick at the zero location above the slider, inline with the text label? Same with Pf?

**Comment by aesculus** [comment]
No unfortunately. I tried a hack by putting a | in the label which worked OK for the SA, but the label of the PF overlays that area.

**Comment by aesculus** [comment]
I just added back in power factor in V1.2 (35). It was a fair amount of work.  Here is what I did:
- Used the trip power factor as a 10% increase to create a pf adjustment during energy calcs
- Applied the pf adjustment to the waypoint energy calcs for all but elevation and climate control
- Applied the pf adjustment to the consumption chart energy calcs for all but elevation and climate control
- Applied the pf adjustment to the soc chart energy calcs for all but elevation and climate control

I tried it out and the combination of speed adjust (less to force trailers to 55 mph), increasing the payload to 5000 and forcing the power factor to around 4-6 seems to give pretty reliable results for towing a large airstream like trailer.  It will be interesting to see how this matches up with reality.

**Comment by aesculus** [comment]
I am wondering if power factor should go to minus 20. Today it's minus 10. Seems like it could benefit from a bit more of a kick for conservative drivers.

**Comment by EVGrokker** [comment]
Agreed. Even if it's rarely usable, it's a nice goal.

**Comment by aesculus** [comment]
Limit changed in V1.2 (37)
