### ISSUE TITLE
Plan Trip Help: Updates to Map Icons section

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#304]
Issue #117 adds a new crosshairs button to the Plan screen, used to control a blue pulsating dot showing the device location. This issue creates accompanying help text.

This help text is to be added to the Plan Trip Help menu. It should replace the entire Map Icons section.

<hr/>
<h3>Map Buttons</h3>

<h3>[globe icon] Zoom to Route</h3>
<p>Touch the globe button to zoom and center the map on the active route segment.</p>
<p>Touch and hold the globe button to zoom to all segments of the current trip.</p>

<h3>[folded map icon]Trip Inspector</h3>
<p>When a trip includes multiple segments, a red numeric badge on the map button indicates the number of segments in the current trip. The active segment is displayed on the map in blue, along with its waypoints. Inactive trip segments are displayed in gray, with gray origin and destination pins, and dots representing waypoint locations.</p>

<p> Touch the map button to to open the Trip Inspector. Touch an individual segment to make it the active segment. Touch outside the Trip Inspector to close it.</p>

<h3>[crosshairs button] Location</h3>
<p>Touch the crosshairs button to center the map on your current location, displayed as a pulsating blue dot. Touch the crosshairs button again to disable display of your current location. EVTO does not automatically track your current location. To quickly find yourself on the map, toggle off, then on, recentering the map on your current location.</p>
<p>EVTO's <strong>Location</strong> feature requires access to Location Services in your device's Privacy settings. If touching the location button does not display your current location:</p>
<ul>
<li>Check your device's <strong>Settings | Privacy | Location Services</strong>, confirming that EVTO is allowed location access.</li>
<li>Check EVTO's <strong>Main | Settings</strong> dialog, confirming that the <strong>Location Services</strong> checkbox is enabled.</li>
</ul>
<p>Displaying your current location consumes additional device power.</p>

<h3>[lightning bolt icon] Tesla Chargers</h3>
<p>Touch to toggle the display of Tesla Supercharger and destination locations on the map. EVTO's database is updated weekly.</p>

<h3>[outlet icon] Other Chargers</h3>
<p>Touch to toggle the display of Level 1, Level 2 and Level 3 chargers locations. Use the Filter Chargers dialog to enable which charger locations are displayed.</p>

<hr/>

**Comment by aesculus** [comment]
I updated the charger sections to reflect that outside of NA there are more destination chargers shown with the lightening bolt icon than superchargers.

Updated in V1.2 (6)

**Comment by EVGrokker** [comment]
In the Filter Chargers help section, the icon is a calendar, should be a funnel. 

Additionally, please revise the wording as follows:

Filter charger types displayed when electrical outlet button is toggled.
