### ISSUE TITLE
Waypoint Inspector dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#305]
This text replaces the entire Waypoint Inspector help content

---
<h2>Waypoint Inspector</h2>
<p><i>Review and manage waypoint details.</i></p>

<h4><img class="panel_help_icon" src="css/images/gray/748-heart.png" />Toggle Favorite status</h4>
<p>Touch the heart button to toggle this waypoint's Favorite status. Favorite waypoints may be quickly accessed 
when creating a new trip or adding waypoints to an existing trip.</p>

<h4><span class="ui-btn-icon-notext ui-icon-eye ui-alt-icon menu-icon"></span>View location<sup>†</sup></h4>
<p>Touch the eyeball button to display a dynamic Google Street View of the waypoint location. To return to the 
Waypoint Inspector, touch the arrow to the left of the waypoint address.</p>
<p class="caveat"><sup>†</sup>Requires Pro version IAP</p>

<h4><span class="ui-btn-icon-notext menu-icon ui-icon-share "></span>Share<sup>†</sup></h4>
<p>Touch the share button to export this waypoint.</p>  
<p class="caveat"><sup>†</sup>Requires Pro version IAP</p>

<h4><img class="panel_help_icon" src="css/images/segment_icon.png" />Split current segment<sup>†</sup></h4>
<p>The current segment may be split at any waypoint along the route by touching the scissors button. The upstream (earlier) 
segment will use the split point as its destination. The downstream (later) segment will use the split point 
as its origin.</p>  
<p class="caveat"><sup>†</sup>Requires Pro version IAP</p>
    
<h4><span class="ui-btn-icon-notext ui-icon-location ui-alt-icon menu-icon"></span>Convert automatic charging stop to waypoint</h4>
<p>When trips are optimized, EVTO automatically selects supercharger stops along your route, marked 
with an 'A'. Subsequent route optimizations may automatically select different supercharger stops, 
depending on your vehicle characteristics and current weather conditions. To convert an automatically 
selected supercharger to a required waypoint, touch the pin button, converting it to a regular waypoint.</p>  
    
<h4><span class="ui-btn-icon-notext ui-icon-edit ui-alt-icon menu-icon"></span> Edit waypoint details</h4>
<p>Touch the pencil button to open the Edit Waypoint dialog, where waypoint details are managed.</p>  

<h4><span class="ui-btn-icon-notext ui-icon-delete ui-alt-icon menu-icon"></span> Remove waypoint from route</h4>
<p>Touch the delete button to remove a waypoint from the current segment. The revised route will be 
recalculated.</p>

<p>If the selected waypoint is an intermediate origin or destination (a 'hinge' pin), deleting it will 
merge the segments on either side of the pin.</p>

<p>Deleting the final destination of a trip deletes the last segment and its waypoints. The previous 
segment's intermediate destination becomes the trip's final destination.</p>

**Comment by aesculus** [comment]
Updated in V1.2 (6)

**Comment by EVGrokker** [comment]
Updated to describe export function.

As noted in #118, the sharing icon is different for iOS and Android. That means you either need to use a platform-specific image for iOS and Android in the help file, or put both images in the help file.

**Comment by aesculus** [comment]
Updated in V1.2 (70). I made the icon dynamic based on OS.  I also copied the programs text into this issue for ease of future editing.

**Comment by aesculus** [comment]
Updated with new subscription info
