### ISSUE TITLE
My Cars dialog: Model X settings variations

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#309]
On a Model X, a 5-seater configuration is mutually exclusive with Rear Climate Control.

Therefore, if 5-seater is checked, Rear Climate Control should be unchecked and disabled.

I think a better way to approach these combos would be to make the seating configuration a spinner in the My Cars dialog: 5, 6 or 7 seater, enabled only when Model X is selected.

The 'Rear Climate Control' should be grouped with the Cabin Temperature setting, enabled only if a Model X user has specified a 6- or 7-seater configuration.

I believe you're intending to add Cockpit settings to the My Cars dialog to establish defaults, so maybe it stays on this page, but Rear Climate Control should be clustered with Cabin Temperature.

**Comment by aesculus** [comment]
I added a feature to change the battery to a 90 when the user selects a Tesla Model X in V1.2 (9)

**Comment by EVGrokker** [comment]
Smart, it defaulted to 85 before.

**Comment by aesculus** [comment]
>On a Model X, a 5-seater configuration is mutually exclusive with Rear Climate Control.
Therefore, if 5-seater is checked, Rear Climate Control should be unchecked and disabled.

This was added in V1.2 (22)
