### ISSUE TITLE
Plan trip to a destination charger does not assume I will recharge at that location

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#31]
When a segment terminates at a destination charger, the subsequent outbound trip should assume that I recharged using the destination charger. However, that SOC should be editable, since I may not have been able to recharge to my standard departure SOC.

**Comment by aesculus** [comment]
This is a duplicate of https://github.com/aesculus/EVTO-App-Feedback/issues/30
