### ISSUE TITLE
Tesla Supercharger location overlay should initially be toggled OFF

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#310]
Suggestion:

Overlay of Tesla Supercharger locations should initially be toggled OFF in a clean installation.

The reasoning: An expected initial sequence would be to plan a trip. When the map is displayed, the user sees a bunch of 'S' pins that have nothing to do with the route they've created. It's confusing. 

It would be cleaner to let them discover the charger overlays by touching the buttons (or [gasp] reading the Help).

**Comment by aesculus** [comment]
Fixed in V1.2 (6)
