### ISSUE TITLE
Waypoint Inspector enhancement: Add ETD (departure time) or Stop time

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#314]
If user has established a Minimum Stop Time for a waypoint, I suggest the Waypoint Inspector should additionally display either:
- Departure time
- Stop time

This would be on the same line as Arrival Time. Also, I think it would be cleaner to use ETA and ETD (or Stop), since the format of the numbers (xx:yy) implies 'Time'.

- ETA 4:51 am (layout padding) ETD 5:21 am
- ETA 4:51 am (layout padding) Stop 0:30 

If you choose to retain 'Arrival', you could still drop 'Time':
- Arrival: 4:51 am (layout padding) Departure: 5:21 am
- Arrival: 4:51 am (layout padding) Stop: 0:30

![wi button layout](https://cloud.githubusercontent.com/assets/26678403/25332926/86ed288e-28a5-11e7-8cb2-a1c8b684888d.PNG)

**Comment by aesculus** [comment]
I think I favor Arrive and Depart (without Time)?

One question?  There is currently charge time which is useful.  But since you can stop without charging, or not charge the whole stop time, then is this going to be confusing if we only have Charge Time listed along with Arrive and Depart?

**Comment by EVGrokker** [comment]
I'm fine with Arrive and Depart. Instead of Charge Time, how about using Stop Time, which ends up being the larger value of charging or Minimum Stop Time, just like in the Edit Waypoint dialog.

**Comment by aesculus** [comment]
I think charge time needs to be what it is. I am pretty sure people want to know how long it's going to take to charge, especially with the idle fees. So you ended up with 1 hour of charging on a 2 hour Minimum Stop Time, you would still have 1 hour left before you departed.

I was just stating that if I did put in a Depart Time, if people did the math they might wonder where the other time was.

We could add another line of Wait Time, which is the difference between Minimum Stop Time - Charge Time.  Often of course it would be 0:00.

**Comment by aesculus** [comment]
V1.2 (51) has a Departure Time
