### ISSUE TITLE
My Cars dialog: Generate default car name based on model selection, other suggestions

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#316]
v 1.2 (2)

Currently, when a user first opens the My Cars dialog, they immediately see:

**Not a Valid Configuration**

which feels hostile, like they did something wrong, and they just started using the app.

A couple of suggestions:
1. As soon as the user selects a model, generate a default car name for the Car Name field, e.g. 'My Model X'.
2. Upon entry for the first time, have an initial configuration that is a valid configuration. That way, if they just click Save, at least the configuration is usable, if not accurate. The default name would be a clue when displaying the Main menu that they will want to update the car name.
3. Rather than display **Not a Valid Configuration**, how about **Configuration Incomplete**? That doesn't seem as judgmental.
4. I'm wondering if you boxed the scrollable area of the My Cars dialog with a thin gray outline if that might make it more visually obvious that the panel is scrollable.
5. Propose moving the Car Name field to the top, just under the Active Car picker.
6. I've found that touching and holding, then dragging in the panel seems to offer the most reliable control. How about adding a line in the header "Touch and drag for all settings".
7. Is there any way to disable the springy dragging of the entire screen when the user touches and drags outside the active panel area?

These suggestions should be considered part of issue #187.

**Comment by aesculus** [comment]
>As soon as the user selects a model, generate a default car name for the Car Name field, e.g. 'My Model X'.

Fixed 1.2 (6)

>Upon entry for the first time, have an initial configuration that is a valid configuration. That way, if they just click Save, at least the configuration is usable, if not accurate. The default name would be a clue when displaying the Main menu that they will want to update the car name.

Fixed 1.2 (6)

>Rather than display Not a Valid Configuration, how about Configuration Incomplete? That doesn't seem as judgmental.

Fixed 1.2 (6)

>I'm wondering if you boxed the scrollable area of the My Cars dialog with a thin gray outline if that might make it more visually obvious that the panel is scrollable.

Did not look any different than a box

>Propose moving the Car Name field to the top, just under the Active Car picker.

Fixed 1.2 (6)

>I've found that touching and holding, then dragging in the panel seems to offer the most reliable control. How about adding a line in the header "Touch and drag for all settings".


Fixed 1.2 (6)

Is there any way to disable the springy dragging of the entire screen when the user touches and drags outside the active panel area?

Not that I can tell. Sort of an artifact of the UI toolset I use I think.

**Comment by EVGrokker** [comment]
Much improved. Nice work.
