### ISSUE TITLE
Main menu | Tutorials should link to new EVTO Tips & Tricks section

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#317]
v 1.2 (2)

Once you've populated the new EVTO website, the 'Tutorials' item in the Main menu should link to it.

**Comment by EVGrokker** [comment]
http://www.digitalautoguides.com/#evto_main

**Comment by aesculus** [comment]
Updated V1.2 (7)

**Comment by aesculus** [comment]
The main menu now just has one link to Web Content via issue #404
