### ISSUE TITLE
Occasional lockups of app if Settings has Location Off and so does Device

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#32]
Fix has been applied but not fully tested yet. Still may be an issue.

**Comment by EVGrokker** [comment]
FWIW, I have Location Services for the app disabled, as well as the check box in the Settings panel, and have had no lockup issues (v1.1.1). Will retest after next release.

**Comment by aesculus** [comment]
I am going to close this for now as I am not getting any reports on this. If they come back we can reopen or make another one and reference this one.
