### ISSUE TITLE
Segment Dialog should include name of hinge point

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#320]
When scissoring a segment, the Segment dialog should include the name of the waypoint where the current route will be segmented, similar to issue #276 where the name of the waypoint to be deleted is included in the Delete Waypoint dialog.

For example, in the screen shot below, the dialog would read "The current trip will be segmented at the Hyatt Vineyard Creek waypoint."

The template should be "The current trip will be segmented at the [name of waypoint] waypoint."

![segment dialog](https://cloud.githubusercontent.com/assets/26678403/25381663/e3ad2ba6-2971-11e7-9156-e6e1f480370e.PNG)

**Comment by aesculus** [comment]
This leaves the question should it be:

"The current segment will be segmented at the Hyatt Vineyard Creek waypoint."

Lots of segment words. We could do divided, split, sectioned ...

**Comment by EVGrokker** [comment]
"The current **trip** will be segmented…" works.

**Comment by aesculus** [comment]
OK

**Comment by aesculus** [comment]
Fixed in V1.2 (6)
