### ISSUE TITLE
Touching an inactive Origin/Destination pin should activate the associated segment

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#321]
v 1.2 (2)

The current behavior with a multi-segment trip allows touching an inactive route segment to activate that segment. This works well.

However, touching an an inactive segment's origin or destination pin does not activate the corresponding segment. This should be possible as well.

In some cases, there would be ambiguity about which segment to activate, if the pin represented both an origin and a destination (hinge pin). In that case, I'd suggest selecting the segment closest to the currently active segment, since the user is probably trying to step forward or backward through their trip.

**Comment by aesculus** [comment]
This is probably related to issue #275 and should be combined.

**Comment by EVGrokker** [comment]
v 1.2.0 (23)
Touching an inactive Origin pin does switch segments, but the recalculation hangs up: 

>Car Data: S85, Charger: 48, Wheels: 19, Tires: 0, Pano: 0, 5 Seat: 0, Rear CC: 0, Bat Life: 100 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (23) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Springfield Supercharger, [110jiq0v9k4fc48uqcszjwk]

**Comment by aesculus** [comment]
Actually it's a bigger problem than that. It won't switch segments no matter how you select them (pushpin, route or Segment Selector).

**Comment by aesculus** [comment]
In V1.2 (29) I have made sure that no pushpins are duplicates of active pushpins.
