### ISSUE TITLE
If possible, add street view icon to waypoint info screen

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#33]
Using the recorded address of the charger, invoke street view directly without the 'drag icon to map' approach.

**Comment by aesculus** [comment]
Could this be a button on the charger Infowindow popup?

**Comment by EVGrokker** [comment]
That would be preferable, since the specific address is already known. No point in making the user guess where to drag.

**Comment by aesculus** [comment]
Done. Added a View button and the map is replaced with Street View at the waypoint location. Part of V1.1.3 Pro feature
