### ISSUE TITLE
Cooperate with PlugShare on a URL Scheme 

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#330]
PlugShare has an excellent, growing database of charging stations with dedicated users providing photos, tips and insights.

If it were possible to implement a URL scheme to export a charging POI from PlugShare to EVTO, that would be a very useful feature.

Scenario:
- User wants to travel to Faraway, ID and needs destination charging.
- EVTO shows nothing in its Outlet database.
- User launches PlugShare and finds the Faraway Holiday Inn with a suitable outlet.
- PlugShare exports POI info (address, charger, contact info) in standardized URL format to EVTO.
- EVTO receives the URL, adds the POI to current route.

This would require defining a standard interchange format for POIs, and a URL scheme for receiving them.

Resources:
[Inter-App Communication on iOS](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html)

**Comment by aesculus** [comment]
I contacted them asking if anything has changed from our last correspondence back in September. I let them know we had about a 1000 downloads of the app and that our customers were clamouring for a more of a direct integration between the to apps.

**Comment by aesculus** [comment]
PlugShare app. Yuk. See my comments via email.

**Comment by aesculus** [comment]
They came back again and stated they did not have the bandwidth to handle non commercial entities.

So we are going to have to come up with a very loose integration theme. Remember "sneaker net"? :-)

**Comment by aesculus** [comment]
Looking into this further:

They do use an API externally that is sort of exposed. It's really simple if you can remember the 4 or 5 digit ID number.  From this you get back a unstructured file that may be able to be culled for the location name, location address and a list of chargers as well as a set of comments about the location.

I can probably use this api to get what we need even though it's not official or structured.

**Comment by EVGrokker** [comment]
Is the supplied number an API key like Dark Sky, or something else? Would it be issued to an end user, or to DAG (like the Dark Sky API key)?

If it's something that the end user needs to register for and somehow enter into their app, say in Settings, that seems manageable. 

Can you point me to the available documentation? I'd like to know more about it.

**Comment by aesculus** [comment]
It's a unique I'd for every station. In the plug share app select the share icon when on a station and see the choices like memo. Then notice the number at the end.

**Comment by EVGrokker** [comment]
Ah, OK. It's a URL scheme. [Here's the documentation](http://developer.plugshare.com/docs/#introduction). It appears that you can register to receive an API key from them.

**Comment by aesculus** [comment]
It appears until you ask. And then you are turned down. Been there. Done that.

**Comment by aesculus** [comment]
I made this a pro feature. There is a rough implementation of this in V1.2 (67). I am a bit worried about it because the API viewer that they provide is very weak on structure and could go wonkers at any time.

**Comment by aesculus** [comment]
I noticed that PlugShare will claim there are CCS charges at a location but in the view API it will most like not list them.  The way the app was written is that it will pull the chargers it sees at the site and give you the option of selecting one of those as the default value entered for you on the Add Waypoint dialog. The user is able to change the charger to any other type/rate they wish to after the dialog closes. It will also set the address, select the location and enter the location name automatically.  The user can change any of this before they select Save to create the waypoint.

**Comment by EVGrokker** [comment]
What is the intended flow to get the unique ID from Plugshare to EVTO?

Here's what I've worked out by trial and error (on iOS), with some observations.

I have a route laid in, and I open Plugshare to add a charger of interest. Touch the 'i' button to view the charger details, then touch the export button to display the options. One of the options is Copy, so I select that.

I return to EVTO Plan screen, select Add Waypoint from the menu, touch the new PlugShare button to open the PlugShare Station dialog. I touch in the Station Id field, then Paste.

EVTO fails to parse the full string copied from PlugShare. If I edit the pasted string down to the trailing digits after the slash, it does parse the string.

I'm not sure what workflow you had in mind, but here's what I'd propose:
- When parsing the Station Id field, if the content is not simply numeric, try scanning it with a regex, looking for content with a trailing slash followed by digits. If you match that pattern, try doing a lookup with that ID. In other words, if the Station Id content looks like this:
`Sea Change Cannabis http://api.plugshare.com/view/location/75904`, use a regex to extract the trailing `75904`, then try to use that to find the charger address and stats.
- Once you have that working, it may not be necessary to have the additional PlugShare button and PlugShare Station dialog. Allow the user to paste the string copied from PS directly into the Location field in the Add Waypoint dialog. When Google fails to return a hit, try parsing as described above. If the regex matches the PlugShare pattern, fetch the PlugShare values and plug them directly into the Name, Address and charger type fields. That would be much simpler for the user.

**Comment by aesculus** [comment]
Right now the flow is just for you to enter  (type) they 4-5 digits.

**Comment by aesculus** [comment]
> Once you have that working, it may not be necessary to have the additional PlugShare button and PlugShare Station dialog. Allow the user to paste the string copied from PS directly into the Location field in the Add Waypoint dialog

The simplest is to rely on the user to use the PlugShare share feature icon and choose copy to clipboard. Then I can fetch the data from the clipboard.

Today I am fetching the plugs too and offering the user a list to choose from.  If I do a direct input to the Add Waypoint dialog from the PlugShare button, you will lose this feature. I could just take the first plug supported and use that as the default.  Note right now outside of the US I am not getting plug types from PlugShare for some reason so this might be more consistent.

**Comment by aesculus** [comment]
In V1.2 (68) you go to PlugShare and get to the sharing icon. From here select Copy.

Now go to EVTO and bring up Add/Edit Waypoint. Select PlugShare and sit back. The address will be entered in the location input, the location will be found (barring and PlugShare address issues - yes I found one) and the name of the charging spot will be filled in too as well as the first charger that it encountered in the list.  They user just needs to verify/change the charger type/rate and press Save.

**Comment by EVGrokker** [comment]
As far as ease of use, not having a separate dialog is a huge improvement.

The only issue that I have at this point is the placement of the PlugShare button in the dialog. By grouping it with Cancel and Save, it's presented as an action that will do something, then close the dialog. 

Ideally, the user action would take place in or near the location field. They've copied the information from PlugShare, so now they're thinking "where do I paste this?"

Ideally, I'd prefer that you recognize the format when it's pasted into the Location field.

If that's impractical, the next best solution would be a button near the Location field labelled 'Paste from PlugShare', that would only be enabled when whatever's on the clipboard conforms to the format. I don't see an ideal spot, but underneath the Location field would be the most obvious.

**Comment by aesculus** [comment]
>The only issue that I have at this point is the placement of the PlugShare button in the dialog. By grouping it with Cancel and Save, it's presented as an action that will do something, then close the dialog.

Well it did do that before you made me change it. :-)

>Ideally, I'd prefer that you recognize the format when it's pasted into the Location field.

I'll work on that if it's possible. Of course there will be no recognition of the capability, except perhaps in the help.  You just go to PlugShare, copy the URL and paste it into the location field.

**Comment by aesculus** [comment]
In 1.2 (69) you just paste from PlugShare into the address field and if it recognizes the format it will kick off the PlugShare routine like it did with the button.

If not the text is just pasted into the field.

This works for waypoints (new or editing).  Do you see a need for this in the New Trips dialog for either the location or destination fields?  The user can always change these to PlugShare locations later if they use the Waypoint Inspector and then edit, which brings up the Waypoint dialog.

**Comment by EVGrokker** [comment]
For consistency, I think it's a good idea to support pasting the PlugShare format anywhere that accepts an address. 

Help text for #170 and #172 needs to be updated to describe this functionality.

**Comment by aesculus** [comment]
> For consistency, I think it's a good idea to support pasting the PlugShare format anywhere that accepts an address.

I think I caught these all but if you find any I missed, let me know. I did New Trips and both New and Edit waypoints.  Maybe when Favorites get's rebuilt, it can put in there too.
