### ISSUE TITLE
Filter Charger Does Not Apply for Tesla Supplied Chargers

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#332]
The Filter Charger should turn off HPWC when deselected. Right now it only filters the NREL chargers.

**Comment by EVGrokker** [comment]
See issue #319, related.

**Comment by aesculus** [comment]
I added the feature to have the Charger Filter toggle HPWC on/off and to display them or not when the user selects the Tesla Charger icon from the map. Added in V1.2 (22)

**Comment by EVGrokker** [comment]
See issue #319, where selecting HPWC only leads to error with NREL overlay. What is the intended behavior here?

**Comment by aesculus** [comment]
Funny that I noticed the exact same thing yesterday too.

For the most part it appears that all HPWC's are contained in the Tesla DB right now. I thought NREL had them but it does not appear to be so.  They certainly have the ability and placeholder for such.

What happens here is that all Tesla charges are contained when using the lightening bolt. The HPWC filter option will toggle those charges on/off in that scenario.

When you only have HPWC selected and then choose the NREL or plug icon, it would not show any chargers because the filter in that case has nothing to show.
