### ISSUE TITLE
Need to insure that everyone knows times are local

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#335]
I thought I had footnotes scattered about but a quick glance did not show me any.

All times in EVTO are local, and not the devices time unless the device is in the same place as is referenced in the app.

A good place to mention this will be in the updated New Trip dialog when we add Date/Time to it. Also needs to be spelled out in the Edit Segment Details help panel too and maybe the main help.

**Comment by aesculus** [comment]
Just a reminder to make sure we mention this in the help as appropriate.

**Comment by EVGrokker** [comment]
Will review tomorrow.

**Comment by EVGrokker** [comment]
To clarify, 'local' means the time at the waypoint or charging stop along the proposed route, correct?

**Comment by aesculus** [comment]
Yes. The times are as if you were at the place you selected. Sort of like flight schedules.
