### ISSUE TITLE
Plan screen: Button appearance

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#336]
For the buttons overlaid on the Plan map, do you have the ability to set their alpha values? Can you use PNG images with transparency?

If so, I'd like to propose a more polished look for the buttons. I've mocked up an image to show the concept.

The white background area of the button images is 60% opaque. The outer edge of each button is stroked with a 1-pixel black line.

If this is possible, and you like the concept, we could experiment with some other background color and transparency possibilities. But the effect would still be a button floating above the map, with some transparency to see the underlying map area.

(I used an old screen shot before the buttons were moved around, but the proposed button appearance is accurate.)

![transparent buttons](https://cloud.githubusercontent.com/assets/26678403/25532706/81711cc8-2beb-11e7-96f4-d55e83b7e7ad.png)

**Comment by aesculus** [comment]
Yes I can do this I think. It looks like you have rounded corners too.

I am not noticing the 60% opacity but if you say so.

**Comment by EVGrokker** [comment]
You should experiment and determine a good color/opacity. My sense is that the background should a touch darker and maybe a touch more transparent, but still enough of a base so that the button pops.

**Comment by aesculus** [comment]
Never mind. Google is tossing out the transparency. Should have guessed this when I went to edit the image and found out they were already transparent.

So basically I can round the corners and put in a 1px black border like you have shown above.  It looks like you expanded the icons a few px too so there was separation between the icon and border.

**Comment by EVGrokker** [comment]
The rounded border will be a nice touch, even without transparency.

**Comment by aesculus** [comment]
This is addressed in V1.2 (23)
