### ISSUE TITLE
1.1.5 release text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#337]
<p>I'm excited to announce that version 1.1.5 of EV Trip Optimizer for Tesla (EVTO) is now available to <a href="https://itunes.apple.com/us/app/ev-trip-optimizer-for-tesla/id1124549080?mt=8"> download for iOS</a> and <a href="https://play.google.com/store/apps/details?id=com.digitalautoguides.teslato">Android</a>. The Standard version of EVTO is still free, allowing you to plan and update one trip at a time. </p>

<p>The team has been working hard to improve EVTO based on your feedback and suggestions. Here are a few of the changes you'll notice in 1.1.5:</p>
<ul>
<li>New 'Location' feature. Touching the crosshair button on the map toggles display of the current location of your device. (Requires Location Services to be enabled).</li>
<li>Reorganized buttons on the map screen for more intuitive operation.</li>
<li>Many improvements in route optimization and weather impact calculations.</li>
<li>Added support for 5-seat Model X.</li>
<li>Squashed bugs.</li>
<li>UI tweaks.</li>
</ul>

<p>We're also proud to unveil an <a href="http://www.digitalautoguides.com/#evto_main">all-new section of our website devoted to EVTO</a>, where you'll find the first two of our 'Tips & Tricks' tutorial series, helping you to master EVTO:</p>
<ul>
<li><a href="http://www.digitalautoguides.com/a-guide-to-ev-terminology">From the Frunk: A User's Guide to EVTO Terminology</a></li>
<li><a href="http://www.digitalautoguides.com/shifting-from-auto-to-manual/">Route Planning: Shifting from Auto to Manual</a></li>
</ul>

<p>Look for additional Tips & Tricks on a regular basis. If there's a particular topic you'd like us to tackle, please <a href="mailto:support@digitalautoguides.com?Subject=Tutorial suggestion">drop us a line</a>. Be sure to check out our <a href="http://www.digitalautoguides.com/a-guide-to-ev-terminology">Terminology guide</a> and let us know what additional EV buzzwords we should be abusing.</p>

<p>If you've previously found EVTO daunting, we heard you. The team has been focused on improving usability and delightfulness. As always, our goal continues to be providing the perfect planning companion app for your Tesla. Please let us know how we're doing. If you find EVTO useful, please take a moment to rate us in the App Store.</p>

<p>PS: If you follow EVTO development, you're aware that we're working a major new feature: All-in-one optimization, where an optimization to any trip segment will update all segments automatically. That's still in the pipeline. We decided to get 1.1.5 in your hands as quickly as possible. Stay tuned for this and other great features coming soon.</p>

**Comment by EVGrokker** [comment]
Ready for your review.

**Comment by aesculus** [comment]
Great. I am going to add a bit about the single optimization for 1.2 at the top as many are going to be expecting this is that.

**Comment by EVGrokker** [comment]
Make the edit here so I can review it before you post it.

**Comment by aesculus** [comment]
While we are getting V1.2 ready, with the single optimization model, we discovered a few things we could not wait to release to you. I'm excited to announce that version 1.1.5 of EV Trip Optimizer for Tesla (EVTO) is now available for download for iOS  and Android. The Standard version of EVTO is still free, allowing you to plan and update one trip at a time.

The team has been working hard to improve EVTO based on your feedback and suggestions. Here are a few of the changes you'll notice in the latest version:
New 'Location' feature. Touching the crosshair button on the map toggles display of the current location of your device. (Requires Location Services to be enabled).
Reorganized buttons on the map screen for more intuitive operation.
Many improvements in route optimization and weather impact calculations.
Squashed bugs.
UI improvements throughout.
We're also proud to unveil an all-new section of our website devoted to EVTO, where you'll find the first two of our 'Tips & Tricks' tutorials, helping you to master EVTO:
From the Frunk: A User's Guide to EVTO Terminology
Route Planning: Shifting from Auto to Manual
We're already planning additional Tips & Tricks in the near future. If there's a particular topic you'd like us to tackle, please drop us a line: support@digitalautoguides.com. Check out our Terminology guide and let us know what additional EV buzz words we should add.

If you've previously found EVTO daunting, we heard you. Our team has been focused on improving usability and delightfulness. Our goal continues to be providing a mobile app that's the perfect planning companion for your Tesla. Please let us know how we're doing in making EVTO an indispensable part of your Tesla ownership.

Again, up next is version 1.2 with a few more surprises and the sought after single trip optimization feature.

**Comment by aesculus** [comment]
Somehow the format and links are not posting correctly

**Comment by EVGrokker** [comment]
I reformatted the first comment in HTML with the links, and appended your 1.2 comment at the end. I don't want to steal the 1.1.5 thunder. See what you think.

Does TMC support HTML postings?

**Comment by aesculus** [comment]
I opened the page and pasted it right in so it seems to be OK. I will repeat this once I have the other edits done.  

I had gone after all the links too and I am not sure why they did not post right into git. :-(

**Comment by EVGrokker** [comment]
The only link missing now is the one for the Android store in the first paragraph.

Let me know before you publish this so I can review one last time.

**Comment by aesculus** [comment]
I just updated the above with the Android link

**Comment by EVGrokker** [comment]
OK, as long as TMC accepts HTML this should be good to go. But don't publish yet until we finish on the DAG pages.

**Comment by aesculus** [comment]
Caught one small edit I had to change after posting. Hopefully within the window.

Form:
> where any single revision to any trip segment will update all segments automatically.
To
> where an optimization to any trip segment will update all segments automatically.

**Comment by aesculus** [comment]
I never want to optimize automatically because it could change the routing. It already does calculations and weather automatically with any change to a segment.

**Comment by EVGrokker** [comment]
You shouldn't trust the documentation department. Just saying. :)

**Comment by aesculus** [comment]
When they are accurate 99.999% of the time it's easy to do that. :-)
