### ISSUE TITLE
Reorganize EVTO FAQs in Categories

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#338]
(content grabbed from the DAG FAQ site 2017-04-28, HTML tagging intact.)
<hr/>

<h3>Batteries</h3>

<h5 class="et_pb_toggle_title">What do the battery colors mean?</h5>
<p>The batteries on the map InfoWindow popup and the <strong>Trips Details</strong> panel show the state of charge upon arrival. (<strong>Note</strong> the origin shows the departure SOC). The colors of the battery image matches the car and mean:</p>
<ol>
<li>Green &#8211; over 20% SOC should be available on arrival</li>
<li>Yellow &#8211; over 10% and up to 20% SOC available on arrival</li>
<li>Red &#8211; 10% or less SOC should be available on arrival</li>
<li>Blue &#8211; the energy reserved at the destination for local travel</li>
</ol>

<h5 class="et_pb_toggle_title">Why are there multiple colors on my battery icon?</h5>
<p>The battery represents the SOC that you will have when you arrive at that waypoint (the origin battery represents the SOC at the start of the trip). Since you can arrive at a waypoint more than once (Return to last charger feature) or retain a certain amount of energy at a destination for local travel, we show both levels on the battery.</p>
<p><strong>Note</strong>: Also indicated below the battery is the numeric SOC for both visits. The first visit SOC is on the left.</p>
<p><strong>Note</strong>: Energy reserved for local travel is shown on the battery in blue.</p>

<h5 class="et_pb_toggle_title">How do you handle older cars whose battery has degraded?</h5>
<p>In the <strong>My Cars</strong> feature you can set the battery life percent of your car from 50-100%. This will be used in the range calculations.</p>

<h5 class="et_pb_toggle_title">How do I determine the battery life % of my car?</h5>
<p>When your car was first manufactured it had a maximum range. Over time the battery will degrade and you will obtain less and less range than what the car was when new. This will affect the accuracy of the calculation the that EVTO application makes in its trip optimization. To correct this we have allowed you to indicate what the battery life is of your car, contained in the <strong>Battery Life</strong> slider in the <strong>My Cars</strong> panel.</p>
<p>To determine your current battery life percent:</p>
<ol>
<li>Obtain the new maximum range of your car from the Tesla site. Be sure to note the model and type, battery size as well as accessories such as wheels and tires that could effect your range.</li>
<li>Determine what 90% of that value is (range * .9)</li>
<li>Charge your car to 90% and record the rated range after charging</li>
<li>Divide the number from step 3 by the number from step 2 and multiply by 100. This is your battery life percent.</li>
</ol>
<p>For example: A brand new Model X 90D with 20&#8243; wheels had an advertised EPA range of 257 miles. 90% of that maximum range is 231 miles. If your car, at 90% charge, is showing 215 rated miles, your battery life percent is 93%.</p>
<h5 class="et_pb_toggle_title">How do I change the starting SOC?</h5>
<p>Your starting SOC (origin) is determined by what you have setup in <strong>Settings</strong> when you created the trip. If you need to change the value after you have created the trip, then use the <strong>Edit Details</strong> in the <strong>Plan Trip</strong> popup menu.</p>

<h3>Charging, Energy and Consumption</h3>

<h5 class="et_pb_toggle_title">The charging times seem too short or too long.</h5>
<p>There are a lot of influences to how much time it takes to charge the car. The app has many models depending on the charger type and the arrival and departure SOC estimates. In addition at the charger itself the number of users, how they are paired and the weather can all play a role. At best the estimates the app gives are the best case scenario. Your times may often be longer.</p>
<p><strong>Note</strong>: The minimum charging time is set to 10 minutes. Even though you may only need a few minutes of charge to reach the desired SOC, the app will never charge for less than 10 minutes.</p>

<h5 class="et_pb_toggle_title">The app seems to over/under estimating my energy consumption.</h5>
<p>First it is important that you have correctly entered your cars values in the <strong>My Cars</strong> menu item on the main panel. If you have done that and your trips are always over or under estimated, you should adjust your <strong>Power Factor</strong>.</p>
<p>Adjusting the power factor can be done in the <strong>Edit Details</strong> menu item from the <strong>Plan Trip</strong> panel. Note if you change the value here it will only be applied for the current trip but will be the default for new trips too. A negative number will be more conservative in its consumption estimates while a positive number will be more aggressive.</p>
<p>This only applies to the driving portion of the optimization algorithm and is essentially a driving style adaptation. If you drive very conservatively you may need a lower setting while if you drive more aggressively, often exceeding the traffic flow and use the brakes rather than regen braking, you will need a higher setting.</p>

<h5 class="et_pb_toggle_title">Can I increase the arrival SOC for one or more waypoints on my trip?</h5>
<p>Yes. Go to the waypoint pushpin and selected <strong>Edit</strong>. Change the <strong>Minimum SOC</strong> for that waypoint. This will force the upstream charger to attempt to satisfy this demand.</p>
<p><strong>Note</strong>: If you want to change the minimum SOC for a automatic charger, you will have to make it required first. You do that by the waypoint <strong>Require</strong> button.</p>

<h5 class="et_pb_toggle_title">What does the option &quot;Plan last charging stop for a return trip&quot; do?</h5>
<p>Very simply it determines how much energy would be required to go from the destination back to the last place you charged.</p>
<p><strong>Note:</strong> This is a lot more detailed than just doubling the power required to get from the last charger to the destination and includes all intermediary waypoints that are not chargers as well as weather and elevation effects that might not be the same in both directions.</p>

<h5 class="et_pb_toggle_title">How can I reserve extra energy at the destination for local travel?</h5>
<p>This feature is contained in the <strong>Edit Details</strong> popup panel in the <strong>Plan Trip</strong> menu.</p>
<p>You enter your required reserve in distance based on your settings (mi or km).</p>

<h5 class="et_pb_toggle_title">Why are there spikes on the Consumption chart?</h5>
<p>Those spikes are caused by short bursts of energy consumed or generated when you arrive or depart waypoints. This is often because your are accelerating/decelerating, climbing/descending or just starting out. While we try to smooth as much of that as possible, you may still see this effect at every stopping place if its significant. These can also appear for short trip legs with drastically different energy consumption patterns such as a short climb up a hill after a turn.</p>

<h5 class="et_pb_toggle_title">Why don&#039;t you get the SOC data directly from the car?</h5>
<p>Currently we are not interfacing directly with the car and have no immediate plans to do so. We value your privacy and are not willing to take on the responsibility of being a potential security leak to your privacy or safety.</p>
<p>Truth be told there is very little value we can obtain from accessing the data in your car. Our algorithms are science based and do not use statistics or deep data mining to try to guess the best possible solution like many other offerings do.</p>

<h5 class="et_pb_toggle_title">Why does the app use percent vs rated miles/km for SOC?</h5>
<p>The app uses percent SOC because that is common and consistent. Rated miles is just using the stated average miles applied to a percent SOC. Rarely does your car ever actually get the rated miles. It&#8217;s generally either above or below that. Our experiences have shown that people confuse rate range verses the estimated range and it is our hope that using percent SOC instead will eliminate some of this.</p>
<p><strong>Note</strong>: There is actually one place the app asks you to enter distance versus SOC percent. That is in the <strong>Edit Details</strong> panel where you have the option of entering a reserved distance (miles or km) to be used when you are at a destination for local travel. It is assumed that all of this energy will be used locally so none of this energy is transferred to the next stop.</p>

<h5 class="et_pb_toggle_title">How do I compensate for towing a trailer?</h5>
<p>You can adjust the <strong>Power Factor</strong> in the <strong>Trip Details</strong> panel to adjust for the extra energy required in towing a trailer.</p>

<h5 class="et_pb_toggle_title">Where do I adjust the speed?</h5>
<p>There is no speed adjustment in the App. Our research and experience has demonstrated that increasing the speed just means that your charging time will go up, often more than the savings in time that you achieved by driving faster. This is because at high speeds your car uses much more energy and that energy is usually charged at a lower rate than your driving speed, hence your trip is actually longer in time. The only situation it really makes sense to drive faster than normal is when you don&#8217;t need to charge (ie the last leg of the trip).</p>
<p>There is a <strong>power factor</strong> in the <strong>Edit Details</strong> you can use to indicate that your driving experiences show you need either more or less consumption than average. This will affect the energy consumed and hence the charging times. The net result will be a more accurate total travel time, even though the estimate of driving time may be off some.</p>

<h5 class="et_pb_toggle_title">Where do I change the global setting for payload, power factor and the cabin temperature?</h5>
<p>Once you set these in a trip, the payload, cabin temperature and power factor become the defaults for the next new trip.</p>

<hr/>

<h3>Connecting with your Car</h3>
<h5 class="et_pb_toggle_title">My calendar entries created by the App do not appear on my Tesla.</h5>
<p>First you must turn on calendar syncing in the Tesla mobile app. See the <strong>Settings &#8211; Calendar Sync</strong> option. The calendar entries from your mobile device will only synchronize to the car when the Tesla app is active. So after using the EVTO and adding calendar entries, ensure that the Tesla app is also active when you want to synchronize the calendar on your mobile device. Also check on the iPhone under General&gt;Restrictions&gt;Privacy&gt;Calendar the setting must be &#8220;allow changes&#8221;.</p>

<hr/>

<h3>Contacting the Development Team</h3>
<h5 class="et_pb_toggle_title">Can I join your beta team?</h5>
<p>E-mail us at info@digitalautoguides.com We are always looking for people with extended requirements and extra time to try various scenarios and help debug the application.</p>

<hr/>

<h3>Exporting Trips and Itineraries, User Data</h3>
<h5 class="et_pb_toggle_title">Where is my trip data stored?</h5>
<p>All trip data is stored on the mobile device. During optimization the list of your chosen waypoints is sent to a server to be used for routing. No personal or car identification information is included and the data is not stored or used beyond the few seconds the optimization takes place.</p>
<p><strong>Note</strong>: If you share a trip then the trip data is stored on a server for 30 days, but no association to a car or user is kept on the server.</p>

<h5 class="et_pb_toggle_title">Can I access the raw trip data?</h5>
<p>Raw trip data is embedded in the app and is not user consumable. However if you have the <strong>Pro</strong> version you can get a Comma Separated Variable (CSV) version of all the energy and travel data for each leg of the trip to be used in other programs like spreadsheets.</p>
<p>To access this data go to <strong>Trip Details</strong> and select <strong>Export Data</strong>.</p>

<h5 class="et_pb_toggle_title">Can I share my trips with others?</h5>
<p>You can share your trips with other EVTO users from the <strong>Current Trips</strong> panel. Use the <strong>Share Trip</strong> menu item to select a trip to be shared. The application will prompt you for a unique four PIN and create an email for you to send to your recipient(s).</p>
<p>To receive a shared trip you will need the unique <strong>Trip ID</strong> and <strong>PIN</strong> as sent in the email and use the <strong>Import Trip</strong> menu item. Just copy the ID and PIN from the email into the popup panel.</p>
<p><strong>Note</strong>: If you import a trip without a multi-trip subscription, it will replace your currently active trip. You will be prompted before the application carries out this action in case you want to cancel the request.</p>

<h5 class="et_pb_toggle_title">What happens to my trips if I migrate to a new device?</h5>
<p>If you anticipate migrating to a new device you should <strong>Share</strong> any trips you want to save to yourself. Then when you receive the new device and install the EVTO application, you can then import the shared trips.</p>
<p>Note that any In App Purchases (IAP) you have made are with your account and not the device. So when you get your device and install the EVTO application, just use the <strong>Restore Purchases</strong> menu item.</p>

<hr/>

<h3>Settings, My Cars</h3>
<h5 class="et_pb_toggle_title">Changes to My Cars or Settings do not update my trips.</h5>
<p>This is by design. After you make changes to your <strong>Settings</strong> or the car that is attached to a trip, you must optimize the trip from the <strong>Plan Trip</strong> menu. In addition some trip attributes like the SOC settings on waypoints and Trip Details will be preserved at their original values. You will need to manually change these if you wish.</p>

<h5 class="et_pb_toggle_title">When will the Model 3 be supported?</h5>
<p>The Tesla Model 3 is built into the application. Once Tesla finalizes the weight and options of the car along with a few key parameters, the application will be able to support the Model 3 along with the Model S/X.</p>

<h5 class="et_pb_toggle_title">How can I indicate I am using the rear climate control for split system cars?</h5>
<p>The cabin climate control is based on the payload. If you exceed 500 lbs of payload on a split system car like the Model X, the climate control energy is increased automatically. This option can be turned off/on in the<strong> My Cars </strong>menu item<strong>, Rear Climate Control</strong> checkbox.</p>

<hr/>

<h3>Standard, Pro and Multi-Trip Versions (IAPs)</h3>
<h5 class="et_pb_toggle_title">Why is there a subscription fee for trip planning?</h5>
<p>We have to pay service providers (weather, trip routing, elevations, charger locations) a fee based on usage.</p>
<p>By default the application allows you to plan one trip for no charge. You can delete this trip or change it as you wish. We feel that heavier users that plan many trips per month, and want to keep them active, should pay for the services they are consuming. We will review the subscription fee over time and adjust it appropriately based on the overall use of the services to ensure that our costs are being covered.</p>

<h5 class="et_pb_toggle_title">What features are provided in the Pro version?</h5>
<p>If you have viewed the <strong>Getting Started</strong> panels or created a trip, then you should be able to get to your current trip, or plan a new trip if there is no active trip, directly from the large button <strong>Resume</strong> on the main panel.</p>
<p>To change the active trip you will have to select one of the trips from the <strong>Current Trips</strong> panel.</p>

<hr/>

<h3>Trips, Routes &amp; Segments</h3>
<h5 class="et_pb_toggle_title">What do the colors on the map push pins mean?</h5>
<p>There are six colors that can be depicted on the map push pins:</p>
<ol>
<li>Green &#8211; indicates you should safely make it to this waypoint</li>
<li>Yellow &#8211; indicates you will probably make it to this waypoint within your set minimum SOC</li>
<li>Red &#8211; indicates it&#8217;s unlikely you will make it to this waypoint with the current limitations. You will need to review your settings or add additional charger(s) between the last green waypoint and the one that indicates red, and/or <strong>Optimize</strong></li>
<li>White &#8211; A white destination pushpin indicates the application needs to be recalculated. This rarely displays for more that a few seconds. This also appears on secondary segments of multi-segments trips when you have optimized a segment prior indicating this segment is a candidate for optimization too</li>
<li>Blue &#8211; The origin always has a blue pushpin</li>
<li>Grey &#8211; Chargers that are not waypoints or not needed for routing, but are shown for information purposes.</li>
</ol>
<p><strong>Note</strong>: The red, green and yellow colors are also utilized on the <strong>SOC</strong> chart with the same meanings.</p>
<h5 class="et_pb_toggle_title">How do I create a new route and start over?</h5>
<p>When you use the new trip feature (from the main panel, <strong>Current Trips</strong> or <strong>Plan Trip</strong> menu) you will create a fresh trip. There is no need to delete waypoints, chargers or origin/destinations.</p>
<p>If you have not subscribed to the multi-trip option, then the currently active trip will be replaced. If you have subscribed then a new trip will be created and the currently active trip will still be available from the <strong>Current Trips</strong> menu item.</p>

<h5 class="et_pb_toggle_title">I can no longer resume my current trip.</h5>
<p>If you delete or archive the active trip, you will need to set another trip active.</p>
<p>Go to the <strong>Current Trips</strong> menu item and then select <strong>Activate Trip</strong> from the popup panel. Your selected trip will now become the current active trip and you can use the <strong>Resume Trip</strong> feature from the main panel.</p>

<h5 class="et_pb_toggle_title">How do I force the planner to use a certain route?</h5>
<p>When you plan a trip you enter your destination. The application starts the trip at you current location unless you have also provided an origin. You can change the origin by editing it from the map pushpin. When you <strong>Optimize</strong>, the application will chose the best route based on the optimization model and conditions forecasted.</p>
<p>If you do not like the routing chosen for you, just add a waypoint (either pressing on the map or using the <strong>Add Waypoint</strong> menu item) anywhere along the route you desire. If needed you can repeat this process to further refine your desired routing. Be sure to <strong>Optimize</strong> after you have settled on all our your added chargers.</p>
<p>One of the biggest influences to your routing will be charging stops. The application will immediately let you know if you can safely reach the next charger to test your ideas. Try different chargers to influence the route and/or overall trips times. Refer to the <strong>Consumption</strong> and <strong>SOC</strong> charts to see how your energy is consumed en route.</p>
<p><strong>Note</strong>: If you <strong>Dislike</strong> a supercharger, it will receive a time penalty and the application will attempt not to use that charger if there are other alternatives. This could dramatically change the routing for a given trip.</p>

<h5 class="et_pb_toggle_title">How do I complete a trip?</h5>
<p>To change the status of a trip from <strong>Plan</strong> to <strong>Taken</strong> just rate the trip. You rate the trip from the <strong>Plan Trip</strong> menu <strong>Rate Trip</strong> item.</p>

<h5 class="et_pb_toggle_title">Why is the New Trip menu item disabled?</h5>
<p>The <strong>New Trip</strong> menu item will be disabled on a continued trip, unless you are on the last segment.</p>
<p><strong>Note</strong>: If you have not subscribed to trip planning, you will be limited to one trip at a time. You will have to replace the current trip in order to create a new trip, or you can just change the destination/origins. Selecting a <strong>New Trip</strong> will prompt you to replace the current trip.</p>

<h5 class="et_pb_toggle_title">What is a continuation trip?</h5>
<p>A continuation trip is a trip with multiple segments. An example would be a trip you took over many days (each day being a trip segment). The first segments destination becomes the next segments origin and so on until you return back to the original origin.</p>
<p><strong>Note</strong>: If you change a origin or destination waypoint that is paired with another trip segment, both waypoints will be updated and both segments will be recalculated automatically.</p>
<p>The trip is handled as one large trip and you can easily move from segment to segment from the <strong>Trip Segment</strong> popup on the map. Use the little map icon on the right center of the map. The total trip stats are also included in the popup panel.</p>

<h5 class="et_pb_toggle_title">How can I divide a trip into segments?</h5>
<p>If you encounter a situation where you would like to divide a longer trip into two or more trip segments, you can use the <strong>Segment</strong> feature. Select the waypoint you would like to segment the trip at and select the <strong>Segment</strong> button from the Infowindow popup. After confirmation the active trip will be divided into two trip segments at that waypoint. This is a <strong>Pro</strong> feature.</p>
<p><strong>Note</strong>: You will need to optimize any segments downstream from the new segment break. Their destination icons will be white to remind you.</p>

<h5 class="et_pb_toggle_title">Why do you need trip segments?</h5>
<ul>
<li>On smaller devices the <strong>Trip Summary</strong> waypoint list could get quite large and unusable</li>
<li>If your routes overlays each other (like first driving from Seattle to Portland and then making a loop trip before going back to Portland and Seattle- a Q), you could not tell which route was inbound or outbound on the tail of the Q and you would not know which waypoints went to which part of the trip on the map</li>
<li>If the total multi-segment trip was shown on small devices, you could not see the details for your current days journey without constantly re-zooming/panning</li>
<li>Each segment can have a different start date/time and therefore a more accurate depiction on the trip, better weather forecasting and it correctly depicts in your calendar for use in the cars navigation system.</li>
<li>You are not required to use the multi-segment feature. You can plan your just trip as one unit if you wish. Just enter a waypoint for each logical segment endpoint.</li>
</ul>

<h5 class="et_pb_toggle_title">New trips only continue the current trip</h5>
<p>If you have purchased the <strong>Pro</strong> feature but have not purchased the multi-trip subscription, then when you use the <strong>New Trip</strong> feature on the <strong>Plan Map</strong>, it will only allow you to continue the current trip.</p>
<p>To replace the trip with a new trip, just use the main menu or <strong>Current Trips</strong> menu, <strong>New Trip</strong> item.</p>

<h5 class="et_pb_toggle_title">What times are displayed for arrival and departure?</h5>
<p>All times are shown in the locations local time zone. So you if you start a trip at 09:00 in MT and then arrive in a PT waypoint one hour later, the arrival time will show as 09:00.</p>

<h5 class="et_pb_toggle_title">What happens to my saved trips if I don&#039;t renew my multi-trip subscription?</h5>
<p>If you had a multi-trip subscription and saved trips and then decided not to renew the subscription, your trips will be saved and you can renew or use them.</p>
<p>However you will only be able to replace the active trip when you create a new trip. You will not be allowed to add to your trips unless you renew your subscription.</p>

<hr/>

<h3>Under the Hood: How EVTO works</h3>
<h5 class="et_pb_toggle_title">How is the optimization performed?</h5>
<p>The application, along with a set of servers, optimizes your trip through a set of fairly complex algorithms. Included in the models are:</p>
<ul>
<li>The characteristics of your car and loading/passengers</li>
<li>The driving time and distance to all your regions superchargers</li>
<li>Any additional waypoints you have selected</li>
<li>The weather en route including temperature, wind speed/direction and precipitation</li>
<li>Your driving power profile (power factor)</li>
<li>Estimated charging times</li>
<li>Elevation gains or losses</li>
<li>Nominal traffic flow</li>
<li>The starting and minimum SOC at waypoints</li>
<li>Any constraints you have placed on waypoints such as minimum charge, return to last charger, reserved destination travel</li>
<li>If you have <em><strong>Disliked</strong> </em>any potential charging stops</li>
</ul>
<p>The application actually optimizes in multiple passes for each request of optimization. First the routing and superchargers are selected based on stops. Then an optimal route is chosen through the selected waypoints and chargers including traffic impacts. Lastly detailed energy consumption and charging times are determined based on fractions of trip segments using all the available information.</p>

<h5 class="et_pb_toggle_title">Why does the Optimizer not use one of the routes shown at first?</h5>
<p>When you first select your destination and optionally an origin, the app shows you the routes Google Maps would take if you were driving an internal combustion engine (ICE) car. The Optimizer decides where to route to based on the fact that you are driving an EV, so it could be that none of the routes Google picked (based solely on driving time), are appropriate for the given situation.</p>

<h5 class="et_pb_toggle_title">What is being optimized?</h5>
<p>The application assists in optimizing your trip from a lot of different perspectives. Most prevalently you would optimize based on the least overall travel time. But you can also use the tool to optimize for least energy consumed, least amount of stops, or shortest distance.</p>

<h5 class="et_pb_toggle_title">How often is the weather forecast updated?</h5>
<p>The weather forecast can be updated every four hours by choosing <strong>Recalculate</strong> from the <strong>Plan Trip</strong> menu panel or automatically if you have made changes to the trip after four hours has expired.</p>

<h5 class="et_pb_toggle_title">What determines the energy needs at waypoints and the destination?</h5>
<p>The application uses science based estimation in determining your travel needs. This means there is a set of algorithms based on the following:</p>
<ul>
<li>Trip distance</li>
<li>Speed of travel</li>
<li>Number of stops</li>
<li>Driving style</li>
<li>Weather &#8211; temperature, wind speed and direction, precipitation</li>
<li>Road conditions</li>
<li>Weight of car and passengers</li>
<li>Car type and features</li>
<li>Elevation changes</li>
<li>Cabin temperature</li>
</ul>
<p>In addition you can reserve additional energy at a destination for local travel and/or enough to get you safely back to the last charger in case there is no destination charger available or utilized.</p>

<hr/>

<h3>User Interface</h3>
<h5 class="et_pb_toggle_title">It&#039;s hard to visualize the table on the Trip Details.</h5>
<p>Small devices like the smart phone means it&#8217;s difficult to provide all of the information needed and still make it readable. You might find it easier to read the tables when the phone is rotated 90°.</p>
<p><strong>Note</strong>: On smaller phone like devices the third column of the <strong>Trip Details</strong> is not shown when the device is vertical. Rotate the device to see this third column.</p>

<h5 class="et_pb_toggle_title">What do the two flat lines represent on the Consumption chart?</h5>
<p>The solid line represents your cars advertised consumption average (rated consumption). The dashed line represents the active trips average energy consumption factor. You can tap on either line to see the value and label.</p>

<h5 class="et_pb_toggle_title">How do I see my entire trip on the map?</h5>
<p>Press the globe icon on the upper right corner of the map.</p>
<p>Whenever you make waypoint changes the current zoom is saved in case you want to further edit that location on the map. It will be reset to the entire trip if you return to the main panel.</p>
<p><strong>Note</strong>: On Android devices you may use the small icon in the upper right corner of the map to make the map fill the entire device.</p>
<p><strong>Note</strong>: On continuation (multi-segment or out and back) trips, only the active segment is zoomed when you press the <strong>Globe</strong> icon.</p>

<h5 class="et_pb_toggle_title">What is the purpose of archiving trips?</h5>
<p>The only real purpose is to remove trips from the list of trips that you are actively using in order to remove clutter. Archived trips can be restored if you need them for additional trip planning.</p>

<h5 class="et_pb_toggle_title">Can I change the chart types or colors?</h5>
<p>Not at this time. All of the charts are automatically generated so they are simple and easy to use. On the comparison chart you can select which trips and trip features you wish to compare so you have some flexibility there.</p>

<hr/>

<h3> Waypoints and Chargers</h3>
<h5 class="et_pb_toggle_title">What if I want to stop at a waypoint for a longer time?</h5>
<p>You can stop at waypoints that are not for charging or when you want to stop for longer than the charging needs indicate. Choose the <strong>Edit</strong> button from the waypoint pushpin and then change the <strong>Minimum Stop Time</strong> slider. This is a Pro feature.</p>
<p><strong>Note</strong>: You can only change these attributes on automatically selected chargers after you make the charger required.</p>

<h5 class="et_pb_toggle_title">How do I change a waypoint address or location?</h5>
<p>To change the address of a waypoint after you have selected it is easy. Just use the <strong>Edit</strong> button on the waypoint pushpin and then enter your new address on the <strong>Edit Waypoint</strong> panel. The trip will be recalculated for you automatically but you will probably need to <strong>Optimize</strong> if the new location is not close the original location.</p>

<h5 class="et_pb_toggle_title">What do the symbols mean on the charger icons?</h5>
<p>Each charger icon (pushpin) has a symbol embedded in it to let you know the type of charger it is. The symbols are the following:</p>
<ol>
<li><strong>S</strong> Tesla Supercharger</li>
<li><strong>H</strong> Tesla HPWC</li>
<li><strong>&#8211;</strong> Level 1 charger</li>
<li><strong>=</strong> Level 2 charger</li>
<li><strong>≡</strong> Level 3 charger</li>
<li><strong>J</strong> J1772 charger</li>
<li><strong>C</strong> CHAdeMO charger</li>
</ol>
<p><strong>Note</strong>: Before chargers are waypoints, they are shown in grey to let you know they are not part of the trip. Automatically selected chargers are shown with a small A contained within a red circle.</p>

<h5 class="et_pb_toggle_title">How can I change the origin?</h5>
<p>By default the origin is either at your current location or is the destination from a continuation or return trip.</p>
<p>If you want to plan a trip independent of your actual location, just enter your origin in the first box. If you later want to update the origin select the <strong>Origin</strong> pushpin and then select <strong>Edit</strong>. Now you can change the address and the program will automatically recalculate. You may need to <strong>Optimize</strong> the trip if the new location is not close to the current location.</p>
<p><strong>Note</strong>: If you have <strong>Location</strong> turned off in the settings, you will have to manually enter your origin for each trip.</p>

<h5 class="et_pb_toggle_title">How can I reorder the waypoints?</h5>
<p>Generally you should not have to reorder the waypoints as they are picked with the route for the most optimal trip. However there are conditions that may require changing the order of one or more waypoints.</p>
<p>Sometimes you may wish to force the waypoint order. If that is the case you may move any of the waypoints using the ∧ and ∨ buttons on the right of the waypoint in the <strong>Trip Summary</strong> popup. When you have reordered the list just select the <strong>Calculate New Routing</strong> button on the <strong>Trip Waypoints </strong>popup. If you wish to restore auto ordering of waypoints then select the <strong>Restore Auto Waypoint Order</strong> button.</p>
<p><strong>Note</strong>: After you <strong>Optimize </strong>a trip, you may need to readjust any waypoints you manually moved out of order. <strong>Calculate</strong> will not affect waypoint order but <strong>Optimize</strong> will.</p>

<h5 class="et_pb_toggle_title">How can I include my own destination or waypoint chargers?</h5>
<p>When you add a waypoint you can select what type of charger it has, if any. After you add a waypoint you can use the <strong>Edit</strong> button of the waypoint icon infowindow popup to change the charger type. Select the type of charger for that waypoint.</p>

<h5 class="et_pb_toggle_title">How can I indicate which supercharger I want to use?</h5>
<p>There are three ways to manually include superchargers into your route:</p>
<ol>
<li>Make an automatically selected Supercharger required.</li>
<li>Select the supercharger from the map</li>
<li>Entering the supercharger name after selecting <strong>Superchargers </strong>from the pull down on the <strong>Add Waypoint</strong> popup panel</li>
</ol>

<h5 class="et_pb_toggle_title">Why is the address disabled so I can&#039;t edit it?</h5>
<p>You cannot edit a waypoint address of a charger that was predefined.</p>

<h5 class="et_pb_toggle_title">How do I add a waypoint to my favorites?</h5>
<p>You can easily add any waypoint as a favorite which you can use when creating trips or adding waypoints. After the waypoint has been added select the pushpin on the map and when the popup window appears, you will notice a small heart at the top of the panel. Just select the heart (it will turn blue) to save that waypoint in your favorites or deselect it (it will turn clear) to remove it from your favorites.</p>
<p>To use the favorites just select the heart next to the address or place name on the <strong>New Trip</strong> or <strong>Edit/New Waypoint</strong> popup panels. A list of your favorites will appear.</p>
<p><strong>Note</strong>: You can edit these favorites from the main menu, <strong>Maintain Favorites,</strong> menu item.</p>

<h5 class="et_pb_toggle_title">How do new superchargers get added to the app?</h5>
<p>We update the supercharger lists every week. The application will automatically download any new superchargers at application startup. If you need to add a new supercharger before that, use the <strong>Add Waypoint</strong> feature and indicate it has a Tesla Supercharger.</p>

<h5 class="et_pb_toggle_title">Can I enter a supercharger name versus choosing one from the map?</h5>
<p>To add a new supercharger by name versus selecting from the map select the <strong>Add Waypoint</strong> menu item. When the popup panel appears change the <strong>Charger Type</strong> to <strong>Tesla Superchargers</strong>. Now you can enter the name of the supercharger in the <strong>Place Name</strong> field. It will find matching superchargers as you type so you don&#8217;t have to enter more than the first few characters.</p>

<h5 class="et_pb_toggle_title">How can I avoid superchargers I don&#039;t like to stop at?</h5>
<p>Select a supercharger pushpin (one that is not an automatically selected charger or not part of your trip). Then select the <strong>Thumbs Down</strong> icon which will turn red. This will force additional time on this supercharger during optimization and if possible, will cause it not to be used in future trips or routing.</p>
<p>You can deselect the <strong>Thumbs Down</strong> icon if you later wish to remove the dislike, or use the <strong>Maintain Favorites</strong> item from the main menu.</p>

<h5 class="et_pb_toggle_title">Will you be providing non Tesla chargers for locations outside of the USA?</h5>
<p>We are currently evaluating adding the ability to see non Tesla chargers at a given place on the map for locations not based in the USA. There is no estimated time for this feature.</p>
<p>Today you can add any type of charger you would like manually. Just use the<strong> Add Waypoint</strong> feature on the <strong>Plan</strong> menu. You can also make this a <strong>Favorite</strong> to be used over and over again.</p>

<hr/>

**Comment by aesculus** [comment]
Sorry to say this but the above cut and paste is moot now. I just reviewed and edited the FAQs.

**Comment by EVGrokker** [comment]
The intent of this issue was both to update the answers, which it sounds like you've already done, and to organize questions by topic.

**Comment by aesculus** [comment]
OK. Once the order is determined I can easily drag them around. I can also put in topic dividers which will make it easier to find things later too.

If you really want I can also add a sidebar/menu to get users to the topic sections faster too.

**Comment by EVGrokker** [comment]
I think the subdivisions I created above are a good first cut, please review. I already grouped them accordingly. I don't think the order within the subdivisions matters. You can do your HTML magic with the layout.

**Comment by aesculus** [comment]
OK. Quite frankly I did not even look at the content. It just made me think it was time to review and edit the FAQs. Not that I know the intent I can go back and finish the job. :-)

**Comment by aesculus** [comment]
Complete
