### ISSUE TITLE
[Advanced Tutorial]: Route Planning: The Sounds of Silence Rally

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#340]
_Work in progress, ready for @aesculus review_

<hr/>

<h3>Route Planning: The 'Sounds of Silence' Rally</h3>
<p><i>Do you hear the Sounds of Silence Tesla Rally calling to you? Use EVTO to quickly scope out a route!</i></p>

<h4>The Big Picture</h4>

![tesla rally pin](https://cloud.githubusercontent.com/assets/26678403/25544088/2501f734-2c16-11e7-9951-bcc5629c3501.png)

<p>The <a href="https://teslamotorsclub.com/tmc/threads/sound-of-silence-rally-custer-sd-may-19-20.86774/">4th Annual "Sounds of Silence" Rally May 19-20, 2017</a> in Custer, SD. If you're wondering how best to arrive charged up for the activities, read on. This tutorial outlines the steps to plan a 3-day road trip from the Bay Area to Custer. We'll plan it in three connected segments, with each day's stopping point at a Tesla Supercharger with hotels available nearby.</p>

<p><i>Note: EVTO calculates optimal routes based on parameters you've specified in <strong>Settings</strong> and <strong>My Cars</strong> to dial in the accuracy of its predictions. If your numbers don't line up with ours, it's probably because we actually weigh our payload baggage before a trip. OCD, right? But of course it could also be the weather forecast for our trip time is different too.</i></p>

<hr/>
<p>"Good morning class!"</p>
<p>A few mumbled responses make it to the front of the room. I put on a big brave grin, like everyone seems excited to be here and happy to see me.</p>
<p>"Welcome to Advanced Route Planning 101! Today we're going to plan a trip from the Bay Area to the <a href="https://teslamotorsclub.com/tmc/threads/sound-of-silence-rally-custer-sd-may-19-20.86774/">4th Annual Sounds of Silence Rally</a> in Custer South Dakota. We'll be using several of EVTO's route-planning tools to build our route."</p>
<p>I wait for the anticipated enthusiastic response… </p>
<p>Crickets.</p>
<p>"OK! Let's get started. First of all, you'll need the EVTO Pro version IAP upgrade. That enables you to add multiple segments to your trips, highly recommended for longer road trips like this one."</p>
<p>I look expectantly around the room. Most heads are nodding that yes, they've purchased the Pro version IAP. It was listed in the syllabus as a requirement.</p>
<p>A hand goes up.</p>
<p>"Yes? You in the back corner?"</p>
<p>"How much is the upgrade?"</p>
<p>Sigh. Not everyone is prepared today.</p>
<p>"It's a lot less than the cost of that double chocolate mocha you're slurping down."</p>
<p>Another hand.</p>
<p>"Is there any way to get it for free?"</p>
<p>Harrumph. "Not for <i>free</i>, but like I told you on the first day of class, you can get a discount on all Apple App Store purchases by using discounted gift cards when they go on sale. Follow @iTunesCardDeals on Twitter to keep up with the latest offers. Anytime you see 15% or better grab it. You can find similar deals available for Google Play gift cards. Google it."</p>
<p>Oh yeah, that got their attention. Lots of scribbling going down. Let's get this show on the road.</p> 
<p>"OK, open EVTO and let's get going."</p>

<h4>1. Preview the Route</h4>
<p>Let's see what EVTO recommends for the most expedient, charger-populated route.</p>
<ol type="a">
<li><strong>New Trip:</strong></li>
<li><strong>Origin:</strong> <i>Fremont CA</i>, aka 'The Mothership'</li>
<li><strong>Destination:</strong> <i>Custer SD</i>, aka 'The Rally'</li>
<li><strong>Waypoint Charger Selection:</strong> <i>Auto</i></li>
<li><strong>Calculate</strong></li>
</ol>
<p>EVTO ponders the nature of the space-time continuum to calculate the optimal route:</p>

![routepreview](https://cloud.githubusercontent.com/assets/26678403/25624620/2e6175f8-2f17-11e7-859e-22a77045a206.PNG)

<p align="center"><i>Auto-routing preview: Fremont CA to Custer SD</i></p>

<p>"Class, you're looking at the optimized route that EVTO calculated from the Bay Area to Custer using supercharging stops. If you were in a hurry, or lazy, you could just use this route and be on your way. But, we're here to learn, so we're going to build this trip in segments."</p>
<p>A hand shoots up. The hand belongs to Mr. Double Chocolate Mocha. <i>Quelle surprise</i>.</p>
<p>"It's only 1548 miles! I can load up with Twinkies, Peanut M&Ms and Big Gulps, and iron-butt it in one stretch. I'll cue up my <a href="https://www.timeout.com/newyork/music/50-best-road-trip-songs">50 Best Road Trips Songs</a> playlist on repeat and I'm outta here!"</p>
<p>I see an opportunity to enhance the average IQ of the group. "Brilliant! You're excused! Don't forget to recycle your drink cup!"</p>
<p>As Mr. DCM exits, I recommit to making the rest of our time together a quality learning experience.</p>
<p>"OK, we'd probably prefer a more leisurely journey, leaving something in the tank for the rally festivities, right? Let's put this together."</p>

<h4>2. Subdivide and Conquer</h4>
<p>Eyeballing the suggested superchargers along the route preview, we're going to pick Elko NV for the first night's stop, and Billings MT for the second night. That puts the longest driving days up front, getting us into Custer mid-afternoon the day before the rally starts to hang silently with our EV brethren.</p>
<p>This tutorial features the use of <strong>Add Segment</strong>, so we're going to start from scratch with our origin, add overnight stops in Elko and Billings, then arrive at our Custer destination.</p>
<ol type="a">
<li><strong>New Trip:</strong></li>
<li><strong>Origin:</strong> <i>Fremont CA</i></li>
<li><strong>Destination Charger Type:</strong> <i>Tesla Superchargers</i></li>
<li><strong>Destination:</strong> <i>Elko Supercharger</i>. With superchargers enabled as a filter, the Elko site pops right up.</li>
<li><strong>Waypoint Charger Selection:</strong> <i>Auto</i></li>
<li><strong>Calculate</strong></li>
</ol>
<p>EVTO calculates our first day journey to Elko. Select <strong>Segment Summary</strong> from the menu to review the itinerary. Looks good. Let's establish our departure date and time to get us to Custer on the afternoon of May 18th.</p>

<p>"OK class, if the rally starts on the 19th, and we want to arrive on the 18th, and it's a three day trip, what day should we leave the Bay Area?"</p>
<p>A couple of hands go up. I point to the quiet one over by the window.</p>
<p>"Will this be on the final exam?"</p>
<p>Shaking my head, I sigh. I point to pocket protector guy. Let's cut to the chase.</p>
<p>"With three driving days, that would be, uhh, um, let's see, a departure date of May 16th." The rest of the class nods in agreement.</p>
<p>"Good! You guys are getting it!"</p>

<ol type="a" start="7">
<li>From the menu, select <strong>Edit Segment Details</strong>.</li>
<li>Change the departure date to <i>May 16</i>.</li>
<li>Change the departure time to <i>8:00 AM</i>.</li>
<li><strong>Save</strong></li>
</ol>

<p>Let's see what time EVTO predicts we'll arrive in Elko. Select <strong>Segment Summary</strong> from the menu to review the itinerary.</p>

![day1summary](https://cloud.githubusercontent.com/assets/26678403/25616468/217a6aa6-2efa-11e7-826a-b816b3dace58.PNG)

<p align="center"><i>Not as Iron Butt as we used to be</i></p>

<h4>3. Next Stop, Billings!</h4>
<p>We'll use EVTO's <strong>Add Segment</strong> feature to add our next stop, Billings MT.</p>
<ol type="a">
<li>From the menu, select <strong>Add Segment</strong>.</li>
<li><strong>Destination Charger Type:</strong> <i>Tesla Superchargers</i></li>
<li><strong>Destination:</strong> <i>Billings Supercharger</i></li>
<li><strong>Calculate</strong></li>
<li>Let's set our Elko (day 2) departure time to 8:00 AM on May 17th. From the menu, select <strong>Edit Segment Details</strong>.</li>
<li>Change the departure date to <i>May 17</i>.</li>
<li>Change the departure time to <i>8:00 AM</i>.</li>
<li><strong>Save</strong></li>
</ol>

<p>"Almost there. We'll add our final segment from Billings to Custer, setting a departure time of 8:00 AM again, and see what time EVTO predicts we'll arrive in Custer."</p>

<h4>4. <a href="http://www.purplepieplace.com">Custer's Last Ice Cream Stand</a></h4>
<p>Once again, we'll use EVTO's <strong>Add Segment</strong> feature to add our final destination, Custer SD.</p>
<ol type="a">
<li>From the menu, select <strong>Add Segment</strong>.</li>
<li><strong>Destination:</strong> <i>Custer SD</i></li>
<li><strong>Calculate</strong></li>
<li>Let's set our Billings (day 3) departure time to 8:00 AM on May 18th. From the menu, select <strong>Edit Segment Details</strong>.</li>
<li>Change the departure date to <i>May 18</i>.</li>
<li>Change the departure time to <i>8:00 AM</i>.</li>
<li><strong>Save</strong></li>
</ol>

<p>Finally, we'll see what ETA EVTO predicts for our arrival in Custer. Select <strong>Segment Summary</strong> from the menu to review our day 3 itinerary.</p>

![day3summary](https://cloud.githubusercontent.com/assets/26678403/25616456/1192b418-2efa-11e7-830b-4f4c96adef79.PNG)

<p align="center"><i>Plenty of time to enjoy the sounds of pre-rally silence!</i></p>

<p>"Good job, class! One last thing…"</p>
<p>The class smiles in anticipation, waiting for it. They know where I'm going.</p>
<p>"What do we do when we find an app to be useful?"</p>
<p>"<strong>RATE IT IN THE APP STORE!</strong>"</p>
<p>I smiled. These guys really do get it.</p>

<p>"Have fun, and be safe out there! Custer's waiting for you!"</p>

<img width="1174" alt="custer awaits" src="https://cloud.githubusercontent.com/assets/26678403/25546648/378759b6-2c21-11e7-89ec-7ea3f83d48b7.png">

<hr/>

<p><i>Got an idea for a tutorial? <a href="mailto:support@digitalautoguides.com?Subject=Tutorial suggestion">Let us know!</a>
</p>

**Comment by EVGrokker** [comment]
<p>I've just posted an advanced route planning tutorial on our website, using EVTO to plan a three-day trip from the Bay Area to the <a href="http://www.blackhillsparks.org/tesla-black-hills-rally-2017-registration-40-per-car/">Sounds of Silence rally</a> (May 19th-20th) in Custer SD.  The tutorial explores using EVTO to lay out a trip with automatic charging stops, as well as building the trip incrementally in segments, day by day, with overnight stops in Winnemucca NV and Billings MT.</p>
<p>You can also explore other <a href="http://www.digitalautoguides.com/evto-tutorials/#evto_basic">Tips & Tricks</a> and <a href="http://www.digitalautoguides.com/tesla-to-frequently-asked-questions/">FAQs</a> at our website.</p>
<p>We're working hard on the next release of EVTO with some exciting new features coming your way. You can get a sneak peek at our new charger graphics in the tutorial. We implemented this change in response to a suggestion from an EVTO user, and we're delighted with the new look.</p>
<p>As always, if you have any suggestions for EVTO or Tips & Tricks requests, please <a href="mailto:support@digitalautoguides.com?Subject=Suggestions">send them our way.</a> Our goal continues to be providing the indispensable trip planning companion for Tesla owners that's always with you. We welcome your assistance.</p>

**Comment by aesculus** [comment]
Here you are:

http://www.digitalautoguides.com/the-sounds-of-silence-rally

**Comment by EVGrokker** [comment]
The tutorial formatting and layout looks good. 

At this point, all that's left to do is (re)creating the Advanced Tips & Tricks section, and adding the link to the newly posted article, then you can post the marketing blurb.

**Comment by EVGrokker** [comment]
Q: Do you have active threads in the Tesla [S](https://forums.tesla.com/forum/tesla-model-s) and [X](https://forums.tesla.com/forum/tesla-model-x) forums?

If so, I'd suggest posting this blurb there. If not, post it as a new thread.

**Comment by aesculus** [comment]
I have a thread in the X form, looked at it last night. Last post by me was March 26th. No S thread.

Is it me or has TMC really slowed to a crawl? Overall I only had 10 screens of posts since Sunday.  Used to get 10-15 daily.

**Comment by EVGrokker** [comment]
Yes, it seems to have slowed down. I always scan 'New Posts' and read everything across all forums, since their organization doesn't really fit their users.

On the other hand, Teslerati has ramped up by a factor of 2-3. Go figure.

**Comment by aesculus** [comment]
OK. Before we post this you had better make sure this all works in V1.1.5.

You will have to uninstall V1.2 and then install from the App store to ensure you have V1.1.5.

**Comment by EVGrokker** [comment]
Well, it was written under 1.1.4 and 1.1.5. I did recreate it in the current beta to get the latest screen shots. I'll reinstall 1.1.5 from the app store and check back in here after testing it there again.

**Comment by EVGrokker** [comment]
Crap. I think there's a bug in 1.1.5 with Add Segment.

I reinstalled 1.1.5, and restored my Pro version IAP.

At step 3, when I call for **Add Segment**, I get the **Confirm New Trip** dialog, which suggests that I should purchase MTS. Multi-segment trips are part of the Pro IAP. In any event, the only blocking dialog I should see here is one telling me I need the Pro IAP. But I have Pro, and it's been restored as verified by the grayed-out menu item.

To confirm that my Pro upgrade lets me segment a trip, I segmented the Fremont-Elko trip midway, which worked fine.

So either the **Add Segment** menu item is mistakenly pointing to **New Trip** functionality, or the Confirm New Trip dialog is mistakenly being displayed for some other reason.

I could rewrite the tutorial to avoid using Add Segment, but I'd rather not. 

Can you look at the logic to see if you can tell why I'm getting that dialog?

**Comment by aesculus** [comment]
Yeah. It's a bug. It only checks to see if you have MST and there are more than 1 trip. It should bypass that if  you are continuing.

I can create a special release of 1.1.5 I think.

**Comment by EVGrokker** [comment]
What do you mean by a special release? A replacement to the existing release in the store?

**Comment by aesculus** [comment]
Yes. Different build. I think I can do this. Might have to addend something like V1.1.5b. I think I had to do this already for Android when I found a mistake.

**Comment by aesculus** [comment]
I think I can distribute it to you first just to check.

**Comment by EVGrokker** [comment]
Same review time for the App Store (several days)?

**Comment by aesculus** [comment]
Not sure. If it's like the beta no.

**Comment by aesculus** [comment]
That hack won't work for iOS, just Android.

I will have to make a V1.1.6 and that will take probably 2 days to get released.

**Comment by EVGrokker** [comment]
Let me think about it. I have another tutorial in the pipeline that should work OK with 1.1.5. I don't want to sidetrack you. I'll review it and see how it works with the released 1.1.5.

**Comment by EVGrokker** [comment]
I'll send you mail offline to discuss.

**Comment by aesculus** [comment]
The sidetracking is done. There is only 5 more minutes of work left to make 1.1.6

**Comment by aesculus** [comment]
I will probably take 4 hours or more to get you a copy of 1.1.6 to test.  You will then be able to try 1.2 or 1.1.6 in testflight.

**Comment by EVGrokker** [comment]
OK

**Comment by EVGrokker** [comment]
"Life is what happens to you while you're busy making other plans."

**Comment by EVGrokker** [comment]
I just updated the TMC post content above, referencing the new release of 1.1.6. Whenever you have the website links in place, you can post this. I ran the entire tutorial under 1.1.6 with Pro IAP and it worked as expected. :)

**Comment by EVGrokker** [comment]
I'll do a different version of the for the Tesla Forums. There's a discussion going on there as well.

**Comment by EVGrokker** [comment]
_(Suggested Tesla Forums post copy. This could go either in S, X, or both.)_

<p>We've just updated EVTO to version 1.1.6, a maintenance release. Please update to stay current with the latest features. You can download the latest release from the <a href="https://itunes.apple.com/us/app/ev-trip-optimizer-for-tesla/id1124549080?mt=8">App Store</a> or <a href="<a href="https://play.google.com/store/apps/details?id=com.digitalautoguides.teslato">Google Play</a>.</p>

<p>You may have been following <a href="https://forums.tesla.com/forum/forums/4th-annual-sounds-silence-road-trip-black-hills-may-19th-20th-3">a thread here about the upcoming 4th Annual Sounds of Silence Rally</a>. EVTO is a perfect planning companion for "what-if" road trips. So…</p>
<p>I've just posted an advanced route planning tutorial on our website, using EVTO to plan a three-day trip from the Bay Area to the <a href="http://www.blackhillsparks.org/tesla-black-hills-rally-2017-registration-40-per-car/">Sounds of Silence Rally</a> (May 19th-20th) in Custer SD.  The tutorial explores using EVTO to lay out a trip with automatic charging stops, as well as building the trip incrementally in segments, day by day, with overnight stops in Winnemucca NV and Billings MT. You'll find our Sounds of Silence tutorial <a href="http://www.digitalautoguides.com/the-sounds-of-silence-rally">here</a>.</p>
<p>You can also explore other <a href="http://www.digitalautoguides.com/evto-tutorials/#evto_basic">Tips & Tricks</a> and <a href="http://www.digitalautoguides.com/tesla-to-frequently-asked-questions/">FAQs</a> at our website.</p>
<p>We're working hard on the next release of EVTO with some exciting new features coming your way. You can get a sneak peek at our new charger graphics in the tutorial. We implemented this change in response to an excellent suggestion from an EVTO user, and we're delighted with the new look.</p>

<p>As always, if you have any suggestions for EVTO or Tips & Tricks requests, please <a href="mailto:support@digitalautoguides.com?Subject=Suggestions">send them our way.</a> Our goal continues to be providing the indispensable trip planning companion app for Tesla owners.</p>

**Comment by EVGrokker** [comment]
(I don't know if tesla forums supports HTML)

**Comment by aesculus** [comment]
>(I don't know if tesla forums supports HTML)

No, not really. They used to but it's really rudimentary now.

This is what they say today:

> Web page addresses and e-mail addresses turn into links automatically.
Lines and paragraphs are automatically recognized. The <br /> line break, <p> paragraph and </p> close paragraph tags are inserted automatically. If paragraphs are not recognized simply add a couple blank lines.

They used to support other tags and I think they do support bold and italics, no graphics.

**Comment by aesculus** [comment]
I may add sentence or two about working on V1.2 and how it's my version of AP1 > AP2.  Still probably a few weeks out. Still running into nuances that crop up in different scenarios of when and where waypoints are placed. :-(

**Comment by EVGrokker** [comment]
It's your call, but I'd encourage you to shy away from specific commitments to dates or features. I'm hoping that these posts capture the attention of folks who aren't yet your customers. They won't relate to the specifics of where you are in the development cycle. Again, your call.

**Comment by aesculus** [comment]
So is the last edit above ready to post then?  Is there anything unique between the Tesla Forums one and the TMC one?

**Comment by EVGrokker** [comment]
Go back up many posts to the initial TMC post. That one contains a link specific to a Sounds of Silence link on TMC. 

The later one is specific to Tesla forums, with a link into a thread there. If they don't accept HTML you'll have to doctor it anyway. You could also post directly in that thread, or start a new one.

**Comment by aesculus** [comment]
OK.

For the link from the Advanced Tutorials I had two areas predefined:
- Route Planning
- Resource Planning
Is this a Route Planning one? And what do you want the title to be?

**Comment by EVGrokker** [comment]
The title is the same as in the tutorial:

Route Planning: The 'Sounds of Silence' Rally

**Comment by aesculus** [comment]
OK. Here is the updated Tutorials page with turning on Advanced and the link to the rally page.

http://www.digitalautoguides.com/evto-tutorials/

I am thinking the two segment summary images should be much smaller. Maybe 1/2 wide from what they are now.

**Comment by EVGrokker** [comment]
The links look good. I trust your judgement on sizing the images for the best layout appearance.

**Comment by aesculus** [comment]
I made it max at 300 px from 500 px. There is a lot of white space to the sides (not on a phone) but the height is much better.

**Comment by EVGrokker** [comment]
👍

**Comment by aesculus** [comment]
TMC one posted and I found this on the Model X forum and posted there

A bit of a hack for web link stuff but ... 

https://forums.tesla.com/forum/forums/4th-annual-sounds-silence-road-trip-black-hills-may-19th-20th-3#comment-1143414

**Comment by EVGrokker** [comment]
I'm hoping that someone following the rally thread sees your post and says something in the rally thread. If no one does, maybe I will. 🙂

**Comment by aesculus** [comment]
It's a nice tutorial. Hope they will.

I could not find a post on the Tesla S forum

**Comment by EVGrokker** [comment]
_(Suggested TMC post copy for [this thread](https://teslamotorsclub.com/tmc/threads/sound-of-silence-rally-custer-sd-may-19-20.86774/page-2#post-2095395))_

<p>For those interested in attending the Sounds of Silence rally, I want to introduce myself. I'm the developer of the EV Trip Optimizer for Tesla app, available on the <a href="https://itunes.apple.com/us/app/ev-trip-optimizer-for-tesla/id1124549080?mt=8">App Store</a> or <a href="<a href="https://play.google.com/store/apps/details?id=com.digitalautoguides.teslato">Google Play</a> for iOS and Android devices.</p>

<p>EVTO is a perfect planning companion for "what-if" road trips. Our team was inspired by this rally, so we created an instructional tutorial on our website, using EVTO to plan a three-day trip from the Bay Area to Custer.  The tutorial explores using EVTO to lay out a trip with automatic charging stops, as well as building the trip incrementally in segments, day by day, with overnight stops in Elko NV and Billings MT. You'll find our Sounds of Silence tutorial <a href="http://www.digitalautoguides.com/the-sounds-of-silence-rally">here</a>.</p>
<p>You can also explore other <a href="http://www.digitalautoguides.com/evto-tutorials/#evto_basic">Tips & Tricks</a> and <a href="http://www.digitalautoguides.com/tesla-to-frequently-asked-questions/">FAQs</a> at our website.</p>
<p>We're working hard on the next release of EVTO with some exciting new features coming your way.</p>

<p>If you have any suggestions for EVTO or suggestions for future Tips & Tricks, please <a href="mailto:support@digitalautoguides.com?Subject=Suggestions">send them our way.</a> Our goal continues to be providing the indispensable trip planning companion app for Tesla owners.</p>
