### ISSUE TITLE
Formatting Error on iPhone with V1.1.5

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#341]
This was reported by a user in AU. Note the undefined in the third row of the address

![image1](https://cloud.githubusercontent.com/assets/283364/25550569/031463a0-2c2f-11e7-9c32-cadefaecc5a8.PNG)

**Comment by EVGrokker** [comment]
You think the wrapping problem is due to the third address line 'undefined'?

**Comment by aesculus** [comment]
Suspicious. I have asked him for the trip report. This device may be just a bit narrower. He said it was an iPhone SE.  That is 640 (320) wide and iPhone 6's are 750 (375) wide.  So probably running out of room.  I may have to reduce the icon spacing on devices smaller than 350 pixels.

**Comment by EVGrokker** [comment]
Are you able to simulate the screen metrics of various devices in your dev environment? If so, are you able to simulate the wrapping error?

**Comment by aesculus** [comment]
I can for most devices. I will have to run this on the simulator under the mac to test for sure. But I have an old iPhone 4S that has basically the same resolution. I can try it there. These are tiny phone for todays standards.

**Comment by EVGrokker** [comment]
Do you have any tools that tell you the mix of devices the app's being downloaded onto?

**Comment by aesculus** [comment]
Yeah, but one is good enough to need support. :-)

**Comment by aesculus** [comment]
The undefined was a separate issue #345

**Comment by aesculus** [comment]
Fixed in V1.2 (15)

**Comment by aesculus** [comment]
There are some more formatting issues introduced with V1.2.  Some of these have been fixed with V 1.2 (70) for the iPhone SE.  More testing is required to flush any remaining items

**Comment by aesculus** [comment]
More formatting issues resolved for iPhone SE in V1.2 (71). I think I am done but will wait for beta user to report back for sure.
