### ISSUE TITLE
Change Non Supercharger (NREL) Model

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#342]
Right now the model is to show you chargers along your route. The proposal is to show chargers at the current map extent.  There are some issues with the new proposal:
- It would add chargers based on the map extent and take away any chargers not contained at the extent. 
- If it exceed the maximum number of chargers returned by NREL, you might see different chargers if you had zoomed in more. This is especially true if a user toggles on the charger and then pan/zooms to an area instead of pan/zooming first and then selecting the icon
- It might cause bigger date returns and therefore a slower response to the user

**Comment by EVGrokker** [comment]
This could work nicely in concert with #291, the rangefinder enhancement. It would be good to know what sort of performance penalty there would be for adding chargers, especially with a slow data connection.

**Comment by aesculus** [comment]
I have changed the view of the non Tesla chargers (NREL) to be the current map extent, up to 500 miles. It is supposed to be capped at 100, but I think that is 100 locations, not certain.

While I was in there I improved the search feature. It seemed to not return consistent results. Note that if you select Chademo you also get the combo chargers. And I have seen J's returned as well at the same location.

V1.2 (11)

**Comment by EVGrokker** [comment]
What's the rationale for showing chargers far away from the current route?

Here's a screen shot from 1.2.0 (10), which seems like the right behavior:

![nrel route](https://cloud.githubusercontent.com/assets/26678403/25614826/f1b713c2-2ef0-11e7-91d9-cb8f84f955e2.PNG)

**Comment by aesculus** [comment]
The production version of the app shows NREL chargers close (5 miles?) for the current route. Users made the case that if the place they want to visit is not on the route, they cannot see if there are any chargers in the area they can use. They wanted the ability to see chargers anywhere they could select as charging waypoints.

In the production version they would first have to stick a waypoint in the area and then toggle the chargers. This also eats up a lot of cycles because I have the figure they wanted to go there and did all the energy calcs etc to see if they could make it, all so they could just see if there was charger in the area. And this would exacerbate the Auto optimization issue being discussed elsewhere.

**Comment by EVGrokker** [comment]
I'm really skeptical of this approach to adding NREL chargers. I think using PlugShare or knowing of a specific destination charger would be much more likely. If the route's established, and they're not near superchargers, then I can understand wanting to see available charging options along the route corridor within the map extent, but only within a certain distance of the route. If I had the entire US continent onscreen, I don't need to see the entire database. If there's no performance hit for clustering and displaying all of them, then it doesn't matter. But if there's any price to be paid for displaying chargers, I'd vote for limiting it. Same comments apply to #358.

**Comment by EVGrokker** [comment]
I could easily make a case to turn off the NREL database feature. :)

**Comment by aesculus** [comment]
I will give you an example of where this came up, but it was more than this one circumstance:

A user in Aptos, CA wants to go to Bakersfield. They use CHADEMO because the have a 75.  There are two choices in routing:

- Use the app to plot a course via superchargers which takes them about 50 miles out of the way but it's the way Google would do it too, so its not on the route

- Pick a spot off route and plug in a CHADEMO adapter, but which one or where are they in that city?  If they do that then can save a lot of time and distance, even though it's off the SC and Google path.

**Comment by EVGrokker** [comment]
My curmudgeonly response:

Use PlugShare to search the CHAdeMO charger, plug the address into EVTO as a waypoint.

**Comment by aesculus** [comment]
> I could easily make a case to turn off the NREL database feature. :)

Because you like Plugshare. Others don't, including me.  While plugshare may be more complete, it is not that easy to use and if I just want a quick look at what might be possible in an area, the NREL charger feature beats it hands down IMHO providing there is charger listed. So my first pass would be to use EVTO and if I was really determined then go to Plugshare.

**Comment by EVGrokker** [comment]
Actually, it's not because I like PlugShare, it's because I believe that when users go off the tesla grid they know something about where they're headed. Maybe a destination charger at a hotel, Mom's dryer outlet, or a familiar CHAdeMO charger location that they should add as a favorite.

I know I'm not going to win this argument, so we can leave it here. But be prepared for endless whining about "why don't you have this (non-Tesla) charger in your database?".

**Comment by aesculus** [comment]
>  Maybe a destination charger at a hotel, Mom's dryer outlet, or a familiar CHAdeMO charger location that they should add as a favorite.

I agree that once they have somewhere they use often, no matter how they found it, they should capture this in the Favorites.

> I know I'm not going to win this argument, so we can leave it here. But be prepared for endless whining about "why don't you have this (non-Tesla) charger in your database?".

Yep
