### ISSUE TITLE
Reduce end point spikes on consumption chart

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#344]
Often starting and stopping the chart a 0 wastes lots of vertical space. Look at normalizing or removing the static value below the real low points.

**Comment by EVGrokker** [comment]
100% agree. Remove static values.

**Comment by aesculus** [comment]
In thinking about this request there could be an issue. I am all good for taking out the start and end trip 0 points.  The others are normalized out because of my smoothing algorithm.

This should take care of 99% of the issues but I foresee some situation that could cause a mid trip drive to 0.  Most likely not but possible. We will just have to keep an eye out for it.

**Comment by EVGrokker** [comment]
So the graph will be labelled SoC on the left Y axis, and Range on the right Y axis?

Each car would have a different right side Y axis range, depending on model, battery size, condition, SA, PF, and the general weather and altitude conditions affecting that trip, right? 

That would be a very nice feature.

**Comment by aesculus** [comment]
That is the goal.

**Comment by aesculus** [comment]
Here is the consumption chart with most of the dead space removed.

![image](https://user-images.githubusercontent.com/283364/27098086-2d8ffd0e-502b-11e7-9a13-5f798a443c89.png)

**Comment by EVGrokker** [comment]
That's handsome.

**Comment by aesculus** [comment]
I decided to dump the y-axis label for phones to give the chart more room. Can you cover what it is in the help?

BTW you can touch the points on the chart and the two lines to get the values.

![image](https://user-images.githubusercontent.com/283364/27111920-69df65d2-5068-11e7-94cc-8721927f8835.png)
