### ISSUE TITLE
Reassess Destination Minimum SoC after Calculating Segment

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#349]
When a user optimizes a value of minimum SoC for the destination gets returned for MST trips. This does not include some of the finer details calculated on the device such as weather. This issue is the considering updating the minimum destination SoC after calculating the segment to be used for the next calculation.

One issue with this is that it will surprise the user if the values change by no action of their own. It would also cause all downstream segments to be recalculated as the user encounters them. There values of course could change too. 

The biggest changes would be the destination SoC and obviously the next segments origin. And therefore any waypoints including the first charger after the origin.

**Comment by EVGrokker** [comment]
Covered by #10.
