### ISSUE TITLE
Segment Summary missing destination icon

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#351]
v 1.2.0 (9)

ID [hh26m8ieyaqbkptn5uisc4] and the PIN [1234]

![img_0455](https://cloud.githubusercontent.com/assets/26678403/25568042/b0e0e18c-2db7-11e7-927e-727264dfc6b5.PNG)

**Comment by aesculus** [comment]
Fixed in V1.2 (10)

**Comment by aesculus** [comment]
BTW when I loaded this trip it had white pushpins. Once I did something to the trip then it forced the auto calculate so they disappeared.

**Comment by EVGrokker** [comment]
Does that suggest that importing needs to optimize upon loading?

**Comment by EVGrokker** [comment]
This trip has some other issues. I'll start a new issue, since the issue was initially a missing icon.

**Comment by aesculus** [comment]
Yes. I think that is a good conclusion. Remember trips are assigned to cars. Your trip, while going to a place I want to go to, may not be the same after optimizing, if I have a different car model
