### ISSUE TITLE
Segmented trip not properly optimizing

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#352]
v 1.2.0 (9)

ID [hh26m8ieyaqbkptn5uisc4] and the PIN [1234]

**Comment by EVGrokker** [comment]
Trying to optimize the first segment yields a red destination pin at all three segment terminations.

**Comment by aesculus** [comment]
This trip is weird. You were able to do this before?

For some reason it is not returning the first destination back to me in the routing. And because of that, you get no other stops. Now to figure out why.

**Comment by EVGrokker** [comment]
Yes, I've built similar trips before that worked fine. I was just trying to figure out where to dive in with exercising all-in-one optimization and this was the first thing I tried.

Sequence: New Trip, Seattle to Santa Barbara. Require, then segment at the two charger locations.

**Comment by aesculus** [comment]
The question is did you actually make the first destination a supercharger?  Because my logic is failing in that instance. If it was a non supercharger, regardless of if it was a charger or not, it seemed to be OK.

**Comment by EVGrokker** [comment]
Yes. I believe I input the origin and destination, then selected the first supercharger to segment. Then I searched for the Petaluma supercharger as a waypoint, added it and segmented it.

**Comment by aesculus** [comment]
I am making progress. If you try it now it still comes up red for the first segment but the others are OK.

Not sure why it's skipping the first chargers. It may be related but seems to be a different problem.  The other one was specific to having a supercharger as the first destination.

**Comment by aesculus** [comment]
Can you look at this trip? For some reason all the destinations have a larger Min Arrival SoC than what I would expect.  Not sure if you changed this or maybe it was a level of code I shipped out.

Anyway I tried it in V1.2 (10) after resetting the Min Arrival SoC on all the destinations to 15%. Then I optimized and all were OK. I optimized again to be sure and they still said 15%.

Now 15% is not a magic number, but the first was set to 76%.  That really should not have been a problem except for the fact that even adding Woodburn (last SC before Springfield) you would get below 15% arrival SoC and therefore the optimizer decided you could not get there, hence no chargers.

Bringing it down to 70% and I got there by the optimizer adding both Centralia and Woodburn. If I brought it down to 15%, it only added Centralia.

Any change the Min Arrival SoC, Try it.

**Comment by EVGrokker** [comment]
I'm still on 1.2.0 (9), is that where you want me to test it?

**Comment by aesculus** [comment]
Yes. I am sort of curious to see if this is something I introduced in an earlier version and corrected. I can do the same on (10).

How did you create these segments?

**Comment by aesculus** [comment]
But first manually fix the min arrival SoC just to make sure that is working. Then we can recreate the trip to see how the wrong Min Arrival SoC settings might have gotten into these destinations

**Comment by EVGrokker** [comment]
I reset the MSoC at Springfield SC (1st stop) to 20%, and all recalcs flowed as expected. 

Sequence creating this trip (pretty sure this is what I did):
New Trip, Seattle to Santa Barbara, Auto mode. 
Require, then segment at Springfield OR.
Add Waypoint: Petaluma CA (forcing reroute), then segment.

**Comment by aesculus** [comment]
I tried that. This is where the problem occurs. Segmenting that charger caused it to absorb a high Min SoC. Now to find out why.

**Comment by aesculus** [comment]
I will open a new problem for this so we can close this one.

**Comment by aesculus** [comment]
Getting closer. When you added Petaluma was it the SC or just the place?

Probably when you add a new place like that you should probably Optimize again, but only if:
- When you add it, if it's a supercharger stop and green, then no big deal.
- If not a SC, if the next segment is green you are probably OK. If not optimize before you segment

The reason is that the segmentation model now looks ahead to see where your next charger is and makes sure when you get to the new segmented destination, you have enough energy to make it to the downstream charger.  This could essentially reset all the chargers for the trip, as it's doing the collective all over again based on the new, significant routing.

**Comment by aesculus** [comment]
Try this in V1.2 (10)

**Comment by EVGrokker** [comment]
Seems to work adding Petaluma as a SC waypoint.  Will keep playing with it.

**Comment by aesculus** [comment]
Try it with just Petaluma too. You have to adhere to the above rule though.

**Comment by EVGrokker** [comment]
This issue should be revisited as part of the resolution of issue #10.

**Comment by aesculus** [comment]
Version 1.2 (11) may fail here. I am having an issue when a SC is a waypoint. It wants to charge there at 100%.

**Comment by EVGrokker** [comment]
1.2.0 (11)
Model X90D, 5-seater, 20% Minimum SoC

New Trip: Seattle WA - Santa Barbara CA, Auto
Trip is calculated/optimized with 9 supercharger stops, 1120 miles

**Comment by aesculus** [comment]
Did this just not complete?

**Comment by EVGrokker** [comment]
I had to answer a call and accidentally clicked Comment. I will complete it in a moment.

**Comment by aesculus** [comment]
OK. I just tried a MST and got an error. Working on that now.

**Comment by EVGrokker** [comment]
(continuation)

The first time I ran this, I got an error dialog that EVTO couldn't find a route through superchargers. Clicking OK did nothing, had to cancel to escape the dialog.

I tried running it again, and it behaved better this time. I will try running again from the top.

**Comment by EVGrokker** [comment]
New Trip: Seattle WA - Santa Barbara CA, Auto
Springfield OR: Require, then segment.
Add Waypoint: Petaluma supercharger
Optimize Routing

Springfield supercharger shows 77% departure SoC, and Grants Pass shows 7% arrival SoC. Because the trip is segmented at Springfield, this should be reset to user's Minimum Departure SoC (90% in my case).

Petaluma: Require/Segment
Optimize Routing
Petaluma correctly shows 90% SoC upon departure,  but Springfield still shows 77%.

**Comment by aesculus** [comment]
OK. Share this trip with me and I will take a look at it. MST have not been fully flushed out yet.  And this could be related to my SC as a waypoint issue mentioned above.

**Comment by EVGrokker** [comment]
You will need the ID [zu6jn29rw8f36bbwutvhun] and the PIN [1234]
