### ISSUE TITLE
Default value for Reserve SoC

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#353]
When a user first installs EVTO, the initial default settings should be selected in such a way that EVTO's SoC predictions will match the car's predictions as closely as possible.

Specifically, the current default for Reserve SoC is 15%, but we believe that the car uses a 20% threshold to begin showing yellow arrival.

The proposal is to set the default Reserve SoC to 20%, to match the car SoC color coding.

We can add explanatory text in Help and T&Ts to encourage experienced users to reset Reserve SoC to a value that more closely matches their risk tolerance.

**Comment by aesculus** [comment]
We should do some research to verify this. What the battery shows on the car may not be the same as the energy (SoC) chart on the car. But I suspect it is the same.

And 20% is really high too. But I understand the need to keep it as close the car initially.

**Comment by aesculus** [comment]
> Specifically, the current default for Reserve SoC is 15%, but we believe that the car uses a 20% threshold to begin showing yellow arrival.

On a recent trip the car was quite happy to have me arrive with 14% SoC to a charger. I am not sure what criteria it uses.
