### ISSUE TITLE
Trip metadata included in exported/shared trips

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#354]
I don't know what details are included when exporting a trip, but I'm guessing that it's only the origin/charger/waypoint/destinations and segment details like departure time and date. Hopefully the data is contained in an XML format so that a parser can process it and skip unfamiliar chunks.

A couple of proposals with respect to exported trips:
- Maintain a schema version number within the exported data to allow additions or revisions to the bundled data
- Include the trip creator's car metrics (car type, battery type, options) for forensic analysis when needed.

**Comment by aesculus** [comment]
It's in CSV format.  You can see it by going to Segment Details > Export Data.  It brings up a window with the segments turn by turn directions and data.

But now I just discovered an error. Because we turned off all copying a while back, you cannot copy this data either. :-(

**Comment by aesculus** [comment]
The copy capability for this panel only is restored in V1.2 (10)

**Comment by aesculus** [comment]
The metadata was added in V1.2 (22)
