### ISSUE TITLE
Reverse order of Charger Types listed in picker

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#355]
When filtering a prospective waypoint or destination by Charger Type, the available charger levels are shown in ascending order, from Level 1 up to Level 3, then Tesla Superchargers.

Since we're optimizing for typical users, whom we expect would mostly be filtering for Superchargers when using this feature, the proposal is to reverse the order of the choices in the picker so that the highest power/most preferable chargers would be displayed first.

**Comment by aesculus** [comment]
Would No Charger still be the first on the list?

**Comment by aesculus** [comment]
I made this change in V1.2 (10) but left the No Charger as the first choice and then flipped the others.  This needs to be thoroughly tested. I did a quick check by adding a waypoint as a charger and it seemed fine.

**Comment by EVGrokker** [comment]
Yes, the default selection would still be No Charger as the first choice.

**Comment by EVGrokker** [comment]
>This needs to be thoroughly tested. I did a quick check by adding a waypoint as a supercharger and it seemed fine.

The only way that this could be a problem with previously saved trips would be if a charging waypoint stored an index into the picker, rather than the returned charger type. The other possible problem could be with Favorited waypoints having associated charger type. Assuming you're storing the type, not a list index, you should be OK.

**Comment by aesculus** [comment]
It always stores the value so it should not be a problem. But then there is my programming. :-)

**Comment by EVGrokker** [comment]
Even if a user reported a problem, we'd just tell them to reset the charger type. Not fatal, not a big deal.
