### ISSUE TITLE
Updated Segment Time Does Not Always Reset Weather Forecast

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#356]
On my Android it seems to work with one caveat. 

This is what I did: 
- Created a new trip 
- Weather at origin at 7am said 57 F which agreed with DS website. DS said at 12 am temp was 61F 
- Changed Edit Segment Details to 2pm. 
- Went to origin, still said 57F 
- Selected origin Edit then Save 
- Checked origin temp again it was 87F - agreed with DS forecast within 1 degree 
- Went back to Edit Segment Details and changed time to 2AM - Save 
- Checked origin temp and it was 60F - again agreeing with DS 

So somehow this Edit Segment Details did not change the forecast period, but after that it did. Not sure why yet. I saw this before but I thought I had fixed it. It seemed like it worked every other time correctly

**Comment by aesculus** [comment]
From a beta user

> However, this time when I created a new trip for testing, I changed the DATE ONLY first.  The weather data was correct.  Then I changed the TIME, and all weather data went to 00:00 in the morning.

>I then did the same thing, except this time changing only the time -- correct weather.  Then changed the date, and all weather went to midnight again.

>So it is something about changing BOTH time and date that is tripping it up.

**Comment by aesculus** [comment]
So the issue is when we went to time machine forecasts instead of getting 48 hours of forecasts we now get 24 hours. The app is set up to receive 48 and when it went to the next day and did not find a forecast slot, it defaults to midnight of the forecast date for it's weather.

The app needs to be updated so it only expects weather from midnight to the next midnight of the forecast day.

**Comment by EVGrokker** [comment]
What happens when user sets a date farther out than available forecast data? Do you apply some average weather penalty, or none at all?

**Comment by aesculus** [comment]
>What happens when user sets a date farther out than available forecast data? Do you apply some average weather penalty, or none at all?

I have no friggin idea what Dark Sky returns when the date is beyond their range.

**Comment by aesculus** [comment]
V1.2 (18) fixes these two issues:

- Weather is now to closest hour at waypoint arrival
- Fixed bug that used midnight weather for the next days forecast
