### ISSUE TITLE
Enhancement: Long press on Outlet button displays Filter Chargers dialog

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#359]
We're moving towards a UI model adding long-press interactions to various buttons.

This is a proposal to add a long-press to the outlet button, which would display the Filter Chargers dialog, currently accessed from the Plan menu. The long-press would be an additional means of opening the Filter Chargers dialog.

**Comment by aesculus** [comment]
Implemented in V1.2 (27);
