### ISSUE TITLE
Redesign waypoint order editing to utilize drag 'n drop

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#36]
For a given route listed in a Trip Summary panel, user should be able to drag any origin, waypoint or destination pin to any new location within the list. That means a waypoint may become an origin or a destination.

Upon reordering, a popup would ask whether user wants the trip optimized (waypoints scrambled to minimize travel distance) or simply recalculated using existing waypoint order. For example, swapping Origin and Destination, then clicking 'Optimize' would reverse the route.

**Comment by aesculus** [comment]
With the changes we made to do touch holds on the waypoints in the Segment Browser, this is no longer possible to use touch and drag to reorder the waypoints. Users will have to move them with the arrows.
