### ISSUE TITLE
NREL filtering not working properly

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#360]
1. Create a trip Seattle - Santa Barbara CA, Manual
2. In the Filter Chargers dialog, enable _Tesla HPWC_ only
3. Press the outlet button to enable the NREL overlay
4. East of Tacoma WA and Puyallup WA, zoom in on the '2' overlay near Lake Tapps until the individual chargers are shown
5. Note that a 'J' and a 'C' are displayed, neither of which are enabled. Should be 'H' only.

**Comment by aesculus** [comment]
H is not working yet. And H does not apply to NREL chargers. Need to figure out how to deal with that.

**Comment by aesculus** [comment]
See issue #332

**Comment by EVGrokker** [comment]
Duplicate of #332.
