### ISSUE TITLE
Filter Chargers dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#361]
v 1.2.0 (10)
- The in-app help text for the Filter Chargers dialog is missing the charger type letter designations.
- The header preceding the list of charger types should read simply **Charger Types:**
- The order of the charger types in the help text should match the order in the Filter Chargers dialog. 

Here's how it should look:

<table style="width:100%">
  <tr>
    <th>Symbol</th>
    <th>Type</th> 
    <th>Level</th>
  </tr>
  <tr>
    <td>≡</td>
    <td>SAE J1772 Combo</td> 
   <td>3</td>
  </tr>
  <tr>
    <td>C</td>
    <td>CHAdeMo</td> 
   <td>3</td>
  </tr>
  <tr>
    <td>H</td>
    <td>Tesla HPWC</td> 
   <td>2</td>
  </tr>
  <tr>
    <td>J</td>
    <td>J 1772</td> 
   <td>2</td>
  </tr>
  <tr>
    <td>=</td>
    <td>NEMA 14-50</td> 
   <td>2</td>
  </tr>
  <tr>
    <td>–</td>
    <td>NEMA 5-20</td> 
   <td>1</td>
  </tr>
  <tr>
    <td>–</td>
    <td>NEMA 5-15</td> 
   <td>1</td>
  </tr>

</table>

**Comment by aesculus** [comment]
It did not look very good with the borders so I left them off

![image](https://cloud.githubusercontent.com/assets/283364/25648356/cce298fc-2f7f-11e7-81e8-06e45659622a.png)

**Comment by aesculus** [comment]
Can you review this in V1.12 (11)

**Comment by EVGrokker** [comment]
I would remove **Charger types:** so that the text reads:

…Use this dialog to filter which charger types are enabled for display:

**Symbol Type Level**
…

**Comment by aesculus** [comment]
Done in V1.2 (12)

**Comment by EVGrokker** [comment]
<h3>Filter Chargers</h3>
<p><i>Specify charger categories to be displayed on the Plan screen</i></p>

<h4>Tesla-specific chargers</h4>
<p>Select Tesla Superchargers, HPWC locations, or both. Enabled Tesla chargers are displayed by toggling the lightning bolt button on the Plan screen.</p>

<h4>Generic chargers</h4>
<p>Select one or more Level 3, 2 or 1 charger categories. Enabled generic charger categories are displayed by toggling the outlet icon on the Plan screen.</p>

**Comment by aesculus** [comment]
Updated in V1.2 (46)
