### ISSUE TITLE
Long trip optimized with added waypoint misses Supercharger opportunity, 

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#365]
v 1.2.0 (11)
This is similar to the Utopia-Gillette trip, adding Kearney, which works well under this release.

However, here's another long trip where adding a waypoint misses a charging opportunity.

New Trip: Fremont CA - Casper WY (auto)
Add Waypoint: Denver CO
Optimize Routing

Denver shows a departing SoC of 41%, and an arrival SoC in Cheyenne of -7%.

There's a Loveland CA supercharger right on the route that optimization didn't add.

**Comment by aesculus** [comment]
This is a good test case.

**Comment by aesculus** [comment]
Hmm. I did not have this issue. Worked great for me as an S85D 19".

![image](https://cloud.githubusercontent.com/assets/283364/25964114/97aad1da-3638-11e7-882c-569c028f439a.png)

**Comment by aesculus** [comment]
Version 1.2 (64) does what you would expect. This is with a MX90D

![image](https://user-images.githubusercontent.com/283364/28655135-64e33c5e-724e-11e7-9f33-0072cb100196.png)
