### ISSUE TITLE
Obsolete route option displayed after adding waypoint

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#371]
v 1.2.0 (14)

Extra route option displayed after adding waypoint, optimizing.

New Trip: Seattle WA - Santa Barbara CA, Auto
Springfield OR: Require, Segment.
Add Waypoint: Tesla Superchargers, Petaluma Supercharger
Zoom into Sacramento - San Francisco - San Jose area. Note that inactive leg on I-680 in east Bay is shown. (See screen shot below).
Petaluma Supercharger: Segment.

Trip is now in three segments, but the I-680 leg is still displayed as an orphan.

Selecting Optimize Routing from the menu, error dialog is shown. This is a valid route with available superchargers.

![extrarouteshown](https://cloud.githubusercontent.com/assets/26678403/26033592/8e6b09a6-386c-11e7-93ea-53533a9fe5dc.PNG)

**Comment by aesculus** [comment]
I need you to share this trip so I can see what it did.

**Comment by EVGrokker** [comment]
I tried recreating this trip to share it with you, but EVTO never concludes the Finalizing stage.

New Trip: Seattle WA - Santa Barbara CA, Auto (see attached screen shot). 

I can Cancel, but the new trip is not active. Tried twice with the same results.

![finalizing](https://cloud.githubusercontent.com/assets/26678403/26035973/a60e6212-3892-11e7-94c8-36b7903737f9.PNG)

**Comment by aesculus** [comment]
OK. I will try it here. There must be an error and that is why you cannot send it to me.

**Comment by aesculus** [comment]
Wait.  This is an active trip no?  It has three segments.  So you cannot share the trip prior to the optimize?  How is it loading?

**Comment by EVGrokker** [comment]
I'm trying to start from scratch with New Trip.

**Comment by aesculus** [comment]
OK. But I really want the trip you have the error on.

**Comment by EVGrokker** [comment]
I understand that. The currently loaded trip, under the dialog, does not exhibit the error, so I was trying to recreate the conditions, then share the trip.

**Comment by aesculus** [comment]
Ah. OK.

**Comment by EVGrokker** [comment]
OK, got it. I wiped data, closed the app, restarted and was able to recreate the orphan segment. Also, I notice that I have 5-seater checked in My Cars, but that does not show in your trip metadata summary.

>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, Rear CC: 0, Bat Life: 100 
Device Info: iPhone; CPU iPhone OS 10_3_1 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (14) 
Location: Unknown 
Trip: Springfield Supercharger, [liiid1wgrrmhvefjxfdqm]

**Comment by aesculus** [comment]
OK. I have the trip and see that it hangs up. Now I can dissect it.

**Comment by aesculus** [comment]
Couple of quick observations:
- Once I had it not get the elevation data when I added a waypoint. Need to figure out why and also do a better job when that error occurs
- If I delete the hinge stop (merge) then it fails. 
- If I completely remove the charger and optimize it works
- If I completely remove the charger and then add it back in again as required, but not segmented it works.
- Then if I segment at that point it fails with no known superchargers.
- And if I merge after this error it works OK after optimizing. Not sure why it was OK here but not the first time at the top of this list.
- After I removed the Springfield charger I added a Eugene, OR stop in (no charger) and then optimized.  That worked OK too.

So besides the other issues, it appears I don't handle a supercharger as a hinge destination.

**Comment by aesculus** [comment]
Making some progress here. Found a few bugs actually. And in the end your concept of restarting the optimization when the hinge destination is a charger will probably be dealt with when this is all said and done.

If I am lucky I might have a test for your by tomorrow night but more likely sometime Tuesday.

**Comment by aesculus** [comment]
Can you take another crack at this with V1.2 (22)?

**Comment by EVGrokker** [comment]
Following the steps outlined in the initial comment still leaves an orphan leg on I-680.

**Comment by aesculus** [comment]
I am not seeing this behavior. As check I imported the trip outlined above and optimized.

After optimization can you select the the trip segments in order too. This should cause a recalc which should refresh that ghost segment.

**Comment by EVGrokker** [comment]
I just tried recreating the trip, and I still see the behavior. Selecting individual segments does not cause the ghost segment to disappear.

**Comment by aesculus** [comment]
Ok. I will snag the iphone and see if I can duplicate it there.

**Comment by EVGrokker** [comment]
v 1.2.0 (42)
I still see the orphan leg sometimes before individual segments have been finally optimized, but by the time the trip route is up to date it's not shown. I'm closing this issue as changes to the Updating Trip status dialog sequence will affect this. We can reopen if necessary after that work is complete.
