### ISSUE TITLE
Progress Dialog missing step, starts over

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#372]
v 1.2.0 (14)

New Trip: Fremont CA - Custer SD, Auto

2 issues: 
1) Step 3 'Calculating Energy' is not displayed in black while step 4 is executing (see screen shot below).
2) Progress dialog is shown twice. After the progress dialog closes, it reopens and goes through the steps again. The second time step 3 does turn black before step 4 executes.

![missingstep](https://cloud.githubusercontent.com/assets/26678403/26033701/c42dda0e-386d-11e7-8519-b2eebd4cbd3f.PNG)

**Comment by aesculus** [comment]
Can you share this trip?


Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by aesculus** [comment]
This was fixed in V1.2 (22) and the issue of it appearing is addressed in Issue #363

**Comment by aesculus** [comment]
I am closing this since we now have a new progress dialog.
