### ISSUE TITLE
My Cars dialog rearranges itself after displaying leading to faulty touches.

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#373]
v 1.2.0 (14)

I've noticed this odd behavior for some time, finally figured out what's happening.

When the My Cars dialog is opened, the order is:
o Model S
o Model X
Notice that Active Car picker and Car Name field are missing.

After a moment, it rearranges to:
Active Car:
(picker)
Car Name:
(text field)
o Model S
o Model X
etc.

Besides being disorienting, the initial display is up long enough to allow an erroneous tap on 'Model X' which ends up in the Active Car picker instead.

Recommend not displaying that dialog until it's fully constructed.

**Comment by aesculus** [comment]
I'll take a look.

**Comment by aesculus** [comment]
Can you try this in V1.2 (22). I attempted to fix it so the dialog does not display until it is ready.

**Comment by EVGrokker** [comment]
That works.
