### ISSUE TITLE
Possible to filter Google addresses by continent?

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#381]
Currently, global results are being returned from searches.

Example:

**New Trip**: _Origin_: Seattle WA
**Destination**: `Oxford` (looking for Oxford Suites in Portland OR) returns hits in the UK and Australia
**Destination**: `Oxford Portland` returns hits in the UK, in addition to the three plausible hits in the US.

Is it possible to filter out results that are not on the same continent? Or maybe by distance?

**Comment by aesculus** [comment]
I only see this after I have done some UK searches. I will look into it. I hope it's not tied to the developer ID.

**Comment by aesculus** [comment]
I think this is this issue https://github.com/aesculus/EVTO-App-Feedback/issues/29 I closed too early.

**Comment by aesculus** [comment]
For North America geography I have set a bias. The other geo's I can't because they are not contained within a fixed rectangle.

Updated in V1.2 (19)

**Comment by EVGrokker** [comment]
I'm still seeing hits from the UK in 1.2.0 (22) using the search term 'Oxford Portland'. The one I want comes up first, but it would be preferable to not see any outside the continent.

**Comment by aesculus** [comment]
This is as good as it gets. Google has outstanding requests to make it firm, more than just biased, but they have been there since 2015.
