### ISSUE TITLE
New Trip dialog, error entering/selecting origin

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#385]
New Trip:
- Select Tesla Superchargers 
- Destination:  Gardenerville NV Supercharger
- Origin: Fremont CA. No pop-up list of results displayed. 

It appears that you are applying the supercharger filter to the origin as well as the destination.

**Comment by aesculus** [comment]
OK. I see that it should only apply the filter to the destination, not both.

While it appears to work, I could not get it to accept the supercharger at the origin.

And now I have another problem. 

For some odd reason it did not calculate an appropriate route for this trip when I did do it correctly. So now I have another issue to look at too. :-(

**Comment by aesculus** [comment]
In V1.2 (27) only the destination will search for superchargers.
