### ISSUE TITLE
Trip Summary enhancement: Add overall SoC graph

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#387]
Lots of design details to work out for trips with multiple segments and many waypoints. Probably require hiding some level of detail: perhaps offering a zoomed-out view of segment nodes only, and a zoomed-in view per segment with waypoint nodes, like current SoC tab.

**Comment by aesculus** [comment]
What about an icon on the SoC chart that toggled between segment and trip view?  For segment view it would be like it is today. 

For trip view I would show it as a bar chart with no distances on the bottom, just a count of destinations. It would be a stacked bar with arrival and departure SoC shown for each bar.

**Comment by EVGrokker** [comment]
Conceptually, that would be a compact method to add another layer/view to the chart.

**Comment by aesculus** [comment]
Implemented in V1.2 (63)

**Comment by EVGrokker** [comment]
Closing this issue as a duplicate of #489.
