### ISSUE TITLE
Implement Google Maps URL scheme to enable 'Export to Google Maps' on iOS, Android

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#39]
iOS has a system-level feature allowing one app to call another with arguments. By constructing a special URL, the app can invoke Google Maps with the currently loaded route, with multiple waypoints, allowing realtime navigation. 

See Google documentation at https://developers.google.com/maps/documentation/ios-sdk/urlscheme
Sample code in both Objective C and Swift is provided.

**Comment by EVGrokker** [comment]
Here's an article about implementation on Android
http://stackoverflow.com/questions/17915901/is-there-an-android-equivalent-to-google-maps-url-scheme-for-ios#17916883

**Comment by EVGrokker** [comment]
Here is a link to the URL scheme for Apple maps on ios devices. This only allows point-to-point routing, unlike Google maps which allows routes with waypoints. Might be useful at some point. 

https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html

**Comment by aesculus** [comment]
Should we close this? I don't want to encourage users to bypass the Tesla navigation system.  EVTO is supposed to compliment the Tesla features, not replace them.
