### ISSUE TITLE
Create Trip Status and Rating Dialog on Current Trips Panel

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#395]
While it would be ideal to contain the trip status (plan or taken) and the trip rating within the Trips Edit dialog, there is not enough room without scrolling the panel. Since scrolling causes user issues it is better to have a dedicated to this probably less often used feature. Therefore the app needs a separate dialog for changing the trip status and rating.

**Comment by aesculus** [comment]
Implemented in V1.2 (23)

**Comment by aesculus** [comment]
I updated the look a bit with some trip characteristics in V1.2 (24):

![image](https://cloud.githubusercontent.com/assets/283364/26560352/aea75c2e-446a-11e7-9da5-6802c1baf528.png)

**Comment by EVGrokker** [comment]
v 1.2.0 (26)
This is functional, but I'd like to see the layout use the same design as the Segment Summary dialog. I've mocked up a design and made a few tweaks:

- Change dialog title to 'Trip Status'
- Change layout of metrics to conform to Segment Summary dialog style
- Change drama icon to gavel icon for Trip Rating


![edittripstatus](https://cloud.githubusercontent.com/assets/26678403/26679716/28226176-468b-11e7-98ff-3c486ef87b14.jpg)

**Comment by aesculus** [comment]
I updated the dialog for 1.2 (27). Note I did not include the times because for MST that would not make much sense without dates and there is not enough room for both.

![image](https://cloud.githubusercontent.com/assets/283364/26705513/83163d5e-46eb-11e7-8bbf-646d536d60a4.png)

**Comment by aesculus** [comment]
I could put in the start date/time if you think it would be needed. I can then sense the SS when the format does not work for some particular country. :-)

**Comment by EVGrokker** [comment]
I do think it makes sense to include at least the departure date, maybe appended to the first line:

San Francisco CA 2017-06-03

**Comment by aesculus** [comment]
I needs to be on a separate line because of length of trip name

**Comment by aesculus** [comment]
![image](https://cloud.githubusercontent.com/assets/283364/26737439/fe3403a2-477e-11e7-99de-7944e6ec624a.png)

Added in V1.2 (28)

**Comment by EVGrokker** [comment]
Nice.
