### ISSUE TITLE
Change Power Factor Slider Color to Neutral When 0

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#396]
To point out when the user has selected a non default power factor ( != 0 ), the slider will be colored. But when it is neutral or zero, it should be the default gray color.

**Comment by aesculus** [comment]
Implemented in V1.2 (23)

**Comment by EVGrokker** [comment]
v 1.2.0 (25)

I'm not seeing any change in the appearance of the Power Factor slider when moved away from 0.

**Comment by EVGrokker** [comment]
We need an explanation of the meaning of the PF slider for help and tuts. Is it a multiplier?

**Comment by aesculus** [comment]
> I'm not seeing any change in the appearance of the Power Factor slider when moved away from 0.
Same here. Not sure what I did to screw this up between builds. I will look. Same with Speed Adjust.

>We need an explanation of the meaning of the PF slider for help and tuts. Is it a multiplier?
When the speed factor is introduced it will change scope slightly.  I propose that the new pf changes the overall power consumption by 10% per unit.  (ie a 1 would be 110% or 1.1 times total energy used).

**Comment by EVGrokker** [comment]
Why not have the displayed value be the actual multiplier? 

It would be easier for you to scale the returned value than explain to users how 1 equals 10. Much easier to explain that '10' represents a 10% PF.

**Comment by aesculus** [comment]
OK. I can divide by 10 under the covers. :-)

**Comment by aesculus** [comment]
In the other thread I stated I did not implement the colors in My Cars yet, just Edit Trip Details.

**Comment by EVGrokker** [comment]
v 1.2.0 (26)
The slider does change color for non-zero values, but negative values change the slider to tones of blue, rather than green. The model should be consistent with the Speed Adjust slider: changes that will positively impact range should be colored green, changes that negatively impact range should be red.

Suggest PF values < 0 cause the slider to be colored green.

**Comment by aesculus** [comment]
The colors are now consistent in V 1.2 *27)
