### ISSUE TITLE
New Trip: Cancelling destination removes Destination Charger Type picker

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#397]
1.2.0 (23)

New Trip: 
**Origin**: _Seattle WA_
**Destination**: _Santa Barbara_, but before touching Calculate, clear field by touching 'X'. 

Destination Charger Type picker is no longer displayed.

**Comment by aesculus** [comment]
I'll check it out on the iPhone. Does not do this on the iPad.

**Comment by aesculus** [comment]
Does this still do this in V1.2 (28)?

**Comment by EVGrokker** [comment]
Appears to be ok.

**Comment by aesculus** [comment]
good
