### ISSUE TITLE
Segment Origin Inspector - enhancements

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#398]
The Origin waypoints of a segment are displayed differently, with a trip time and distance for the entire segment. This enhancement builds on that difference, refining the appearance of the waypoint inspector for segment origins:

1. Add the segment destination below the origin.
2. Prefix the origin with the segment number.
3. Add an Arrival time
4. Delete the Departure SoC (redundant with battery image)
5. Align data for improved readability

![segmentsummary](https://cloud.githubusercontent.com/assets/26678403/26549348/73cdcff8-442d-11e7-84e3-e0303060fcfe.jpg)

**Comment by aesculus** [comment]
Is this for all waypoints or just the origin? And if for all how do you want the destination laid out?

What about hinge waypoints?

**Comment by EVGrokker** [comment]
This would be for all origins, including hinge points beginning a new segment. You were already treating these differently than the mid-segment waypoints, so it's less dramatic a change than it may seem at first glance. It's  building on what you already had.

**Comment by aesculus** [comment]
What do you want the destination pins to contain?

**Comment by EVGrokker** [comment]
I think the destination pin display is fine as is.

**Comment by aesculus** [comment]
I made the following changes in V1.2 (26):
- Changed the label to Departure
- Removed the Charge To item
- Added the Arrival item
- Relocated the battery down a bit

At this point I cannot easily fix the columnar formatting. That will have to wait another day.

I was also uncertain at to where or why to put the segment number. It would seem better on the waypoint name vs the address.  Also your sample was one of those ghost superchargers that is not really a supercharger in the db.

![image](https://cloud.githubusercontent.com/assets/283364/26618319/db910daa-458e-11e7-949e-301cd66a0005.png)

**Comment by EVGrokker** [comment]
This looks good.

**Comment by EVGrokker** [comment]
If we add a segment number prefix, it should be before the name and just after the heart. So it would be 

[heart] 1: Springfield Supercharger

That helps establish that this waypoint inspector is formatted differently from leg stops. If you'd rather not add it, that's fine.

**Comment by aesculus** [comment]
OK. That makes more sense. The first proto had it on the address.

Do you really think we need the number? I think it's redundant and ruins your clean look. I suspect they know what segment they by the title in the dialog.  Maybe it should be in the dialog title if anywhere.

**Comment by EVGrokker** [comment]
Nuke the number.

**Comment by aesculus** [comment]
I like Nukes, oh wait. That's someone else's line. :-)
