### ISSUE TITLE
Add Waypoint dialog: Enable Destination field upon initial display

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#399]
To reduce any confusion about the difference between the Name and Destination fields, I propose that you set the focus to the Destination field upon displaying this dialog. This will make it clear that the user is to enter the destination first. They may choose to set the Charger Type first, but because the focus was initially in the Destination field they'll know to go back to it.

**Comment by aesculus** [comment]
Added in V1.2 (24)

**Comment by aesculus** [comment]
I had to alter this slightly in (26). It turns out if it's populated the the cursor jumps to the end and it cuts off long names.  So I am only setting focus now for new dialogs.
