### ISSUE TITLE
Add radio to Edit Details for time to be arrival or departure

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#4]
Proposed Pro Feature.  See google maps. Arrive by / Depart at

**Comment by EVGrokker** [comment]
I would add that the ability to edit departure time should also be a Pro feature. Standard app feature would be planning from now, with ability to recalculate to current conditions.

**Comment by aesculus** [comment]
This should probably be done in the new Trip Edit dialog and not in the segment edit details.  Also not sure how to do this with a MST.  I could so some sort of hack, but your really need to plan the whole trip and then figure out how much time it takes, then take the end time and subtract the trip time. Trouble with this method is that it does not account for weather differences etc which could alter trip time.

**Comment by aesculus** [comment]
This is not really doable without a huge amount of resources and probably huge Google API costs too. You would have to route the trip and do all of the calculations. Then see when you arrived and how much time it took. Then you would have to go back and reset the start time based on the expected arrival time minus the trip time. Even then it would not be correct because weather could be different and that in turn could cause the trip time to change and now you are chasing your tail.

This is another great idea that is just not worth it in the large scheme of things.

**Comment by aesculus** [comment]
Well it appears the masses want this feature. Probably not going to be able to do Arrive By.

**Comment by aesculus** [comment]
Implemented in V1.2 (101) without Arrive By.
