### ISSUE TITLE
Implement Google Maps URL scheme to send route to car's browser

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#40]
I have no friggin' idea how that's done, but it would be a well-received feature.

**Comment by EVGrokker** [comment]
This appears to be a dead-end, as displaying maps.google.com on the car's browser does not show current location, and therefore would not be able to follow a route. However, the feature is still a useful concept to export an EVTO segment to a desktop browser.

**Comment by aesculus** [comment]
Keep this open. I can probably add some javascript to keep the location. TBD

**Comment by aesculus** [comment]
Should we close this?  I am still not certain of the purpose with sending a map to the browser in the car.  The car's navigation system will be the primary map for a journey. EVTO will just provide the waypoints (ie the user adds the events with the calendar and has the Tesla app configured appropriately). If not the user will have to manually enter the waypoints.
