### ISSUE TITLE
Trip Segments dialog: Long-press action enhancement

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#403]
For the Trip Segments dialog (invoked by touching the folded map icon), I propose that a long-press on a segment does two things:
- Closes the Trip Segments dialog
- Opens the Segment Summary dialog on the associated segment.

The intent is that after switching to the Segment Summary dialog, touching outside of it to dismiss it simply returns the user to the map display. There's no modality that tries to return to the Trip Segments dialog.

**Comment by aesculus** [comment]
Implemented in V1.2 (26)

**Comment by EVGrokker** [comment]
I'm not sure how long of a long press you've implemented, but it seems too quick. I just touched a segment to switch to it and the Segment Summary comes up. I like the feature, but a longer press would be good before activating.

**Comment by EVGrokker** [comment]
Before you change it, how long is it currently? It seems more reasonable the longer I play with it.

**Comment by aesculus** [comment]
750 ms.  I can change that.  The Globe is only using 500 ms.

**Comment by EVGrokker** [comment]
The response time seems inconsistent, but this is hardly a showstopper. Let's leave it alone for now, and I'll document it in the context help.
