### ISSUE TITLE
Main Menu: Consolidation possibilities

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#404]
As discussed, it would be good to try to consolidate some items in the main menu. There are currently 18 items in the production version of the app (beta version has an extra 'Wipe Data' command). 

By comparison, the Plan menu has 11 items.

Here's what I've got so far, with suggestions/comments in the right column. If we did what's suggested below, we'd reduce the count by 3, and increase the Plan menu by 1, for a new ratio of 15 in the Main menu and 12 in the Plan menu.

<table>
  <tr>
    <th>Item</th>
    <th>Comment</th> 
  </tr>
  <tr>
    <td>Car Model/Name</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>Plan a Trip</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>Current Trips</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>Settings</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>My Cars</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>Maintain Favorites</td>
    <td>This could be moved to the Plan menu, since it's about waypoints and chargers, not trips.</td> 
  </tr>
  <tr>
    <td>Purchase Pro Version</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>Multi-Trip Subscription</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>Restore Purchases</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>Archived Trips</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>Compare Trips</td>
    <td>Could this be made part of the Current Trips menu?</td> 
  </tr>
  <tr>
    <td>Feature Matrix</td>
    <td>Feature Matrix, Tutorials and FAQs are all accessible from the same DAG web page. These could be combined into a single item. Perhaps 'Online Resources', with an explanation in the Help menu of what's available online?</td> 
  </tr>
  <tr>
    <td>Getting Started</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>Tutorials</td>
    <td>Feature Matrix, Tutorials and FAQs are all accessible from the same DAG web page. These could be combined into a single item.  Perhaps 'Online Resources', with an explanation in the Help menu of what's available online?</td> 
  </tr>
  <tr>
    <td>FAQs</td>
    <td>Feature Matrix, Tutorials and FAQs are all accessible from the same DAG web page. These could be combined into a single item.  Perhaps 'Online Resources', with an explanation in the Help menu of what's available online?</td> 
  </tr>
  <tr>
    <td>Feedback Report</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>Help</td>
    <td>(no change)</td> 
  </tr>
  <tr>
    <td>About EVTO</td>
    <td>(no change)</td> 
  </tr>
</table>

**Comment by aesculus** [comment]
EVGrokker wrote:
> Maintain Favorites This could be moved to the Plan menu, since it's 
> about waypoints and chargers, not trips.
Maybe. But currently the Plan menu is about a Trip and not Trips in 
general, nor complementary things to trips.
> Compare Trips Could this be made part of the Current Trips menu?
I would think it could be. It's actually the same underlying data. We 
would have to move the help over of course.
> Feature Matrix Feature Matrix, Tutorials and FAQs are all accessible 
> from the same DAG web page. These could be combined into a single 
> item. Perhaps 'Online Resources', with an explanation in the Help menu 
> of what's available online?
That should be easy to do.

-- 
Chris Couper

**Comment by EVGrokker** [comment]
>> Maintain Favorites This could be moved to the Plan menu, since it's
 about waypoints and chargers, not trips.

>Maybe. But currently the Plan menu is about a Trip and not Trips in
general, nor complementary things to trips.

All waypoint and charger actions are currently in the Plan screen. So it follows that managing them as favorites would be in the same area.

**Comment by aesculus** [comment]
I guess I am ok with it.  Do you want to move it now or after we redesign the Favorites feature?

**Comment by EVGrokker** [comment]
I'd propose moving it now, as part of the next major release.

**Comment by aesculus** [comment]
Moved in V1.2 (27)

**Comment by EVGrokker** [comment]
Compare Trips still needs to be relocated to within the Current Trips menu, so I'll leave this open for now. I'll also create an issue to review the help text for both the Main and Plan menus.

**Comment by aesculus** [comment]
I moved Compare Trips into the Current Trips menu and removed it from the main menu in V1.2 (34).

**Comment by aesculus** [comment]
We need to figure out the correct name for Compare Trips. See issue #425
