### ISSUE TITLE
Destination Waypoint - Split battery display

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#406]
This doesn't look right.

The inspector says that the arrival SoC is 39%, with 20% reserved for local use.

If I add that up, that would be 59%, which doesn't match the displayed combination of yellow and blue.

If I assume there's 39% total battery upon arrival, with 20% earmarked for local use, that matches the graphics, but the '39%/20%' looks wrong.

Suggestions: 
- The first number should be the arrival SoC without the reserve number. 
- The second number should be the reserve.
- I'd suggest using a '+' instead of a slash: 19% + 20%
- I'd suggest making the font for the SoC smaller, perhaps the same size as the other bolded numbers to the left.

![destinationreserve](https://cloud.githubusercontent.com/assets/26678403/26658842/923181d8-4621-11e7-8523-5b01642265f4.PNG)

**Comment by aesculus** [comment]
I'll check out the levels.

>The first number should be the arrival SoC without the reserve number.
The second number should be the reserve.

The original idea was the SoC you wanted 39% plus the 20% that was going to be added on top. So that is what you are asking for no?

Looks like I need to adjust the battery up a bit

**Comment by aesculus** [comment]
This has been fixed in V1.2 (27). For some reason any character but the "/" results in the battery not formatting correctly. So for now it stays.

I had to fix the Segment Details panel too. Also it might be off 1% because of some rounding I had to do but who is going to notice? (someone probably)

![image](https://cloud.githubusercontent.com/assets/283364/26664796/16c7f770-4649-11e7-9bc9-52878064ca8f.png)

**Comment by EVGrokker** [comment]
I'd still like to see the font size of the SoC numbers below the battery reduced to match the size of the other metrics, for example Arrival Time. 

The slash makes the sequence hard to read. If '+' doesn't format well, here are a couple of other alternatives:
49% • 20% (bullet)
49% | 20% (pipe)
49% ⋮ 20% (vertical ellipsis)

**Comment by aesculus** [comment]
I posted the picture before I changed the font.

I will continue to investigate alternatives to the "/" character but anything else I try screws up the battery fill. Not sure why that is.

**Comment by EVGrokker** [comment]
I'm guessing that the problem with the separator overlaying the battery image is a z-ordering problem. I assume that the text is html; how about switching to an even smaller font for the separator to reduce its layout space requirements?

**Comment by aesculus** [comment]
It's totally weird. Makes no sense.

**Comment by aesculus** [comment]
I added a space before and after the '+' and it seems to now be OK. Go figure.

![image](https://cloud.githubusercontent.com/assets/283364/26706220/883c4968-46f0-11e7-92c5-5525ffdf2b4b.png)

**Comment by EVGrokker** [comment]
The layout of the split battery numbers looks good, but the relative size compared to the battery and other text in the dialog still looks large.

I think if you formatted it to match the text size of the other bolded text in the Waypoint Inspector it would fit more comfortably.

**Comment by aesculus** [comment]
The placement of the battery is a bit obtuse. Kind of changes based on the amount of content.  It could probably be fixed but that would take some time and I have other fish that need frying.

I can make the font the same size but there are a few worries:
- The font on the other items is dependant on Google. If they change the API then the font could change too.
- Changing the font actually impacts the battery position so it's not trivial (see sample below).  But I can do it if we are sure we want it changed.
- Aesthetically I like the larger numbers (it was even larger before). I think those numbers are important and so being bigger may make them easier to see

The image below is with a matched font size with the screwed up battery. If you like this size better I will make the change.

![image](https://cloud.githubusercontent.com/assets/283364/26736770/5d063308-477c-11e7-9485-7f48466984d4.png)

**Comment by EVGrokker** [comment]
Independent of the implementation issues, I like the rendering in the image above. I would be in favor of that.

**Comment by aesculus** [comment]
> I like the rendering in the image above

The smaller font then?

**Comment by EVGrokker** [comment]
Yes for the smaller font.

**Comment by aesculus** [comment]
Implemented in V1.2 (28)

![image](https://cloud.githubusercontent.com/assets/283364/26737895/f8d9767e-4780-11e7-94f3-2dc9b5d241f0.png)

**Comment by EVGrokker** [comment]
Lovely.
