### ISSUE TITLE
Add Context Help to Segment Summary, Trip Summary dialogs

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#407]
I'd like to add the '?' button to both the Segment Summary dialog and the Trip Summary dialog.

Because it's possible that the list will overflow the available space, the best approach would be to locate the '?' button in the top left corner. I vaguely recall that this presented problems in another dialog, but that would be optimal.

**Comment by aesculus** [comment]
Ii could probably be added in the gray header section. Upper left corner?

![image](https://cloud.githubusercontent.com/assets/283364/26684444/e3545fac-469b-11e7-89dd-ec3fef279948.png)

**Comment by EVGrokker** [comment]
Upper left is most consistent with placement in other dialogs (lower left).

The alternative would be changing the design of this panel to be like My Cars with a scrolling interior that would allow a lower left placement in the static panel, but I'm guessing that's less desirable from an implementation perspective.

**Comment by aesculus** [comment]
Since I changed the structure I think it could be done in the lower part but a lot more work. Also I don't think it would get noticed down there in it's own little window now that we have moved everything to the top.  I will do the upper left in line with the title.

**Comment by aesculus** [comment]
You are all set for this and the trip summary too.

![image](https://cloud.githubusercontent.com/assets/283364/26697890/7fe7bb26-46c8-11e7-9f54-1f1a6f509927.png)

**Comment by EVGrokker** [comment]
See issues #409 and #410 for html Help text.
