### ISSUE TITLE
Segment Browser dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#409]
<h3>Segment Browser</h3>
<p><i>Review a segment's statistics and waypoints.</i></p>

<p>The <strong>Segment Summary</strong> dialog may be invoked from the Plan menu, or by long-pressing a segment name in the <strong>Trip Summary</strong> dialog.</p>

<p>The segment's individual waypoints are listed with recommended charging time (when applicable), elapsed trip time upon arrival, cumulative miles driven upon arrival, and the predicted SoC (State of Charge) of the battery upon arrival and departure from the waypoint. The recommended charging level is shown in striped gold.</p>

<p>Touching an individual waypoint will open the <strong>Waypoint Inspector</strong>, where further details about an individual waypoint may be reviewed.</p>

<p>The summary section at the bottom provides a snapshot overview of the segment's details:</p>
<ul>
<li>Departure and Arrival times (ETD and ETA)</li>
<li>Predicted energy requirements (kWh)</li>
<li>Predicted average efficiency (Wh/mile or Wh/km)</li>
<li>Predicted average speed (mi/hr or km/hr)</li>
<li>Predicted EVTO Quality Index ('Q' factor)</li>
<li>Total charging time required en route (lightning bolt icon)</li>
<li>Total elapsed time (stopwatch)</li>
<li>Total segment distance (mi or km)</li>
<li>Total 'behind the wheel' driving time (car icon)</li>
</ul>

<h4>Important note about times:</h4>
<p>The departure times (ETD) and arrival times (ETA) for charging stops and waypoints are always displayed in the local time zone, which may not be the same time zone that you are in when planning or reviewing a segment.</p>

<h4>Important notes about charging before beginning a segment:</h4>
<ul>
<li>EVTO assumes an initial SoC matching your <i>Default Origin SoC</i> (specified in <strong>Settings</strong>) upon departure. An individual segment's <i>Default Origin SoC</i> may also be edited from the <strong>Edit Segment Details</strong> dialog, accessed from the Plan menu.</li>
<li>EVTO assumes that after the conclusion of a segment, you will recharge to your <i>Default Origin SoC</I> before beginning your next segment or trip.</li>
</ul>

**Comment by EVGrokker** [comment]
Ready for your review.

**Comment by aesculus** [comment]
> Predicted average efficiency (Wh/mile)

and km

> EVTO assumes that after the conclusion of a segment, you will recharge to your Default Origin SoC before beginning your next segment or trip.

Actually if I can get the optimizer to work correctly, this only applies to destinations with chargers.  Without a charger EVTO will attempt to approach or depart with extra charging to ensure a smooth transition.

So if a user wants to wait before or after their destination, EVTO should be able to find the optimal charging situation in both segments. If they don't want to wait they should state the destination has a charger and EVTO will work as you stated above.

**Comment by EVGrokker** [comment]
Let's wait until you have the optimizer behavior functional as you want it, then I'll revise the text accordingly.

**Comment by EVGrokker** [comment]
Updated with note about time zones in response to #335.

**Comment by aesculus** [comment]
Updated in V1.2 (32)

**Comment by EVGrokker** [comment]
Updated with EVQI (phi) factor.

**Comment by EVGrokker** [comment]
Updated with 'Q' factor

**Comment by aesculus** [comment]
Updated in V1.2 (46)

**Comment by aesculus** [comment]
Am I supposed to be swapping text for icons? I think it's better not to embed them in sentences. IE I like it the way it is.

**Comment by EVGrokker** [comment]
No embedded icon. Text intended to be included as is.
