### ISSUE TITLE
Redesign the Trip Details panel

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#41]
Reconstruct this panel to be expanding/collapsing details on an individual waypoint. The list initially presents as the route’s waypoints, with their pin icons friendly names and battery, as you have now. I’ll call this the waypoint title bar. Touching waypoint title bar expands the view so that the waypoint title bar is at the top of the display, and the bottom 80% is either the deep data view, or the map. Use a tabbed interface to switch between data and waypoint's map location.  It would be important that the phone-scale rendering be sensible in portrait mode, so there may be some finicky layout constraints for the deep data view, but I think it could be done.

Touching the title bar again collapses the deep view of the waypoint, and allows you to scroll the list to select a different waypoint.

**Comment by EVGrokker** [comment]
After reviewing email discussion, I now realize that the top panel can be swiped left/right to display adjacent waypoint information. Suggest changing title bar in this panel to reflect that. For example, **Stanwood (3/9)** would mean that the Stanwood waypoint is the third waypoint of 9 (including Origin and Destination) in this trip. Also, highlighting the selected waypoint in the list below would provide visual feedback. This would be an acceptable short-term fix, but the initial request to redesign this panel stands.

**Comment by EVGrokker** [comment]
Attached are two waypoint information view from the Trip Details, portrait and landscape.

Note that in portrait mode, the data display simply doesn't work.

In landscape mode, the data display is much better. There's a lot of white space in the column alignment, I think it should be possible to squeeze everything into portrait mode. Perhaps using icons instead of text labels would free up enough space.

**TYPO:** footer text should read "… Verify with your car's navigation system." (add possessive apostrophe) 

![img_0294](https://cloud.githubusercontent.com/assets/26678403/24331099/2ef5aa54-11e2-11e7-9d3e-082a35eccb38.PNG)

![img_0295](https://cloud.githubusercontent.com/assets/26678403/24331100/387b3cba-11e2-11e7-97d6-7aa509b42d9d.PNG)

**Comment by aesculus** [comment]
I just noticed the top of the header seems to merge with the phone status stuff. Is this an artifact of the screen capture or is this happening on this panel?

**Comment by EVGrokker** [comment]
It's acceptable. Once you start scrolling the panel the phone status stuff goes away.

**Comment by aesculus** [comment]
But it should not be this way.  Is it on all panels or just this one?  This is what it is supposed to look like with the status stuff above the EVTO titles and navigation buttons.

![img_0051](https://cloud.githubusercontent.com/assets/283364/24764819/6e6051dc-1aaa-11e7-9e32-8a82a8855723.PNG)

**Comment by EVGrokker** [comment]
Try it on your iPhone, completely different layout.

**Comment by aesculus** [comment]
OK. It ran out of the house before I could get hold of it. :-)

I will make sure it looks like the iPad.

**Comment by aesculus** [comment]
>Note that in portrait mode, the data display simply doesn't work.

OK. This is an artifact of trying to do Responsive Design but wrong.  The values get dropped below the labels in portrait mode so it's hard to visualize.

This same issue is found on the Current Trips panel. Take a look there too. It's not quite as bad but probably needs a redesign too.

**Comment by aesculus** [comment]
This was updated in V1.2 (80)
