### ISSUE TITLE
Trip Browser dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#410]
<h3>Trip Summary</h3>
<p><i>Review a trip's statistics and segments.</i></p>

<p>The <strong>Trip Summary</strong> dialog is displayed by touching the folded map icon on the Plan screen.</p>

<p>The trip's individual segments are listed. Touching an individual segment name makes it the active segment. Long-pressing the active segment name invokes the <strong>Segment Summary</strong> dialog, providing an in-depth overview of the active segment's details.</p>

<p>The summary section at the bottom provides a snapshot overview of the trip details:</p>
<ul>
<li>Total trip mileage (mi or km)</li>
<li>Number of segments</li>
<li>Number of waypoint stops</li>
<li>Predicted energy requirements (kWh)</li>
<li>Predicted average efficiency (Wh/mile or Wh/km)</li>
<li>Predicted average speed (mi/hr or km/hr)</li>
<li>Predicted average EVTO Quality Index ('Q' factor)</li>
<li>Total charging time required en route (lightning bolt icon)</li>
<li>Total 'behind the wheel' driving time (car icon)</li>
</ul>

<h4>Important note about times:</h4>
<p><i>Departure times (ETD) and arrival times (ETA) are always displayed in the individual segment's local time zone, which may not be the same time zone that you are in when planning or reviewing a trip.</i></p>

<h4>Important notes about charging before beginning a trip:</h4>
<ul>
<li>EVTO assumes an initial SoC matching your <i>Default Origin SoC</i> (specified in <strong>Settings</strong>) upon departure.</li> 
<li>The <i>Default Origin SoC</i> for a trip's initial segment may be edited from the <strong>Edit Segment Details</strong> dialog, accessed from the Plan menu.</li>
</ul>

**Comment by EVGrokker** [comment]
Ready for your review.

**Comment by aesculus** [comment]
> Predicted average efficiency (Wh/mile)
and km

**Comment by EVGrokker** [comment]
Edited.

**Comment by aesculus** [comment]
Implemented in V1.2 (28)

**Comment by EVGrokker** [comment]
v 1.2.0 (28)

I just noticed that the word 'mileage' is used instead of the more agnostic 'distance' which would be appropriate for both US and metric.

><p>The summary section at the bottom provides a snapshot overview of the trip details:</p>
><ul>
><li>Total trip <strike>mileage</strike> distance (mi or km)</li>
></ul>

**Comment by aesculus** [comment]
Updated in V1.2 (29)

**Comment by EVGrokker** [comment]
Updated in response to #335.

**Comment by aesculus** [comment]
Updated in V1.2 (32)

**Comment by EVGrokker** [comment]
Updated formatting of note about times

**Comment by aesculus** [comment]
Updated in V1.2 (39)

**Comment by EVGrokker** [comment]
Updated with EVQI phi factor

**Comment by EVGrokker** [comment]
Updated with 'Q' factor.

**Comment by aesculus** [comment]
Updated in V1.2 (46)
