### ISSUE TITLE
Plan menu: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#411]
<p>The Plan screen is where trips are created and edited. A trip may be composed of a single segment, with a simple one-way route from an origin to a destination. Or, a trip may contain two segments that go to a destination, then return to the origin, known as a round trip.<sup>†</sup></p>
<p>EVTO also supports multi-segment trips<sup>†</sup>, where the destination of one segment automatically becomes the origin of the next segment. EVTO visualizes each segment of a multi-day road trip, complete with pre-planned charging stops along the way.</p>
<p class="caveat"><sup>†</sup>Requires Pro version IAP</p>
<hr />

<h4>Tab Overview</h4>
<h5>Plan tab</h5>
<p>The Plan tab displays a map overview of your trip. Pinch to zoom into a specific area of your route, or touch and drag to scroll the map. Buttons along the right edge of the map are used to control the map display. Refer to the <strong>Map Buttons</strong> section below for details.</p>
<hr />

<h5>Consumption tab</h5>
<p>This chart estimates instantaneous energy consumption along your route. The dashed horizontal line predicts average efficiency across the segment. The solid horizontal line indicates rated efficiency for your car. Touch either line to display its value.</p>
<hr />

<h5>SoC tab</h5>
<p>This chart depicts both State of Charge (SoC) and remaining range as you progress along your route. On phones, nodes are labeled with the waypoint's initials.</p>
<p>The graph displays both SoC (left vertical axis) and rated range (right vertical axis) throughout the segment. Touch a node, or anywhere along the graph line, for predicted SoC.</p>
<p>Touch the bar chart button in the lower left to toggle to a display of SoC at each stop during the entire trip. Segments are divided by vertical dashed lines. Touch the node button in the lower left to return to a display of the current segment.</p>
<hr />

<h4>Map Buttons</h4>

<h5><img class="panel_help_icon" src="css/images/gray/881-globe.png" />Zoom to Route</h5>
<p>Touch the globe button to zoom and center the map on the current segment.</p>
<p>Long-press the globe button to zoom to all segments of the current trip.</p>

<h5><img class="panel_help_icon" src="css/images/gray/852-map.png" />Trip Browser</h5>
<p>When a trip includes multiple segments, a red numeric badge on the map button indicates the number of segments in the current trip. The active segment is displayed on the map in blue, along with its waypoints. Inactive trip segments are displayed in gray, with gray origin and destination pins, and dots representing waypoint locations.</p>
<p>Touch the map button to to open the Trip Browser. Touch an individual segment to make it the active segment. Long-press on a segment to open the Segment Browser. Touch outside the Trip Browser dialog to close it.</p>

<h5><img class="panel_help_icon" src="css/images/gray/947-target-reticle2.png" />Location</h5>
<p>Touch the crosshairs button to center the map on your current location, displayed as a pulsating blue dot. Touch the crosshairs button again to disable display of your current location. The blue dot location updates to your current location as you move, but the map does not automatically reposition to your location. To quickly find yourself on the map, toggle location off, then on, recentering the map on your current location.</p>

<p>EVTO's Location feature requires access to Location Services in your device's Privacy settings. If touching the location button does not display your current location:</p>
<ul>
<li>Check your device's <strong>Settings | Privacy | Location Services</strong>, confirming that EVTO is allowed location access.</li>
<li>Check EVTO's <strong>Main | Settings</strong> dialog, confirming that the <strong>Location Services</strong> checkbox is enabled.</li>
</ul>
<p>Displaying your current location consumes additional device power.</p>

<h5><img class="panel_help_icon" src="css/images/gray/856-lightning-bolt.png" />Tesla Chargers</h5>
<p>Touch to toggle the display of Tesla Supercharger locations on the map.</p>

<h5><img class="panel_help_icon" src="css/images/gray/935-power-socket.png" />Other Chargers</h5>
<p>Touch to toggle the display of Level 1, Level 2 and Level 3 chargers locations. Use the Filter Chargers dialog to enable which charger locations are displayed.</p>

<hr />

<h4>Pins</h4>
<p>Trip segments are marked with an Origin pin, a Destination pin, automatic charging stops added by EVTO, and any additional waypoints you've added manually.</p>
<hr />
<h5>Origin Pins</h5>
<ul style="list-style-type:none" class="icon_list">
<li><img src="pictures/map_icons/marker-icon-blue-sm.png"/>Origin pins are blue with a white interior. An origin's SoC is established by the default SoC Reserve in the <strong>Settings</strong> dialog. After a trip is created, the Origin SoC may be edited in the <strong>Edit Segment Details</strong> dialog.</li>
</ul>
<hr />

<h5>Destination Pins</h5>
<ul style="list-style-type:none" class="icon_list">
<li><img src="pictures/map_icons/marker-icon-green-checker-sm.png" />Destination pins for the final segment of a trip are shown with a black and white checkerboard interior, with arrival SoC indicated by the pin color described below.</li>
<li><img src="pictures/map_icons/marker-icon-green-checker-grey-sm.png" />Destination pins for intermediate trip segments are shown with a gray and white checkboard interior, with arrival SoC indicated by the pin color described below.</li>
<li><img src="pictures/map_icons/marker-icon-white-checker-sm.png" />Destination pins are white indicating this segment needs to be recalculated.</li>
</ul>
<hr />

<h5>Pin Colors</h5>
<ul style="list-style-type:none" class="icon_list">
<li><img src="pictures/map_icons/marker-icon-red-checker-sm.png" />Red: Arrival SoC predicted to be at or below 5%.</li>
<li><img src="pictures/map_icons/marker-icon-yellow-checker-sm.png" />Yellow: Arrival SoC predicted to be between 5% and the specified Reserve SoC. The default Reserve SoC is defined in Settings, or may be edited for individual waypoints.</li>
<li><img src="pictures/map_icons/marker-icon-green-checker-sm.png" />Green: Arrival SoC predicted to be at or above your specified Reserve SoC. The default SoC is defined in Settings, or may be edited for individual waypoints.</li>
</ul>
<hr />

<h5>Waypoint Pins</h5>
<p>Waypoint pins may represent points of interest (POIs) or charging stops, with the pin color representing predicted SoC upon arrival at the waypoint as described in Pin Colors above.</p>
<hr />

<h5>Charging Waypoints</h5>
<p>Charging waypoints are shown with an interior key:</p>
<ul style="list-style: none;">
<li><strong>C</strong>&nbsp;&nbsp;CCS Adapter</li>
<li><strong>E</strong>&nbsp;&nbsp;CEE Adapter</li>
<li><strong>H</strong>&nbsp;&nbsp;Tesla HPWC Level 2</li>
<li><strong>J</strong>&nbsp;&nbsp;J1772 Level 2</li>
<li><strong>M</strong>&nbsp;&nbsp;CHAdeMO Level 3</li>
<li><strong>R</strong>&nbsp;&nbsp;Roadster Adapter</li>
<li><strong>S</strong>&nbsp;&nbsp;Tesla Supercharger</li>
<li><strong>-</strong>&nbsp;&nbsp;&nbsp;&nbsp;Level 1 Charger</li>
<li><strong>=</strong>&nbsp;&nbsp;&nbsp;Level 2 Charger</li>
<li><strong>&#x2261;</strong>&nbsp;&nbsp;&nbsp;Level 3 Charger</li>
</ul>
<hr />

<h5>Automatic Waypoints</h5>
<ul style="list-style-type:none" class="icon_list">
<li><img src="pictures/map_icons/charger-marker-green-sm-a.png" />Automatic waypoints are charging waypoints selected by EVTO, symbolized with a small (A). Green charging stops indicate that the arrival SoC should be above your SoC Reserve specified in <strong>Settings</strong>.</li>
<li><img src="pictures/map_icons/charger-marker-red-sm-a.png" />EVTO predicts an arrival SoC of 5% or less. Add a charging stop en route, or increase the initial SoC for the segment. </li>
<li><img src="pictures/map_icons/charger-marker-yellow-sm-a.png" />EVTO predicts an arrival SoC less than your preferred SoC Reserve specified in <strong>Settings</strong>. Consider a slight speed adjustment during this leg to reach the charging stop with adequate reserve energy.</li>
<li><img src="pictures/map_icons/charger-marker-grey-sm-a.png" />EVTO identified this as a potential charging stop during initial optimization, but determined it to be unnecessary during final route review. If conditions change while en route, consider it as an provisional charging stop along your route. If you prefer to ignore it, simply delete it.</li>
</ul> 
<hr />

<h4>Plan Trip menu items</h4>
<h5><img class="panel_help_icon" src="css/images/gray/746-plus-circle" />New Trip</h5>
<p class="menu_item_summary">Create a new trip</p>
<p>Enter an origin by name or address, your current location, or select from saved Favorites. Add a destination, and you're on your way. Origins and destinations may be entered by name (Disneyland), address (1600 Pennsylvania) or latitude and longitude (37.4874054,-121.9413378).</p>
<p>Specifying a Destination Charger Type of 'Tesla Superchargers' before entering a destination will filter the search results, making it easy to quickly select a supercharger by name.</p>
<p>Enabling the 'Plan as a round trip' checkbox<sup>†</sup> plans the trip in two segments, with the destination of the first segment becoming the origin of the second segment, returning to your starting point.</p>
<p class="caveat"><sup>†</sup>Requires Pro version IAP</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/858-line-chart-toolbar.png" />Add Segment<sup>†</sup></h5>
<p class="menu_item_summary">Displays the Add Segment Details dialog</p>
<p>Add a new continuation segment to your current route.</p>
<p class="caveat"><sup>†</sup>Requires Pro version IAP</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/704-compose.png" />Edit Segment Details</h5>
<p class="menu_item_summary">Displays the Edit Segment Details dialog</p>
<p>Customize each segment of your trip, including departure date and time, initial SoC at the segment origin, and energy reserved at the destination for local travel. </p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/704-compose.png" />Edit Trip Details</h5>
<p class="menu_item_summary">Displays the Edit Trip Details dialog</p>
<p>Customize your trip details, including the name, departure date and time, estimated payload, climate control. You may also specify a Speed Adjust factor, informing EVTO that you typically drive above or below the posted speed limits. Specify a Power Factor to inform EVTO that this trip will use more power than normal, for example when towing a trailer.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/popups/709-plus.png" />Add Waypoint</h5>
<p class="menu_item_summary">Inserts a waypoint into the current trip segment.</p>
<p>Enter a PoI or an address, or touch the heart to display a list of previously saved Favorites. Selecting a favorite populates the name, address and charger type fields. You can also specify a minimum stop time at the waypoint, and the minimum SoC you'd like to arrive with. If the minimum SoC is achievable, EVTO will try to adjust previous charging stops to accommodate the SoC target specified.</p>
<p>To use a frequently-used address stored as a Favorite, touch the black heart and your waypoint details will be loaded in the dialog. Personalize the waypoint description by editing the name field at the top of the Edit Waypoint dialog, for example 'Home'. Select the charger type, if any, then Save to close the dialog.</p>
<p>To make a frequently-used address a Favorite choose any waypoint pushpin and toggle the heart icon in the upper left of the popup. You can then reuse these waypoints as described above.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/popups/759-refresh-2.png" />Refresh Auto Chargers</h5>
<p class="menu_item_summary">Re-evaluates auto charger selection</p>
<p>EVTO recalculates your route at the specified departure time, factoring in any newly added waypoints, along with the latest weather forecasts to determine any required auto charging waypoints. If you have disliked any Superchargers (by touching the 'thumbs down' button in the Charger Inspector), they will be avoided, if possible, when planning your route.</p>

<h5><img class="panel_help_icon" src="css/images/gray/852-map.png" />Trip Browser</h5>
<p class="menu_item_summary">Displays the Trip Browser dialog</p>
<p>Review your trip segments in list form. Touch an individual segment to make it the active segment. Long-press on a segment to open the Segment Browser. Touch outside the Trip Browser dialog to close it.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/748-heart.png" />Maintain Favorites</h5>
<p class="menu_item_summary">Displays the Maintain Favorites dialog</p>
<p>Unfriend favorite waypoints or give a disliked supercharger location another chance.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/popups/789-map-location.png" />Segment Summary</h5>
<p class="menu_item_summary">Displays the Segment Browser dialog</p>
<p>Review your segment origin, waypoints and destination in list form. Touch a waypoint to see estimated arrival time, drive time, distance, average speed, wind and weather conditions, along with the estimated SoC upon arrival. A segment overview concludes with total stats for the entire segment.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/popups/786-browser.png" />Segment Details</h5>
<p class="menu_item_summary">Displays the Segment Details dialog</p>
<p>Review a detailed analysis of each waypoint along your segment route. Slide left and right to change the currently displayed waypoint data, or touch a waypoint in the list. A map inset shows a closeup view of the selected waypoint.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/popups/851-calendar.png" />Add to Calendar</h5>
<p class="menu_item_summary">Displays the Add to Calendar dialog</p>
<p>EVTO will add an entry to your device calendar for the origin, each waypoint, and the destination from your current trip segment. With your device calendar synced to your car, you can select the waypoint address on the car's display and the navigation system will create a route to that waypoint. This features requires the Tesla app for your mobile device, with calendar access enabled.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/popups/798-filter.png" />Filter Chargers</h5>
<p class="menu_item_summary">Displays Filter Chargers dialog</p>
<p>Filter charger types displayed when electrical outlet button is toggled.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/739-question.png" />Help</h5>
<p class="menu_item_summary">Displays this help panel</p>
<p>You are here!</p>

**Comment by EVGrokker** [comment]
Ready for your review.

**Comment by aesculus** [comment]
> EVTO does not automatically track your current location.

The blue dot does move, but the map will not pan.

> EVTO's database is typically updated weekly.

Can we remove this? I don't want this to become an issue - like now - when it might not happen weekly for any particular reason.

>An origin's SoC is established by the default SoC Reserve in the Settings dialog

Need to clarify the settings value is used when the trip/segment is created and can be changed for each segment after using the Edit Segment Details

>Specify a Power Factor to inform EVTO that this trip will use more power than normal, for example when towing a trailer.

more or less power than normal

**Comment by EVGrokker** [comment]
HTML updated in response to your suggestions.

**Comment by aesculus** [comment]
Updated in V1.2 (29)

**Comment by EVGrokker** [comment]
Updated Consumption and SoC tab descriptions.

**Comment by aesculus** [comment]
Updated in V1.2 (42)

**Comment by EVGrokker** [comment]
v 1.2.0 (42)
Multiple edits to bring things up to date.

**Comment by aesculus** [comment]
Applied in V 1.2 (43)

**Comment by EVGrokker** [comment]
v 1.2.0 (43)

Note that in the Automatic Waypoints section, the second list item is intended to be prefixed with an image of a red automatic waypoint.

**Comment by aesculus** [comment]
Updated in V1.2 (44).

Did you want to describe the rare gray auto waypoint here too? What about yellow?

**Comment by EVGrokker** [comment]
Can you provide a rough draft of them, and I'll review and edit?

**Comment by aesculus** [comment]
[img of yellow automatic waypoint]A yellow automatic waypoint indicates that EVTO predicts the charging stop is reachable, but just under your limits. A slight adjustment to your driving speed or a change in weather may affect you arriving within your stated goals.

[img of gray automatic waypoint]A gray automatic waypoint indicates that EVTO chose this as a potential charging stop but after additional consideration felt it was optional. You may delete these after optimization if you are comfortable with the routing.

**Comment by EVGrokker** [comment]
Ready for your review.

**Comment by aesculus** [comment]
Updated in V1.2 (45).

You did not want to offer to suggest they remove the grey ones if they feel comfortable?

**Comment by EVGrokker** [comment]
I was trying to describe it in such a way that doesn't make it sound like a bug. "We considered it, realized that it was on the edge, so we're leaving it there as an FYI in case you need it."

It seemed more like we should be suggesting they can ignore it if they don't need it. It's provisional, and we kept it just in case they needed to know about it.

Text updated. See what you think of the revision.

**Comment by aesculus** [comment]
I like that better because we don't want them to keep a stop if they don't plan on going there. If they are on the margin then they can leave it and stop if they want to. If not, they can delete it.

**Comment by EVGrokker** [comment]
v 1.2.0 (63)

Updated to describe addition of the bar chart and node buttons in the SoC chart.

**Comment by aesculus** [comment]
Applied in V1.2 (64)

**Comment by aesculus** [comment]
We

**Comment by EVGrokker** [comment]
Comment:
The behind-the-scenes intelligence of how and when to recalculate has improved dramatically since 1.x. Users who were used to having to invoked optimization probably learned the reflex.

I have some proposed modifications to both the menu title and the help text below. Comments welcome.

<hr/>

A couple of options for the Plan menu function description:
- Optimize Routing (current value)
- Reoptimize Routing
- Evaluate Routing

With respect to the Help text within the Plan menu help:
>Displays an Optimizing Route popup
EVTO recalculates your route at the specified departure time with the latest weather forecasts. If you have Disliked any Superchargers by touching the 'thumbs down' icon in the map waypoint popup, they will be avoided if at all possible when planning your route.

How about:
Review Routing for Additional Optimizations
EVTO reevaluates your route at the specified departure time with the latest weather forecasts. If you have applied significant modifications since the route was initially created, the route may need to be recalculated. By default, EVTO recalculates routes automatically when necessary. Use this menu item to invoke an immediate recalculation.

**Comment by aesculus** [comment]
>The behind-the-scenes intelligence of how and when to recalculate has improved dramatically since 1.x. Users who were used to having to invoked optimization probably learned the reflex.

There are two things that go on in the server:
- It looks for superchargers to fill in gaps (auto chargers)
- It minimizes charging times between segments
The rest happens on the device.  So the device is a heavy play in optimization and where most of the logic (well at least from a functional perspective) is going on.

I was thinking that the menu title maybe should be something like:
- Add Auto Chargers
- Update Auto Chargers
- Assign Auto Chargers

Using the Optimize term implies that you MUST do this to have an optimal route, when it's only necessary if you want the auto chargers (which would cause a re routing if changed) refreshed.

Having said this, most would probably do a optimize if they were expecting to use any superchargers.  This came up when a user had a completely manual route that could not use superchargers.  It broke the server optimizer (still working on why) but it could never actually benefit from optimizing because there were no possible superchargers in the path of the route.

**Comment by EVGrokker** [comment]
>Using the Optimize term implies that you MUST do this to have an optimal route, when it's only necessary if you want the auto chargers (which would cause a re routing if changed) _refreshed_.

'Refreshed' seems to be the key word. 

How about: 
- Refresh Auto Chargers
- Refresh Charging Stops
- Refresh Optimal Chargers

**Comment by aesculus** [comment]
I am leaning towards:
- Refresh Auto Chargers

**Comment by aesculus** [comment]
I changed the menu and help to "Refresh Auto Chargers" in V 1.2 (82)

I also updated the icon to be this 
![image](https://user-images.githubusercontent.com/283364/29834283-35522c06-8ca3-11e7-8cd5-63573e1be9b6.png)

**Comment by aesculus** [comment]
The help text for Refresh Auto Chargers should be updated.

**Comment by aesculus** [comment]
I updated the charger adapter labels in the help text with the new values

**Comment by EVGrokker** [comment]
Updated 'Refresh Auto Chargers' section in initial post.

**Comment by aesculus** [comment]
I made some small edits and implemented it in V1.2 (82)

**Comment by EVGrokker** [comment]
v 1.2.0 (82)

The header section for Refresh Auto Chargers appears twice in Help (see screenshot below).

Also, I did another edit on the accompanying text to refer to 'thumbs down' as a button, not an icon, and some other minor edits.

<hr/>

![img_0908](https://user-images.githubusercontent.com/26678403/29930199-f3c7e4b8-8e2a-11e7-8b72-fd2047ae57a7.PNG)

**Comment by aesculus** [comment]
Updated in V1.2 (83)

**Comment by aesculus** [comment]
Updated with new subscription info

**Comment by aesculus** [comment]
Cleaned up this help to reflect all of the changes to date.
