### ISSUE TITLE
Main menu: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#412]
<h3><img class="panel_help_icon" src="pictures/icons/icon-small.png" />Main Panel</h3>

<h4>Main screen overview</h4>
<p>The EV Trip Optimizer for Tesla (EVTO) helps you plan and optimize long-range travel in your Tesla. In addition to traditional route-planning features, EVTO evaluates weather conditions, elevation changes and charger availability along your route, displaying your predicted power consumption during the trip.</p>
<p>Your car’s characteristics and your driving style provide additional fine-tuning of predicted power consumption. With EVTO, you can plan trips on your mobile device at your convenience, wherever you are.</p>
<p>The Main screen is where you provide your car’s characteristics, and describe your driving style
and preferences. With the purchase of EVTO Pro version features and a Multi-Trip subscription, you’ll
add the ability to save and manage multiple trips. Refer to the
<a href="http://www.digitalautoguides.com/evto-features/">EVTO Feature Matrix</a> to compare EVTO’s standard, Pro and Multi-Trip features.</p>

<p>EVTO requires data connectivity for full functionality. Without connectivity, maps are unavailable, but trip data may be reviewed.</p> 
<hr />

<h4>Main menu items</h4>

<h5><img class="panel_help_icon" src="css/images/gray/746-plus-circle" />Plan a Trip</h5>
<p class="menu_item_summary">Displays the 'New Trip' dialog</p>
<p>Enter an origin by name or address, your current location, or select from saved Favorites. Add a destination, and you're on your way. Origins and destinations may be entered by name (Disneyland), address (1600 Pennsylvania) or latitude and longitude (37.4874054,-121.9413378).</p>
<p>Specifying a Destination Charger Type of 'Tesla Superchargers' before entering a destination will filter the search results, making it easy to quickly select a supercharger by name.</p>
<p>Enabling the 'Plan as a round trip' checkbox<sup>†</sup> plans the trip in two segments, with the destination of the first segment becoming the origin of the second segment, returning to your starting point.</p>
<p class="caveat"><sup>†</sup>Requires Pro version IAP</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/710-folder.png" />Current Trips</h5>
<p class="menu_item_summary">Opens the Current Trips screen</p>
<p>Review and manage trips saved on your device. Share trips with other EVTO users, or import trips they share with you. EVTO allows a single trip when initially installed. Purchase the Pro version
IAP to enable multiple trip storage. Trips may be moved to the Trips Archive folder for future reference.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/740-gear.png" />Settings</h5>
<p class="menu_item_summary">Displays the Settings dialog</p>
<p>Adjust personal preferences describing your driving style and geographic location.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/815-car.png" />My Cars</h5>
<p class="menu_item_summary">Displays the My Cars dialog, specifying your EV’s characteristics</p>
<p>Specify vehicle options affecting range. Name your car, then select its characteristics, including model, motors, battery size and condition, charger, wheel size and tire type. With the Pro
version IAP, up to 5 cars may be managed.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/745-unlocked.png" />Purchase Pro version</h5>
<p class="menu_item_summary">Upgrades EVTO to add Pro features</p>
<p>Refer to the <a href="http://www.digitalautoguides.com/evto-features/">EVTO Feature Matrix</a> to compare EVTO’s standard, Pro and Multi-Trip features.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/745-unlocked.png" />Multi-Trip Subscription</h5>
<p class="menu_item_summary">Upgrades EVTO with an annual subscription enabling multi-trip support.</p>
<p>Refer to the <a href="http://www.digitalautoguides.com/evto-features/">EVTO Feature Matrix</a> to compare EVTO’s standard, Pro and Multi-Trip features.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/880-bank.png" />Restore Purchases</h5>
<p class="menu_item_summary">Restores previously-purchased IAP features to EVTO</p>
<p>Required after reinstalling the App, or installing EVTO on a new device.</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/755-filing-cabinet.png" />Archived Trips<sup>†</sup></h5>
<p class="menu_item_summary">Opens the Archived Trips screen</p>
<p>A list of all trips previously archived from the Current Trips screen. Archived trips may be restored to Current Trips.</p>
<p class="caveat"><sup>†</sup>Requires purchase of Multi-Trip subscription</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/729-top-list.png" />Feature Matrix</h5>
<p class="menu_item_summary">Compares standard, Pro and Multi-Trip versions of EVTO.</p>
<p><a href="http://www.digitalautoguides.com/evto-features/">EVTO Feature Matrix</a></p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/896-road-sign.png" />Getting Started</h5>
<p class="menu_item_summary">A quick introduction to the features of EVTO</p>
<p>Displays an introductory series of screens providing a quick overview of EVTO’s features and capabilities</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/897-graduation-cap.png" />Web Content</h5>
<p class="menu_item_summary">An online resource for FAQs, tutorials and how-tos for getting the most out of EVTO.</p>
<p><a href="http://www.digitalautoguides.com/trip-optimizer-tutorial/">EV Trip Optimizer for Tesla Tutorials</a></p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/704-compose.png" />Feedback Report</h5>
<p class="menu_item_summary">A place to report problems or make comments</p>
<p>Sends an email of your comments or problems and optionally attaches your current trip for analysis by our support team</p>
<hr />
<h5><img class="panel_help_icon" src="css/images/gray/739-question.png" />Help</h5>
<p class="menu_item_summary">Main screen help</p>
<p>You are here!</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/724-info.png" />About EVTO</h5>
<p class="menu_item_summary">About the application, including our
<a href="http://www.digitalautoguides.com/dag-license/" rel="external">Terms of Use</a>,
<a href="http://www.digitalautoguides.com/dag-privacy-policy/" rel="external">Privacy Policy</a> and
<a href="license.html">License Agreement</a></p>

**Comment by EVGrokker** [comment]
Ready for your review. Note that the icon for the 'Plan a Trip' menu item needs to be corrected.

**Comment by aesculus** [comment]
> Purchase the Pro version IAP to enable multiple trip storage. 

It's the subscription that does this. Pro is for the extra features. There were a few references to multi trip assigned to Pro in the help.

Compare requires Pro, and obviously MTS too since you would only be able to compare one trip. :-)

**Comment by aesculus** [comment]
Local Travel it is in V1.2 (29)

**Comment by EVGrokker** [comment]
Compare Trips updated to reflect both Pro and MTS purchases.

**Comment by aesculus** [comment]
Updated in the app.

**Comment by EVGrokker** [comment]
Removed the Compare Trips section, relocated to Current Trips help. Removed section included here for historical reference.

<h5><img class="panel_help_icon" src="css/images/gray/754-scale.png" />Compare Trips<sup>†</sup></h5>
<p class="menu_item_summary">Opens the Compare Trips screen</p>
<p>Compare route characteristics of selected trips. Select the trips of interest to display any of the following fields in tabular format:</p>
<ul>
<li>Status</li>
<li>Name</li>
<li>Rating</li>
<li>Stops</li>
<li>Distance</li>
<li>Trip Time</>
<li>Drive Time
<li>Charge Time</>
<li>Total kWh</li>
<li>Efficiency</li>
<li>Elevation Change</li>
<li>Average Speed</li>
<li>Weather Impact</li>
</ul>
<p class="caveat"><sup>†</sup>Requires purchase of Pro version and Multi-Trip subscription</p>
<hr />

**Comment by aesculus** [comment]
Removed from main menu help in V1.2 (40)

**Comment by EVGrokker** [comment]
v 1.2.0 (41) 
Compare Trips section is still included in the Main menu help content.

**Comment by aesculus** [comment]
I just did a wholesale swap again on V1.2 (42). Last time I had just pulled the section (I thought).

**Comment by EVGrokker** [comment]
I appended a sentence 'EVTO requires data connectivity for full functionality.' to the first section in response to #450. I couldn't come up with an additional description of what does work in the absence of connectivity that I was comfortable with. If you want something more, give me a starting point and I'll work with it.

**Comment by aesculus** [comment]
I appended a bit more where you did. You can edit that as you see fit.

**Comment by EVGrokker** [comment]
I revised it the paragraph describing functionality with/without connectivity.

**Comment by aesculus** [comment]
Updated in V1.2 (62)

**Comment by aesculus** [comment]
Updated with new subscription info
