### ISSUE TITLE
Segment Summary dialog needs to be scrollable

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#414]
The new look for the segment summary dialog is excellent. One feature that is really handy is the ability to create a very long trip (for example Seattle-Denver using Auto), then segment it at superchargers based on how many miles you want to drive per day.

However, when the number of charging stops overflows the screen, there's no way to scroll the list to be able to see the bottom summary panel without selecting the waypoint that you're dragging. 

There needs to be a 'draggable zone' that allows scrolling the list without opening the waypoint inspector upon releasing the touch. 

It can't be the waypoint repositioning arrows on the far right. The center section where the name is should be touchable. That leaves either the pin location (left) or the battery area (near right). I'd suggest the pin area as the safe draggable area.

![scrollable copy](https://cloud.githubusercontent.com/assets/26678403/26753367/88217622-4819-11e7-92a1-3452d0a09020.jpg)

**Comment by aesculus** [comment]
Let me see why it's selecting vs just scrolling. I don't think it should auto select.  Perhaps I can do something where you actually have to press and hold to bring up the waypoint inspector?

**Comment by EVGrokker** [comment]
I was going to suggest that as well. If we use the same long-press timing used in the Trip Summary, that would make sense.

**Comment by aesculus** [comment]
I found that for iOS devices I had a touch event to replace the click event to zoom to the waypoint. This is why it was firing when longer lists needed to be scrolled.  I am not sure why that was there, as the click event seems to work OK.

In V1.2 (29) I am removing that touch event so see if it still zooms OK when clicked and does not zoom when just scrolling.

When I was in there I notice an issue. After the scroll event the origin and summary list items were blank.  I have not seen this before and I did not test it in the compiled version.  Does your show the same?

**Comment by EVGrokker** [comment]
It's hard to tell because after dragging it immediately opens the waypoint inspector. I do observe that while dragging, the summary is blank, but it appears to redraw before the dialog is dismissed in favor of the waypoint inspector.

**Comment by aesculus** [comment]
OK. Keep an eye on it.

**Comment by EVGrokker** [comment]
v 1.2.0 (3)
After scrolling a list of waypoints longer than the available screen, the segment summary data in the footer is blank.

![missingsummary](https://cloud.githubusercontent.com/assets/26678403/26762136/7e9f16e4-48f1-11e7-94b4-642607db6e4a.PNG)

**Comment by EVGrokker** [comment]
v 1.2.0 (30)

The scrolling behavior works as expected with lists of waypoints longer than the available screen real estate.

**Comment by aesculus** [comment]
I don't like it covering the tabbar either.

**Comment by EVGrokker** [comment]
Agreed.

**Comment by aesculus** [comment]
We may be stuck with it covering the tabbar. Investigating both issues.

**Comment by aesculus** [comment]
Well I got the tabbar issue resolved but still cannot figure out the first and last item disappearing act.

**Comment by EVGrokker** [comment]
Maybe an issue relating to the fact that the summary detail in not in a list item, and since it's not in the list, it's not rendered until the bottom of the list is visible. If you can get a notification when the bottom of the list is displayed and do a refresh? Just a wild guess.

**Comment by aesculus** [comment]
It only does this in iOS, not Android. I think it's something quirky with the UI Framework.  I created a hack to overcome it. Not the best but it works.

And it affects both the first and the last elements. I even tried it without the summary element and then the last waypoint had the same issue.

V1.2 (31).

**Comment by EVGrokker** [comment]
v 1.2.0 (33)

Going through the 'Journey is the Destination' tutorial (#324), at step 2.1, the folded map icon shows a '2' badge for the outbound and return segments, but only the outbound segment is listed in the Trip Summary when touching the folded map button.

**Comment by aesculus** [comment]
I fixed that problem and uncovered two more:
- The optimizer added Aberdeen on the return segment when it did not need to
- The stats on the second leg are flummoxed in the Trip Inspector

**Comment by aesculus** [comment]
Hopefully with the resolution of #418 and #433 this works.

**Comment by EVGrokker** [comment]
The original issue is resolved.
