### ISSUE TITLE
Edit Segment Details dialog: Dest. Reserve reference

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#415]
v 1.2.0 (28)

The label for the Destination Reserve field needs to be updated to be location-agnostic.

Two options:
- Dest. Reserve (mi or km)
- Dest. Reserve (distance)

What would you think about changing this label to 'Reserve Energy (xxx)'? I don't like seeing the abbreviation for Destination.

**Comment by aesculus** [comment]
Right now the mi or km is depicted by what's in settings.

Often its referred as local travel.  Would Local Travel (mi) be acceptable?

**Comment by EVGrokker** [comment]
I'm not opposed to 'Local Travel', but the value that the user supplies here is subsequently referred to as 'reserve energy'. I was trying to keep them connected. Your call.

**Comment by aesculus** [comment]
But reserve energy would have to be by kWh or at least SoC. I was trying to make it simpler for them to account for the energy by entering what they really want to buffer, distance.

We just need to be uniform and clear. I also agree about the abbreviation thing.

**Comment by EVGrokker** [comment]
OK, I'm good with 'Local Travel (mi/km)'. I'll explain further in the help.
