### ISSUE TITLE
In-app help and menu text needs to be reviewed for consistency, grammar, typos

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#42]
I will help with this.

**Comment by EVGrokker** [comment]
- [x] Review Getting Started screens (issue #67)
- [x] Review all dialogs: add icons, check for title consistency with menu items (multiple issues)
- [ ] Review all in-app Help content

**Comment by aesculus** [comment]
V1.1.3 (3) has the new Main Help. Please review for format and accuracy.  I added the Feedback Report and did some minor edits.

**Comment by EVGrokker** [comment]
Feedback on Main screen Help provided in issue #128. It looks very good, the formatting is much improved.

**Comment by aesculus** [comment]
Plan Trip help is now updated.  Need the map icons described.

**Comment by EVGrokker** [comment]
This issue can be closed. Current help to-do's are being tracked in issue #169
