### ISSUE TITLE
Touching folded map button does not display trip segments

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#420]
V 1.2.0 (31)

Touching the folded map button does not invoke the Trip Segments dialog.

**Comment by EVGrokker** [comment]
This is with a single-segment trip. With a multi-segment trip it seems to be ok.

**Comment by aesculus** [comment]
Yep.  Using an else if when I should have just used an if

Fixed in V1.2 (32)
