### ISSUE TITLE
Edit Trip Details dialog: Help text

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#421]
<h3>Edit Trip Details</h3>
<p><i>Edit trip metrics</i></p>

<h4>Name</h4>
<p>Rename your trip. The default trip name is derived from the initial destination.</p>

<h4>Date and Time</h4>
<p>Tweak the trip's departure date and time. When planning a trip for a future date, set the departure date and time using these fields. EVTO uses available weather and road condition reports to predict driving time and range. Touch the clock icon to reset time or date to the current time.</p>

<p><strong>Important note about departure times:</strong> The departure time for a trip is always displayed in the local time zone of the trip's origin, which may not be the same time zone that you are in when planning or reviewing the trip.</p>

<h4>Payload</h4>
<p>Use this field to inform EVTO of additional weight in the car above the curb weight, including passengers and baggage. This helps EVTO estimate the required energy along your route.</p>
<p><i>Note: When using a tow hitch, include the weight of the additional load.</i></p>
        
<h4>Climate Control</h4>
<p>Use this field to specify your preferred cabin temperature while driving. If you don't anticipate using climate control while underway, uncheck the Climate Control checkbox.</p>
<p><i>Note: Enabling climate control during charging stops does not negatively impact range calculations for the trip.</i></p>
    
<h4>Speed Adjust</h4>
<p>Use this slider to inform EVTO that you typically prefer to drive over (or under) the posted speed limits. The slider is color-coded, reflecting that higher speeds incur an energy penalty, while lower speeds return an energy bonus.</p>

<h4>Power Factor</h4>
<p>Use this slider to inform EVTO that you anticipate requiring extra energy for this trip, typically because you're towing a trailer, or have something attached to the car, like bicycles or skis. Positive numbers impose an energy penalty. </p>
<p>For example, a Power Factor of <i>10</i> imposes an additional 10% energy requirement when EVTO plans your trip. You can also use the Power Factor setting to inform EVTO that you aggressively seek opportunities to reduce energy requirements whenever possible by using hypermiling techniques, like drafting.</p>
<p>Identifying an accurate Power Factor setting for a particular configuration requires trial and error experimentation.</p>

**Comment by EVGrokker** [comment]
Ready for your review.

**Comment by aesculus** [comment]
Updated in V1.2 (37)

**Comment by EVGrokker** [comment]
Updated to reflect change from 'Cabin' to 'HVAC', addition of HVAC checkbox. Ready for your review.

**Comment by aesculus** [comment]
Not to be picky but hvac does include ventilation which bears no cost. Is that going to be an issue?

**Comment by EVGrokker** [comment]
If you'd prefer **Climate Control** to match what's displayed in the car, we can use that.

**Comment by aesculus** [comment]
If it will fit. Yes.

**Comment by EVGrokker** [comment]
Updated: ~~HVAC~~ Climate Control

**Comment by aesculus** [comment]
Barely.

![image](https://user-images.githubusercontent.com/283364/27003824-f4280e46-4db2-11e7-8771-9ec877d18aa3.png)

**Comment by EVGrokker** [comment]
Can you append Fº/Cº to the number in the edit box? 

Or, can you reduce the width of the text edit field, creating some space on the right side, and add Fº/Cº there?

**Comment by EVGrokker** [comment]
Or run with it like you have it.

**Comment by aesculus** [comment]
At one time I made them smaller and then it look weird because the () descended below the other text and it looked like they were misaligned. Maybe I should not have made the () smaller too.

I can dump them or make them smaller. The other options are going to be an issue with arranging the input objects. I am already treading on thin ice the way I had to force it.

**Comment by EVGrokker** [comment]
I'd be ok with dumping them. I think they'd be obvious units to users based on their geographic location.

**Comment by aesculus** [comment]
![image](https://user-images.githubusercontent.com/283364/27003888-57696f94-4db4-11e7-8e9d-1f8b972bf972.png)

**Comment by EVGrokker** [comment]
Meh.  I vote no units.

**Comment by aesculus** [comment]
Even easier. Gone, just like the time spent to put them in. :-)

**Comment by EVGrokker** [comment]
Updated to note that hypermilers can be comfortable during charging stop.

**Comment by aesculus** [comment]
Updated in V1.2 (37)

**Comment by EVGrokker** [comment]
Added note to Payload section reminding those towing to include the additional weight

**Comment by aesculus** [comment]
Updated in V1.2 (39)

**Comment by aesculus** [comment]
Moved comments into this help and removed sa and pf in V1.2 (89)
