### ISSUE TITLE
Decide How to Compose the Compare Trips Feature

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#425]
When first conceived it was intended to be able to compare trips. Later when the app supported trip segments, the capability actually turned into compare segments.  It shows each segment stored in the app, and does not actually show trips, like the Current Trips panel does.

So we need to decide if we keep the name Compare Trips and also if it belongs on the Current Trips menu or if it should be renamed Compare Segments and stay on the Main menu.

**Comment by EVGrokker** [comment]
At the risk of being curmudgeonly, I think that Compare Trips is a minor feature that will only appeal to a small percentage of users, infrequently. My preference would be to move it to the Current Trips menu, where it would be available to those who want it, but out of the way of the mainstream users. I feel the same way about the Segment Details feature - I'd be happy to move that to Current Trips as well.

**Comment by aesculus** [comment]
I changed the title to reflect looking more at the feature than just the title. I agree that the trip view is more useful. I will rethink it in those terms and stick with the title as it is.

**Comment by aesculus** [comment]
Compare Trips is now actually Compare Trips in V1.2 (35).
