### ISSUE TITLE
Pressing the Globe Icon with No Trip Selected

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#427]
Sends the user off to the middle of the Pacific Ocean.

**Comment by aesculus** [comment]
In V1.2 (34) it will do nothing for a press or long press if there is no current trip.

**Comment by EVGrokker** [comment]
I didn't think it was possible to view the Plan screen without an active trip. How did you accomplish this?

**Comment by aesculus** [comment]
I didn't either. A few months ago a beta user found a bug in doing so. I asked how he got there. Just cancel the New Trip dialog when it appears.
