### ISSUE TITLE
Friendly names not properly displayed on Trip Summary, Trip Details waypoint lists

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#43]
1. Load trip [5bbafwn92acf41d2txxvxn], PIN[1234]
2. Select the second (return) segment Burlington - Seattle with multiple stops
3. Display Trip Summary or Trip Details, note that addresses are shown instead of friendly waypoint names.

Note that the waypoints were added by dropping pins on the map to force a particular routing, and that they were not added by searching Google by name or address. This may be a factor.

**Comment by EVGrokker** [comment]
![img_0281](https://cloud.githubusercontent.com/assets/26678403/24326553/a655ebba-116d-11e7-957e-54f6167aace5.PNG)

**Comment by aesculus** [comment]
Added to Version 1.1.2
