### ISSUE TITLE
Editing trip parameters yields unexpected energy results

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#430]
>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 94 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (35) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Bend OR, [aplayhu1qg46604hvnpfp]

I used this trip as a baseline for evaluating the effects of editing various trip parameters. For all trips, the payload is 220 (which I note is not included in the the Bug Report metadata above). I'd suggest adding Payload, Cabin, Speed Adjust and Power Factor to the metadata reports to facilitate analysis of trips using them.

I chose this trip because the initial calc showed an energy requirement of 102.4 kWh, which made it easier to evaluate the effect of parameter tweaks. 

Temperatures en route:
- Origin: 60º
- Centralia SC: 64º
- Sandy SC: 71º
- Destination: 86º

<table>
  <tr>
    <th>#</th>
    <th>Cabin</th> 
    <th>SF</th>
    <th>PF</th>
    <th>kWh</th>
    <th>ET</th>
    <th>DT</th>
    <th>Comments</th>
  </tr>

  <tr>
    <td>1</td>
    <td>75</td> 
    <td>0</td>
    <td>0</td>
    <td>102.4</td>
    <td>6:39</td>
    <td>5:51</td>
    <td>Default</td>
</tr>

  <tr>
    <td>2</td>
    <td>68</td> 
    <td>0</td>
    <td>0</td>
    <td>101.8</td>
    <td>6:32</td>
    <td>5:51</td>
    <td>HVAC to 68º</td>
</tr>

  <tr>
    <td>3</td>
    <td><strong>0</strong></td> 
    <td>0</td>
    <td>0</td>
    <td>108.2</td>
    <td>6:39</td>
    <td>5:51</td>
    <td><strong>No HVAC causes higher energy reqs?</strong></td>
  </tr>

  <tr>
    <td>4</td>
    <td>0</td> 
    <td>10</td>
    <td>0</td>
    <td>120.8</td>
    <td>6:02</td>
    <td>5:02</td>
    <td>SF +10, looks reasonable</td>
   </tr>

  <tr>
    <td>5</td>
    <td>0</td> 
    <td>0</td>
    <td>20</td>
    <td>127.2</td>
    <td>7:01</td>
    <td>5:51</td>
    <td>PF +20, looks reasonable</td>
   </tr>

  <tr>
    <td>6</td>
    <td>0</td> 
    <td>0</td>
    <td><strong>-20</strong></td>
    <td><strong>98.9</strong></td>
    <td>6:31</td>
    <td>5:51</td>
    <td><strong>Should a negative PF reduce kWh by a related amount?</strong></td>
   </tr>

  <tr>
    <td>7</td>
    <td>0</td> 
    <td>-10</td>
    <td>0</td>
    <td>98.2</td>
    <td>7:41</td>
    <td>7:00</td>
    <td>SF -10, looks reasonable</td>
   </tr>
</table>

In general, it looks like the effects of tweaking SF and PF are plausible (though real-world correlation is needed). However, the effect of disabling HVAC is suspect, and it seems like a negative PF should yield a larger benefit.

**Comment by aesculus** [comment]
Pesky 0 values and the King's units.

Fixed in V1.2 (36).

**Comment by aesculus** [comment]
> Should a negative PF reduce kWh by a related amount?

No. It is only applied to the non elevation and non climate portion of the energy consumption. So it will never be the same % unless you have the cabin off and never go up or down a hill.  You can try that by going down I5 somewhere that has no elevation change.

**Comment by EVGrokker** [comment]
v 1.2.0 (36)

This looks better. Here's a comparison of various tweaks on the Winnemucca - Boise route with a Level 2 charging stop at the Say When:

<table>
  <tr>
    <th>#</th>
    <th>Cabin</th> 
    <th>SA</th>
    <th>PF</th>
    <th>kWh</th>
    <th>Eff</th>
    <th>CT</th>
    <th>ET</th>
    <th>DT</th>
    <th>Comments</th>
  </tr>

  <tr>
    <td>1</td>
    <td>75</td> 
    <td>0</td>
    <td>0</td>
    <td>71.6</td>
    <td>281</td>
    <td>0:27</td>
    <td>4:30</td>
    <td>4:04</td>
    <td>Default</td>
</tr>

  <tr>
    <td>2</td>
    <td>0</td> 
    <td>0</td>
    <td>0</td>
    <td>65.5</td>
    <td>257</td>
    <td>0:18</td>
    <td>4:21</td>
    <td>4:04</td>
    <td>No HVAC looks right</td>
</tr>

  <tr>
    <td>3</td>
    <td>0</td> 
    <td>-10</td>
    <td>0</td>
    <td>58.0</td>
    <td>227</td>
    <td>0:15</td>
    <td>5:05</td>
    <td>4:51</td>
    <td>10 mph under</td>
</tr>

  <tr>
    <td>4</td>
    <td>0</td> 
    <td>+10</td>
    <td>0</td>
    <td>74.9</td>
    <td>294</td>
    <td>0:32</td>
    <td>4:01</td>
    <td>3:30</td>
    <td>10 mph over</td>
</tr>

  <tr>
    <td>5</td>
    <td>0</td> 
    <td>0</td>
    <td>+30</td>
    <td>86.6</td>
    <td>337</td>
    <td>0:53</td>
    <td>4:56</td>
    <td>4:04</td>
    <td>Light towing load</td>
</tr>

  <tr>
    <td>6</td>
    <td>0</td> 
    <td>-10</td>
    <td>+30</td>
    <td>75.7</td>
    <td>297</td>
    <td>0:34</td>
    <td>5:24</td>
    <td>4:51</td>
    <td>Towing, speed reduction</td>
</tr>
</table>

**CT**: Clock time 
**ET**: Elapsed time 
**DT**: Driving time
