### ISSUE TITLE
Add Waypoint, Updating Trip dialog: Icon overlaps Title

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#432]
v 1.2.0 (35)

The Add Waypoint dialog formatting of the title bar has changed. The '+' icon now overlaps the 'Add Waypoint' text.

This is also true for the status dialog (scales icon, 'Updating Trip')
![dialogicon](https://user-images.githubusercontent.com/26678403/26878641-68d1b554-4b4b-11e7-914a-16675ffa4b8d.PNG)

**Comment by aesculus** [comment]
Add waypoint fixed in V1.2 (26).  I did not see crowding of the scale icon in the Updating Trip dialog. I did not check on an iPhone though, just iPad and Android.

**Comment by EVGrokker** [comment]
v 1.2.0 (35)

Here's a snapshot from the Updating Trip dialog on the iPhone showing the overlap:

![overlap](https://user-images.githubusercontent.com/26678403/26897921-6a38782e-4b87-11e7-952f-12d925e25241.PNG)

**Comment by aesculus** [comment]
OK. I will have to snag the iPhone then.

**Comment by EVGrokker** [comment]
v 1.2.0 (36) 

[scales] + Updating Trip still needs to be adjusted to remove overlap.

**Comment by aesculus** [comment]
I think I found it in V1.2 (38).

**Comment by EVGrokker** [comment]
Looks good in v 1.2.0 (37)
