### ISSUE TITLE
Optimizer Not Accounting for Hinge Charger

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#433]
The server side of the optimizer is not accounting for a charger at a hinge origin and is therefore trying to find a charging source immediately afterward.

**Comment by aesculus** [comment]
I believe I have fixed this now on the server.

**Comment by EVGrokker** [comment]
Appears to be resolved.

**Comment by aesculus** [comment]
Well maybe not if your Boise trips has been flummoxed.
