### ISSUE TITLE
Add Payload, Cabin, Speed Adjust and Power Factor to Feedback Report

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#434]
These are missing from the Feedback Report

**Comment by aesculus** [comment]
Added in V1.2 (36).

**Comment by aesculus** [comment]
Payload and cabin temp were rounded for imperial units in V1.2 (37)

**Comment by EVGrokker** [comment]
>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 100, PF: 6, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (37) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Oxford Suites Portland - Jantzen Beach, [1l60p8sw41jg2wyk3q0ndw]
