### ISSUE TITLE
Real-world towing data 

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#437]
Courtesy of @Ohmman at [TMC](https://teslamotorsclub.com/tmc/posts/2137661/): 

Yesterday we went from Sonoma to Mount Shasta.

Statistics -- there is a marked discrepancy between what the trip meter on the car says and what TeslaFi.com reports via the API. I'm not exactly sure how to reconcile those, but will try to pay attention to remaining range and do my own pencil calculations at some point moving forward.

The good news - the car reported sustained consumption around 548Wh/mi at 55mph on flat I-5 driving in completely still weather. HVAC was on, outside temperatures in the low 90s.

The TeslaFi.com details, which again, are higher than the car's reports:

Sonoma - Vacaville SC
41.39 miles
602 Wh/mi
42 mph average speed
-125.7 ft elevation change

Vacaville SC Charging
Start 70%, End 99%
Avg Voltage: 404.33V
Avg Amperage: 81.88A
Estimated Charging time: 50 min
Actual Charging time: 43 min

Vacaville SC - Corning SC
112.51 miles
629 Wh/mi
45 mph average speed (truly 55mph the whole way but a long stop in traffic dropped the average)
+175.5 ft elevation change

Corning SC
Four connections due to throttling (seemingly due to heat)
Start 13%, End 99%
Actual Charging time: 1 hr 23 min

Corning SC - Train Park Resort
98.17 miles
668 Wh/mi (car reported 606 Wh/mi)
51 mph average speed
+1968.1 ft elevation change

The park hosts were not available and there was a little confusion at the very nice and quaint Train Park Resort. We got a pull-through site but no 50A connection. There was a small site nearby with a 14-50, and I considered unhitching and plugging the car in overnight. After a very long day of driving, I decided instead to just head to the Mount Shasta SC this morning and cook breakfast in the camper while the car charged. No real time lost.

Summary
252.08 miles
640 Wh/mi
5 hours 32 minutes driving
2 hours 20 minutes Supercharging

**Comment by EVGrokker** [comment]
Another set of towing data from [this post](https://teslamotorsclub.com/tmc/posts/2141227/):

Mt. Shasta SC - Klamath Falls SC
81.84 miles
668 Wh/mi
44 mph average speed
+619.4 ft elevation change

Klamath Falls SC Charging
Plugged in twice trying to find a good way to situate.
Start 30%, End 99%
Actual time: 1 hour 36 minutes

Klamath Falls SC - LaPine State Park
122.67 miles
523 Wh/mi
47 mph average speed
+99 ft elevation change

**Comment by EVGrokker** [comment]
See issue #306 for discussion of Power Factor implementation.

**Comment by EVGrokker** [comment]
https://teslamotorsclub.com/tmc/posts/2141227/

Bend, OR - The Dalles SC
135.74 miles
524 Wh/mi
46 mph average speed
-3597.8 ft elevation change

The Dalles SC Charging
Start 14%, End 100%
Avg Voltage: 397V
Avg Amperage: 130A
Estimated Charging time: 1 hr 30 min
Actual Charging time: 1 hr 22 min

The Dalles required unhitching, so we've only gotten away with staying hitched in one location. I am not terribly comfortable blocking stalls except in very vacant locations, so I err on the side of unhitching. Even with our weight distribution setup, it only takes about 5 minutes on each side of the process. 

We had the pleasure of visiting with @bonnie here, who was gracious enough to come and say hello. She was in her normal form, evangelizing to anyone caught remotely drooling over the cars, and helping a couple who was Supercharging for the first time. Thanks for coming, @bonnie.

The Dalles SC - Arlington, OR CHAdeMO
55.21 miles
564 Wh/mi
50 mph average speed
+142 ft elevation change

Arlington, OR CHAdeMO charging
Start 63%, End 79%
Avg Voltage: 389.47V
Avg Amps: 59.58A
We maybe could have skipped Arlington, considering the nice tailwind, but I wasn't in the mood to be stressed. I also wanted to see where the "Chairman of Charging" had charged. 

Arlington, OR - Columbia Sun RV Resort (Kennewick, WA)
77.28 miles
639 Wh/mi (car reported 570 Wh/mi)
58 mph average speed
+303.4 ft elevation change

After charging in Arlington, I saw we'd have plenty of juice to make it so I went ahead and drove 60mph for the stretch to the RV park. It was nice to feel like I wasn't completely standing still next to the 80-85mph traffic for a change.

Going 60 mph, here is the trip readout over 30 miles. Remember that we had a friendly tailwind since we were going in the easy direction through the Gorge. Still.. the car is constantly reporting better consumption numbers than TeslaFi. My 55 mph number is just under 550Wh/mi (car reported) whenever I get flat and still conditions.

**Comment by aesculus** [comment]
See his email to me: 

_More in a few days but it's proving quite useful if not terribly accurate. It's better than anything else available. _

:-)

**Comment by EVGrokker** [comment]
>Vacaville SC - Corning SC
Initial SoC 99%
112.51 miles
629 Wh/mi
45 mph average speed (truly 55mph the whole way but a long stop in traffic dropped the average)
+175.5 ft elevation change
Arrival SoC 13%

I just tried modeling this leg. I did some research on the 22' Sport, it's listed as 3500 max lbs, so I used a Payload of 4000 lbs. With climate control at 68º, SA of -10, and PF of 30, EVTO predicts:
- 609Wh/mi (vs 629 actual)
- 13% Arrival SoC (vs 13% actual)
- 58mph (vs reported 55mph)

**Comment by aesculus** [comment]
Well one leg worked. The question is how multiple legs do I guess. I need to try Sonoma to Mt shasta or something. 

Another tweet for trailers. Un hook time in no pull through but you could also use min stop time here  

This then would compromise the idea of filling time charging but maybe that could be a checkbox

**Comment by EVGrokker** [comment]
IMHO, including the time for unhooking is overkill. I'd just factor it into the stop time as you suggested. Trailer-towers are an edge case, and adding SA and PF was 98% of what they need.

**Comment by EVGrokker** [comment]
An X owner traveling with a bike rack posting on [TMC](https://teslamotorsclub.com/tmc/posts/2140862/):
<hr/>

>We'll be traveling to Jackson, WY later this month and I was trying to make a stop at Craters of the Moon work. I see RV parks in Mountain Home and Arco that would be helpful. 
Are there any options I'm missing?
Oh yeah, we'll be in our 90D but with bikes on the back so 200 - 210 is about our range.

And a reply:
>Glad to see some questions near me. I went to that area last year, but I didn't have the Tesla with me. Yeah, going straight across highway 20 from Boise to Arco is possibly going to be too long probably with bikes hurting your aerodynamics. But I think charging up in Twin Falls and then heading up highway 26 should be totally easy (like just over 100 rated miles, plus some extra for the bad aerodynamics).
We stayed at the KOA campground in Arco, which is a really great place, and I would totally recommend it. We were tent camping, and they even had TT-30 outlets right next to our site, which we could have used. We also saw a lot of really big RV's, so I think they have 14-50 outlets at those other spots too. Call and make sure of that.
The entrance to the Craters of the Moon area is only about 20 miles back west of Arco, so I would still recommend staying at the KOA in Arco, where you can actually have a decent restaurant there in town for dinner and breakfast.
We did this trip on a weekend and saw a few really good things. On Saturday morning, we saw Experimental Breeder Reactor 1, which was the first nuclear reactor in the world to generate electricity. They do excellent guided tours seven days a week, but it's only open from Memorial Day to Labor Day. Then, we did the Philo Farnsworth TV and Pioneer history museum in Rigby. It's dinky and quirky and kind of interesting and is only $2.
Then on Sunday, we started back toward Boise, so we went to Craters of the Moon and got to crawl around in some of the underground caves, which was really cool (literally). Then, we went to the Shoshone Ice Caves, which are on highway 75 north of Twin Falls. Since you would probably be coming up from Twin Falls on your way out to Arco and Idaho Falls, you could see that on your way out there. There's a terribly cheesy gift shop you have to wait in before the tour, but the cave is really interesting.

**Comment by aesculus** [comment]
I would suspect power factor would be helpful here.

For the trailer tutorial it would probably be good to show a table of various towing items with the payload, speed adjust and power factor for each type as an example.

**Comment by aesculus** [comment]
I am pretty sure when used in towing mode it should probably be done manually although after setting all the parms you could take a fist pass with optimize. The reasons are:
- Lots of trial and error to get the three factors tweaked (pf, sa, payload) for the given trip
- Different charging stops may need extra time (ie no pull through so have to use min time to add for trailer unhook/rehook.
- Expectations might be set to reality once you see how long some segments might take. The elapsed times should help here
- Segmentation is going to be critical for trailer users.  Each day must be a segment IMHO

**Comment by aesculus** [comment]
>EVTO with power factor saved me time yesterday. I charged less than I had originally planned at both Ritzville and Superior due to recommendations from the app that confirmed my slowly growing experience. Probably saved over 30 minutes. I'm dialing it in more but would love a more granular power factor (instead of having 5% increments).

**Comment by EVGrokker** [comment]
I'd really like to keep the slider if at all possible rather than going to a typed-in PF. That would be complicated because of the negative values, and just not as elegant as the slider.

Can you try reducing the granularity to see how it feels on a phone-size screen? My guess is that it's going to be too fussy at increments of 1 to hit a particular number. An alternative would be 2.5 increments, subdividing the existing stops in half. That would probably be OK.

**Comment by aesculus** [comment]
I can't imagine how a granularity of 1 is going to make more than a few % difference. Way out of the apps accuracy realm IMHO.

**Comment by EVGrokker** [comment]
Agreed, but this is one of those controls where the user's perception of their control is important. It's like the difference between 69º and 70º with climate control - not much difference in the actual energy consumed, but appeals to the OCDs among us.

**Comment by aesculus** [comment]
Wait. That is real. And what is also real is that a setting of 75F is real comfortable in the summer and freezing cold in the winter, especially around my feet.

**Comment by EVGrokker** [comment]
Was the request for more granularity from Ohmman?

**Comment by aesculus** [comment]
Yes

**Comment by EVGrokker** [comment]
I'm closing all issues tagged Test Cases, as they exist only for reference and are not directly involved with proposed app revisions. Locating test cases is merely a matter of selecting 'test cases' from the Labels list. They are still available for comment and updates.
