### ISSUE TITLE
Allow user to access device address book to specify waypoint address

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#44]

**Comment by aesculus** [comment]
Decision time:  I started to play with some UI stuff here regarding contacts. First off we are running out of room on the waypoint dialog button areas.  With PlugShare it pretty much fills it up (I think I might still be in trouble with my iPhone SE user(s)).

So I decided to mock up an more iconic and scrunched button group on the waypoint dialog:

![image](https://user-images.githubusercontent.com/283364/28811312-302a4db0-7643-11e7-86ba-7f2ae80a61a4.png)

To me it looks too crowded.  Also I am not in favor of mixed text and iconic buttons in the same grouping.  If, during the redesign of the Favorites double purpose that dialog to be favorites, dislikes and contacts, it would make the button group simpler (like it is today). Issue #28.

The other advantage is that with new trips, you could use contacts there too where right now it would only work for waypoints.

**Comment by EVGrokker** [comment]
My comments on #330 apply here as well, I don't think the button belongs in the bottom row. We agree that it looks crowded and confusing.

At a minimum, I'd suggest adding the two buttons, 'Paste from PlugShare' and 'Paste from Address Book' to be side by side on a line below the Location field.

If you could integrate both of these new 'Paste from' features into the Favorites dialog, that would be preferable. The idea would be that upon opening the Favorites dialog, the top lines would be 'Paste from Address Book' and 'Paste from PlugShare'.

I'm not sure of the user actions when pasting from Address Book. Would they simply copy the address field from a contact and paste it into the Location field? That would negate the need for a special paste function.

**Comment by aesculus** [comment]
You did not notice in all this confusion that the help button got covered over. :-)

There are (will be) some differences:
- if I do the Plugshare copy/paste then there will be no UI feature
- Contacts will actually be more like the favorites. It would probably be a search panel or some means to list contacts directly from your contacts in the device from which you would choose.
- Favorites is a list based feature

The Contacts directly from the device does have security implications which might require a warning. I will have to look into the store requirements.  Uses might also not be too happy about me digging into their contact list too.

**Comment by EVGrokker** [comment]
I'm leaning away from a direct link to Contacts at the moment. I'm pretty sure if the user simply copies an address from their address book, then pastes it into the Location field, and Google parses it, that's enough.

**Comment by aesculus** [comment]
I tend to agree.  Don't need to get it more complicated.  I can do some testing of the content of a Contacts paste to see if I can strip relevant data. TBD.

**Comment by aesculus** [comment]
I don't see any way to copy a contact in iOS.  So it looks like we will just have to pass on this feature in light of the privacy concerns of the app getting access to the users contact data.

I did verify that copying the address from the Contacts app into the location field does work. But of course you will not get the name from the contacts in this case. It will default to the first set of words up to the ',',

**Comment by aesculus** [comment]
I am closing this since the work around of just copy/pasting the address is appropriate.
