### ISSUE TITLE
Add a Car Picker to Current and Archive Trips

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#441]
Use a car picker to set the active car in Current Trips.  All trips will be shown but trips of the non active car will be grayed out. 

This bears a few questions:
- Should selecting a non active cars trips make that car active and go to that trip, or should the user be forced to change the active car first? If so why?
- This is going to bring up the issue of being able to transfer or at least copy a trip from one car to another which is a can of worms. Do we want to go there?  Changing a car features in an existing trip has huge ramifications.

**Comment by EVGrokker** [comment]
I propose a simpler alternative - only show Current Trips (or Archived Trips) for the currently selected car.

Reasoning:
- We would need to add another visual cue to the Current Trips list to differentiate which car a trip belongs to. We already use bold for the active trip, which means either adding an additional bit of text associating a trip with a car or using a different color scheme. Seems needlessly complicated for little return.
- Who are the primary users of multiple car configs? 1) Users with multiple cars, like an S and an X. Those trips would likely be different from one another, e.g. commuting vs road trips, so keeping the trips separate seems fine. 2) Users with one car but multiple profiles, like someone who occasionally tows an Airstream or uses a bike rack. Again, these seem like different types of trips which would naturally be segregated by the profile selection.
- I think we can educate Pro users (the only ones this applies to) through Help and Tutorials that Current Trips (and Archived Trips) maintains separate folders for each profile.
- If a user wants to copy an existing trip to a different car, you have addressed that in a FAQ.
- Reading down the screen (see image below), the flow is 'Current Trips', then 'Thunder'. That makes sense that what follows is a list of Current Trips associated with Thunder.
- Less complex implementation.

![currenttrips](https://user-images.githubusercontent.com/26678403/27004886-1e0e7670-4dcf-11e7-9c33-8c6a5d436ab2.jpg)

**Comment by aesculus** [comment]
I could ad a car numbe. Not as good as a name but...

The reason it could be good would be able to test various configuration. Ie traileron no trailer or hypermiling vs std using the compare feature.

**Comment by aesculus** [comment]
On the new Current Trips phone layout there is lots of room on the third line for the car name.  Unfortunately no so on the tablet version since it uses the table layout. So for the phones I can put in Car: name of car after the Whr/mi.  For the tablets just state the car number in a new Car column.

I also propose changing the Sort By Rating to be Sort By Car then. This way you can catalog trips by name, date or car.

**Comment by EVGrokker** [comment]
We're thinking along the same lines.

My sense is that trips are always grouped by car, but within those individually grouped trips, additional sorting would be done by name or date.  Then we don't need to come up with an extra identifying car datum within each trip metric. 

I'd also like to see each car's trips collapsible in the same way you have them now. I'll use '+/-' to represent a collapsing button. So the hierarchy would look something like below (the hyphens are there to force indentation). This creates two levels of collapsibility:

+/- [Car 1 name]
----- +/- [Year - 2016]
---------- trip
---------- trip

----- +/- [Year - 2017]
---------- trip
---------- trip

+/- [Car 2 name]
----- +/- [Year - 2017]
---------- trip
---------- trip

**Comment by aesculus** [comment]
If we just let the user pick a trip from the list, then that trip will auto activate the current car.  I don't see a need for the car picker and it would ruin your clean look. With the new sorting by cars, the picker also has much less importance.

I am going to hold the picker enhancement until we get some time with the new approach above.

**Comment by aesculus** [comment]
We also might want to review the need for the Activate menu item in Current Cars menu now that both tablet and phone lists support auto activate and resume from touch.

**Comment by aesculus** [comment]
I tried the double collapse and it was too busy and too many clicks. So I just stuck with the three collapsable categories and then sorted by date.

Since I am auto selecting the current car when you touch a trip and activate it, I did not see a need to change the intensity of the trip name. So bold is the current trip (with that car the current car) and the other trips are shown equally along with their car position (tablet) or car name (phone).

![image](https://user-images.githubusercontent.com/283364/27006981-7c90f88e-4df8-11e7-9794-8b6f67d72d14.png)

**Comment by aesculus** [comment]
One thing to consider when you get this to play with:

Today I am opening the first grouping.  But perhaps what I should always do is to open the group that the current trip is a part of.

**Comment by EVGrokker** [comment]
v 1.2.0 (37)

I am not seeing any updates in the Current Trips display. I have two active car profiles, but I'm not seeing anything like your screen grab above.

More generally, I have to admit that I'm ambivalent about this additional complexity in the Current Trips screen. I acknowledge the benefit of being able to compare trips with different cars, but I'm uncomfortable with impact that this has on the layout and UI for simply browsing among current trips for the active car.

I think there's a redesign of Current Trips for a future release. I'm wondering if it makes sense to postpose adding the ability to compare trips between cars until that redesign.

If you're in agreement, I'd drop back to my original proposal to add a car picker at the top of the current trips display as rendered in the initial image posted in this thread.

**Comment by aesculus** [comment]
Can you share your screenshot after you get V1.2 (38) operating if there still is an issue?

Does your list items not show the car name in the 3rd row?

There was a bug in (37) that did not auto expand the current trip correctly. I think I have fixed that now so whatever trip is highlighted, that list should auto expand.

**Comment by EVGrokker** [comment]
This appears to be working as you described it. I was expecting something different and missed your implementation approach.

Comments:
- I don't like the header format of `[+/-] Car - [car name]` and `[+/-] Year - [year]`, it's clunky, and unnecessarily wordy. The user named their cars, so if they see a familiar name in the header, they're going to know it's their car. Similarly, a year is familiar enough that there's no need to prefix it. The same applies to status.
- I think the best compromise would be to replace the grouping word (Car/Year) with an icon:
Group by Car: `[+/-] [car icon] Thunder`
Group by Year: `[+/-] [calendar icon] 2017`
Status: I don't see any need to prefix it, because the trips are either Planned or Taken, so you can simply use those words as the headers.
- The default behavior appears to be Group by Year when first opening the Current Trips dialog. I'm OK with that, as long as you remember the last sort-by the user selected when the dialog closed and reapply that when reopening. So, if I am looking at trips sorted by Car when the dialog is closed, I'd like to see that be the same sort when I reopen the dialog.

**Comment by aesculus** [comment]
In V1.2 (39) 
- I scrapped Year, Car, Status and Name in these lists.
- Labels are now a smaller font.
- App remembers your sort selection for the life of the session

**Comment by EVGrokker** [comment]
This looks excellent. Nice work.
