### ISSUE TITLE
Trip Browser: Include active car in summary?

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#448]
v 1.2.0 (37)

With the recent improvements on managing multiple car configurations, I'm looking at the Trip Browser and wondering which car a trip is associated with. Currently, the only way to discover this would be to exit the Trip Browser, go to the Main screen, open the My Cars dialog. That's clunky.

I propose that you add the active car name to the summary section at the bottom of the Trip Browser dialog. It could be added as a new line, at the top of the summary section, centered with simply the car's name. The font would be the same size and weight as the start and end dates for the trip.

Alternatively, you could add the car name under 'Trip Browser' in the header, in a font matching the data detailed in the summary.

**Comment by EVGrokker** [comment]
Arguably this same enhancement should apply to the Segment Browser as well.

**Comment by aesculus** [comment]
Added in V1.2 (38)

![image](https://user-images.githubusercontent.com/283364/27016179-bf4c827c-4ed1-11e7-9e5a-83979b2f3348.png)

**Comment by EVGrokker** [comment]
Looks good in both Trip and Segment browsers.
