### ISSUE TITLE
My Cars dialog: Switching to Model X does not enable 5-seater option

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#449]
v 1.2.0 (37)

When creating a new car profile, selecting an unused profile from the picker (e.g. 'My Car 2') configures the new car as a Model S.

When I change that to a Model X, it used to be the case that you would change the default attributes to match a version of the X. It no longer does that - it keeps the attributes from the S. That's not a major issue, but it was useful.

While I'm defining the attributes for the new car which is an X, the '5-seater' option is disabled. If I Save and reopen the dialog, I can then enable the 5-seater option. But enabling that checkbox should take place immediately upon selecting an X as the model.

**Comment by aesculus** [comment]
Fixed in V1.2 (38)
