### ISSUE TITLE
Initial screen sequence for freshly installed app

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#45]
When the app is first installed, certain dialogs should be presented before the user sees the main panel:

1. **My Cars** dialog with a useful set of defaults. Even if the user accepts the defaults, they will be aware that this customization dialog exists.
2. **Settings** dialog to ensure they'll see the appropriate supercharger database for their location

After completing this sequence, the Main panel is displayed with two buttons, **New Trip** and **Getting Started**. Experienced users may skip **Getting Started** and go directly to planning a trip. If they bypass the introductory **Getting Started** screens, the appropriate flag is set to indicate that those screens have been viewed. 

After this initialization, visits to the Main panel show two buttons, **New Trip** and **Resume Trip**. If there is no active trip, **Resume Trip** is grayed out.

This feature request supersedes issue #25.

**Comment by EVGrokker** [comment]
Just a note from testing 1.1.3 (3) that this is still an open issue and should be implemented before the next release.

**Comment by aesculus** [comment]
I tried a simple approach to this. Did not work. There are other dialogs that can be presented during initialization that conflict.

Thinking about making this happen in the Getting Started sequence when the user pressed the Let's Get Started button for the first time. This would also require disabling the New Trip and other trip related menu items until they did the Getting Started.

**Comment by EVGrokker** [comment]
See also issue #287. After doing a fresh install then importing a trip previously defined, unable to get to the imported trip without going through the Getting Started screens.

**Comment by aesculus** [comment]
I have been thinking more about this, especially after dealing with issues on TMC and emails for new users. Clearly they are not reading anything and expect the app to just work for them, or work like the other apps. This is causing frustration for them and lots of extra work for me and potentially bad ratings for the app.

I propose the following:
- Start the app without the main menu icon or gray it out
- Only show the Getting Started button. This is the only actionable item
- Make the new user go through each of the panels (ie remove the Let's Get Started button at the top until the last panel is shown)
- Once the have done that they will next see the Settings panel
- After confirming the settings they will see the My Cars panel
- At this point they have some familiarization with the app and they have at least looked at both the Settings and My Cars panels so they are ready to begin - Turn on the menu and replace the Getting Started button with Plan a Trip button or optionally just take them to the New Trip dialog.

**Comment by EVGrokker** [comment]
Your proposal sounds reasonable. I think it's worth implementing to test the flow. It's really imperative that they know about Settings and My Cars, and this is the best way to assure it. The training wheels come off after they've completed the initiation rites.

**Comment by aesculus** [comment]
> The training wheels come off after they've completed the initiation rites.

Sometimes I feel sorry for Tesla, especially the local service guys. Often I wait for my car to be serviced so I see all the issue/questions the customer present to them. I just don't get why they don't loose their patience at times. :-)

And you see this big time on TMC too. I suspect it's even worse for those that have no forum or someone to bounce ideas off of.

**Comment by aesculus** [comment]
In V1.2 (60) I updated the Getting Started panels to reflect the changes we have made. I have changed the initial startup sequence. This is what occurs:
- Start the app with the main menu icon disabled
- Only show the Getting Started button. This is the only actionable item
- At the Getting Started panel they can choose Let's Get Started anywhere and they will be taken to the the My Cars dialog
- After selecting Cancel or Save on the My Cars panel they will see the Settings panel
- At this point they have some familiarization with the app and they have at least looked at both the -Settings and My Cars panels so they are ready to begin
- Turn on the menu and replace the Getting Started button with Plan a Trip button

**Comment by EVGrokker** [comment]
v 1.2.0 (60)

>Start the app with the main menu icon disabled
Only show the Getting Started button. This is the only actionable item

I uninstalled and reinstalled v 1.2.0 (60). The Main Menu item is enabled.

>At the Getting Started panel they can choose Let's Get Started anywhere and they will be taken to the the My Cars dialog

Confirmed.

>After selecting Cancel or Save on the My Cars panel they will see the Settings panel
At this point they have some familiarization with the app and they have at least looked at both the -Settings and My Cars panels so they are ready to begin

Confirmed.

>Turn on the menu and replace the Getting Started button with Plan a Trip button

'Plan a Trip' is now visible, but as noted in the first item the main menu was active throughout.

**Comment by aesculus** [comment]
Hmm.  I'll wipe the device and see what happens on my end.  That menu should have been disabled.

**Comment by aesculus** [comment]
I deleted the app on the iPad and then installed it from TestFlight. When it came up the hamburger icon was disabled and only the Getting Started was available.  After selecting _Let's Get Started_ the My Cars was shown and the hamburger was still grayed out. When the Settings displayed the hamburger became enabled.

Can you try that sequence on your iPhone?

**Comment by EVGrokker** [comment]
v 1.2.0 (61)

I deleted the app from my iPhone, then reinstalled from TestFlight.

I relaunched EVTO, and I see 'Getting Started', but the menu is enabled, and not grayed out.

After touching 'Getting Started', then touching 'Let's Get Started', the 'My Cars' dialog is displayed.

Are you sure that you want to try to disable the menu? It seems reasonable that a new user might want to look at the menu to see what help facilities are available, for example. 

Here's another approach that might work: Upon initially opening a freshly installed app, immediately open the first screen of the 'Getting Started' sequence. That way, they'll immediately be presented with the choice of swiping through those screens, or touching 'Let's Get Started', which routes them through My Cars and Settings.

I've seen this approach used on many apps that I use regularly, and I don't find it annoying.

**Comment by EVGrokker** [comment]
v 1.2.0 (61)

Bug: 
- Install fresh copy of EVTO
- Touch 'Getting Started'
- Touch 'Let's Get Started'
- Save or Cancel out of the My Cars and Settings dialogs
- From the Main menu, touch 'Getting Started' to revisit the intro screens
- Touching 'Let's Get Started' does not escape the initial screen sequence

**Comment by aesculus** [comment]
> Touching 'Let's Get Started' does not escape the initial screen sequence

When I tested this just now I could not get out of the Getting Started panel.  The Let's Get Started button did nothing. Is that what you mean?

I fixed this in V1.2 (62).

**Comment by aesculus** [comment]
>Here's another approach that might work: Upon initially opening a freshly installed app, immediately open the first screen of the 'Getting Started' sequence. That way, they'll immediately be presented with the choice of swiping through those screens, or touching 'Let's Get Started', which routes them through My Cars and Settings.

For some reason I cannot find an acceptable way to do this using the framework I have to work under, so I just left the menu enabled and will hope for the best. :-(

**Comment by aesculus** [comment]
In V1.2 (90) I have changed the sequence to first show the settings and then My Cars. This was to allow the user to set the units prior to having to set the temperature or distance using the wrong units.
