### ISSUE TITLE
Optimizer hangs after pinning, segmenting at Supercharger

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#450]
>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 100, PF: 0, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (37) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Springfield Supercharger, [3tjsiqzuuxxiz1dat428c]

New Trip: Seattle - Fess Parker Inn, Santa Barbara
Select Springfield Supercharger, pin it, segment.
Optimizer hangs during 'Updating Trip' dialog in Optimizing Route.

**Comment by aesculus** [comment]
Yeah. This trip is a mess. Was this created with (37)? It's missing a date in Grants Pass and it goes down hill from there.

**Comment by aesculus** [comment]
Can you provide me the steps you took to get to this point? Somehow I think when you segmented the next segment start time did not get properly set.

**Comment by EVGrokker** [comment]
The steps are listed in the initial comments. Here's a slightly less terse version:
1. New Trip: Seattle WA - Fess Parker Inn, Santa Barbara, Auto Waypoint selection
2. Open the Springfield Supercharger Waypoint Inspector
3. Pin Springfield as a required stop
4. Segment at Springfield.

It was created with 1.2.0 (37)

**Comment by EVGrokker** [comment]
I just tried the same trip with 1.2.0 (38), following the same steps, leading to the same results - it hangs in the Updating Trip dialog on the Finalizing step.

>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 100, PF: 0, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (38) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Springfield Supercharger, [kf6u96ys93bf9dk2sriel]

**Comment by aesculus** [comment]
Ok. I will do same. I think the date is not getting set right at the segment.

**Comment by aesculus** [comment]
Please try this on V1.2 (58).  It works for me now with all the updates.

- I took the trip that is defined above and merged the two segments as a test.
- This resulted in a single segment trip with Springfield SC being required
- Next I segmented the Springfield SC

**Comment by EVGrokker** [comment]
Looks good.
