### ISSUE TITLE
Add Waypoint does not return validated locations

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#451]
>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 100, PF: 0, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (37) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Spokane WA, [myeret4oehl1bj0podpk61]

Adding a waypoint does not return a list of matching locations to select from. In the referenced trip, I tried adding the Kennewick SC with the Charger Type set to Tesla Superchargers, and then I tried simply Kennewick with no Charger Type. Both fail.

**Comment by aesculus** [comment]
Yes I flummoxed this last night when I improved the layout. Forgot to take out some test stuff. Fixed in V1.2 (38)
