### ISSUE TITLE
My Cars: Proposed layout enhancement

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#453]
v 1.2.0 (37)

The new layout for My Cars is excellent. There's an enhancement I'd like to propose that I think would make it even better.

The proposal is to move the active car picker to the top-most position of the dialog, and move the tab bar below it. 
- The content of the active car picker doesn't change from tab to tab. All of the other content below is variable.
- The conceptual flow of the dialog from top to bottom is My Cars - specific car - configuration details. Moving the car picker up fits in better with the flow of general to specific.
- Moving the tab bar away from the dialog header helps to make it more visible and thus discoverable.

![mycarstabbar](https://user-images.githubusercontent.com/26678403/27012618-4a5e4cfc-4e90-11e7-82e9-6fa6bff3f4e1.jpg)

**Comment by aesculus** [comment]
But doesn't the current behavior match what you want? The tabs just state what category you are viewing. The picker changes the car. All the content below the picker is car based.

I could reset the tab to the first one whenever you changed the picker if that would help you.

Otherwise what I am saying is that the app should be working exactly as you want, just that the tabbar is higher up.  I think mine looks cleaner but that's debateable (just like my main menu position :-)

**Comment by EVGrokker** [comment]
The behavior is correct, my comment was only with respect to appearance. 

In my mind, the function of a tab is to present related, but separated controls grouped in some meaningful way. There's an implication that each tab contains unique controls.

And I like visual hierarchies that tell the user a story. To me, the car selection is a higher level subject matter to the tab content, which contains all the specific details for that car.

But I'll defer to your decision.

**Comment by aesculus** [comment]
Happy now? I was saving this for something more important.

![image](https://user-images.githubusercontent.com/283364/27408593-5073b50a-5692-11e7-9afa-b9b98ffc095a.png)

**Comment by EVGrokker** [comment]
I applaud your good taste and high standards.

**Comment by EVGrokker** [comment]
v 1.2.0 (48)
I prefer the new layout, as it flows more logically. 

It would breathe a bit better if you could increase the amount of space between the tab bar and the content below. In the image below, there should be at least as much space above the 'Payload' and 'Climate Control' labels as there is below. The other two tabs should be adjusted as well.

![mycarsspacing](https://user-images.githubusercontent.com/26678403/27432276-c2c5ce52-570c-11e7-9957-7bb36ce26183.PNG)

**Comment by aesculus** [comment]
Fixed in V1.2 (49)

![image](https://user-images.githubusercontent.com/283364/27444753-3156d298-572c-11e7-8003-363b4926c454.png)
