### ISSUE TITLE
Current Trips: Selection and Action UI

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#454]
v 1.2.0 (38)

Comments:
- During the selection process, you have use the abbreviations `Del` for Delete and `Sel` for Select. These seem unnecessary, as there's plenty of room for the respective words. Suggest replacing the abbreviations with the actual action words. And, upon reflection, it probably makes sense to always use `Select`, even with the Delete action, since the action verb is in the upper right corner. So the sequence is always Select, then Action.
- When trips are displayed, I think the button at the right end of the first line (a gavel in the image below) should act to open the Edit Trip Status dialog. Even if the current image is a thumbs up/down, I still think that offering an express way to edit both status and rating of the trip would be beneficial.
- Similarly, I'd suggest that a long-press on the trip name opens the Edit Trip Details dialog. 
- Appearance: I'd like to see the same font style (smaller/lighter) for units applied here as in the Segment and Trip Browser summaries. That means that `mi`, `hrs`, `kWh` and `Whr/mi` would be displayed in the smaller/lighter font. 
- Metrics: Eventually, I'd like to see this trip summary section match the summary shown in the Trip Browser. There are some minor details to resolve. If you want to pursue this now, we can discuss those details.

![img_0743](https://user-images.githubusercontent.com/26678403/27032361-ba9e3800-4f31-11e7-9136-07a139b4ed2e.PNG)

**Comment by aesculus** [comment]
>During the selection process, you have use the abbreviations Del for Delete and Sel for Select. These seem unnecessary, as there's plenty of room for the respective words. Suggest replacing the abbreviations with the actual action words. 

This is a carryover from the older format that was supposedly responsive but not. You can see why it is needed though and also short in the iPad version

![image](https://user-images.githubusercontent.com/283364/27044598-f75831f8-4f52-11e7-8c46-263040ed802e.png)

>And, upon reflection, it probably makes sense to always use Select, even with the Delete action, since the action verb is in the upper right corner. So the sequence is always Select, then Action.

I was trying to point out that when you see Sel you were to expect the blue checkmark and when you say Del you were to expect a red - .

>When trips are displayed, I think the button at the right end of the first line (a gavel in the image below) should act to open the Edit Trip Status dialog. Even if the current image is a thumbs up/down, I still think that offering an express way to edit both status and rating of the trip would be beneficial.
Similarly, I'd suggest that a long-press on the trip name opens the Edit Trip Details dialog.

I can look into this.  Do you feel that there might be an issue with too many touchy things going on in the list item?  People could inadvertently touch where the rating icon is expecting the app to take them to the trip?

>Appearance: I'd like to see the same font style (smaller/lighter) for units applied here as in the Segment and Trip Browser summaries. That means that mi, hrs, kWh and Whr/mi would be displayed in the smaller/lighter font.

SMOP

>Metrics: Eventually, I'd like to see this trip summary section match the summary shown in the Trip Browser. There are some minor details to resolve. If you want to pursue this now, we can discuss those details.

Not now. I need to get the friggin app to actually work. :-(

**Comment by aesculus** [comment]
In V1.2 (39) 
- I scrapped Year, Car, Status and Name in these lists.
- Touching rating icon opens Trip Status dialog
- Labels are now a smaller font.
- App remembers your sort selection for the life of the session

>I'd suggest that a long-press on the trip name opens the Edit Trip Details dialog.

I am deferring this one for the time being.

**Comment by EVGrokker** [comment]
Current Trips looks fabulous.
