### ISSUE TITLE
Edit Waypoint dialog: Layout, text enhancements

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#455]
v 1.2.0 (38)

Minimum Stop Time and Minimum Arrival SoC look squished on a phone-sized device. Suggestions:
- There's plenty of real estate here to put each slider on its own line.
- I'm not sure why we need 'Minimum' associated with Stop Time.  If you're editing a waypoint, and you want to declare that you'll be there for xx minutes, what does 'Minimum' mean? Can we label it simply `Stop Time (mins)`?
- Arguably, the same logic could be applied to Arrival SoC. Why not simply label it `Arrival SoC`, then explain in help that it's a target number, and that EVTO will use it as a minimum goal when calculating?

![editwaypoint](https://user-images.githubusercontent.com/26678403/27033226-a4c00ab4-4f35-11e7-92e7-ea143d3280f8.PNG)

**Comment by aesculus** [comment]
I will make them full width and get rid of minimum. Hope they read you help.

**Comment by aesculus** [comment]
Updated in V1.2 (39) along with fixing spacing problem on location field.
