### ISSUE TITLE
Current Trips panel: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#458]
<h3>Current Trips</h3>
<i>Manages trips saved on your device. The Standard and Pro versions of EVTO support a single trip. Purchase a Multi-Trip subscription to enable storage of multiple trips on your device.</i> 

<p>Upon opening the Current Trips screen, the active trip is displayed in bold. To change active trips and return to the <strong>Plan</strong> screen, touch the title area of any trip. Current Trips may be viewed by Year, by Car or by Status. Within each view, categories may be collapsed and expanded using the <strong>+/-</strong> buttons. To edit a trip's status, touch the button to the right of the trip name, opening the Trip Status dialog. Trips whose status is <i>Taken</i> may be rated.</p>
<hr />
    
<h5><img class="panel_help_icon" src="css/images/popups/709-plus.png" />New Trip</h5>
<i>Displays the New Trip dialog</i>
<p>Creates a new trip. Standard version and Pro versions replace your current trip with a new trip. With a Multi-Trip subscription, the current trip is saved on your device before a new trip is created.</p>
<hr />
 
<h5><img class="panel_help_icon" src="css/images/popups/704-compose.png" />Edit Trip Details</h5>
<i>Opens the Edit Trip Details dialog</i>
<p>To review a trip's details, select this menu item, then touch the radio button corresponding to the trip, then touch <strong>Edit</strong> in the upper right corner to open the Edit Trip Details dialog. This dialog allows editing the departure time and date, payload, climate control, speed adjustment and power factor.</p>
<hr />
    
<h5><img class="panel_help_icon" src="css/images/popups/704-compose.png" />Edit Trip Status</h5>
<i>Opens the Edit Trip Status dialog</i>
<p>Toggle a trip's status between <i>Planned</i> and <i>Taken</i>. Completed trips may be rated for future reference.</p>
<hr />
    
<h5><img class="panel_help_icon" src="css/images/popups/808-documents.png" />Copy Trip as New<sup>†</sup></h5>
<i>Selects a trip to copy</i>
<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you would like to copy, then touch <strong>Copy</strong> in the upper right corner to clone the selected trip. Trip metrics will be recalculated using current conditions and the active car's default characteristics.</p>
<p class="caveat"><sup>†</sup>Requires purchase of Multi-Trip subscription</p>
<hr />
    
<h5><img class="panel_help_icon" src="css/images/popups/753-signpost.png" />Reverse Route<sup>†</sup></h5>
<i>Selects a trip to copy and reverse</i>
<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you would like to copy and reverse, then touch <strong>Reverse</strong> in the upper right corner to create a reversed clone of the selected trip. Trip metrics will be recalculated using current conditions and your selected car's characteristics.</p>
<p class="caveat"><sup>†</sup>Requires purchase of Multi-Trip subscription</p>
<hr />
    
<h5><img class="panel_help_icon list_icon" src="css/images/popups/854-list.png" />Group by Car</h5>
<i>Change grouping of current trips</i>
<p>Current trips are grouped by the car for which they were created. The Pro version of EVTO supports up to five car profiles.</p>
<hr />
    
<h5><img class="panel_help_icon list_icon" src="css/images/popups/854-list.png" />Group by Year</h5>
<i>Change grouping of current trips</i>
<p>Current trips are grouped by the year in which they were created.</p>
<hr />

<h5><img class="panel_help_icon list_icon" src="css/images/popups/854-list.png" />Group by Status</h5>
<i>Change grouping of current trips</i>
<p>Current trips are grouped by their status, <i>Planned</i> or <i>Taken</i>.</p>
<hr />
    
<h5><img class="panel_help_icon" src="css/images/popups/711-trash.png" />Delete Trips</h5>
<i>Selects trip(s) to delete</i>
<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) you would like to delete, then touch <strong>Delete</strong> in the upper right corner to remove the trips from your device.</p>
<hr />
    
<h5><img class="panel_help_icon" src="css/images/popups/755-filing-cabinet.png" />Archive Trips<sup>†</sup></h5>
<i>Select trips to archive. Archive Trips requires a Multi-Trip subscription.</i>
<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) you would like to archive, then touch Archive in the upper right corner. Archived trips are removed from the Current Trips list, but retained on your device for future use. Archived trips may be moved back to the Current Trips list from the Archived Trips panel.</p>
<p class="caveat"><sup>†</sup>Requires purchase of Multi-Trip subscription</p>
<hr />
    
<h5><img class="panel_help_icon" src="css/images/gray/754-scale.png" />Compare Trips<sup>†</sup></h5>
<i>Opens the Compare Trips screen</i>
<p>Compare route characteristics of selected trips. Select the trips of interest to display any of the following fields in tabular format:</p>
<ul>
<li>Status</li>
<li>Name</li>
<li>Rating</li>
<li>Stops</li>
<li>Distance</li>
<li>Trip Time</>
<li>Drive Time
<li>Charge Time</>
<li>Total kWh</li>
<li>Efficiency</li>
<li>Elevation Change</li>
<li>Average Speed</li>
<li>Weather Impact</li>
<li>EVTO Quality Index ('Q' factor)</li>
</ul>
<p class="caveat"><sup>†</sup>Requires purchase of Pro version and Multi-Trip subscription</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/gray/815-car.png" />Move to Car<sup>†</sup></h5>
<i>Assign existing trip to a different car</i>
<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you would like to assign to a different car, then touch <strong>Move</strong> in the upper right corner.</p>
<p class="caveat"><sup>†</sup>Requires purchase of Pro version and Multi-Trip subscription</p>
<hr />

<h5><img class="panel_help_icon" src="css/images/popups/702-share.png" />Share Trip</h5>
<i>Shares a trip with another EVTO user</i>
<p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you would like to share, then touch <strong>Share</strong> in the upper right corner. The <strong>Share Trip
</strong> dialog is displayed. Assign a 4-digit PIN, then touch <strong>Confirm</strong>. An email is composed with the unique trip ID and the assigned PIN. Enter the recipient's email address, then touch <strong>Send</strong>. The shared trip will be available to the recipient for 30 days.</p>
<hr />
    
<h5><img class="panel_help_icon" src="css/images/popups/703-download.png" />Import Trip</h5>
<i>Displays the Import Trip dialog</i>
<p>Enter the unique trip ID sent to you, the associated 4-digit PIN, then touch <strong>Import</strong>. The imported trip will be added to your list of current trips.</p>
<hr />
    
<h5><img class="panel_help_icon" src="css/images/popups/739-question.png" />Help</h5>
<i>Displays this help panel</i>
<p>You are here!</p>

**Comment by aesculus** [comment]
<i>Manages trips saved on your device. The Standard and Pro versions of EVTO supports a single trip. 
    Purchase a Multi-Trip subscription to enable storage of multiple trips on your device.</i>
    
    <h5><img class="panel_help_icon" src="css/images/popups/709-plus.png" />New Trip</h5>
    <i>Displays the New Trip dialog</i>
    <p>Creates a new trip. Standard version and Pro versions replace the current trip with your new trip. 
    Multi-Trip subscribers saves the current trip, and creates a new one.</p> 
    
    <h5><img class="panel_help_icon" src="css/images/popups/784-target.png" />Activate Trip</h5>
    <i>Selects a saved trip to activate</i>
    <p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you 
    would like to activate, then touch <strong>Activate</strong> in the upper right corner to load the 
    selected trip. To cancel, touch <strong>Cancel</strong> in the upper left corner.</p>
    
    <h5><img class="panel_help_icon" src="css/images/popups/704-compose.png" />Trip Inspector</h5>
    <i>Opens the Trip Inspector dialog</i>
    <p>Trip inspector help.</p>
    
    <h5><img class="panel_help_icon" src="css/images/popups/808-documents.png" />Copy Trip as New</h5>
    <i>Selects a trip to copy</i>
    <p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you 
    would like to copy, then touch <strong>Copy</strong> in the upper right corner to clone the selected trip. 
    Trip metrics will be recalculated using current conditions and your car's characteristics.</p>
    
    <h5><img class="panel_help_icon" src="css/images/popups/753-signpost.png" />Reverse Route</h5>
    <i>Selects a trip to copy and reverse</i>
    <p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you 
    would like to copy and reverse, then touch <strong>Reverse</strong> in the upper right corner to 
    create a reversed clone of the selected trip. Trip metrics will be recalculated using current 
    conditions and your selected car's characteristics.</p>
    
    <h5><img class="panel_help_icon list_icon" src="css/images/popups/854-list.png" />Group by Rating</h5>
    <i>Displays saved trips by assigned rating value</i>
    <p>Current trips may be grouped and displayed by the year in which they were created (the default view), 
    by the rating value you've assigned (0-5 stars), or by their status, 'Plan' or 'Taken'.</p>
    
    <h5><img class="panel_help_icon list_icon" src="css/images/popups/854-list.png" />Group by Status</h5>
    <i>Displays saved trips by trip status</i>
    <p>Current trips may be grouped and displayed by the year in which they were created (the default view), 
    by the rating value you've assigned (0-5 stars), or by their status, 'Plan' or 'Taken'.</p>
    
    <h5><img class="panel_help_icon" src="css/images/popups/711-trash.png" />Delete Trips</h5>
    <i>Selects trip(s) to delete</i>
    <p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) 
    you would like to delete, then touch <strong>Delete</strong> in the upper right corner.</p>
    
    <h5><img class="panel_help_icon" src="css/images/popups/755-filing-cabinet.png" />Archive Trips</h5>
    <i>Select trips to archive</i>
    <p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) 
    you would like to archive, then touch Archive in the upper right corner. Archive Trips requires a 
    Multi-Trip subscription. Archived trips are removed from the Current Trips list, but retained on your 
    device for future use.</p>
    
    <h5><img class="panel_help_icon" src="css/images/popups/702-share.png" />Share Trip</h5>
    <i>Shares a trip with another EVTO user</i>
    <p>Current trips are listed with radio buttons. Touch a trip's radio button to select the trip you 
    would like to share, then touch <strong>Share</strong> in the upper right corner. The <strong>Share Trip
    </strong> dialog is displayed. Assign a 4-digit PIN, then touch <strong>Confirm</strong>. An email is 
    composed with the unique trip ID and the assigned PIN. Enter the recipient's email address, then touch 
    <strong>Send</strong>. The shared trip will be available to the recipient for 30 days.</p>
    
    <h5><img class="panel_help_icon" src="css/images/popups/703-download.png" />Import Trip</h5>
    <i>Displays the Import Trip dialog</i>
    <p>Enter the unique trip ID sent to you, the associated 4-digit PIN, then touch <strong>Import</strong>. 
    The imported trip will be added to your list of current trips.</p>
    
    <h5><img class="panel_help_icon" src="css/images/popups/739-question.png" />Help</h5>
    <i>Displays this help panel</i>
		<p>You are here!</p>

**Comment by EVGrokker** [comment]
Ready for your review.

**Comment by aesculus** [comment]
I need my Edit Trip Status back
Need to add Compare Trips - from the old main help?

**Comment by EVGrokker** [comment]
Updated with Compare Trips section borrowed from Main. 

I don't think we ever had Edit Trip Status help. I'll work on it now.

**Comment by EVGrokker** [comment]
Updated to add Edit Trip Status line. Note that it needs the suitcase icon url.

**Comment by aesculus** [comment]
> Updated to add Edit Trip Status line. Note that it needs the suitcase icon url.

Did not make it here.

**Comment by EVGrokker** [comment]
Huh. Who knew you actually had to press 'Update Comment'.

**Comment by aesculus** [comment]
Updated in V1.2 (40)

**Comment by EVGrokker** [comment]
Updated with EVQI phi factor

**Comment by EVGrokker** [comment]
Updated with 'Q' factor.

**Comment by aesculus** [comment]
Updated in V1.2 (46)

**Comment by aesculus** [comment]
Updated in V1.2 (91)

**Comment by aesculus** [comment]
Updated with new subscription info
