### ISSUE TITLE
Archived Trips panel: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#459]
<h3>Archived Trips</h3>
<i>Manages archived trips saved on your device. The Standard and Pro versions of EVTO support a single trip. Purchase a Multi-Trip subscription to enable storage of multiple trips on your device.</i> 

<p>Archiving a trip allows you to keep a trip on your device, but removes it from the <strong>Current Trips</strong> screen. This is useful for trips you take infrequently, but  would like to keep available for future reference.</p>

<p>Touching a trip's title restores it to the Current Trips list and loads it as the currently active trip. To restore multiple trips to the Current Trips list, use the <strong>Restoring Trips</strong> feature described below.</p>
    
<h5><img class="panel_help_icon" src="css/images/popups/776-recycle.png" />Restoring Trips</h5>
<i>Select trips to restore</i>

<p>Archived trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) you would like to restore, then touch <strong>Restore</strong> in the upper right corner.</p>    
    
<h5><img class="panel_help_icon list_icon" src="css/images/popups/854-list.png" />Group by Car</h5>
<i>Change grouping of archived trips</i>
<p>Archived trips are grouped by the car for which they were created. The Pro version of EVTO supports up to five car profiles.</p>
    
<h5><img class="panel_help_icon list_icon" src="css/images/popups/854-list.png" />Group by Year</h5>
<i>Change grouping of archived trips</i>
<p>Archived trips are grouped by the year in which they were created.</p>

<h5><img class="panel_help_icon list_icon" src="css/images/popups/854-list.png" />Group by Status</h5>
<i>Change grouping of archived trips</i>
<p>Archived trips are grouped by their status, <i>Planned</i> or <i>Taken</i>.</p>    
    
<h5><img class="panel_help_icon" src="css/images/popups/711-trash.png" />Delete Trips</h5>
<i>Selects trip(s) to delete</i>
    
<p>Archived trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) you would like to delete, then touch <strong>Delete</strong> in the upper right corner.</p>
    
<h5><img class="panel_help_icon" src="css/images/popups/739-question.png" />Help</h5>
<i>Displays this help panel</i>
    
<p>You are here!</p>

**Comment by aesculus** [comment]
<i>The <strong>Archived Trips</strong> screen manages trips archived on your device. The standard and 
    Pro versions of EVTO support a single trip. Purchase a Multi-Trip subscription to enable storage of 
    multiple trips on your device.</i>

		<p>Archiving a trip allows you to keep a trip on your device, but removes it from the 
    <strong>Current Trips</strong> screen. This is useful for trips you take infrequently, but 
    would like to keep available for future reference.</p>
    
    <h5><img class="panel_help_icon" src="css/images/popups/776-recycle.png" />Restoring Trips</h5>
		<i>Select trips to restore</i>

		<p>Archived trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) you 
    would like to restore, then touch <strong>Restore</strong> in the upper right corner.</p>    
    
    <h5><img class="panel_help_icon list_icon" src="css/images/popups/854-list.png" />Group by Rating</h5>
    <i>Displays archived trips by assigned rating value</i>
    
    <p>Archived trips may be grouped and displayed by the year in which they were created (the default view), 
    by the rating value you've assigned (0-5 stars), or by their status, 'Plan' or 'Taken'.</p>
    
    <h5><img class="panel_help_icon list_icon" src="css/images/popups/854-list.png" />Group by Status</h5>
    <i>Displays archived trips by trip status</i>
    
    <p>Archived trips may be grouped and displayed by the year in which they were created (the default view), 
    by the rating value you've assigned (0-5 stars), or by their status, 'Plan' or 'Taken'.</p>
    
    <h5><img class="panel_help_icon" src="css/images/popups/711-trash.png" />Delete Trips</h5>
    <i>Selects trip(s) to delete</i>
    
    <p>Archived trips are listed with radio buttons. Touch a trip's radio button to select the trip(s) 
    you would like to delete, then touch <strong>Delete</strong> in the upper right corner.</p>
    
    <h5><img class="panel_help_icon" src="css/images/popups/739-question.png" />Help</h5>
    <i>Displays this help panel</i>
    
    <p>You are here!</p>  </div>

**Comment by EVGrokker** [comment]
Ready for your review.

**Comment by aesculus** [comment]
Updated in V1.2 (40)

**Comment by EVGrokker** [comment]
Added a description of the one-touch restore feature.

**Comment by aesculus** [comment]
Updated V1.2 (42)

**Comment by aesculus** [comment]
Updated with new subscription info
