### ISSUE TITLE
Prioritized feature list for v 1.3.0

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#46]
1. Drag and drop waypoint reordering in **Trip Summary** (issue #36)
2. Ability to add car-specific, user-supplied images as background for main panel (issue #2)
3. Redesign **Maintain Favorites** dialog to allow editing of waypoint details. (issue #28)
4. Add *Open in Google Maps* for local device, car browser (issue #39, #40)

**Comment by aesculus** [comment]
I am thinking that we have made so many changes to 1.1 that it should perhaps be 1.2 now.

**Comment by EVGrokker** [comment]
Agreed.

**Comment by aesculus** [comment]
OK. I am re-labeling this to V1.3

**Comment by EVGrokker** [comment]
These items have been folded into issue #290, Upcoming Release Objectives.
