### ISSUE TITLE
Archived Trips is broken when changing Group By

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#460]
v 1.2.0 (39)

Moving trips from Current Trips to Archive Trips works.

Opening Archived Trips initially shows the archived trips properly, but once you change the Group By item (Year, Car, Status) all trips vanish with the message "There are no trips to display for this car".

Exiting the Archived Trips screen and reopening it shows the archived trips again, but any attempt to change the sorting once again loses all displayed trips.

**Comment by aesculus** [comment]
OK. I must admit to not checking this out beforehand.

**Comment by aesculus** [comment]
Hah. This has been broken forever. Nobody, including me, has looked at sorting archive trips for eon's.

Fixed in V1.2 (40)

**Comment by EVGrokker** [comment]
Definitely improved, but not quite right.

After touching one of the Grouping options in the menu, Archived Trips are properly displayed, but the menu does not dismiss. I have to touch away from the menu to dismiss it.

Perhaps an unintended behavior, but something we need to address:

When displaying Archived Trips, touching a listed trip loads it and displays it in the Plan screen. That's nice, but the trip should be automatically moved back to the Current Trips list when this happens. It's not, it's still in the archived trips. Effectively, this should be a shortcut for Restore Trip.

And finally, when looking at archived trips, it should be possible to edit their ratings by touching the button to the right of the title, consistent with the behavior in the Current Trips screen.

**Comment by aesculus** [comment]
Fixed the menu thing in V1.2 (41).

I never intended to have it go to Plan with a click. Forgot to put that logic in.  So you want it to do that by default on row touch? Note when you do this via the menu you get a prompt first, so it should be consistent at least.

Not sure why the Status dialog is not showing.  Trying to debug that now.

**Comment by aesculus** [comment]
OK. Figured out why the Status dialog did not appear. I never intended the user to change the status or anything on an archived trip. The Status dialog is only a part of the Current Trips panel.  So I would need to generalize this if you wanted this feature on Archived Trips and also add it to the menu, which means more complications.

I vote to keep it not editable from the Archive panel.

**Comment by EVGrokker** [comment]
I'd like a single touch to restore it to active status, if that's OK with you. If you don't want to edit ratings from the Archive, I'm OK with that.

**Comment by aesculus** [comment]
Then I should remove the prompt from the menu then too?  If they select it and then select Restore there should be no warning/prompt?

**Comment by EVGrokker** [comment]
I think the behavior between the two screens should be consistent. In other words, in Current Trips, a single touch activates the trip and returns to the plan screen. Same for Archived Trips.

To archive a group of trips, you multi-select them, then get a prompt to confirm moving them to Archived. To unarchive a group of trips, you multi-select them, then get a prompt to confirm moving them to Current. 

Does that make sense?

**Comment by aesculus** [comment]
That works for me. I just have to force any trip showing on in Plans to be non archived. Trivial

**Comment by aesculus** [comment]
Version 1.2 (41) will force an archived trip to un-archived and open the Plans panel with the trip if selected.

The only panel that will open the Trip Status is the Current Trips via the menu or icon.
