### ISSUE TITLE
Current Trips menu: Edit Trip Status listed, but does nothing

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#461]
v 1.2.0 (39)

Edit Trip Status is listed in the menu, and transitions to the selection panel, but the Edit button does not open the dialog.

Suggest that since we have direct access to the Edit Trip Status dialog by touching the rating button, we simply remove this item from the menu.

**Comment by aesculus** [comment]
Nah. It was a bug in adding the icon select. Its fixed in V1.2 (40).

As an added bonus I fixed the same bug that was in Edit Trip Details in the Current Trips menu too.

**Comment by EVGrokker** [comment]
Oddly, getting to Edit Trip Details works for me in v 1.2.0 (39). it was just Edit Trip Status that didn't work.
