### ISSUE TITLE
Edit Trip Status dialog: Help text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#462]
<h3>Trip Status</h3>
<p><i>Modify a trip's status as <b>Planned</b> or <b>Taken</b>.</i></p>

<h5>Trip Status:</h5>
<ul>
<li><i>Planned:</i> Trip is still in the planning stages.</li>
<li><i>Taken:</i> Trip has been completed.</li>
</ul>

<h5>Trip Rating:</h5>
<p>After marking a trip <i>Taken</i>, the <strong>Trip Rating</strong> section becomes active, allowing you to apply a thumbs up or thumbs down rating to the trip for future reference.</p>

**Comment by aesculus** [comment]
> Review a trip's statistics

Not really statistics or was this a typo?

**Comment by EVGrokker** [comment]
Take 2 ready for your review.
