### ISSUE TITLE
Should Ripple Date Apply to Segments Start Times?

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#463]
The ripple date/time feature shoves all following segments down whatever the delta is when a segment or trip is changed. I am not sure if this is the correct behavior we want.

Clearly if the date changes you would want to shove the following segments accordingly.

But what if the start time just changes? For example the user gets a late start and still wants the other segments to start at the same time?  Today if you increase the trip or a segment by 15 minutes, the following segments are pushed out the same amount.  

It would seem to me there should be some logic on when the ripple actually happens. This topic is to debate what that logic might be.

**Comment by EVGrokker** [comment]
I think the following ripple logic would be acceptable:
- If the affected segments currently start on the same day, the delta should be minute-for minute. In other words, if segment 1 starts at 8am and segment 2 starts at 5pm on the same day, and the user edits segment 1 to start at 9am, then segment 2's start time should ripple to 6pm. This insures that back-to-back segments on the same day won't overlap.
- If the affected segments start on different days, the delta should be day for day. In other words, if segment 1 starts at 8am on Monday, and segment 2 starts at 8am on Tuesday, changing segment 1 to 9am on Monday has no effect on segment 2's start time or date. If segment 1 changes from 8am Monday to 8am Tuesday, then segment 2 changes from 8am Tuesday to 8am Wednesday, retaining the one-day separation between start times.
- I can cover this in both the local help and a tutorial.

**Comment by aesculus** [comment]
OK. Sounds good.  I will see if I can code this up

**Comment by aesculus** [comment]
Implemented in V1.2 (41)

**Comment by EVGrokker** [comment]
Same issue as #428.
