### ISSUE TITLE
Help panels: Dragging past end causes map to spring

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#465]
While the Trip Browser help is displayed, dragging past the end of the available help causes the underlying map panel to spring upward and bounce back. The preferable behavior would be either:
- The help content springs upward and bounces back
- No springiness.

This applies to the other help panels that use the same dialog structure as Trip Browser.

**Comment by aesculus** [comment]
These springy things are inherent in iOS and my UI framework. Interestingly they don't do this on Android.  I will look for a solution but nothing has cropped up yet.

**Comment by EVGrokker** [comment]
If it were the help panel that sprung it wouldn't be an issue. It seemed like you resolved a similar issue on the Main page.

**Comment by aesculus** [comment]
No. It's still there, at least for me. Try it yourself.

Just press and drag up on the picture and see if you don't see a gray background that springs back.  This does not happen on Android.

**Comment by aesculus** [comment]
Well the solution for this was right under my nose. I was not looking in the correct place.

Fixed in V1.2 (42)

**Comment by EVGrokker** [comment]
Yay! Much nicer.
