### ISSUE TITLE
Current Trips list: Trip type icon obscured

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#467]
v 1.2.0 (41)

When viewing a list of trips, if the trip name is long enough, and the trip is either segmented or a round trip, the additional icon appended to the trip name is partially obscured.

In the image below, the round circle at the end of the final listed trip is only partly visible.

![obscuredtripicon](https://user-images.githubusercontent.com/26678403/27180015-861c9482-518e-11e7-88d7-9f33bd18f520.PNG)

**Comment by aesculus** [comment]
Fixed in V1.2 (42)

![image](https://user-images.githubusercontent.com/283364/27190913-e0ea3434-51aa-11e7-97b1-103efa5776a4.png)
