### ISSUE TITLE
Real world trip recreated: Business Insider

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#469]
_We drove the Tesla Model X from San Francisco to New York in just under a week to see what it's really like to take an all-electric vehicle on an aggressive cross-country road trip. We limited our charging to Tesla's network of US Supercharger stations, of which there are 861. Each day we travele..._

[http://flip.it/gtRXh2](http://flip.it/gtRXh2)

<hr/>
I recreated this trip under 1.2.0 (41). I guessed it's a 100D based on the screen shot of the SoC at 3:48. I used default SA and PF with a payload of 350 lbs. Here's the final map after optimization:

![sf-nymap](https://user-images.githubusercontent.com/26678403/27200998-31be6bcc-51d9-11e7-9cb3-eb8dfda271a4.PNG)

And here are the steps I took to create it:

- New Trip: San Francisco CA - Manhattan NY (Manual)
- Added charger stops at Las Vegas NV, Salt Lake City, Denver, Council Bluffs IA, Country Club Hills, Macedonia (best guess based on verbal description of overnights).
- Segmented at each of those charging stops
- Optimized each segment manually

Here's the Trip Browser summary (which just barely fits into a single screen). That summary looks excellent. Note that the average speed shows 79mph, which seems high, but many of the flat states have higher speed limits. 

![sf-nytripbrowser](https://user-images.githubusercontent.com/26678403/27200849-a4eb62fe-51d8-11e7-917b-e055a6badb29.PNG)

This is probably a good candidate for a tutorial.

**Comment by EVGrokker** [comment]
Interesting stat emerges from this trip: note that they had 43 hours behind the wheel, and 11.5 hours of en-route supercharging (not including overnight segment charging).

Assuming a 90% SoC upon departure each segment, that's a ratio of 16 minutes of en route charging per hour of driving.

**Comment by EVGrokker** [comment]
Here's the saved SF-NY Business Insider trip after segmenting for each overnight, but before optimizing:

>Car Data: X100D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 0, Rear CC: 0, Bat Life: 100, Payload: 159, PF: 0, SA: 0, Temp: 21 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (41) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Las Vegas, NV Supercharger, [o5w817t940oi0diebofxr]

**Comment by aesculus** [comment]
I wonder how long they charged at each stop. I am suspicious that they did not charge to 100% or close to it.

But if they left when the car told them too then it was probably close to ideal.

**Comment by aesculus** [comment]
Can you share that trip?

**Comment by EVGrokker** [comment]
The pre-optimized trip is 3 comments above.

**Comment by aesculus** [comment]
>note that they had 43 hours behind the wheel

They did drive fast (43 hrs vs Google's estimate of 51 hrs). I suspect a SA of at least 5 would probably be appropriate. That of course would bring up the charging times, probably closer to what they actually used.

**Comment by aesculus** [comment]
>Optimized each segment manually

You don't need to do that anymore because it's all done at once now. However:
-  You need to visit them in order to get the calcs done and distributed
- The second optimize could improve the trip some. Hard to say by how much

**Comment by EVGrokker** [comment]
I'm closing all issues tagged Test Cases, as they exist only for reference and are not directly involved with proposed app revisions. Locating test cases is merely a matter of selecting 'test cases' from the Labels list. They are still available for comment and updates.
