### ISSUE TITLE
Waypoint Inspector: Displayed SoC graphic misaligned

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#470]
While recreating the Business Insider trip in #469, before the segmenting or optimization, I observed that the energy deficits are not aligned properly within the battery icon:

![img_0756](https://user-images.githubusercontent.com/26678403/27201801-44df7054-51dc-11e7-9672-91a720160efe.PNG)

**Comment by aesculus** [comment]
I thought we forced all negatives to be 0 on the battery.

Also when I optimized that segment came back with not superchargers for me but no errors either.  Have not dug into the depth of it yet.

Did you get chargers for that segment?

**Comment by aesculus** [comment]
OK. I optimized again and this time it came up with chargers.

I noticed that when I switch segments the bounds of the map don't change. Need to fix that.

**Comment by EVGrokker** [comment]
After segmenting at the 7 overnight SCs, I then optimized the first segment, then went through each segment in order to allow each of them to optimize. After visiting each segment, all segments has auto-assigned chargers. The first image of the map in #469 shows the pinholes where all of the SCs were assigned. So yes, EVTO supplied chargers for that segment. 

The screen shot was early in the construction process.

**Comment by aesculus** [comment]
Here is what I got after the second optimize.  Note it sort of cheated them on the first stop and arrive at HR kind of lean, although I would have taken it.

![image](https://user-images.githubusercontent.com/283364/27202143-3c34ef76-51d5-11e7-8e6f-c14841d1312b.png)

**Comment by aesculus** [comment]
![image](https://user-images.githubusercontent.com/283364/27202166-5f44db2a-51d5-11e7-88b0-85f69eb3bd44.png)

**Comment by aesculus** [comment]
![image](https://user-images.githubusercontent.com/283364/27202204-83babc90-51d5-11e7-80fd-28bfc4bedbdf.png)

**Comment by EVGrokker** [comment]
All that hard work on the trip browser was worth it. That looks awesome on both devices.

**Comment by aesculus** [comment]
I think I will dig up these guys emails and send them this last picture and explain the project to them

**Comment by EVGrokker** [comment]
v 1.2.0 (42)

I forced this error, and it appears that the red and gold striped battery fill is properly rendered within the battery outline. There's a gap at the left end between the outline and the fill, but it's a minor concern.

**Comment by EVGrokker** [comment]
v 1.2.0 (48)
This looks correct now.
