### ISSUE TITLE
Map Bounds Not Reset When Selecting a Segment From the Trip Browser

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#471]
It also appears that the bounds are not locked when moving from segment to segment.

**Comment by EVGrokker** [comment]
v 1.2.0 (42)
I'm observing that in the Trip Browser, touching a segment once activates it, with its route rendered in blue and its waypoint pins displayed. However, the map is not recentered. Touching the segment a second time in the Trip Browser causes the map to recenter. 

The preferred behavior would be for the map to recenter along with activation on the first touch.

**Comment by aesculus** [comment]
This will all get resolved when I revisit this bounding problem.

**Comment by aesculus** [comment]
The bounds were addressed in V1.2 (45). This will get more attention when I work on the auto recalc.

**Comment by aesculus** [comment]
I am still not completely happy with how this is working yet.  It does not see that the map bounds stick after a change unless you close the app.

**Comment by aesculus** [comment]
Fixed in V1.2 (53)
