### ISSUE TITLE
Consumption graph: Efficiency popup formatting

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#472]
v 1.2.0 (42)

For the two popups, suggest a minor format tweak:
- Rated: `Rated: 350 kW/mi` (all on one line, no parens)
- Avg: `Avg: 331 kW/mi` (all on one line, no parens)

If you feel you need to break them into two lines to fit, suggest:
```
Rated:
350 kW/mi
```
```
Avg:
331 kW/mi
```

**Comment by aesculus** [comment]
This? Note I fixed the same popup on the corners of the red line too.

![image](https://user-images.githubusercontent.com/283364/27238582-51bde2d2-5282-11e7-84f8-44ab118b0352.png)

**Comment by aesculus** [comment]
Whoops. The labels were wrong too. It's not kW/mi but Whr/mi

![image](https://user-images.githubusercontent.com/283364/27238700-cb2ab35c-5282-11e7-8bad-c84a09faf7d9.png)

**Comment by EVGrokker** [comment]
I think they would look better with a colon after 'Rated' and 'Avg'.

**Comment by aesculus** [comment]
OK.

**Comment by EVGrokker** [comment]
v 1.2.0 (43)

Notice that the Consumption tab popups can be displayed such that they're partially off-screen on a phone-sized device.

What would you think about always rendering the popup in the center of the screen, but including a circle around the touched area to identify the part of the graph referred to by the popup?

![consumption](https://user-images.githubusercontent.com/26678403/27260106-dacec10e-53e0-11e7-972d-f66e7168fa5e.jpg)

**Comment by aesculus** [comment]
I found a hack on the web to solve the problem in V1.2 (44). Basically if the tooltip is on the edge, it mirrors its location.

![image](https://user-images.githubusercontent.com/283364/27261661-6305392a-53fc-11e7-938a-deac9b3e3bcf.png)
