### ISSUE TITLE
New Trip dialog: Currently active car

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#473]
When initiating a new trip, it would be very helpful to know the currently active car. I propose adding a field or control at the top of the New Trip dialog, just below the header.

Two alternatives for implementation:
1. Add a text field above the origin edit field with the name of the currently active car. No need to give it a label, as the user will recognize their car names.
2. Add a picker control above the origin edit field displaying the currently active car, and allowing the user to select the car for which the trip will be created. At that point, the active car would continue to be the one selected for the new trip.

Option 2 is definitely preferable, as requiring the user to switch back to the Main screen, then open My Cars to switch cars, then initiate a new trip is awkward. If you need additional real estate, I think you can safely remove the 'Destination Charger Type:' label.

![newtrip car](https://user-images.githubusercontent.com/26678403/27230665-36c1050a-526d-11e7-9a30-bd1f6fb4c816.jpg)

**Comment by aesculus** [comment]
This OK?

![image](https://user-images.githubusercontent.com/283364/27235913-9ffaf1d4-5277-11e7-95a4-0d14b8cb1165.png)

**Comment by EVGrokker** [comment]
Perfect.

**Comment by aesculus** [comment]
Implemented in V1.2 (43).  Selected car now becomes the current car and the new trip will be allocated to that cars trips.

Note this option will not display when you are continuing and existing trip (ie Add Segment).

**Comment by EVGrokker** [comment]
Looks great.
