### ISSUE TITLE
Comparing trip variables to score different driving strategies

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#474]
I've been playing around with an idea to come up with a "trip quality" index that factors in the amount of time one spends charging versus driving, as well as evaluating total trip time.

In this context, a 'perfect' trip would be one requiring no charging stops and no limits on how fast you drive. In other words, the higher the quality index, the closer the experience to a traditional ICE trip where you're not worried about refueling.

If we can come up with a good algorithm for ranking trips, this is a factor that could be added to the Compare Trips matrix. Or, it could be added to the trip summary in the Trip Browser as a secret sauce EVTO quality index.

The formula I've arrived at for this initial pass incorporates charging time, elapsed time and distance driven.

The resulting number is between 0 and 1, with 1 representing a 'perfect' trip.

Here's the formula:

**1.00 - (charge time/elapsed time) - (extra minutes/best minutes) - (extra miles/best miles)**

This trip tweaks Speed Adjust, from Seattle to Bend:
**SA**: Speed Adjust | **Mi**: Distance | **CT**: Charging time  | **ET**: Elapsed time

<table>
  <tr>
    <th>SA</th>
    <th>Mi</th> 
    <th>Stops</th>
    <th>CT</th>
    <th>ET</th>
    <th>Score</th>
  </tr>
  <tr>
    <td>-10</td>
    <td>329</td> 
    <td>2</td> 
    <td>:25</td>
    <td>7:25</td>
    <td>.68</td>
  </tr>
  <tr>
    <td>-5</td>
    <td>329</td> 
    <td>2</td> 
    <td>:37</td>
    <td>6:59</td>
    <td>.72</td>
  </tr>
  <tr>
    <td>0</td>
    <td>329</td> 
    <td>2</td> 
    <td>:37</td>
    <td>6:28</td>
    <td>.80</td>
  </tr>
  <tr>
    <td>+5</td>
    <td>329</td> 
    <td>2</td> 
    <td>:44</td>
    <td>6:09</td>
    <td>.83</td>
  </tr>
  <tr>
    <td>+10</td>
    <td>329</td> 
    <td>2</td> 
    <td>:50</td>
    <td>5:52</td>
    <td>.86</td>
  </tr>
  <tr>
    <td>+15</td>
    <td>351</td> 
    <td>3</td> 
    <td>:60</td>
    <td>5:54</td>
    <td>.73</td>
  </tr>
</table>

This tells us that there's a rising quality to this trip as we travel over the speed limit until somewhere between 10 and 15 over, which triggers the need for an extra charging stop that takes us off the optimal route.

Here's another way to use the trip quality index - comparing two trips to the same destination which take different routes.

This trip is from Seattle to Twisp WA. There are two possible routes, each using a different SC.
**SA**: Speed Adjust | **Mi**: Distance | **MPH**: Speed | **CT**: Charging time  | **ET**: Elapsed time

<table>
  <tr>
    <th>SA</th>
    <th>Mi</th> 
    <th>MPH</th> 
    <th>Stops</th>
    <th>CT</th>
    <th>ET</th>
    <th>Score</th>
  </tr>
  <tr>
    <td>0</td>
    <td>224</td> 
    <td>51</td> 
    <td>1</td> 
    <td>:15</td>
    <td>4:41</td>
    <td>.88</td>
  </tr>
  <tr>
    <td>0</td>
    <td>208</td> 
    <td>52</td> 
    <td>1</td> 
    <td>:15</td>
    <td>4:16</td>
    <td>.94</td>
  </tr>
</table>

This tells us that the shorter route is better (no surprise). However, if the shorter route was significantly slower, this would skew the results in favor of the longer, but faster alternative.

If we were rating this trip as a simple excursion, a score of 94 suggests high potential for an enjoyable outing.

**Comment by aesculus** [comment]
Way cool.

**Comment by aesculus** [comment]
I am not sure yet how to implement this. I don't really have a way to tag trips that are the same. That is the user's responsibility in Compare Trips to only compare trips they know to be equal.

As far as getting close to an ICE trip, would that not always be the shortest time?  I do have a goal and placeholder for optimizing on time, energy, distance,  and stops. I suspect when people use it, they will discover that minimum trip time is almost always the best choice. The minimum energy has value if you have to pay for the electricity.

Minimum stops might force some real long charge times so users can skip chargers. That's OK if you on a single charge trip and were planning on a meal at the charge and were going to be waiting anyway. Minimum distance I cannot think of a good reason for.

**Comment by EVGrokker** [comment]
Here's how I'm thinking about this.

This is an opportunity to introduce some unique and proprietary metrics that none of the other planners have. It's also an opportunity to come up with a fun name tied to EVTO. I don't have anything definite in mind yet, but something like the 'EVTO Index' or 'EVTO Rating' that clearly ties to the app.

I see the implementation in distinct stages. 

Initially, I'd say it's only for single trips, meaning that the formula is simplified: **1 - (CT/ET) * 100**. All this tells you is the proportion of time spent charging, versus behind the wheel, where we all want to be. (It doesn't penalize non-charging waypoint stops.) It becomes part of the Segment Browser and Trip Browser summaries with a distinctive icon. (We can discuss the formula separately if needed.)

The number would be a peer to efficiency and consumed energy, so it would logically be grouped with them.

The second stage implementation would add another comparison metric in the Compare Trips feature. The formula would factor in the time and distance penalties as described in the initial description. Because this number won't match the single trip rating, we would come up with a different name or description for the metric when comparing trips. 

Stage 1 you could implement anytime. 

Stage 2 would be later, when the Compare Trips feature is getting a makeover.

**Comment by aesculus** [comment]
We already have a rating which is just a subject vote.

So I would go for the EV Index, EV Efficiency Index,  or something that helps them see how efficient they are. Something shorter of course if possible so we have room for it.

I think right now ET is wait time in it so that would have to be backed out? Or is that now the same as just CT/DT where DT is the drive time?

**Comment by EVGrokker** [comment]
Terminology (all of these are already included in segment summary):
**CT**: Charging Time (allocated to charging while en route)
**DT**: Driving Time (behind the wheel)
**ET**: Elapsed Time (segment origin to destination)

What we want to represent with the number is the relative 'pain' of having to stop to recharge in a given segment.

A segment with no charging stops has a perfect score of 100.
A segment with one charging stop is penalized by the ratio of the amount of time spent charging to the amount of time spent either a) behind the wheel (DT) or b) from origin to destination. (ET).

The argument for a) (CT/DT) is that the pain penalty is only compared to the behind-the-wheel driving time, completely ignoring any non-charging waypoint stops. 

The argument for b) (CT/ET) is that the pain penalty is compared to the entire segment time. For example, if I stop to go shopping for an hour somewhere, added to a three-hour trip, the proportion of time spent charging is less, because the one-hour shopping stop is now considered part of the trip, so it diminishes, and the overall score is higher. In fact, in looking at the numbers in the table below, mid-90s is probably about as high a score as you could expect. 

I'd prefer the range have as much breadth as possible, so I'd vote for b), CT/ET.

The argument against both of these is that if I manage to combine charging with eating, I essentially get a pain-free trip, since I would have stopped for a food break anyway. But let's not go there.

Let's consider a segment with a non-charging waypoint stop, say Starbucks. This should be transparent to the index, since the user opted for it, and it doesn't diminish the quality of the trip. In fact, it probably enhances it (bathroom stop, snack).

Here's a sample trip with a single, short charging stop, no Starbucks:
Seattle - Portland, +10 SA
<table>
  <tr>
    <th>SA</th>
    <th>Mi</th> 
    <th>Stops</th>
    <th>CT</th>
    <th>DT</th>
    <th>ET</th>
    <th>1-CT/DT</th>
    <th>1-CT/ET</th>
  </tr>
  <tr>
    <td>+10</td>
    <td>174</td> 
    <td>1</td> 
    <td>:15</td>
    <td>2:30</td>
    <td>2:45</td>
    <td>90%</td>
    <td>91%</td>
  </tr>
</table>

Seattle - Portland, +10 SA, 1-hour non-charging waypoint added (adds 10 mins to DT, 60+10 to ET)
<table>
  <tr>
    <th>SA</th>
    <th>Mi</th> 
    <th>Stops</th>
    <th>CT</th>
    <th>DT</th>
    <th>ET</th>
    <th>1-CT/DT</th>
    <th>1-CT/ET</th>
  </tr>
  <tr>
    <td>+10</td>
    <td>174</td> 
    <td>1</td> 
    <td>:15</td>
    <td>2:40</td>
    <td>3:55</td>
    <td>91%</td>
    <td>94%</td>
  </tr>
</table>

**Comment by aesculus** [comment]
> The argument against both of these is that if I manage to combine charging with eating, I essentially get a pain-free trip, since I would have stopped for a food break anyway. But let's not go there.

Why not? EV bigots would claim this is exactly what you should do. In fact they would plan their trip around such an event.  Which sort of leads to an interesting optimization question which is related to the debate for issue #103.

**Comment by aesculus** [comment]
Here are some icon candidates:
![726-star 2x](https://user-images.githubusercontent.com/283364/27264702-38f7a9e6-5439-11e7-8a10-000799b6ac53.png)
![776-recycle 2x](https://user-images.githubusercontent.com/283364/27264706-4e2fb3a8-5439-11e7-9223-829be1458d39.png)
![833-diamond 2x](https://user-images.githubusercontent.com/283364/27264711-68d42626-5439-11e7-8bfc-101792dbc7a0.png)
![870-smile 2x](https://user-images.githubusercontent.com/283364/27264713-85a843fe-5439-11e7-8e40-6bf7455d27f2.png)
![970-medal 2x](https://user-images.githubusercontent.com/283364/27264721-b24b8a92-5439-11e7-9966-75a41c0c4a1f.png)
![955-trophy 2x](https://user-images.githubusercontent.com/283364/27264724-c2f4347a-5439-11e7-8c51-434ddbb074fd.png)

**Comment by EVGrokker** [comment]
>> The argument against both of these is that if I manage to combine charging with eating, I essentially get a pain-free trip, since I would have stopped for a food break anyway. But let's not go there.

>Why not? EV bigots would claim this is exactly what you should do. In fact they would plan their trip around such an event.  Which sort of leads to an interesting optimization question which is related to the debate for issue #103.

I disagree. 

This proposal is about adding another metric that is the product of a formula representing a ratio between time spent charging and time spent en route. It's an objective measurement, intended to enable a quick 'apples to apples' comparison with other trips. In that respect, it's the same type of metric as consumed energy, average efficiency or average speed. It's simply a computed number describing a characteristic of the trip.

#103 proposes to allow users more influence on how EVTO calculates energy requirements. "I'm planning to have a meal during this stop, so even though EVTO told me I only need to charge for 20 minutes to reach my next stop, I'm informing EVTO that I plan to spend 60 minutes charging at this stop."

If a user plans a particularly clever trip masking charging stops as coffee breaks, bathroom breaks and lunch breaks, declaring that trip to be every bit as efficient as an ICE trip, that's a subjective judgment, because EVTO has no way of knowing how they plan to spend their time while the car's charging. That's the can of worms I was trying to avoid opening. If an EV bigot judges a trip to be a prizewinner, they should apply a 'thumbs up' to reward themselves. The app has no opinion about the meaning of thumbs up/thumbs down. That's a judgment with meaning only to the user.

I think the majority of EVTO users would find the number interesting. A minority (EVBs, quants, nerds) would think it doesn't go far enough. I'm aiming for the 80%.

PS - I like the diamond.

**Comment by aesculus** [comment]
>If a user plans a particularly clever trip masking charging stops as coffee breaks, bathroom breaks and lunch breaks, declaring that trip to be every bit as efficient as an ICE trip, that's a subjective judgment, because EVTO has no way of knowing how they plan to spend their time while the car's charging. 

Actually that IS the interesting optimization question.  "I plan on needing a meal, where should I do that to get the highest score?".

Any if we go for ET and CT shouldn't the formula be:

(ET-CT)/ET * 100

Basically no charge get's you a score of 100.  If you start off empty and need a charge just to get where you are going you could end up with a score much less than 100, and if you charge at a real slow charger you could end up negative, taking more time to charge than the time it took to drive, even without the 'other stuff' time.

**Comment by EVGrokker** [comment]
1) Great minds think alike. I believe your formula and mine are equivalent.

2) I like the feature you're describing. It's related to #252, the idea of scheduling stops based on user preferences. My 'can of worms' concern would be the UI for such a feature, indicating timeframe flexibility, length of stop, etc. Your idea to propose optimized stops is a legitimate enhancement opportunity unto itself.

3) My proposed index score is simply an additional data point on a segment and trip summary, without requiring any additional UI input from the user.

>Basically no charge gets you a score of 100. If you start off empty and need a charge just to get where you are going you could end up with a score much less than 100, and if you charge at a real slow charger you could end up negative, taking more time to charge than the time it took to drive, even without the 'other stuff' time.

Agreed, though with the current model you'd really have to go out of your way to set up a trip with an empty tank. And charging at a slow charger, like a destination charger, should incur a penalty - that's the point of the index. One 15 min charging session imposes a tiny penalty. The more charging time is required, the higher the penalty on the score.

**Comment by aesculus** [comment]
So is this the formula then?

(ET-CT)/ET * 100

**Comment by EVGrokker** [comment]
👍

**Comment by aesculus** [comment]
> It becomes part of the Segment Browser and Trip Browser summaries with a distinctive icon. 

Where exactly do you want to place this? Not much room on these browsers.  It can fit in the line with the car name but the others are pretty maxed out and I don't want to add another line.

It could probably fit in the third line too as that one is probably not going to grow much based on trip length.

**Comment by aesculus** [comment]
I am leaning towards the first row with the car name.

**Comment by EVGrokker** [comment]
I was visualizing at the end of the line with consumption, efficiency and average speed. It  looks like it would fit physically, and definitely logically. That's the 4th line of the trip browser, 3rd line of the segment browser.

**Comment by aesculus** [comment]
Maybe. The kWh could grow and it might look crowded. Let me mock both up to see how it looks.  Since these are all text based and the new one is an icon with text, it's not going to balance out too well. Where do you want it?

**Comment by EVGrokker** [comment]
With icon, left edge works best, since it would be above CT, and they're related. Also doesn't break up the flow of numbers and text as it would on the right edge. 

The other option would be to come up with a textual abbreviation instead of using an icon and stick it on the right end. 

And, we need a cool name for it, since no one else is doing it.

**Comment by aesculus** [comment]
You could also make an acronym for it.

**Comment by EVGrokker** [comment]
EFI: EVTO Freedom Index
EXR: EVTO X-factor Rating
EQI: EVTO Quality Index
EQR: EVTO Quality Rating
ESR: EVTO Secret Rating

**Comment by EVGrokker** [comment]
EXP: EVTO X-factor Performance

**Comment by aesculus** [comment]
EQI or EVQI

**Comment by EVGrokker** [comment]
Another idea. Let's be purposefully vague with this, not explain it very well, and use a mysterious nonsense Greek symbol for it. (I'm serious). Let's have fun with it.

**Comment by EVGrokker** [comment]
ξ
ψ
ϔ

(These are all Unicode)

**Comment by EVGrokker** [comment]
How about referring to it as EVQI, and we use a symbol in the summaries for brevity and mystique. The help will refer to the EVQI factor, but it would be displayed as a percentage with the symbol: 

94% [symbol]

**Comment by EVGrokker** [comment]
Theta: A special function of several complex variables.
θ

**Comment by aesculus** [comment]
There is also pi which is a funky ratio Π

**Comment by aesculus** [comment]
https://en.wikipedia.org/wiki/Golden_ratio

**Comment by aesculus** [comment]
&Phi;

I think so.  It would depend on what Apple does with it but the above is a standard HTML rendition.

**Comment by aesculus** [comment]
Here is the lowercase one if you like it better.

&#981;

**Comment by EVGrokker** [comment]
I do prefer the lower case rendition because it doesn't conflict with the upper case being used in multi-phase power systems which are vaguely related. It's quirky, unique, fun. 

Are you OK with all of this malarkey?

**Comment by aesculus** [comment]
Sure. Now that we have honed into the small phi symbol, where again do you want to place it:

<b>&#981;:93</b>

**Comment by aesculus** [comment]
Or do you want:

<b>93</b>&nbsp;&#981;

**Comment by EVGrokker** [comment]
I'd put it at the right end of the line, after avg speed. All the other numbers look familiar, the last one will be a head-scratcher at first. 

Formatting: Logically, I think it makes more sense as [symbol: value], because you would read it as "this trip has a phi factor of 93." 

Visually, I'd rather see the units after the number for layout consistency with the others on that route - [value symbol], with the number in bold and phi in the smaller/lighter font matching the others. 

My vote would be [value symbol], no colon, smaller/lighter phi.

**Comment by aesculus** [comment]
I'll let you check the math.

![image](https://user-images.githubusercontent.com/283364/27308406-41720f10-5503-11e7-8c90-3d26b4b35db6.png)

**Comment by EVGrokker** [comment]
I agree with your math.

That's the capital phi - can you use the lower case phi?

I like the balance of the summary section - it looks more stable with each line wider than the last.

**Comment by EVGrokker** [comment]
Actually, I've been looking at different lower-case phi - it looks more like a stylized lower-case p: 𝞿

**Comment by aesculus** [comment]
Here you go. Yours is actually the current version (loopy one) vs my old school classic one.

![image](https://user-images.githubusercontent.com/283364/27309124-343c5fd6-5507-11e7-8753-f347ae9ef5e6.png)

Where do we want to apply this on Current Trips?

![image](https://user-images.githubusercontent.com/283364/27308937-2a70ce7a-5506-11e7-9f74-add4ad180c20.png)

**Comment by EVGrokker** [comment]
Current Trips: I'd put it after Whr/mi, before Car, in the third row.

**Comment by aesculus** [comment]
OK. That is what I thought too.

**Comment by aesculus** [comment]
![image](https://user-images.githubusercontent.com/283364/27309886-6511dbbe-550b-11e7-98b2-830498bc7421.png)

**Comment by aesculus** [comment]
This thing is going to cause a lot of controversy.  Hope we have it right. I just tried 3 scenarios with the Disneyland Trip:
- The 75 was swapping an early SC for a J adapter that tool 60 minutes to charge about 10%
- Then I tried removing it and seeing what would happen. The car made it to the next charger but at 10% SOC and got a score of 88
- Then I optimized and it filled in a charger and again got a score of 88.

**Comment by EVGrokker** [comment]
We'll call it experimental if there's flak. :)

I don't want to assume that you've already taken care of the trip summary, but that would be an average of the individual segment phis, right?

**Comment by aesculus** [comment]
>I don't want to assume that you've already taken care of the trip summary, but that would be an average of the individual segment phis, right?

Yes. Picture above but it was a one segment trip. Math is pretty straight forward.

Now off to fold this into Compare Trips.

**Comment by aesculus** [comment]
iPad Version. Do you want symbol or acronym?

![image](https://user-images.githubusercontent.com/283364/27310185-5e40e116-550d-11e7-897f-d0ab6a418310.png)

**Comment by EVGrokker** [comment]
I like the enigmatic phi symbol for the iPad. The help text will describe the acronym.

**Comment by aesculus** [comment]
Off to you to describe this all via the various help panels. The functionality is implemented in V1.2 (45) for Segment Browser, Trip Browser, Current Trips, Compare Trips and Compare Chart

**Comment by EVGrokker** [comment]
The lower-case phi is rendered as an upper-case phi in all locations on an iPhone. If it's rendered correctly on Android as you pictured it above, we need to select a symbol that will render the same on all platforms.

I was trying to avoid the upper-case phi because it's the symbol for phase in electricity, which is vaguely related to charging and has the potential for confusion.

**Comment by EVGrokker** [comment]
Worst case, we can use the upper case phi, but since we're not yet commited, here are a couple of other alternatives I found, which would tie to the 'Q' in Quality Index:

Qoph (Phoenician 'Q', means '100' in Hebrew)
HTML for Qoph: `&#x10912;`
<p>&#x10912;</p>

Greek 'Q' (Qoppa)
HTML for Qoppa: `&#x3D9;`
<p>&#x3D9;</p>

I like the first one for a couple of reasons - it looks like a node, it means '100', and it relates to 'Q'.

**Comment by EVGrokker** [comment]
I'm skeptical of the Trip Browser average.

>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 100, PF: 0, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:15, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (45) 
IAP: Pro:1, Sub:1 
Location: Known 
Trip: Grants Pass Supercharger, [y43t65ptexvovh6569bc]

This trip is in three segments, with segment Q factors of 88, 89 and 90 (after optimization), but it's reporting a trip Q factor of 96.

**Comment by aesculus** [comment]
> The lower-case phi is rendered as an upper-case phi in all locations on an iPhone.

I used the HTML version which only differs by `&Phi; vs &phi;`. Apple must be translating it to upper case for some reason.  Let me try the hex code instead.

>This trip is in three segments, with segment Q factors of 88, 89 and 90 (after optimization), but it's reporting an average trip Q factor of 96.

OK. I admit to not doing a deep check on the average score here.  Not sure why it would not work though but will check it out.

**Comment by EVGrokker** [comment]
After sleeping on it, I'd rather use the Q character. It doesn't have a descender, so it will look better in context. 'Q factor' sounds better than 'phi factor'. And Q ties directly to Quality. I won't change my mind again. :)

**Comment by aesculus** [comment]
So the first one then? &#x10912;

**Comment by EVGrokker** [comment]
Yes, Qoph, assuming you're OK with it.

**Comment by aesculus** [comment]
It's fine. Let me take it for a test spin on the iPad and see what Apple thinks of it. :-)

**Comment by aesculus** [comment]
It appears to have passed the 'sniff test'.  We will have to see what the compiler does to it though.

**Comment by EVGrokker** [comment]
V 1.2.0 (46)

Looks correct in Apple-land.
