### ISSUE TITLE
Compare Details: Share does nothing

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#475]
The 'Share' entry in the Compare Details chart does nothing.

**Comment by aesculus** [comment]
That's because this was a placeholder and never got final love.

Suggestions for what you would like it to do? Or go away?

**Comment by EVGrokker** [comment]
I'd send it away.

**Comment by aesculus** [comment]
You're not very nice.  I am going to disable it and then bring it back and wave it in your face later when you want it.

I am already sensing love from you for the Compare Trips feature now that we have the 'Q'. :-)

**Comment by EVGrokker** [comment]
Like always, I'm trying to lighten your load by moving things out of your field of view whenever reasonable. I figure if I can remove 1 item from your to-do list for every 99 I add, that's something.

**Comment by EVGrokker** [comment]
Seriously, disable it for now, let's revisit after the major release finds its way to the masses.

**Comment by aesculus** [comment]
And our issue list was under 100 a few times this week. :-)

**Comment by EVGrokker** [comment]
That was a conscious goal. I'll get there again.

**Comment by EVGrokker** [comment]
See? One step closer.
