### ISSUE TITLE
Communications Error: Charger display

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#476]
v 1.2.0 (45)

I attempted to use the chargers overlay to display chargers, and received the error displayed below. I tried with all non-Tesla chargers enabled, and individuals charger types, and always get the error.

I think that this is a bug rather than a communications error, but I have some feedback on the dialog.

Suggestions:
- If there is a communication error like this, suggest the wording should be something less technical, like "Error retrieving charger locations. Try again later."

![nrelerror](https://user-images.githubusercontent.com/26678403/27332104-ba591020-557d-11e7-99e4-b829468b62d6.PNG)

**Comment by aesculus** [comment]
> I think that this is a bug rather than a communications error, but I have some feedback on the dialog.

Yes. It's a bug. I rearranged everything and did not go back and sanitize the NREL request so it was looking for data that was probably in the wrong format (ie the1st entry is now SC where it did not appear before). Sorry.

**Comment by aesculus** [comment]
Fixed in V1.2 (46) along with a better model for removing other chargers that did not fit the filter criteria but were at the same location. NREL was returning all chargers at a location as long as one fit the criteria.
