### ISSUE TITLE
Waypoint Inspector: 'Charge to' redundant, can be removed

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#479]
With the addition of the split battery display, the Waypoint Inspector no longer needs to display the line 'Charge to:'. It can be removed.

Reference #314, a proposal to add ETD (or Departure Time) to the Waypoint Inspector. These two issues could be resolved at the same time.

<img width="272" alt="screen shot 2017-06-25 at 5 44 23 am" src="https://user-images.githubusercontent.com/26678403/27515808-86d32f16-5969-11e7-970b-71e4400da7b0.png">

**Comment by EVGrokker** [comment]
Depending on your design decision with the charging delta in #103, you could also opt to keep the charging stats in the text block, removing them from below the battery. Might be a cleaner look.

But they don't need to be in both places.

**Comment by aesculus** [comment]
Removed on V1.2 (51)
