### ISSUE TITLE
Edit Trip Details dialog: Reset Time field to current time, revisit Power Factor control

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#48]
Two options for **Time** field:
1. Long press resets to current time without opening time-setting popup
2. Change 'Clear' button to 'Now'.

Power Factor: is this a percentage multiplier? Should it be?
Editing this number is very finicky. How about a popup spinner that ranges from -50% to +50%, or something similar?

**Comment by aesculus** [comment]
This is what I have done for the Date and Time. I cannot get rid of the X but if you touch either one you will get a clock icon that will set both Date and Time to now.

Not sure what you mean by a  popup spinner.  Is the slider really that finicky?

**Comment by EVGrokker** [comment]
I'm confused by the 'X'. What is it? Shouldn't that control be a date field (is it currently a text field)? Touching it should bring up a set up date spinners to set the month, day and year. 

The clock icon doesn't communicate 'reset' or 'now'.  Thinking about an alternative.

**Comment by EVGrokker** [comment]
Is there room to add a 'Reset date and time to now' button just below the time and date fields? That would be cleaner.

**Comment by aesculus** [comment]
That X seems to be defined by the UI and it's for Android. Sorry.  Here is the iOS version.
![image](https://cloud.githubusercontent.com/assets/283364/24510305/b0323d06-151d-11e7-8a26-f8326cd99fe3.png)
Kind of running out of room and I think we have some additional plans for this dialog (like your avoid highways, tolls, ferries) that we need to save room for.

**Comment by EVGrokker** [comment]
That looks fine on iOS.
