### ISSUE TITLE
Waypoint Inspector: Layout revision

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#480]
This is a proposed revision to the layout of the items in the Waypoint Inspector. The objective is to organize items in a more logical sequence:
- Arrival time
- Charge time
- Departure time
- Distance (to next stop)
- Drive time (to next stop)
- Average speed (to next stop)
- (Predicted weather conditions to next stop)

I also moved the battery icon up to the same level as the arrival time and charge time, since that's when the charging occurs, and it creates space below it for a weather icon along the next leg (#68) in the future. The space between Charge Time and Departure Time is intentional, as it helps emphasize that all the following items refer to the next leg. Arguably, there could be a horizontal line element separating them as well. 

![waypointinspector](https://user-images.githubusercontent.com/26678403/27583491-cab142f2-5af1-11e7-8b9b-8f588cd67ac4.jpg)

**Comment by EVGrokker** [comment]
Question: Are my assumptions in the previous comment correct about the fields in the lower section? In other words, _Distance_ is the distance to the next stop, _Drive Time_ is the predicted time driving to the next stop, and weather is the predicted conditions to the next stop?

**Comment by aesculus** [comment]
No. All to this stop.

**Comment by EVGrokker** [comment]
Oops. Let me revisit this. I'll come back with a different proposed layout.

**Comment by EVGrokker** [comment]
Another question: Is the weather shown on the Origin Waypoint Inspector for the leg or the entire segment?

**Comment by EVGrokker** [comment]
Updated layout enhancements proposal for all three versions of the Waypoint Inspector (Origin/Waypoint/Destination):
- Revised labels for clarity and consistency
- Regrouped data into logical groups
- Moved battery up
- Added a separator to create room under battery for local weather conditions.

![waypointinspectorx3](https://user-images.githubusercontent.com/26678403/27645273-e85a7c46-5be2-11e7-94de-04f5ea47729c.jpg)

**Comment by aesculus** [comment]
>Another question: Is the weather shown on the Origin Waypoint Inspector for the leg, the specific address, or the entire segment?

The specific address. 

The way the weather is used is that the app divides the weather forecasts into 3 segments. The first segment between waypoints uses the starting weather, and the last segment uses the arrival weather. The segment in the middle uses an average of wind speed/direction, temperature and precip.

**Comment by aesculus** [comment]
Don't forget you can also charge at a destination, especially if it's a hinge. So you still could have Charge Time there too.

Otherwise it looks good.

This might take some time to implement because I sort of hacked my way into the battery thing and it now needs to be completely rebuilt to accommodate the fixed position at the top.

**Comment by EVGrokker** [comment]
Once I started thinking about the line items, I assumed that it was specific to the address, which supports the layout decisions in the most-recently posted rendering.

>Don't forget you can also charge at a destination, especially if it's a hinge. So you still could have Charge Time there too.

Charge time would go below the divider, above the weather in the right-most panel when destination charging is specified. It would match the look of the center panel, minus departure time.

**Comment by aesculus** [comment]
>Charge time would go below the divider, above the weather in the right-most panel when destination charging is specified. It would match the look of the center panel, minus departure time.

OK.

**Comment by aesculus** [comment]
Question: It the bolding intentional or just quick and dirty and all labels should be non bold?

**Comment by EVGrokker** [comment]
The bolding is an artifact of approximating the text you're using in Photoshop. I got the size approximately correct, but I couldn't make the text any less bold without a different font. The intent is that you would use the same font you've been using, but with different labels.

**Comment by aesculus** [comment]
OK. Just checking.

**Comment by aesculus** [comment]
Is leg time really the old drive time?  That does not see right because to me leg time would be:
drive time + charge time + wait time

**Comment by EVGrokker** [comment]
Yes, I changed Drive Time to Leg Time, without requiring any changes in the way you're calculating it. Here's my reasoning:

The Origin Waypoint is different than the others. Waypoints and Destinations report the time and distance to get _to_ them, but of course that doesn't apply to the Origin. Instead, you opted to show Segment Time and Distance (originally Trip Time and Distance, but I edited them to be consistent with our use of Trip and Segment elsewhere). 

The Origin needs to say 'Segment Time' and 'Segment Distance' to make it clear that it's referring to the entire segment, including all stops up and including the Destination. That's why I chose to go with 'Leg Time' and 'Leg Distance', to make it clear that it was referring to the time and distance required to get from the previous stop to this one. To me, 'leg time' means once you're in the car and driving. ('Leg distance' isn't ambiguous.)

'Leg Time' and 'Leg Distance' are grouped with the leg's average speed, which also reinforces the idea of actual driving time. I consider stop time (including charging) to be outside of leg time.

Do you have an alternative in mind?

**Comment by EVGrokker** [comment]
>This might take some time to implement because I sort of hacked my way into the battery thing and it now needs to be completely rebuilt to accommodate the fixed position at the top.

A minor visual tweak to the battery charging delta when you rebuild it: Consider using a chevron (≫)
`&#187;` as the separator between the starting and ending charge values:

<img width="83" alt="screen shot 2017-06-28 at 2 45 37 pm" src="https://user-images.githubusercontent.com/26678403/27659379-7c46ba0a-5c10-11e7-9183-0c600ab168ab.png">

**Comment by aesculus** [comment]
> leg time would be:
drive time + charge time + wait time

So my issue is maybe it should be Leg Drive Time? To me leg time is all the accumulated time for that leg including driving, charging and waiting.

That is why I had called it just drive time and charge time and I was going to let them do the math or stop time (the amount in addition to charge time).

**Comment by EVGrokker** [comment]
What if it were simply 'Time' and 'Distance' for Waypoints and Destination?

**Comment by aesculus** [comment]
I think users want to know the drive time and charge time, maybe the wait time too if they don't like to do the math.

**Comment by aesculus** [comment]
This is what I think the charging stops should look like:

![image](https://user-images.githubusercontent.com/283364/27668526-84ecc17e-5c36-11e7-91db-5e9f22a235a3.png)

**Comment by aesculus** [comment]
Updated in V1.2 (52)

**Comment by EVGrokker** [comment]
This looks really good. 'Other time' is a bit ambiguous but I don't have an better alternative.

Two suggestions:
- Include a space either side of the chevron to let it breathe more
- Reduce the width of the divider to be the max length of the weather conditions line, so that it doesn't extend so far into the battery and weather icon space. 
- Consider the horizontal positions of the battery, weather and 'x' button. The weather and 'x' appear to be centered with one another, but the battery appears to be positioned slightly to the left of them. Suggest nudging the battery slightly to the right so all three elements look aligned. I think the right edge of the battery can comfortably go to the right edge of the amenities container if you need to go that far (but no farther).

**Comment by aesculus** [comment]
![image](https://user-images.githubusercontent.com/283364/27704714-58a8cbaa-5cc0-11e7-941f-2bcaa6735e6d.png)

**Comment by EVGrokker** [comment]
Very nice. 👍

**Comment by aesculus** [comment]
> This looks really good. 'Other time' is a bit ambiguous but I don't have an better alternative.

I was thinking Additional Time at one point.

**Comment by EVGrokker** [comment]
Let's let it percolate for awhile. There are so many tasty improvements to enjoy.

**Comment by EVGrokker** [comment]
v 1.2.0 (52)

The charging delta wraps to a new line:

![waypointinspector](https://user-images.githubusercontent.com/26678403/27733612-397a20fa-5d54-11e7-812f-461c4d305051.PNG)

**Comment by aesculus** [comment]
This was fixed in V1.2 (58) but when the user has set Distance instead of % it will wrap.
