### ISSUE TITLE
Origin Waypoint Inspector: Arrival Time does not agree with Segment Browser

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#481]
>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 1361, PF: 4, SA: -10, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:15, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (51) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Portland OR, [9rg9m9rik2relmyky1ux]

The Segment Browser and the Destination Waypoint Inspector both say that this trip ends at 11:06 am, but the Origin Waypoint Inspector says the trip ends at 12:07pm. There is no time zone difference between the Origin and Destination points.

**Comment by EVGrokker** [comment]
v 1.2.0 (51)

I just tried again with a newly created trip and I'm seeing the same 1-hour time difference:

>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 0, Rear CC: 0, Bat Life: 100, Payload: 1361, PF: 4, SA: -10, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:15, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (51) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Bend OR, [1vsvnj0hc8ls3knotuq2ja]

**Comment by aesculus** [comment]
This works on my iOS devices.

What happens if you turn location services on?

**Comment by EVGrokker** [comment]
I enabled Location Services, then optimized, and I'm still seeing the one-hour difference. It is only incorrect on the Origin waypoint inspector - everywhere else it's correct.

**Comment by aesculus** [comment]
I still cannot duplicate this on any device.

If you do an Edit Trip and save does it fix it?

**Comment by EVGrokker** [comment]
v 1.2.0 (52)
Edit Trip and Save does not affect the problem.

I thought of a factor which might be influencing the time computation: Both the Origin and Destination for this trip are in a different time zone than the one I'm physically in when planning the trip. I'm wondering if possibly the Origin's predicted ETA is shown in my device's time zone, rather than the Destination's actual time zone? 

In other words, the arrival time of 3:54 (shown in the Seattle image) would be correct for the time zone I'm physically in, but not the local time at the Destination.

![timedelta](https://user-images.githubusercontent.com/26678403/27733466-7fccba1e-5d53-11e7-9c65-74798977c60f.jpg)


Here's the referenced
 trip, created in (52) after wiping data:
>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 100, PF: 0, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:15, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (52) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Bend OR, [4sm2921xc7q8nwftmy56fe]

**Comment by aesculus** [comment]
Can you check this with V1.2 (56)?

**Comment by EVGrokker** [comment]
Still seeing this problem in v 1.2.0 (56)

>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 100, PF: 0, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (56) 
IAP: Pro:1, Sub:1 
Location: Known 
Trip: Bend OR, [9clznleuktbx174s2zb5j]

I have a hunch that the problem is related to the fact that my device time is one hour ahead of the trip's origin and destination.

**Comment by aesculus** [comment]
Is the time zone for your device set to Mountain Time or do you have the clock 1 hour ahead manually?

**Comment by aesculus** [comment]
OK. I see it now. If I set the timezone to the one prior I get the arrival time on the origin waypoint inspector to show at the device time vs local time. I can fix that.

**Comment by aesculus** [comment]
Fixed in V 1.2 (57).  Funky TZ math. Was inadvertently making a new date vs just using the existing trip date as is and that caused the shift.
