### ISSUE TITLE
Import Trip Should Allow for Car Selection

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#482]
When importing a trip it is assigned to the current car. The dialog should allow the user to change the car it is assigned to.

**Comment by aesculus** [comment]
I loaded up the trip and get the same times.

I also did a Save on the origin just in case and did come up with 11:34 as my arrival for both the Origin Inspector and Segment Summary. The Trip summary had 11:33 which is a rounding error I thought I had fixed but may be stuck with for now.

Can you try to Save again and see if it is OK? Was this a new trip you created from scratch with the last build or one that was already in the system?

**Comment by aesculus** [comment]
Added in V1.2 (52)

**Comment by EVGrokker** [comment]
I'm closing this based on previewing the implementation online. Looks good.
