### ISSUE TITLE
My Cars: No tab initially highlighted 

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#483]
v 1.2.0 (51)

When returning to the My Cars dialog after adding an additional car, the active tab label is not highlighted (in blue). I'm observing this in both the online version (52) as well as iOS (51).

**Comment by aesculus** [comment]
I cannot duplicate this with either the web or IOS version.

Can you describe the steps exactly?

**Comment by EVGrokker** [comment]
Here are the steps I used:
- Delete the app, reinstall fresh
- **My Cars**: Configure a Model X: 68º, 5-seater, Save
- **Plan Trip**: Seattle WA - Portland OR, Auto
- View trip on **Plan** screen
- Back to **Main** screen
- Open **My Cars**
- No tabs are highlighted

**Comment by aesculus** [comment]
OK. I was able to duplicate it with that scenario.

Fixed in V1.2 (53)
