### ISSUE TITLE
Edit Waypoint: Increasing Minimum Stop Time not reflected in Destination's Arrival SoC

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#484]
v 1.2.0 (52)

New Trip: Seattle - Bend, Auto
Sandy Supercharger converted from Auto to Required
Initial charging allocation is :26, 17% ~ 65%
Arrival SoC in Bend: 15%

Minimum Stop Time adjusted to 1:30
Charging delta now shows 15% ~ 100%, :15 minute non-charging wait time
Arrival SoC in Bend: 15%

The problem is that adjusting the MST to 1:30 causes the Sandy OR supercharging to increase from 65% to 100%, but this extra SoC is not properly reflected in the arrival SoC in Bend, which stays at 15% in both cases.

>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 100, PF: 0, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:15, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (52) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Bend OR, [4sm2921xc7q8nwftmy56fe]

**Comment by aesculus** [comment]
Working on it.

**Comment by aesculus** [comment]
This should be fixed in V1.2 (53) along with new server code.

**Comment by EVGrokker** [comment]
v 1.2.0 (55)
Seems to be working correctly.
