### ISSUE TITLE
Compile all the help in a web view

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#487]
Put all of the help on a web page accessible by the app. Include a way to do searches by keywords etc.

**Comment by EVGrokker** [comment]
I like this idea. I should include screen shots of the relevant dialog or screen so that it can be consulted away from the app. Structurally, it could be organized starting with the main screen, going through each menu item, then the Plan screen.

**Comment by aesculus** [comment]
If we do it right we should be able to forklift the content as is, plus your screen shots and then wrap in a structure that resembles the app structure. This way there is minimal extra work, especially as we make changes and it will be essentially the same in both platforms.

**Comment by aesculus** [comment]
Complete
