### ISSUE TITLE
Overall Trip Chart

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#489]
A user requested some form of trip summary that combines salient details from the segments in a chart form.  One idea is the create a SoC chart, but instead of waypoints, it would be at the segment destination level.  Could include other metrics as well.

**Comment by aesculus** [comment]
Implemented in V1.2 (63).  Will need help text update.

Note there is now a little bar and line chart button on the lower right corner that toggles the segment SoC chart (line) and the trip SoC chart (bar).  You can also touch the vertical dashed line to see the name of the destination waypoints.  The lower bar depicts the arrival SoC and the upper part of the bar the charging SoC if appropriate.

**Comment by EVGrokker** [comment]
For visual consistency, I'd suggest that the upper part of the bar be rendered in gold to match the recharging color shown in the battery icon.

**Comment by EVGrokker** [comment]
#411 updated to add descriptive help text.

**Comment by aesculus** [comment]
How about this?

![image](https://user-images.githubusercontent.com/283364/28627383-83687ab8-71d6-11e7-9642-aa0e176ae034.png)

**Comment by EVGrokker** [comment]
Yes, that's consistent with the battery imagery.
