### ISSUE TITLE
Edit Trip Details: Add relative speed adjustment

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#49]
([From TMC app thread, requested by user BerTX](https://teslamotorsclub.com/tmc/posts/2008995/))

Add a control to indicate user's preference to drive at some lower speed. This could be expressed as a max preferred speed (e.g. 55) or a percentage of speed limit (e.g. 80%)

**Comment by aesculus** [comment]
This was done in V1.1.2
