### ISSUE TITLE
Support Limited Off Line Use of EVTO

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#490]
Some users have noticed that EVTO is still needed off line (for example when they are on a trip and out of range of communications). They still want to see the the details at waypoints so they can configure the Tesla navigation and keep track of the predictions versus attainment to make adjustments.

Today the menus and panels have been designed to only work effectively with online use.  This issue is to support some form of limited off-line use. There are three instances of use for EVTO involving connectivity:
1. Fully connected
2. The app was loaded when connected, but has lost connectivity
3. The app was started when connectivity was not available

The first is supported today.  The second is important because some of the routines (Google Maps API's) are downloaded at startup.  Many of the features such as the display of paths, waypoints and the Waypoint inspector utilize this but do not need to go to a server.

The menus and features that could be available for off-line use should be turned on.  

A static map background violates Google's agreements so that will not be possible. The routes can be shown along with the waypoints but no may background will display.

We would need to provide some form of information on what can and cannot be performed under each of the three scenarios. Maybe just a limitation list would be better than a full comparison.

**Comment by aesculus** [comment]
In V1.2 (60) I updated the app to support more of a limited offline capability. This required:
- Adding the Trip Browser to the Plans menu just below the Optimize menu item
- Change the New Trip icon to a (+) because it was a conflict with the Trip Browser icon
- Updated the Plan Menu help
- Updated the Main menu help with the new icon
- Updated the New Trip dialog icon

**Comment by EVGrokker** [comment]
v 1.2.0 (60)

The New Trip icon is absent in Plan menu, New Trip dialog, and Plan help.

![newtripmissingicon](https://user-images.githubusercontent.com/26678403/28461084-405dd202-6dd2-11e7-8124-1bf52553b9d1.png)

**Comment by EVGrokker** [comment]
I'm not sure how to approach documenting this. Can you give me a description of what you have in mind?

**Comment by aesculus** [comment]
My Bad.  Left off the file extension. Android filled it in for me.

Fixed in V1.2 (61)

**Comment by aesculus** [comment]
> I'm not sure how to approach documenting this. Can you give me a description of what you have in mind?

I thought I did but I agree it's abstract.  Basically:
- You can use EVTO when not connected to view existing trip information but you cannot make changes
- If you have loaded EVTO when there was connectivity you can see the waypoints and route against a blank map, and also select the waypoint inspector, even without current connectivity
- Due to Google licensing requirements, map backgrounds cannot be supported for offline use

**Comment by EVGrokker** [comment]
Ugh. 

Wouldn't it be simpler/cleaner to say that EVTO requires connectivity for full functionality, rather than saying how it's going to break when there's no connectivity?

**Comment by aesculus** [comment]
I have had a number of users state this is a cool feature and they use it a lot. There were a few things that could get them in trouble with the way it was originally I fixed.

I am ok with not mentioning this at all though, but it does not break when there is no connectivity, it just has reduced functionality. Big difference.
