### ISSUE TITLE
Migrate Social Sharing to a new Generic Platform

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#491]
There are times in the app where the user needs/wants to share information with the developer, themselves or others via email or some other form of sharing.  Today EVTO supports native email in the device but it would be preferable for other types of social sharing to be available based on the user's needs.

Note for the Feedback Report, only email should be supported.

This should also fix the problem occurring when users have chosen gmail. Issue #323.

**Comment by EVGrokker** [comment]
I would separate this issue into two groups of apps. _Social media_ would be Instagram, Twitter or Facebook, where the user is posting to a broadcasting platform. This would be useful if the user was taking a publicized road trip and wanted to communicate progress to a large group of followers.

_Messaging_ apps would be Messages or WhatsApp, one-to-one communications with another person, like email.

I would prioritize messaging apps over social media.

**Comment by aesculus** [comment]
I agree functionAly. I found a plug in that can do both so the underlying technology is the same. That is the part that will require most of the effort.

**Comment by aesculus** [comment]
emails and social sharing now done via plugin in V3.5
