### ISSUE TITLE
Rangefinder: Help Text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#494]
<h3>Rangefinder</h3>
<p><i>Determine the distance to a selected charging station.</i></p>
<p>To quickly estimate the distance to a charging station, enable either the Supercharger overlay (lighting bolt) or charger overlay (electrical outlet), then touch a charger icon to display the Charger Inspector. Touch the car icon to display the Rangefinder.</p>
<p>Estimated time and distance from both the current segment's Origin and Destination are displayed. To add this charging stop as a waypoint, close the Rangefinder, then touch the pin button in the Charger Inspector to add the charger to the current segment.</p>
<p>With Location Services enabled in Settings, the distance from your current location to the selected charging station is also displayed.</p>

**Comment by EVGrokker** [comment]
Help for the Distance Estimator is ready to be added.

**Comment by aesculus** [comment]
Added in V1.2 (67)

**Comment by aesculus** [comment]
Needs update now that it is Rangefinder

**Comment by EVGrokker** [comment]
The related Rangefinder functionality is contained in issue #291.

Updated content, ready for integration.

**Comment by aesculus** [comment]
Updated in V1.2 (80)

**Comment by aesculus** [comment]
The help text needs updating based on the new Current Location capability

**Comment by EVGrokker** [comment]
Updated help text to reflect Current Location capability.

**Comment by aesculus** [comment]
Updated in V1.2 (83)
