### ISSUE TITLE
Getting Started: Help Text

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#496]
[screen 1]
Plan your trip, waypoints and charging using one simple to use App for all your mobile devices.

[screen 2]
Plan a new trip with just a destination, and let EVTO do the rest. Begin from your current location or saved favorite, like 'Home' or 'Work'. Search locations by address or place name.

[screen 3]
Add waypoints and charging stops. Select the charger type, and EVTO calculates how long you need to recharge to reach your next stop. Contextual help is just a menu click away.

[screen 4]
Optimize routes to let EVTO automatically select Supercharger locations. Or, touch the lighting bolt or plug icons to display nearby chargers, manually adding them as route waypoints.

[screen 5]
EVTO reduces range anxiety by visualizing energy consumption and state of charge (SoC) along your route. Edit your trip details to reserve energy for local driving once you're arrived at your destination.

[screen 6]
Plan extended multi-segment road trips. Today's destination automatically becomes tomorrow's origin. And you can return to your starting point too.

[screen 7]
Purchase the Pro Version and Multi-Trip IAPs to save and reload multiple trips, email your itineraries, and share trips with other EVTO users.

[screen 8]
Compare the same trip taken at different times to analyze how driving conditions and charging choices affect overall trip time.

[screen 9]
Customize EVTO with your car's characteristics and your driving style. With the Pro IAP you can have up to five cars defined, for example one for towing and one for commuting.

**Comment by EVGrokker** [comment]
v 1.2.0 (70)
Proposed revisions:
[screen 1]
Plan your trip, waypoints and charging using one ~simple to use App~ simple-to-use app for all your mobile devices.

[screen 3]
Add waypoints and charging stops. Select the charger type, and EVTO calculates how long you need to recharge to reach your next stop. Contextual help is ~just a menu click away~ always available.

[screen 4]
Optimize routes to let EVTO automatically select Supercharger locations. Or, touch the lighting bolt or plug ~icons~ buttons to display nearby chargers, manually adding them as route waypoints.

[screen 9]
Customize EVTO with your car's characteristics and your driving style. With the Pro IAP you can have up to five ~cars~ car profiles defined, for example one for towing and one for commuting.

**Comment by aesculus** [comment]
Updated in V1.2 (71)
