### ISSUE TITLE
Trip Browser badge: Include '1' for single-segment trips

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#497]
v 1.2.0 (70)

I propose that the Trip Browser button (folded map icon) be badged with '1' whenever a single-segment trip is active. This would be a visual reminder to free users that it's possible to have multi-segment trips. It would also be visually consistent across all trip types.

**Comment by aesculus** [comment]
Implemented in V1.2 (71)
