### ISSUE TITLE
Support for Chromebooks

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#498]
At least on TMC member would like to use the app on a Chromebook. Today Play says it's  not a supported platform.  That may be the result of missing touch and gps but both of these are not really required as much as expected.  There may be other issues as well.

**Comment by EVGrokker** [comment]
Wouldn't that mean running in a standard browser?

**Comment by aesculus** [comment]
No. Won't do that.  It might mean just telling Play it's OK to relax the requirement for some features. Early investigation only showed that others are trying to do it but I did not spend enough time actually finding a solution, if one even exists yet. One entry I saw was from July 2017 so it's still a fresh issue.

**Comment by aesculus** [comment]
Not going to support
