### ISSUE TITLE
Update Waypoints when My Cars/Settings Change

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#5]
Consider having Settings and My Cars changes apply to the current trip, or at least prompt the user if they want it that way.

Minimum SOC is saved in trips (min_wp_soc) but any waypoint created uses settings. Auto chargers always use settings which means they can differ. - maybe update current trip with new settings and My Car attributes as a prompt?

**Comment by EVGrokker** [comment]
Edit Trip Details is now available to tweak Speed Adjust and Power Factor per trip.
