### ISSUE TITLE
Plan Trip panel: Drag waypoint pin to new location

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#50]
When viewing a route with waypoints, a long press on a pin (Origin, waypoint or Destination) enables  the pin to be dragged to a new location.

**Comment by aesculus** [comment]
There are a lot of ramifications to this:

- The address is going to be whatever it was dragged too. Not some known address
- I cache addresses so it's more efficient and each one costs $$$ in Google land
- Every change in address requires a complete recalc of the route
- Every change in address needs to have the weather fetched for that address. Again $$$ to the weather folks
- If its a significant move, it will require optimization
- If the user dinks around trying to position the waypoint it will rack up huge $$ and peformance issues
