### ISSUE TITLE
Edit Segment Details causes Optimizer to hang

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#502]
v 1.2.0 (76)

Trip: Grants Pass Supercharger, [2c682mscj3eg5wj3zd1iya]
>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 0, Rear CC: 0, Bat Life: 100, Payload: 159, PF: 0, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_3 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0, Show Soc: 0 
Version: 1.2.0 (76) 
IAP: Pro:1, Sub:1 
Location: Unknown 

After creating the trip from Seattle - Fess Parker, then segmenting at Grants Pass, then adding Petaluma as a waypoint and segmenting there, I open the Edit Segment Details dialog to change the name of the final segment from 'Fess Parker…' to Santa Barbara. Upon closing the dialog, the optimizer hangs at about 20%.

**Comment by aesculus** [comment]
Fixed in V1.2 (77)
