### ISSUE TITLE
Update OK buttons in two dialogs for consistency

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#503]
v 1.2.0 (74)

After invoking Add to Calendar, the 'Calendar Update' dialog displays [Cancel | Ok]. Should be 'OK' for consistency with other dialogs.

The same applies to the Store Error dialog after invoking Restore Purchases, should be 'OK' for consistency. (I can't see what the dialog looks like if contact with the store is successful.)

**Comment by aesculus** [comment]
Hmm. That should totally not do it on the Calendar or Restore Purchase. Something is amiss here.

**Comment by aesculus** [comment]
This is what appears on the iPad in 76

![image](https://user-images.githubusercontent.com/283364/29242139-008be63e-7f3c-11e7-96f2-03285c8ee66d.png)

**Comment by EVGrokker** [comment]
Sorry, I misled you. What I was trying to communicate is that the button should read ~Ok~ OK

**Comment by aesculus** [comment]
Ah.  Fixed in V1.2 (78) then.
