### ISSUE TITLE
UI template for App Store rating incentive

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#505]
This issue is a generic discussion of the feature initially implemented in v 1.2.0 (79), where rating the app unlocks some new functionality.

The initial incentive functionality, planned for v 2.0, is the Rangefinder (#291).

The intent is to provide different incentives with significant releases, so this issue exists to discuss the general mechanism and UI.

The initial implementation adds a menu item to the Plan screen menu between Feedback Report and Help:

![img_0854](https://user-images.githubusercontent.com/26678403/29324714-f210fcb0-8199-11e7-85d0-927157cac7c3.PNG)

Upon touching the menu item, the following dialog is displayed:

![img_0855](https://user-images.githubusercontent.com/26678403/29324875-7f88ecce-819a-11e7-8563-7dd9b25dde80.PNG)

After the user completes the App Store review process, the menu item will no longer be displayed, unless the user reinstalls the app, or installs the app on a different device.

The initial incentive, Rangefinder functionality, is invoked from the Charger Inspector dialog by touching the car button. Before the App Store rating has been completed, the same dialog prompting the user to complete a review is displayed.

**Comment by EVGrokker** [comment]
Comments on the dialog:

1. Suggest retitling the dialog 'Unlock <feature>', for consistency with the menu item. For the initial implementation, this would be 'Unlock Rangefinder'.
2. Suggest the following wording: App Store ratings help other Tesla owners discover EVTO. To unlock the Rangefinder feature, touch the Rate button to go to the App Store and leave a review. It takes just a moment of your time, but it makes a big difference to us. Thanks!

**Comment by aesculus** [comment]
I had to make it platform dependant with App Store and Google Play. Implemented in V1.2 (80)
