### ISSUE TITLE
Optimize Should Return Partial Results if No Optimized Route Found

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#507]
Currently the optimizer will return with an error message when no routing can be done with the current settings for all segments, even those that complete OK.  The error message may also need to improve to reflect what is going on instead of just a generic route cannot be found.

I propose these changes:
- Return the segment number that caused the failure in the message.  ie the 3rd out of 5 segments may have no routing. This way the user might be able to fix something in a particular segment (eg destination SoC)
- Return all the valid prior segments before the error segment
- Stop the optimization process when it encounters the first segment that cannot be optimized to save execution time

**Comment by EVGrokker** [comment]
Do you have a sample trip that this displays this behavior?

**Comment by EVGrokker** [comment]
Please post the text of the error dialog as currently implemented in v 1.2.0 (81).

**Comment by aesculus** [comment]
>Do you have a sample trip that this displays this behavior?

You will have to set your region to AP.

uvn2igz0p8buxpikvsls1i

**Comment by aesculus** [comment]
![image](https://user-images.githubusercontent.com/283364/29779165-98cd1cec-8bc6-11e7-8af2-cca6b43ebddb.png)

**Comment by aesculus** [comment]
V1.2 (81) has a partial implementation of this as shown above.  I may not be able to do the other parts within a segment because the optimizer works forwards to find options, and then backwards to find solutions.  So if it encounters a part of a segment that cannot be reached, it has nothing to work backwards from.

Note that this is a very rare circumstance in areas like EU and NA where superchargers are fairly dense and reachable.  But in AP (like AU and NZ) where supercharger are few and far between, manual mode using non superchargers is the order of the day. Optimizing in this case only makes sense if part of the route can use superchargers.

**Comment by EVGrokker** [comment]
>You will have to set your region to AP.
uvn2igz0p8buxpikvsls1i

Is there a PIN associated with the trip? I am unable to import it.

**Comment by EVGrokker** [comment]
PIN 1313 does it.

Now that I can see the error dialog in context, it seems that you could provide more specific details in the dialog. And, it's an opportunity to recommend a solution.

For example:
No route found to [waypoint name]. Try adding a charger manually.

What is the thinking behind providing the Minimum SoC Arrival value?

**Comment by aesculus** [comment]
The Minimum Arrival SoC is what cannot be met, but there could be a host of reasons.  If you want to take a crack at some generic wording I can use that along with the waypoint name in the error dialog.

The Minimum Arrival SoC might be a bit misleading too as there is sort of a incremental cutoff in units of 10.  So someone could try adjusting it by 1 point at a time and not hit the threshold until they hit a factor of 10.

**Comment by EVGrokker** [comment]
How about:

No supercharger found along route to [waypoint name]. Try adding a charger manually, limiting speed, or adjusting Minimum Arrival SoC in the Edit Waypoint dialog.

**Comment by aesculus** [comment]
I updated your text slightly by adding "increasing the Departure SoC"

**Comment by aesculus** [comment]
Implemented in V1.2 (81)
