### ISSUE TITLE
Add Tesla Destination Chargers in North America

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#508]
Today Tesla standard chargers are shown for Asia and Europe in the app. Many of these are destination chargers. In North America Tesla uses standard chargers for HPWC at service centers and galleries. They use the tag 'destination charger' on a non Tesla premise.

The app today only provides superchargers and standard chargers which means that the North America destination chargers are not shown,

There are almost 6400 destination chargers in the Tesla database and I am a bit worried about performance both in displaying chargers but also in downloading the database after updates.

**Comment by EVGrokker** [comment]
Having the destination chargers in the NA database is a huge plus, and seems like a must-have feature.

In terms of performance, you could create a third category 'destination chargers' within the Tesla chargers, controlled by the charger filter dialog. 

Obviously, the database of destination chargers would update more frequently than the superchargers. 

If you're concerned about performance, perhaps the database refresh could be a manually invoked feature?

**Comment by aesculus** [comment]
>If you're concerned about performance, perhaps the database refresh could be a manually invoked feature?

Today the files are updated whenever the server date changes. The device keeps track of the servers charger file date. So it only happens once per change during startup.

I think the concern for performance is more related to displaying the icons when the user selects the lightening bolt icon.  True they can use the filter to remove the HPWC from displaying so hopefully that will mitigate it.

**Comment by aesculus** [comment]
It turns out I have about 1/2 the worldwide destination chargers already loaded. There are about 2500 more in the US that need to be added.

I will probably wait until the next version is in place with the charger filter so I don't overrun the chargers icons. The current version only filters NREL HPWC and not the ones from Tesla.

**Comment by aesculus** [comment]
I added the destination chargers for NA and as predicted, the performance on displaying the charger pins is pretty dismal IMHO.  Turning off HPWC in the filter removes the issue so I have changed the default value for new installs to not use the HPWC in the display of lightening bolt chargers.

This is in V1.2 (84) but I have not yet populated the server with these chargers yet.  Can you try the web version on your device and see what you think?

**Comment by EVGrokker** [comment]
I tried the web version.  

Comments:
- This seems like a must-have feature. The more chargers available in-app, the better. 
- Yes, the performance is slower, but the resulting display of charger cluster is what the user is hoping for. I presume that the performance is influenced by the scope of the map zooming? In other words, if you're zoomed tightly on an area, the fetch is quicker?
- Once a fetch has been performed, are the results cached on the device, or is it a new fetch every time the display is toggled?
- I'm wondering if HPWC chargers should be grouped with conventional chargers (under the outlet button), or perhaps given their own toggle button.

**Comment by EVGrokker** [comment]
Q: Will it be possible when using Add Waypoint to filter by HPWC charger, similar to how you can filter by supercharger?

**Comment by aesculus** [comment]
It does this now. Pick one you know by name and then change the charger type to hpwc and start typing.

**Comment by EVGrokker** [comment]
I'm confused. There are four different types of HPWCs listed in the charger picker. Does it matter which one is selected? I'm trying it with the Kirkwood Mountain Resort, and I'm not seeing any filtering applied with the first two listed HPWCs.

**Comment by aesculus** [comment]
OK. Seeing that too. I tested it with another location and I thought it worked but it must have been Google recognizing the place name vs the app pulling from the db.  Looking into it.

**Comment by aesculus** [comment]
Can you try this now with the web version?

**Comment by aesculus** [comment]
>Once a fetch has been performed, are the results cached on the device, or is it a new fetch every time the display is toggled?

Every time. The data is already in the device once the app is loaded.  It's processing ~4,000 destination waypoints and putting them on the map that costs the hit.  On slow devices it may be a big deal, not sure. I don't think the clustering does anything here.

Note when I implemented this I had to add a progress spinner since it takes so much longer than just superchargers.

**Comment by aesculus** [comment]
> I presume that the performance is influenced by the scope of the map zooming? In other words, if you're zoomed tightly on an area, the fetch is quicker?

Nope. After some flack I received before about this approach I decided to put them all in. :-)

**Comment by aesculus** [comment]
I noticed that the car shows amenities for the destination chargers but this repository I get from Tesla only has amenities for superchargers.  Go figure.

**Comment by aesculus** [comment]
I am going to have to wait to add the destination chargers to production because the current version does not have the ability to filter HPWC.

**Comment by aesculus** [comment]
This was applied in the chargers released in early January 2018.
