### ISSUE TITLE
[Advanced Tutorial]: Segmenting Manual Routes

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#509]
(This might be integrated as a sidebar into another more general tutorial about segmenting trips.)

Not sure if this is worth a mention in help or within a tutorial. It had me wracking my brain looking for a bug until I realized what was happening:
- Create a route with manual waypoints
- Waypoints are all green
- Decide to split the route between waypoints
- Split shows that the departure SoC is the same before and after the split on the split waypoint
- Waypoint after the split now is yellow

What happened? Why is it not the same as before?
Wait for it ...

When we split the segment at the waypoint the default is to start the new segment the next day. This causes the weather to be different. If the weather is worse (a headwind) then the energy consumption will be higher and it might flip from meeting the requirement to missing the requirement.

**Comment by aesculus** [comment]
I should add it to the faq too.

**Comment by aesculus** [comment]
I updated the FAQs
