### ISSUE TITLE
Pin label alignment needs tweaking

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#510]
In the attached image, the alignment of the identifying letters within the pins is off-center.

![pinlabels](https://user-images.githubusercontent.com/26678403/29826596-e5611d5a-8c94-11e7-816a-5b35b74318f7.PNG)

**Comment by aesculus** [comment]
I'll have to drag out the iPhone. It's fine on all the other devices.

**Comment by aesculus** [comment]
Is this OK now?

**Comment by EVGrokker** [comment]
I neglected to include a note about how to recreate this trip when opening the issue, and I can't find the original email. I believe it had to do with the Asia Pacific region, and a situation where there weren't superchargers available for a given stretch. Do you still have the trip ID or details so that I can recreate the trip?

**Comment by aesculus** [comment]
You could do it with any trip you manually add HPWC to. That is an iPhone SE which you won't be able to duplicate anyway.

**Comment by EVGrokker** [comment]
I posted the original image, so it was from an iPhone 7+.

It appears to be OK now.
