### ISSUE TITLE
Enhancement: Ability to favorite an origin/destination from the New Trip dialog

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#511]
This overlaps with #142, the ability to Favorite from the Add Waypoint dialog. I believe that we had some discussion elsewhere about this, but I can't find an issue that specifically addresses this issue. It feels like we got half way there with the ability to add favorites from the Add Waypoint dialog. Given the timing, this may be an enhancement for a subsequent release, but I want to make sure it's documented.

Scenario: User is creating a trip, and realizes that they are supplying an address that will be used frequently. They want to mark the Origin or Destination in the New Trip dialog as Favorite. From the current UI, the obvious way to add this functionality would be touching the heart button at the right edge of the Origin/Destination field to bring up the Favorites picker. 

1: User fills in Origin address, then touches the Heart button on the right end of the Origin field.

![new trip](https://user-images.githubusercontent.com/26678403/29933021-4eec2388-8e33-11e7-82c6-a85f4933bc1a.PNG)

2: 
An additional line would be inserted at the top of the list, 'Add [Origin/Destination, depending on which heart they touched]'. For example, 'Add 45500 Fremont Boulevard'. 

![favorites picker copy](https://user-images.githubusercontent.com/26678403/29933257-3f1c0c4c-8e34-11e7-87e6-75f8edf788a1.png)

3. Touching the 'Add' line would bring up a subsequent dialog giving the user the opportunity to provide a friendly name before the address is added to the favorites list. (The screenshot below is derived from the top half of the Add Waypoint dialog.)

![add favorite](https://user-images.githubusercontent.com/26678403/29933511-17dec9de-8e35-11e7-9dfb-f5da2ec29223.png)

**Comment by aesculus** [comment]
Yeah we never finished this scenario. Probably for another release.

Right now they create the trip and then simply select the Waypoint Inspector for any waypoint they want to favorite and select it's heart.  I almost favor the current approach as I think we are putting in too many additional tasks with your scenario. While it may seem logical to do it all at once, my experience is that most users will be overwhelmed by the option and probably not even think of it.

**Comment by EVGrokker** [comment]
v 1.2.0 (83)

This almost works correctly. 

Scenario:
- New Trip
- Origin: 45550 Fremont Boulevard, Fremont
- Destination: Sacramento CA
- (Auto) Calculate

After the trip calculates: 
- Touch the Origin pin.
- Touch the Edit (pencil) button
- Clear the friendly name field
- Type in 'Tesla HQ'
- Touch the Favorite button in the Edit Waypoint title bar
- Touch Save
- From the Plan menu, touch Maintain Favorites
- Note that the entry is listed by its address, not its edited friendly name

If this scenario captured the edited friendly name correctly, it would be a workable solution for the near term.

**Comment by aesculus** [comment]
Fixed in V1.2 (84).  If you change the name in the editor it will update that favorite with the new name too.
