### ISSUE TITLE
Provide Option for Military Time

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#515]
Some users don't like the AM PM thing and would like to see times via 24 hour format.

**Comment by EVGrokker** [comment]
The obvious place for a 'Time Format' setting would be in the Settings panel.

One approach would be to reduce the width of the Default Start time to half, then use the other half for a 'Format' pair of radio buttons, '12' and '24'.

Or, you could reduce Location Services to half width, putting it on the same line as Default Start Time, and put a full-width pair of radio buttons 'AM/PM' and '24' grouped with Imperial/Metric and Percent/Distance.

**Comment by aesculus** [comment]
I actually created the half wide start time with a format picker. Looked ok. 

Then realized that the system was set to a user's format preference so no need to ask. 

Now I am hunting for a means to find out what the systems setting  is.

**Comment by aesculus** [comment]
I could not find anyway to detect the user's time format so took your suggestion and added it to the line where the default start time is on Settings

![image](https://user-images.githubusercontent.com/283364/30346795-cf4e9f08-97be-11e7-91e0-5dc17bd8a17d.png)

**Comment by aesculus** [comment]
Feature implemented in V1.2 (87)

**Comment by EVGrokker** [comment]
Help content updated (issue #173).

**Comment by EVGrokker** [comment]
I'd suggest that the Default Start Time change to match the selected Time Format?

For example, the default is '8:00 AM'. If the user selects the '24 hour' time format, the display format for the Default Start Time field should switch to '0800'.

**Comment by aesculus** [comment]
It's a bit of a funky solution. The picker just sets the output format. You have to go to the device settings and choose your input format. One top of that I noticed on my Android it still wanted to display the input in AM/PM even though I could pick in 24 hours.  Not sure why and I have no control over how the picker behaves.

**Comment by aesculus** [comment]
Approved by the user who made the request.
