### ISSUE TITLE
My Cars dialog update

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#52]
Touching _My Cars_ in the Main panel menu opens the **What Car are You Driving?** dialog. For consistency, I suggest that this dialog should be renamed **My Cars**, prefixed with the auto icon as it is in the menu. The 'Current Car:' label could remain as is, or perhaps be 'I'm currently driving:'.

**Comment by aesculus** [comment]
I changed Current Car to Active Car which closer aligns to Active Trip and means the car the app is working with on trips.
