### ISSUE TITLE
Allow Trip Start Time Override in New Trips

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#520]
A user would like to see this on new trips.  Right now the destination time field may be just a placeholder until I can figure out a reasonable way to do issue #4 

![image](https://user-images.githubusercontent.com/283364/30787907-f650a3fc-a147-11e7-9754-dd899d9a07d3.png)

**Comment by aesculus** [comment]
This is implemented in V1.2 (98) by stealing space from the car selector. For the iPhone SE there was not enough room on the origin and destination inputs.  Also I am not prepared to implement the Arrive By feature at this time and will revisit that at a later date.

There is no label so I hope it's self evident. If the user clears the value and then save it will use the default start time from settings, from which the default value is supplied.

Help will need to be adjusted.

![image](https://user-images.githubusercontent.com/283364/30840952-ebda962a-a22e-11e7-912c-b727ce1fd8b0.png)

**Comment by EVGrokker** [comment]
Help updated in #174.
