### ISSUE TITLE
New Feature List for V2.0

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#523]
This topic is a collection of items that should be announced as significant new features for V2.0. This would be any external communication and in the store descriptions.

<hr/>

<p>EVTO 2 is the complete reinvention of the only EV trip planner designed for phone-sized devices. Plan trips on your phone with multiple waypoints. Explore charging options using the charger overlays, or import a charger location from PlugShare. Save frequently-used locations like 'Home' to speed up trip planning. EVTO 2 is the only EV trip planner you'll need, and it's always with you.</p>

<p>Some of EVTO 2's latest features and highlights:</p>
<ul>
<li>Full support for Tesla Model 3 and Roadsters</li>
<li>New 'My Cars' dialog with Model, Cockpit and Energy options for up to 5 Tesla profiles</li>
<li>End-to-end automatic charger allocation and routing for multi-segment routes</li>
<li>Improved accuracy of energy consumption based on weather and elevation changes</li>
<li>Updated Waypoint Inspector with visual representation of battery SoC and predicted weather conditions</li>
<li>New Trip Browser with quick-reference summary of key trip stats</li>
<li>New Segment Browser with quick-reference summary of individual waypoint stats</li>
<li>New charging time estimator with manual override</li>
<li>Per-segment speed offset adjustment, maximum speed preference</li>
<li>Tesla Destination Chargers added to database</li>
<li>New Rangefinder feature for off-route chargers</li>
<li>Updated design for Consumption and SoC charts</li>
<li>Improved route export to device calendar</li>
<li>PlugShare copy/paste integration</li>
<li>New tutorials and extensive contextual help</li>
<li>Many more under-the-frunk improvements</li>
</ul>

<p>Upon installation, EVTO is limited to a single trip of up to 500 miles/800 km with automatically selected supercharger stops and up to three additional manual waypoints. With the purchase of a monthly or annual in-app subscription, save multiple trips and create multi-segment trips with no practical limits on distance or waypoints.</p>

**Comment by EVGrokker** [comment]
I took a first cut at polishing and organizing the new feature list.

**Comment by aesculus** [comment]
> Many more under-the-hood improvements

Looks good. But shouldn't this read:

_**Many more under-the-frunk improvements**_

**Comment by EVGrokker** [comment]
Doh. You win.
