### ISSUE TITLE
Purchase Subscription dialog typo, formatting

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#525]
v 2.0.0 (1)

When purchasing a subscription, the dialog below is displayed. The last sentence should read "Purchase ~an~ a Monthly Planning subscription?", and it should begin a new paragraph.

![purchase subscription](https://user-images.githubusercontent.com/26678403/31545014-c3d04fc6-afda-11e7-9c9d-bea7f82d9941.PNG)

**Comment by aesculus** [comment]
Fixed in V2 (2)
