### ISSUE TITLE
Segment Browser displays negative SoC stops incorrectly.

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#526]
Trip: Bend OR, [dgk4vng8zaw9f0askiedtp]

Note Loveland and Rawlins charging stops are not rendered correctly.

![negative_soc](https://user-images.githubusercontent.com/26678403/31545107-3a0b0dde-afdb-11e7-80eb-b33bbb6ac817.PNG)

**Comment by aesculus** [comment]
Fixed in V2.0 (2)
