### ISSUE TITLE
Main panel menu layout & design

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#55]
*Help* should be last in this menu, as it is in all other menus. Users can reasonably expect a Help entry in the menu, and will search until they find it. Putting it at the bottom familiarizes them with all other menu entries on the way to finding it.

*Plan a Trip* should be removed after issue #45 is closed, which adds a *New Trip* button on the Main panel.

With those changes in place, I'd recommend the following structure:
(The following four menu items will always be active regardless of IAPs):
- _Current Trips_ (See Issue #51, renaming the associated dialog to match)
- _Settings_
- _My Cars_
- _Maintain Favorites_

(The next group deals with IAPs and premium features, and would initially be grayed out, except Restore Purchases and Feature Matrix. ):
- _Purchase Pro version_ (grayed out if not yet purchased)
- _Multi-Trip subscription_ (grayed out if not yet purchased)
- _Trips Archive_ (grayed out if Multi-Trip not yet purchased)
- _Compare Trips_ (grayed out if Multi-Trip not yet purchased)
- _Restore Purchases_
- _Feature Matrix_ (note renaming as requested in issue #54)

(The next group is informational, in ascending level of detail):
- _Getting Started_
- _Tutorial_
- _FAQs_
- _Help_

(and finally…)
- _About EVTO_

**Comment by aesculus** [comment]
The ordering has been completed. Waiting to finish this when the new buttons are applied

**Comment by aesculus** [comment]
Can we move Current Trips to the top? It's probably the most used menu item.

**Comment by aesculus** [comment]
Also shouldn't the Restore Purchases be just after the two purchase options?

**Comment by EVGrokker** [comment]
The reason that I put Restore Purchases after Compare Trips is that I proposed that it should be grayed out (along with Trips Archive) if the MTS IAP was not purchased. You'd see four grayed-out items in sequence on a standard installation. 

I moved Current Trips to top in first comment.

**Comment by EVGrokker** [comment]
If you feel strongly about moving Restore Purchases to just after the IAPs, go for it. If you do, post a comment so I know the menu order for the Help file authoring.

**Comment by aesculus** [comment]
This what I have now:

Plan a Trip - TBD for later update to remove
Current Trips
Settings
My Cars
Maintain Favorites

Purchase Pro version (grayed out if not yet purchased)
Multi-Trip subscription (grayed out if not yet purchased)
Restore Purchases
Trips Archive (grayed out if Multi-Trip not yet purchased)
Compare Trips (grayed out if Multi-Trip not yet purchased)
Feature Matrix

Getting Started
Tutorial
FAQs
Feedback Report
Help

About EVTO

**Comment by EVGrokker** [comment]
'Trips Archive' should be renamed to 'Archived Trips' to be more consistent with 'Current Trips'.

**Comment by aesculus** [comment]
Done
