### ISSUE TITLE
Purchase Subscription dialog

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#58]
The title bar should be renamed to **Multi-Trip Subscription**, prefixed by a closed lock icon. 

**Current dialog text:**
---
You are about to purchase the Yearly Subscription Fee for $1.99.

Unlimited planning for one year. You can cancel within the first 30 days for no charge. This subscription will auto-renew before the subscription expires unless cancelled. Terms of Use http://www.digitalautoguides.com/dag-terms-of-use/ The Privacy Policy and Terms of Use are available on the main menu or at http://www.digitalautoguides.com/dag-privacy-policy.

Is this what you want to do?

Proposed dialog wording:
---
You are about to purchase Multi-Trip support for an annual subscription fee of $1.99.

Purchasing a Multi-Trip annual subscription allows you to save multiple trips that may be reloaded from the **Current Trips** or **Archived Trips** folders. You may cancel your Multi-Trip subscription within the first 30 days for no charge.

Your subscription will auto-renew before your anniversary date. To manage or cancel your subscription, refer to your App Store. ([Apple](https://support.apple.com/en-us/HT202039), Android).

[Terms of Use for EVTO](http://www.digitalautoguides.com/dag-terms-of-use/).
[Privacy Policy for EVTO](http://www.digitalautoguides.com/dag-privacy-policy)

Continue with purchase of Multi-Trip annual subscription?

---
Caveats: 
- I don't know if there are some specific legalese issues with the App Store(s) that dictate specific wording.

**Comment by aesculus** [comment]
There are certain conditions/wording. I will did it up and post it here. I think you are pretty close though.  Once I have this next update approved I will see if I can get Apple to sniff test your wording prior to the next update.
