### ISSUE TITLE
Support Tesla Roadsters

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#6]
To support Roadsters you could remove all SC and only use HPWC or maybe get a set of NREL Tesla chargers on route or stash them into another file?

Not sure what else besides car details would be needed to support Tesla Roadsters.

**Comment by EVGrokker** [comment]
I have a friend with a Roadster who might be willing to weigh in.

**Comment by aesculus** [comment]
You can check with them. I have no idea what it would take or what type of chargers they use. I thought they used HPWC but not sure.

**Comment by aesculus** [comment]
From a Roadster user who has the app:
>Some other thoughts about using the program with public charging, and with the Roadster in mind...

>1.  I noticed that you give a "charge time" estimate for charging stops.  Is that estimate based on a fixed (6kw?) rate, or is it dynamic from a database somewhere?  Public chargers have a variety of charging rates.

>2.  The "charge to" value is in % SoC,but the Roadster display is only in Ideal Miles.  I can calculate what that % is, but it would nicer if your app did that for me.  (You have the 90% value for Ideal Miles in the car's settings.  I presume it's linear math from there, no?)

>3.  Related, the Roadster basically has 2 useful settings (modes) for charging; Standard (to about 83%), and Range (to about 94%).  We don't get to enter a charge limit value when charging.  (Those are values for the original battery.  Not sure what the %'s are for the new 3.0 battery.)  The original battery is about 57kwh (53 usable); I believe the 3.0 battery is in the high 70's.

>4.  Is there any way to get more of the PlugShare-type data for the public charging spots?  Stuff like # of chargers, success score, current status, etc?  And, fill in with more of the available charging locations?  Unlike with the superchargers, there's a very wide range of public sites out there, and a lot of ICEing.  With experience, I'd know which ones to include.  But experience typically comes with a price...

>5.  Perhaps you could add a "progress" (road rally) tab that displays in real time what the plan says you should be at for distance traveled, distance remaining, estimated range (what the model thinks your range should be) and SoC %, etc.?  I do something similar (but less sophisticated) when I use the Roadster's in-dash Nav system.  It tells me the distance remaining to my destination, which I can mentally compare to the car's estimated range remaining.  Not counting terrain (where your model has a big advantage), the offset between the two should remain constant.  I can use any trend in that metric to adjust my driving in real time, thus avoiding trouble down the road.  Or if nothing else, for the warm & fuzzy anxiety reduction that comes from knowing I'm traveling to plan.

>6.  Kind of silly, but on the main (startup) screen, you have a big button for "resume trip".  How about another for "new trip"?  It's kind of buried in the menu...

**Comment by aesculus** [comment]
V1.2 (47) is the first implementation of the Roadster. All optimizations features are turned off for the Roadster and for this release, there are no cabin control energy calcs being done.

**Comment by aesculus** [comment]
V1.2 (51) has some improvements to charging times for Roadsters who have diminished max charge rates.  There are also improvements to the energy consumption estimates.

**Comment by EVGrokker** [comment]
@aesculus: up to you when to close this issue.

**Comment by aesculus** [comment]
I have a round trip to TMC Connect to to use as reference to fine tune the energy usage. Getting closer.

**Comment by aesculus** [comment]
At this point my Roadster user thinks that V1.2 (58) is close enough. We will continue to fine tune it over time for accuracy but I am going to close this now as complete.
