### ISSUE TITLE
Plan Trip panel menu layout and design

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#61]
_New Trip_
_Edit Segment Details_
_Add Waypoint_
_Optimize Segment_
_Calculate Segment_
_Refresh Segment_
_Reverse Route_ (propose making this a standard feature, since waypoint reordering will accomplish the same thing)
_Copy as New Trip_ (grayed out if Multi-Trip IAP not purchased)
_Rate Trip_
_Segment Summary_ (looking for something more distinctive, maybe 'Itinerary'?)
_Segment Details_ (looking for something more distinctive here, maybe 'Metrics'?)
_Add to Calendar_
_Filter Chargers_ (see issue #47, proposed changes to name and icon)
_Help_

**Comment by EVGrokker** [comment]
See issue #73 proposing to relocate 'Recalculate  with current conditions' to this menu. Suggest placing it after 'Calculate'.

**Comment by EVGrokker** [comment]
Updated menu items based on email discussion - _Segment Summary_, _Segment Details_, added _Refresh Segment_ from issue #73.

**Comment by aesculus** [comment]
BTW the next version does not have Calculate Route. No need for it. The only time it was need was if you did something to the My Cars data and I am going to just suggest that people reoptimize then.

See my comment on https://github.com/aesculus/EVTO-App-Feedback/issues/73

**Comment by EVGrokker** [comment]
I'm relieved that Calculate Route is being retired.

**Comment by aesculus** [comment]
Done. V1.1.3
