### ISSUE TITLE
Plan Trip menu: New Trip dialog

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#62]
Title: Change to **New Trip**, prefix with folded map icon

Suggested text:
---
Creating a new trip will replace your current trip.

To manage multiple trips, please consider purchasing a Multi-Trip Subscription.

Replace current trip with a new trip?

**Comment by aesculus** [comment]
I left the title as Confirm New Trip as it is a confirmation. The next popup says New Trip.

For this particular dialog (prompts) I cannot add icons in the headers.

**Comment by aesculus** [comment]
Implemented in V1.1.3
