### ISSUE TITLE
Plan Trip menu: Copy as New Trip dialog with no Multi-Trip subscription unnecessary

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#63]
When there is no MTS IAP, selecting _Copy as New Trip_ brings up a **Subscription Warning** dialog.

As proposed in issue #61, this menu item would be grayed out if the IAP has not been purchased. 

Therefore, this dialog should be removed.

**Comment by aesculus** [comment]
Done. Disabled when no subscription.
