### ISSUE TITLE
Plan Trip menu: Reverse Route dialog unnecessary

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#64]
As proposed in issue #61, Reverse Route should be a standard feature that replaces the current route. Therefore, this dialog may be deleted.

If a user wanted to create a copy of the current route, then reverse it, this would require the MTS IAP. The sequence would be Copy Current Route, then Reverse Route.

**Comment by aesculus** [comment]
Implemented in V1.1.3 (3)
