### ISSUE TITLE
Plan Trip menu: Add to Calendar dialog update

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#66]
Title of dialog should be changed to 'Add to Calendar', prefixed with calendar icon to match menu text.

Suggested dialog text:
---
Clicking **OK** will create a calendar entry for the origin, destination and each route waypoint. 

This action is not undoable by EVTO. If you wish to remove the calendar entries, you must do so in your device's calendar app.

Add route to calendar?
 [Cancel] [OK]

---
In the following dialog **Calendar Update**, prefix the title with the calendar icon. 

Suggested dialog text:
---
"[trip name here]" has been added to your calendar. 
[Ok]

---
### Commentary ###
I know that part of the design is to use the unique IDs in the calendar so that you can find and replace them if the user updates the trip, but I don't think you need to call attention to this feature in this dialog, since the app is Doing The Right Thing anyway.

**Comment by aesculus** [comment]
I just wanted them to understand why the gibberish was there. A few of my beta users thought I was just spamming.

Ideally I would like to get rid of the code but right now it appears that Android does not have a unique code for a calendar event where iOS does

**Comment by aesculus** [comment]
Can we revisit this issue: I think item 1 was omitted by #242

**Comment by EVGrokker** [comment]
v 1.1.4 (3)

This is now broken in a fresh installation.

1. Create round trip, Seattle - Moclips.
2. Select outbound segment
3. Plan menu | Add to Calendar
4. The first time I do this, I get a dialog saying that EVTO wants to access my calendar, and asks for me to approve. I do so.
5. The dialog closes, and the menu remains displayed, so it appears that nothing happened.
6. I go to the calendar, and the origin and destination were added to the calendar.
7. Delete those two entries from the calendar.
8. Try Plan menu | Add to Calendar again.
9. Menu does not dismiss, but the two events are added to the calendar.

The confirmation dialogs need to be restored. I'd suggest the dialog sequence suggested in the first comment in this issue. You could delete 'This action is not undoable by EVTO. If you wish to remove the calendar entries, you must do so in your device's calendar app.' I think that's the part that was too much.

And while we're on the subject, it would be a good idea to reformat the calendar entries to get the gibberish out of the title, either into the Notes section, or appended after the name.

**Comment by aesculus** [comment]
I revisit this in V1.2. For now I have restored what was there before V1.1.4 (4) in V1.1.4 (8)
