### ISSUE TITLE
Getting Started screens proposed revisions

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#67]
_Comments: The purpose of the Getting Started screens is to provide hand-holding for the new user, with just enough help to get you planning your first trip. A quick overview of a few feature highlights should be provided, along with how to find more help within the app._

---

#### Screen 1 of 9: ####
_(I propose removing the interactive 'touch an icon to jump to that feature' as it's unusual to see an interactive feature in a static screen sequence. Users are familiar with a series of dots meaning 'swipe to the next screen'. So maybe you can replace that circle of icons imagery with the app's logo.)_

Plan trips, add waypoints and find chargers along the way. EVTO utilizes your car's characteristics and current weather conditions to intelligently plan your charging stops.

---
#### Screen 2 of 9: #### 

Plan a new trip with just an origin and destination, and let EVTO do the rest. Begin from your current location or a saved favorite, like 'Home' or 'Work'. Search destinations by address or place name. 

---
#### Screen 3 of 9: #### 
Add waypoints along your route, including charging stops. Select the charger type, and EVTO calculates how long you need to recharge to reach your next stop. Extensive contextual help is just a menu click away.

---
#### Screen 4 of 9: #### 
Use the Optimize feature to let EVTO automatically select Supercharger locations along your route. Or, touch the lighting bolt icon to display nearby Tesla Superchargers, manually adding them as route waypoints.

---
#### Screen 5 of 9: #### 
EVTO reduces range anxiety by visualizing energy consumption and state of charge (SOC) along your route. Edit your trip details to reserve energy for local driving once you've arrived at your destination. 

---
#### Screen 6 of 9: #### 
Plan extended multi-segment road trips. Today's destination automatically becomes tomorrow's origin. 

---
#### Screen 7 of 9: #### 
Purchase the Pro Version and Multi-Trip IAPs to save and reload multiple trips, email your itineraries, and share trips with other EVTO users.

---
#### Screen 8 of 9: #### 
Compare the same trip taken at different times to analyze how driving conditions and charging choices affect overall trip time.

---
#### Screen 9 of 9: #### 
Customize EVTO with your car's characteristics and your driving style. 

Let's go!

---

**Comment by aesculus** [comment]
Confirmed for V1.1.3

**Comment by EVGrokker** [comment]
Please see revisions to screens 3 & 4 reducing word count.
