### ISSUE TITLE
Iconize the weather on the trip map.

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#68]
Use icons to depict windspeed, direction, precip and temperature at each waypoint.

**Comment by EVGrokker** [comment]
Suggest using a 'partly cloudy' icon on the map to toggle weather icons on/off.

**Comment by aesculus** [comment]
I am wondering if this would just get ugly. The user currently has the opportunity to select a waypoint and see the weather both textual and iconically.  

The other issue I see here is that there could be big gaps in the weather (ie if there were no stops and a user had a MS100D that could go over 300 miles) the weather could change dramatically from what would be depicted.  This just advertise a issue with the app in that it only provides weather for waypoints, not consistently along the trips route.

**Comment by EVGrokker** [comment]
It's fine with me to close this issue. As you point out, the addition of weather icons at waypoints accomplishes the objective in a much cleaner fashion than adding them to the map.

**Comment by aesculus** [comment]
Issue closed based on discussion above
