### ISSUE TITLE
My Cars dialog: Current Car dropdown should only show as many cars as are defined, need ability to delete car definition

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#75]
Currently, all five slots are populated with placeholder 'Model S' text. There should only be as many entries in this list as the user has defined.

Additionally, need to add a button to this dialog to delete the currently displayed car definition. If it's the only car in the list, reset to default values and leave it in the list.

**Comment by aesculus** [comment]
Why?  The user bought 5 cars worth.  They don't have to use them. I had to default the values to something so I picked the most common model.
