### ISSUE TITLE
Maintain Favorites dialog - show an empty row if no waypoints are favorited, chargers are disliked

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#76]
If there are no favorited waypoints or disliked chargers, add a single empty row so that the user understands that this dialog displays a list. Grayed out 'No favorites' placeholder text hints that they can add favorites from a waypoint dialog. 

Same for charger dislikes, suggest 'No supercharger dislikes' placeholder text.

**Comment by aesculus** [comment]
Fixed in V 1.1.4 (2)
