### ISSUE TITLE
Favoriting a waypoint, then editing its friendly name should update that name in Maintain Favorites list

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#77]
If I favorite an already-created waypoint, then change its name, that change is not reflected in the Maintain Favorites dialog - it still shows the original name.

**Comment by aesculus** [comment]
Just to confirm: You want me to hunt down every instance of the favorite in the app and change it's name? If so that is going to be a change in the app because the favorite is only a means to create a waypoint. There is no favorite ID associated with a waypoint at this time so no way to link them.

**Comment by EVGrokker** [comment]
I misunderstood the architecture of the Favorites list. I assumed that any changes to a  Favorite waypoint would be stored in a central location dynamically referenced by its clients. I think that also means that when you persist charger type for Favorites, that will be static as well, right?

**Comment by aesculus** [comment]
That is correct. 

If you want this feature it will be a enhancement rather than a bug.

**Comment by EVGrokker** [comment]
I think this is worth keeping in the list for future improvements. Please mark this issue as an enhancement request.

**Comment by aesculus** [comment]
Is this related to https://github.com/aesculus/EVTO-App-Feedback/issues/27?

**Comment by EVGrokker** [comment]
Yes, it is related. Suppose that I create a Cabin waypoint and mark it as a favorite. I tell EVTO I have a 110v outlet. I create some trips with my Cabin destination, and EVTO dutifully calculates my charging time with the 110v outlet. Those trips are saved in my Current Trips folder.

A month later I decide I'm really an EV guy at heart, so I upgrade my Cabin charger to a HPWC or 14-50. My expectation is that the next time I reload a trip involving the Cabin favorite, EVTO should realize that I changed the charger type since the last time I took this trip. I shouldn't have to replace the waypoint, or update the charger type - EVTO should do the right thing. 

That's why I think that it would be a good idea to have Favorites be a database accessed dynamically for its most recent attributes (Name and Charger, at a minimum), rather than statically storing the waypoint info from the time the segment was originally created.

**Comment by aesculus** [comment]
OK. Let me think about how to re-architect the Favorites so they are more connected. I think I see another key/value pair in the Waypoints object. :-)

**Comment by aesculus** [comment]
This should be addressed in V1.2 (85)

**Comment by EVGrokker** [comment]
v 1.2 (90)

Confirmed.
