### ISSUE TITLE
Plan Trip | New Trip | Continue the current trip

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#78]
Scenario: 

Pro version. Current trip is one-segment with an origin and destination, no waypoints. From the Plan Trip menu, I select New Trip. The 'Continue the current trip' checkbox is checked and grayed out, meaning that I can't disable it. I'm only provided with the option to provide a destination, which will become a continuation segment of the current segment.

I'm confused. Here's my expectation of the behavior:

Since the standard version does not enable Out & Back trips (two-segment), the standard version shouldn't allow continuation trips (multi-segment) either.

Since the Pro version enables Out & Back, it should also enable the option of multi-segment continuation trips. These are not independent trips, which would require the Multi-Trip IAP; they are linked segments of a single trip.

If that's correct, then my observation that the checkbox is checked but disabled from user input is a bug. Selecting New Trip from the Plan Trip menu (Pro version) should give me the option of an entirely new trip (by unchecking the checkbox) or continuing the current trip (when the checkbox is enabled).

**Comment by aesculus** [comment]
> Pro version. Current trip is one-segment with an origin and destination, no waypoints. From the Plan Trip menu, I select New Trip. The 'Continue the current trip' checkbox is checked and grayed out, meaning that I can't disable it. I'm only provided with the option to provide a destination, which will become a continuation segment of the current segment.

If you are Pro and have a subscription it will prompt you if you want to Continue the trip.

But if you have no subscription then it does as is reported above. The help file tried to explain that. It's a bit weird in that to actually create a brand new trip, you have to go out to the main menu or to the Current Trips panel.

However if the current trip is an O&B then you get a complete New Trip dialog like there is no current segment.

**Comment by EVGrokker** [comment]
This seems like an unnecessary complication.

If the intent is that both Pro and MTS IAPs are required for continuation trip planning, then I'd suggest that if a user is Pro only (no MTS), that checkbox is grayed out and disabled.

If the intent is that Pro only users may utilize continuation planning, then the control should not be grayed out - you should be able to check or uncheck the box.

I think that the behavior of the **Main | New Trip** button should be functionally equivalent to invoking the **Plan Trip | New Trip** menu item. I don't think that having purchased MTS should affect this behavior, only Pro.

Proposed behavior (from either Main or Plan Trip screens), with Pro version:
If current trip is Out & Back, this is a new trip, with the option to create it as an O&B. It will replace the current trip.

If current trip is a single-segment or multi-segment trip, dialog presents the **continuation** checkbox. If user checks it, only the destination text box is active. If the user disables it, that implies that this is a new trip, and the origin text box is also enabled.

Does that make sense?

I really want to avoid 'New Trip' having subtly different behavior depending on where it's invoked from.

**Comment by aesculus** [comment]
The problem is when they have Pro but no subscription. How do I differentiate between wanting a completely new trip verses extending the trip? Then the dialogs will be different again because when they do this outside of the map menu, it will prompt them that they are replacing the trip.

**Comment by EVGrokker** [comment]
For all versions (_Standard, Pro, MTS_),  **Main screen | New Trip** and **Plan Trip menu | New Trip** execute the same functionality.

_Standard_ and _Pro_: User is warned that creating a new trip will replace the current trip. Upon confirming, they see the New Trip dialog.

_MTS_: No warning dialog, just open the **New Trip** dialog. Current trip will be saved to **Current Trips**, to be replaced by new itinerary to be provided by user, when user clicks **Save** to close dialog.

Dialog behavior depends on the IAP level they're at:
_Standard_: **This is an Out & Back trip** is unchecked and disabled. They can only plan a new trip with an origin and destination.

_Pro_: **This is an Out & Back trip** is enabled. They can plan their new trip either as a one-way or O&B, depending on the state of the checkbox.

MTS: Depends on Standard or Pro, follows that behavior. Current trip will be saved to **Current Trips**, to be replaced by new itinerary to be provided by user, when user clicks **Save** to close dialog. 

---

So what about continuation trips?

My first instinct was to add another checkbox to this dialog to indicate continuation trips, but the combinations would be too confusing.

So, instead I propose adding a menu item to the Plan Trip menu: **Continue trip** or **Add segment**. 

This dialog doesn't need a continuation checkbox, since it's implied by the menu selection.

It would be grayed out for Standard users, enabled for Pro users. 

---


![img_0298](https://cloud.githubusercontent.com/assets/26678403/24466371/7f6737b6-1465-11e7-9ae7-92e7df4e8720.PNG)

**Comment by aesculus** [comment]
Hmm. I will think about it. Also not it probably should be grayed out for Pro users who are on an Out and Back trip too.

**Comment by EVGrokker** [comment]
Agreed, if an O&B trip is active (only applies to Pro users), the menu option to add a segment should be grayed out.

**Comment by aesculus** [comment]
OK. I think I can make this change.

**Comment by aesculus** [comment]
Implemented in V1.1.3 (3)
