### ISSUE TITLE
Create new pin types representing hinge points in Out & Back, Multi-segment trips

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#79]
These would be used for points representing the destination of one segment and the origin of the next (hinge points), creating an additional visual cue that the currently displayed segment is a linked segment of a larger trip.

For multi-segment trips, the new pin types for origin and destination would also have to visually communicate their meaning in a mid-trip segment. Consider segment two of a three-segment trip. Perhaps the mid-trip origin pin could be a standard blue origin pin with a green center, and the mid-trip destination could be a SoC destination pin (green/yellow/red) with a red center. 

Out & Back trips would share the pin scheme with multi-trip segments. Segment 1 would use a standard blue origin pin, and a SoC destination pin (green/yellow/red) with a red center. Segment 2 would use a blue pin with a green center as the origin, and the standard checkered pin as the destination, colored with the appropriate SoC color.

In the image below:
Top row: Single-segment origin and destination pin pair.
Second row: Out & Back segments. The first pin pair represents segment 1 (Out), the second pin pair represents segment 2 (Back).
Third row: Multi-trip segments. The first pair represents segment 1, the second pair represents all middle segments, the third pair represents the final segment.

(Note that I have not properly colored the destination pins with SoC info, that would be dependent upon the state of the segment plan.)

![pin pairs](https://cloud.githubusercontent.com/assets/26678403/24453732/f3586c62-143d-11e7-9fd5-04f0f5d27572.jpg)

**Comment by aesculus** [comment]
I get the concept and will think about it a bit.

Just a note: All origins are blue. All destinations were either colored (green, yellow, red) based on arrival SOC with one exception: A white destination meant that the segment needed to be optimized.

**Comment by EVGrokker** [comment]
Oops, I realized that all origins are blue. I corrected the description text in the first comment. And I forgot about the arrival pin outer color. But the interior coloring would remain as described above. I'll append the descriptive text.

**Comment by aesculus** [comment]
So the interior color would represent the SOC like the outer pin would?

What about changing the checkerboard to a different pattern and still leaving the pin color the way it is? Too me it would be more uniform.

Now to think what the intermediate pattern should be. :-)

**Comment by EVGrokker** [comment]
Interior color means mid-trip segment origin (green) or destination (red).

Colored checkerboards (red) would be fine as long as there's sufficient resolution to see the color. 

I went with red and green since those represent stop and go universally, and match the racing flag meaning. Regardless of what scheme you choose, it seems that these are good visual cues to emphasize what kind of segment you're looking at.

**Comment by EVGrokker** [comment]
OK, yet another idea.

Suppose that an intermediate segment's destination interior is a gray checkerboard pattern, with the exterior color representing SoC upon arrival. Gray suggest 'incomplete', so the visual message would be 'this is the destination of this segment, but not the final destination of the trip'.

That way there's no confusion between the meaning of the SoC colors on the exterior edges of the pin, and the interior pattern.

**Comment by aesculus** [comment]
How about this?
![marker-icon-green-checker-gray](https://cloud.githubusercontent.com/assets/283364/24465301/6ae99d82-1461-11e7-8958-8a926c2346b2.png)

**Comment by EVGrokker** [comment]
I meant keeping the white areas of the checkerboard white, and changing the black areas to gray. I should have been more specific. That looks too dark to me.

**Comment by aesculus** [comment]
OK. How about this one?
![marker-icon-green-checker-gray2](https://cloud.githubusercontent.com/assets/283364/24487625/d0c447a6-14c5-11e7-9023-e82aaf5431f1.png)

**Comment by EVGrokker** [comment]
I think that will work nicely.

**Comment by aesculus** [comment]
Done. V 1.1.3

**Comment by EVGrokker** [comment]
This looks excellent in the latest beta. 

Suggestion: my test trip [5bbafwn92acf41d2txxvxn], PIN[1234] finishes with an SoC of 32%. I think the final segment destination pin should show a color representing the arrival SoC. For example, green would be at or above your default departure SoC. Red would be at or below your minimum SoC. Yellow would be in between.

**Comment by aesculus** [comment]
Used to be this way. Changed to battery level. If you want it like this open an issue as enhancement. 

Green would be at and above min soc, yellow below but red? Not sure. Maybe less than 5% no matter what.

**Comment by EVGrokker** [comment]
The attached image should help explain the suggestion to change the rendering of the final destination pin.

The pin is shown with a checkered flag interior, but a white exterior. The suggestion two comments above is to change the rendering of the final destination pin using SoC colors in the exterior area (white, in the image below) to indicate the projected battery level upon completion of the trip.

---

![img_0315](https://cloud.githubusercontent.com/assets/26678403/24608484/89337fce-182b-11e7-9aef-0efc47498af6.PNG)

**Comment by EVGrokker** [comment]
This is visible on segment 2 of [0t8du4s2f7w5kwxxy3zi08es9y] PIN [1234]

**Comment by aesculus** [comment]
This white outside means that the trip should be optimized.  A segment upstream was changed.

If you optimize this segment the pin will go to the correct color/shade.

This will go away, or severely be diminished, in V1.1.4 when I implement holistic optimization.

**Comment by EVGrokker** [comment]
Aha. Didn't know that. That's something to be documented as part of a 'what pin colors mean' help topic, which I will do.

**Comment by aesculus** [comment]
It's should be in the Help file for the trip panel today. I have not finished updating the help yet (only partially through the main panel), so you still have time. :-)

**Comment by EVGrokker** [comment]
What's the timeline for the next release? How much time do I have?

**Comment by aesculus** [comment]
At least three days for sure. Wed EOD?

**Comment by EVGrokker** [comment]
I'm still traveling with brief windows available, but I will do my best.
