### ISSUE TITLE
It’s possible to add multiple waypoints to the Favorites list with the same name

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#8]

**Comment by EVGrokker** [comment]
I'd suggest that both the Name field and the Address field should be evaluated when determining if the proposed favorite is a dup.

**Comment by aesculus** [comment]
I am now checking the address as well as the place ID in v1.2 (58). The name though is not unique. I understand that users could inadvertently create a bunch of favorites with the same name but different addresses. It's not likely though unless they edit the name as place names are usually unique.

Checking unique names would require a major overhaul of the favorites feature and will have to remain for another day,

**Comment by aesculus** [comment]
V 1.2 (62) should check for duplicate names.
