### ISSUE TITLE
Plan Trip menu: New menu item 'Add Segment'

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#80]
This is a followup feature enhancement to issue #78 concerning the difference between planning a new trip and extending a current trip.

This proposal is to add a menu item to the Plan Trip menu, **Add Segment**, after the **New Trip** menu item. This is a Pro level feature, so it would be grayed out in the menu for Standard users.

The name could be **Continue Trip** or **Add Segment**. (Edit: **Add Segment** is preferred to eliminate ambiguity with 'Resume Trip' on Main screen, as discussed in next comment.)

The dialog would be titled the same as the menu entry. The icon could be the folded map icon with a superimposed '+'.

The **Continue the current trip** checkbox would be unnecessary, since it's implied by activating the menu item.

---

![img_0299](https://cloud.githubusercontent.com/assets/26678403/24467221/890541f2-1468-11e7-8b92-8c2a81e5c266.PNG)

**Comment by EVGrokker** [comment]
In thinking more about this, I'm now convinced the feature should be called **Add Segment**. 

On the main screen we have **Resume Trip**, which sound the same as **Continue Trip**. To avoid ambiguity, I think this menu function should be referred to as adding a segment, rather than continuing a trip.

**Comment by aesculus** [comment]
Created an Add Segment and removed all checks for continuation on the New Trip dialog.

Fixed in V1.1.3 (3)
