### ISSUE TITLE
Main screen menu header should reflect selected car's name

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#82]
After configuring my car in the My Cars dialog, opening the Main menu displays a header with 'Model X' on the left and 'My Car' on the right. 'My Car' should display the name I assigned in the My Cars dialog. If it doesn't fit, it should be truncated to the first n letters that would fit.

**Comment by aesculus** [comment]
OK. This is a bug. Fixed in 1.1.3. 

If you exit the app and come back in again I think you will see it's set correctly. What's happening is that it did not get refreshed when your first saved it. When I changed to a name vs a VIN I made an error on the instruction to update the field.
