### ISSUE TITLE
Restore Purchases after a fresh install

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#84]
Main menu | Restore purchases.

After pressing this, I get a popup asking me to log into the App Store, but behind that is a dialog saying that my purchases were restored. Apparently I don't actually need to log into the App Store to restore purchases. 

If that's correct, the 'Log into App Store' dialog shouldn't be displayed when restoring purchases.

**Comment by aesculus** [comment]
That Log into the App store is an Apple thing.  Not sure why it's happening. I saw that too.  Nothing I can do about it as far as I know.

BTW this stuff started happening to me after the 10.3 iOS update. :-(
