### ISSUE TITLE
New Trip dialog layout needs work - buttons off the bottom edge of dialog panel

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#85]
Creating a New Trip on an iPhone 7+ has layout issues. The Cancel and Save buttons are off the bottom of the dialog.  See attached screenshot.

![img_0303](https://cloud.githubusercontent.com/assets/26678403/24504776/5fb459ce-150c-11e7-8029-de9b340377a6.PNG)

**Comment by aesculus** [comment]
OK. I will work on this a bit.  I think I also need to hide these buttons while you are in location search mode because the list can force these off the bottom too.

**Comment by aesculus** [comment]
I think this is related to https://github.com/aesculus/EVTO-App-Feedback/issues/110

Time to get out the iPhone 6S+ to see what it is doing here. Something with regard to resolution interpolation I suspect.

**Comment by aesculus** [comment]
When the panel is not a popup I have to extend the top so it does not interfere with the status stuff on the top of the iDevice. But when it's a popup like this it should not be extended. Note the title bar is a bit tall.

**Comment by aesculus** [comment]
Check this again when V1.1.3 (3) comes out. I have reduced the height of the header on popups. It may need a bit more tweaking.

**Comment by aesculus** [comment]
I need this checked in V1.1.3 (5) @EVGrokker

**Comment by EVGrokker** [comment]
This looks correct in 1.1.3(5)

**Comment by aesculus** [comment]
Good
