### ISSUE TITLE
Multi-segment trips: Consumption and SoC tabs allow swiping to blank screen

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#86]
(1.1.2) When viewing a trip with multiple segments, touching the Consumption or SOC tabs initially displays the corresponding data correctly. However, while on either of those tabs, swiping right goes to an empty display. I believe the intent was to disable swiping from these tabs.

**Comment by aesculus** [comment]
I just pulled it for V1.1.3.

Another user complained that V1.1.2 did not show the SOC tabs but I have not gotten a trip yet to test yet.

>However, while on either of those tabs, swiping right goes to an empty display. I believe the intent was to disable swiping from these tabs.

I was not able to duplicate the swipe to a blank screen but I guess it's moot since I pulled this code anyway.

**Comment by aesculus** [comment]
I am already missing this feature. :-(

**Comment by EVGrokker** [comment]
If you re-enable the feature make it so that the selected segment tracks the same in all three panels. Swiping to a different segment in consumption or SoC causes map to change as well.

**Comment by aesculus** [comment]
It should have done that before. When you swiped on SOC and Consumption, it was supposed to (did?) change the map too.

But I cannot swipe the map because Google thinks that is what you want to do, swipe the map. That panel will not swipe to change segments

**Comment by EVGrokker** [comment]
That's an acceptable trade off because from the map you select segments using the segment selector. If you can keep all three tabs in sync I say go for it.

**Comment by aesculus** [comment]
And don't forget. If you can see any of the other segments (route or destination/origins) you can select it that way too. Plus I owe you the long press on the map thing. Working on that now.

**Comment by EVGrokker** [comment]
One other UI suggestion if you decide to re-enable this feature: In the Consumption and SoC tabs, prefix the segment name with its number in the segment list, letting the system truncate the label (if needed) automatically: '3. Burlington Costco Return 2017…'.

**Comment by aesculus** [comment]
But why would this not also be on the map tab?  BTW they are the same panel so the heading is always the same.

If we decide to do something like this we should consider creating a new issue and also dealing with the 3 of 6 type of labeling too.

**Comment by EVGrokker** [comment]
You're right, the title should be identical on all three tabs.
