### ISSUE TITLE
Review what happens if you change an MST departure charger type

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#91]
Not fully tested yet.

**Comment by EVGrokker** [comment]
Is this related to issue #90, where you expect to be using a destination charger of a certain type or capacity, but discover a different charging capacity upon arrival?

**Comment by aesculus** [comment]
Yes. They are related.  How do you combine these things in Git? Or do you just close one and move some text over?

**Comment by EVGrokker** [comment]
I would pick which one you want as the ongoing issue, add relevant info from the one you're about to close and a link using #. Then, close the other with a comment 'merged with #xx'

**Comment by aesculus** [comment]
OK. That's what I thought but wanted to be sure.

**Comment by aesculus** [comment]
Hopefully fixed with https://github.com/aesculus/EVTO-App-Feedback/issues/90
