### ISSUE TITLE
Plan Trip | SoC tab layout issues, typo

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#92]
In the attached screen shot, the legend explaining the color values overlays the graph.

I think you can afford to reduce the vertical height of the graph and give the legend dedicated space below. 

Also, notice the typo in the y axis label 'Remaining Engery', should be 'Remaining Energy'.

![img_0306](https://cloud.githubusercontent.com/assets/26678403/24551553/b9560204-15d7-11e7-8990-2cb0881ccd62.PNG)

**Comment by aesculus** [comment]
Looks like I should also use abbreviations for the color labels on small devices like I do the waypoints

**Comment by aesculus** [comment]
Fixed in V1.1.3
