### ISSUE TITLE
No way to edit Trip name in Current Trips or Archived Trips.

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#94]
As far as I can tell, you can currently rename segments, but not an entire trip.

In the Current Trips screen, it should be possible to rename a trip. Suggest making the Name field an edit control. That would be the simplest solution.

The same enhancement would apply to Archived Trips screen.

**Comment by aesculus** [comment]
Sounds like a good idea.

Actually changing the first segments name changes the overall trip name but that is filled with issues because often the last segment is really where the name should come from, your destination.

**Comment by aesculus** [comment]
What if I added an Edit Details menu item on the Current Trips that brought up the Edit Details panel so the user could change the name, date/times and other trip factors?

It could also apply help apply all of this uniformly across all the segments, which sort of needs to happen (ie change the trip name and all the segments get that name with their destination name in ().

I could prompt them if they wanted to apply various details like payload and power factor applied across too.

**Comment by EVGrokker** [comment]
Yes, with the following clarification. 

On the Main screen, everything is about global settings and Trips. On the Plan Trip screen, nearly everything is about trip segments (New Trip being the exception). 

In Main|Current Trips and Main|Archived Trips menus, the item would be 'Edit Trip Details'. In Plan Trip menu, the item would be 'Edit Segment Details'. In the current beta (1.1.3) several menu items referencing trips need to be renamed to refer to segments: Trip Details and Trip Summary should be Segment Details and Segment Summary. 

I disagree about trip renaming applying to segments automatically. I might want to name my trip 'Road Trip 2017' and name the segments by the town I'm staying in each night.

**Comment by aesculus** [comment]
>Trip Details and Trip Summary should be Segment Details and Segment Summary.

Yep. In the todo list

>I might want to name my trip 'Road Trip 2017' and name the segments by the town I'm staying in each night.

This is sort of how it works (is supposed to) today. The segments have the trip name and then in parentheses the name of the destination for that segment.

![image](https://cloud.githubusercontent.com/assets/283364/24558549/61ff8afc-15f0-11e7-9008-0d9388f73977.png)

**Comment by aesculus** [comment]
Another thing on this. Today as pointed out the trip name displayed in Current Trips is the first segment with it's (day). I need to scrub the (day) part as it can make the name too long for the table plus it's not really the trip name.

If this does not work I am going to have to stick the trip name in every segment like I do the master key.

**Comment by EVGrokker** [comment]
How about putting trip name in the title bar: Moab Segments, then just segment number and name per item.

**Comment by aesculus** [comment]
>How about putting trip name in the title bar: Moab Segments,

Some trip names are long so this is not a good idea

>then just segment number and name per item.

The segments are in order. Would a number really help here?

**Comment by EVGrokker** [comment]
Ideally I think 1/9, 2/9… would be best for establishing context in the segment sequence. My bias would be to truncate the tail end of the segment name as that seems less important. This is all fine tuning that we can polish over time.

**Comment by EVGrokker** [comment]
Adding Edit Trip Details to the main menu (home screen) seems like the best approach. This dialog would mimic the design of Edit Segment Details from the Plan Trip menu. Similar, not identical.

**Comment by aesculus** [comment]
I will need to add a field to at least the first segment to hold an overarching trip name since I have not concept of a master trip, other than an unique ID that every segment has appended to it.

That field would initially be the first segments name and could be edited later from the Current Trips menu.

**Comment by aesculus** [comment]
> Adding Edit Trip Details to the main menu (home screen) seems like the best approach. This dialog would mimic the design of Edit Segment Details from the Plan Trip menu. Similar, not identical.

Now we need to think of other things we would want to change besides the name, or maybe not at this juncture.

**Comment by EVGrokker** [comment]
The name is really the only variable- everything else is derived from the segments. I'd say display some read-only data fields from the Current Trips screen. The only edit control at this time would be the name.

**Comment by aesculus** [comment]
OK. Simpler.

**Comment by EVGrokker** [comment]
Proposed layout for Edit Trip Details dialog, invoked from Main menu.

Notes:
- Initially, only Name field is editable. Eventually, departure date and time would be editable, as discussed in issue #97. Date and time fields are read only.
- This design may imply adding a Comments field for the trip, which is a useful addition if it doesn't already exist.


---
![edit trip details](https://cloud.githubusercontent.com/assets/26678403/25179181/fd007208-24c5-11e7-9dc8-8e8f7dc1e755.png)

**Comment by aesculus** [comment]
We could also move the trip rating here too.

**Comment by EVGrokker** [comment]
This should be referred to as the "Trip Inspector".

**Comment by aesculus** [comment]
> Proposed layout for Edit Trip Details dialog, invoked from Main menu.Proposed layout for Edit Trip Details dialog, invoked from Main menu.

I propose this should be a part of the Current Trips menu and not a part of the main menu. The main menu is trip agnostic.

**Comment by EVGrokker** [comment]
I prefer this approach, but it pushes forward the need to redesign the Current Trips screen. I'm not sure if there's an open issue for this, but my idea is an expanding list item when you touch a saved trip that exposes directly editable details.

**Comment by aesculus** [comment]
>I prefer this approach, but it pushes forward the need to redesign the Current Trips screen. 

Nah. For right now I just add another menu item right after Activate Trip. Easy peasie.

> but my idea is an expanding list item when you touch a saved trip that exposes directly editable details.

Save that idea for the redesign. :-)

**Comment by aesculus** [comment]
This is what the menu would look like. Note I had to change the Activate icon, which I think is more appropriate anyway.

![image](https://cloud.githubusercontent.com/assets/283364/25307124/959e5f7a-2750-11e7-845a-720720b3902b.png)

**Comment by EVGrokker** [comment]
I know it probably feels like we're chasing our tails here, but I think this menu item should **Edit Trip Details** to match **Edit Segment Details** in the Plan menu. The dialogs are intended to be similar, so we want the user to be able to guess what this function does based on consistent naming.

I think that 'Trip Inspector' needs to mean you're looking at the entire trip at once, which is what you get when you touch the folded map on the Plan screen - a list of all segments making up the current trip. To me, that's the Trip Inspector. But I need to see these changes in context before I can feel certain about this.

**Comment by aesculus** [comment]
OK. I was just going by what was up thread, but I may have gotten lost. Edit Trip Details if better for me.

**Comment by EVGrokker** [comment]
I admit I'm all over the map with this. Forgive me for dithering. Let's go with Edit Trip Details and see how that feels.

**Comment by aesculus** [comment]
I can do Name (expecting it's the same as the last segment name), Date/Time (the first segments Date/Time), Rating (from first segment) but comments has me.

If we want to keep a comment in the Segment Details then I would have to add a trip comments somewhere (probably in the first segment).

I guess the same could be for the Trip Name. If you don't want to use the last segments name, then I have to add one too. My worry on the name is that I don't want to chase the trip name every time someone updates the last segment name. I already have to do that in the case of merge/delete so maybe that's ok.

**Comment by EVGrokker** [comment]
Ideally there would be a trip comments field independent of individual segments. If that's too much trouble, I'd opt for keeping individual segment comments over a single trip comment field. 
I would opt for initially naming the trip based on the first destination input when creating the new trip. Once they edit the trip name, no need to chase the last segment. 

If they don't rename the trip, but add a segment, creating a new final destination, I would chase that change.

**Comment by aesculus** [comment]
I think you just made the case for a independent trip name. It will default to the first segments name. I think I will let them fix it if they add/merge or delete segments, at least initially.

As for trip comments: Can we leave that out for now and just let the put in comments on the segments?

**Comment by EVGrokker** [comment]
No trip comments for now. 

Trip named during New Trip creation, any subsequent changes are up to the user.

**Comment by aesculus** [comment]
App will now have an independent trip name (default is first segment name). This will appear in the Current and Archive Trips panels. The segment name will still appear in any segment dialog/panel.

Implemented in V1.2 (23)

**Comment by aesculus** [comment]
The ratings are now part of this dialog. Issue #389

**Comment by aesculus** [comment]
New dialog for editing master trip details:

![image](https://cloud.githubusercontent.com/assets/283364/26513600/3f38db74-4221-11e7-9658-1e6f642e2fa8.png)

**Comment by aesculus** [comment]
The date/time will ripple down through the segments. In addition this is where you can set the Planned vs Taken attribute. If the trip is not Taken, the Trip Rating options are reset to the drama icon - not rated, and are grayed out.

**Comment by aesculus** [comment]
This was updated in V1.2 (28)

It's now referred to as the Trip Status dialog.

![image](https://cloud.githubusercontent.com/assets/283364/26751026/c9dd5318-47e4-11e7-9cf9-3b26925022cd.png)

**Comment by EVGrokker** [comment]
It is now possible to edit the current trip's name in Edit Trip Details.
