### ISSUE TITLE
Changing Trip Date May not Refresh Weather

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#95]
A user reported that changing the trip date did not cause the weather to refresh.

**Comment by aesculus** [comment]
This is a confirmed bug. Changing the trip date/time does get new weather but the waypoint forecast times are not being shifted.

**Comment by aesculus** [comment]
It appears that I was wrong. It seems to take two passes to update the weather. Not sure why yet.

**Comment by EVGrokker** [comment]
How would a user know that weather was not being refreshed?

**Comment by aesculus** [comment]
They were watching the temperatures after changing the date/time to see what effect it had on overall energy consumption.

If you follow the trip date/time change with a pseudo waypoint edit, it should force the new weather to be applied.

Now I need to figure out why the waypoint info needs these two passes. There is some kind of caching going on internally to a commercial plugin I need to flush out.

**Comment by aesculus** [comment]
This actually seems to have some pretty big repercussions.  When the weather does not update it causes the efficiency to be miss-calculated. This in turn can cause the optimizer to use the wrong value when optimizing.  

What happens is that the route could change between optimizations as the weather lags, if the weather has a large influence on the power consumption.

**Comment by aesculus** [comment]
This problem occurs because the trip date has been changed but the arrival date, calculated after the date has been changed, is still set for the old value. The weather is using the arrival date to obtain its forecast data.

A new algorithm for determining which date the weather should be forecast for each waypoint needs to be created.

**Comment by aesculus** [comment]
Fixed in V1.2 (3)
